const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{build}=require('esbuild'),{spawn}=require('node:child_process');
const wait=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,label,time=20000){let start=Date.now();while(Date.now()-start<time){if(await fn())return;await wait(40);}throw Error('Timeout: '+label);}
async function run(){await build({entryPoints:['src/main/search-service.ts'],outfile:'dist/main/search-test.cjs',bundle:true,platform:'node',external:['electron']});const {SearchService}=require('../dist/main/search-test.cjs');const out=path.resolve('work/cache-0.9');await fs.mkdir(out,{recursive:true});const root=await fs.mkdtemp(path.join(out,'index-'));const cache=path.join(root,'file-index.bin');await fs.writeFile(cache+'.123456.1.tmp','old');await fs.writeFile(cache+'.tmp','partial');await fs.writeFile(cache+'.backup.tmp','keep');await Promise.all(Array.from({length:1450},(_,i)=>fs.writeFile(path.join(root,'item-'+i+'.txt'),'x')));const settings={roots:[root],excluded:[],maxEntries:1000,fuzzy:true,pinyin:true};let service=new SearchService(cache,settings,()=>{});let maxTemp=0,monitorEnabled=false,monitor=setInterval(async()=>{const files=await fs.readdir(root);if(monitorEnabled)maxTemp=Math.max(maxTemp,files.filter(n=>/^file-index\.bin(?:\.\d+\.\d+)?\.tmp$/.test(n)).length);},20);
try{await until(()=>!service.state().running&&service.state().count===1000,'limit 1000');await until(async()=>{try{return (await fs.stat(cache)).size>1000;}catch{return false;}},'first save');assert.ok(!(await fs.readdir(root)).includes('file-index.bin.123456.1.tmp'));assert.equal(await fs.readFile(cache+'.backup.tmp','utf8'),'keep');assert.equal((await fs.readFile(cache)).subarray(0,8).toString(),'ONEIDX06');monitorEnabled=true;
 service.rebuild({...settings,maxEntries:2000});await until(()=>!service.state().running&&service.state().count===1452,'grow limit');await Promise.all(Array.from({length:80},(_,i)=>fs.writeFile(path.join(root,'changed-'+i+'.txt'),'burst')));await until(()=>service.state().count===1532,'watch changes');await until(async()=>!(await fs.readdir(root)).includes('file-index.bin.tmp'),'settled');await wait(3000);const stable=(await fs.stat(cache)).mtimeMs;await wait(3500);assert.equal((await fs.stat(cache)).mtimeMs,stable,'cache must not trigger its own watcher');assert.equal((await service.query('file-index.bin')).items.some(i=>i.path===cache||i.path===cache+'.lock'),false);
 service.rebuild(settings);await until(()=>!service.state().running&&service.state().count===1000,'shrink limit');await fs.writeFile(path.join(root,'beyond-limit.txt'),'cap');await wait(600);assert.ok(service.state().count<=1000);await service.stop();assert.ok(!(await fs.readdir(root)).includes('file-index.bin.tmp'));
 // Simulate files left by an interrupted former writer and verify precise recovery.
 monitorEnabled=false;await fs.writeFile(cache+'.987654.9.tmp','interrupted');await fs.writeFile(cache+'.tmp','interrupted');service=new SearchService(cache,settings,()=>{});await until(()=>service.state().count===1000&&!service.state().running,'restart');assert.ok(!(await fs.readdir(root)).includes('file-index.bin.987654.9.tmp'));monitorEnabled=true;assert.equal(await fs.readFile(cache+'.backup.tmp','utf8'),'keep');
 // A second helper cannot race cleanup or writes against the same cache.
 const exe=path.resolve('dist/native/One.Index.exe');const second=spawn(exe,[cache],{windowsHide:true});let response='';second.stdout.on('data',b=>response+=b);await new Promise(r=>second.on('exit',r));assert.match(response,/索引缓存不可用/);
 // Replacement failure leaves no temporary file and keeps searching usable.
 await until(async()=>{try{return (await fs.stat(cache)).size>100;}catch{return false;}},'saved');await wait(2500);await fs.rename(cache,cache+'.saved');await fs.mkdir(cache);service.rebuild({...settings,maxEntries:2000});await until(()=>service.state().error.includes('缓存保存失败'),'write failure');assert.ok(!(await fs.readdir(root)).includes('file-index.bin.tmp'));assert.ok((await service.query('item-')).total>0);await fs.rmdir(cache);await fs.rename(cache+'.saved',cache);await service.stop();assert.ok(maxTemp<=1);console.log(JSON.stringify({result:'PASS',limits:[1000,2000,1000],singleTemp:true,noSelfIndexLoop:true,coalescedWrites:true,legacyTempRecovery:true,unrelatedFilesPreserved:true,exclusiveCache:true,failedWriteCleanup:true,gracefulExit:true,root}));
}finally{clearInterval(monitor);await service.stop();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
