const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),{buildSync}=require('esbuild');
const source=buildSync({entryPoints:['src/shared/csv-preview.ts'],bundle:true,platform:'node',write:false}).outputFiles[0].text,moduleObject={exports:{}};vm.runInNewContext(source,{module:moduleObject,exports:moduleObject.exports});const {CsvStore}=moduleObject.exports;
test('CSV preserves complete wide and long records instead of clipping rows or columns',()=>{const lines=[Array.from({length:120},(_,col)=>'column_'+col).join(',')];for(let row=0;row<1200;row++)lines.push(Array.from({length:120},(_,col)=>`R${row}_C${col}`).join(','));const store=new CsvStore(lines.join('\r\n'),',');assert.equal(store.shape.rows,1201);assert.equal(store.shape.columns,120);assert.equal(store.cell(1200,119),'R1199_C119');assert.equal(store.range(1190,112,32,16).cells.at(-1).text,'R1199_C119');});
test('quoted delimiters, escaped quotes and exact CRLF inside a field survive decoding',()=>{const store=new CsvStore('name,value\r\n"hello,world","line1\r\nline2"\r\n"a""b",""\r\n',',');assert.equal(store.shape.rows,3);assert.equal(store.cell(1,0),'hello,world');assert.equal(store.cell(1,1),'line1\r\nline2');assert.equal(store.cell(2,0),'a"b');assert.equal(store.cell(2,1),'');});
test('TSV, blank records, ragged rows and a trailing empty field remain accessible',()=>{const store=new CsvStore('甲\t乙\r1\t2\t3\r\n\nlast\t','\t');assert.equal(store.shape.rows,4);assert.equal(store.shape.columns,3);assert.equal(store.cell(0,2),'');assert.equal(store.cell(1,2),'3');assert.equal(store.cell(2,0),'');assert.equal(store.cell(3,0),'last');assert.equal(store.cell(3,1),'');assert.equal(store.cell(3,2),'');});
test('empty files and terminal newlines do not invent records',()=>{assert.equal(new CsvStore('',',').shape.rows,0);assert.equal(new CsvStore('\n',',').shape.rows,1);assert.equal(new CsvStore('a\n',',').shape.rows,1);assert.equal(new CsvStore(',',',').shape.columns,2);assert.equal(new CsvStore('a\n\n',',').shape.rows,2);});
test('long values have bounded page previews and full cell data on request',()=>{const value='中文\n'.repeat(20000)+'END',quoted='"'+value.replaceAll('"','""')+'"',store=new CsvStore('value\n'+quoted,',');const cell=store.range(1,0,1,1).cells[0];assert.equal(cell.truncated,true);assert.equal(cell.text.length,240);assert.equal(store.cell(1,0),value);});
test('invalid table ranges and malformed quoted fields fail explicitly',()=>{const store=new CsvStore('a,b\n1,2',',');for(const args of [[-1,0],[0,-1],[2,0],[0,2],[.1,0]])assert.throws(()=>store.cell(...args));for(const args of [[0,0,65,1],[0,0,1,33],[0,0,0,1],[5,0,1,1]])assert.throws(()=>store.range(...args));assert.throws(()=>new CsvStore('"open',','));assert.throws(()=>new CsvStore('"closed"wrong',','));assert.throws(()=>new CsvStore('a|b','|'));});
test('literal quotes in an unquoted field are not removed',()=>{const store=new CsvStore('a"b,c\n"padded"  ,value',',');assert.equal(store.cell(0,0),'a"b');assert.equal(store.cell(1,0),'padded');});
