const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),{buildSync}=require('esbuild');
const source=buildSync({entryPoints:['src/renderer/deferred-work.ts'],bundle:true,platform:'node',write:false}).outputFiles[0].text;
function fixture(t,work){t.mock.timers.enable({apis:['setTimeout']});const module={exports:{}};vm.runInNewContext(source,{module,exports:module.exports,setTimeout,clearTimeout});let active=true,calls=0;const deferred=new module.exports.DeferredWork(300,()=>active,async()=>{calls++;if(work)await work();},error=>{throw error;});return{deferred,active:value=>active=value,calls:()=>calls};}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('automatic edits coalesce before starting work',async t=>{const f=fixture(t);f.deferred.request();t.mock.timers.tick(100);f.deferred.request();t.mock.timers.tick(299);assert.equal(f.calls(),0);t.mock.timers.tick(1);await settle();assert.equal(f.calls(),1);});
test('inactive pages retain the latest edit without starting work',async t=>{const f=fixture(t);f.deferred.request();f.active(false);f.deferred.sync();t.mock.timers.tick(1000);assert.equal(f.calls(),0);f.deferred.request();f.active(true);f.deferred.sync();t.mock.timers.tick(300);await settle();assert.equal(f.calls(),1);});
test('availability is checked again at the execution boundary',async t=>{const f=fixture(t);f.deferred.request();f.active(false);t.mock.timers.tick(300);assert.equal(f.calls(),0);f.active(true);f.deferred.sync();t.mock.timers.tick(300);await settle();assert.equal(f.calls(),1);});
test('edits during an active task wait for release and visibility',async t=>{let release;const first=new Promise(r=>release=r);const f=fixture(t,()=>first);f.deferred.request();t.mock.timers.tick(300);assert.equal(f.calls(),1);f.deferred.request();f.deferred.request();t.mock.timers.tick(1000);assert.equal(f.calls(),1);f.active(false);release();await settle();t.mock.timers.tick(1000);assert.equal(f.calls(),1);f.active(true);f.deferred.sync();t.mock.timers.tick(300);await settle();assert.equal(f.calls(),2);});
test('a fresh explicit result clears a queued automatic refresh',async t=>{const f=fixture(t);f.deferred.request();f.deferred.clear();t.mock.timers.tick(1000);await settle();assert.equal(f.calls(),0);});
