const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{build}=require('esbuild');
async function run(){
 const out=path.resolve('work/dialog-smoke');await fs.mkdir(out,{recursive:true});const profile=await fs.mkdtemp(path.join(out,'profile-')),env={...process.env,ONE_TEST_MODE:'1',ONE_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;
 const harness=path.join(out,'runtime.js');await build({stdin:{contents:'export * from "./src/renderer/dialog";',resolveDir:path.resolve('.')},outfile:harness,bundle:true,platform:'browser',format:'iife',globalName:'dialogHarness'});
 const app=await electron.launch(process.env.ONE_PACKAGED_EXE?{executablePath:process.env.ONE_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env}),errors=[];app.on('window',p=>p.on('pageerror',e=>errors.push(String(e))));
 try{
  const page=await app.firstWindow();page.on('pageerror',e=>errors.push(String(e)));await page.waitForSelector('[data-page=color]');await page.locator('[data-page=color]').click();await page.locator('#color-format-edit').click();const formats=page.getByRole('dialog',{name:'显示格式'});await expect(formats).toBeVisible();await expect(formats.locator('.one-dialog-body')).toBeVisible();assert.equal(await formats.evaluate(d=>d.matches(':modal')),true);
  const duplicateIds=await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);});assert.deepEqual(duplicateIds,[]);
  await formats.evaluate(async d=>{await Promise.all(d.getAnimations().map(a=>a.finished.catch(()=>{})));});await page.screenshot({path:path.join(out,'formats.png')});
  const continuity=await formats.evaluate(d=>{const frame=()=>{const style=getComputedStyle(d),backdrop=getComputedStyle(d,'::backdrop');return{opacity:Number(style.opacity),transform:style.transform,backdrop:backdrop.backgroundColor,filter:backdrop.backdropFilter};};document.querySelector('#color-formats-close').click();const animation=d.getAnimations().find(a=>a.animationName==='dialog-out');if(!animation)throw Error('Missing closing animation');animation.currentTime=50;const before=frame();document.querySelector('#color-format-edit').click();const after=frame();const entering=d.getAnimations().find(a=>a.animationName==='one-dialog-in');entering.currentTime=70;const closingBefore=frame();document.querySelector('#color-formats-close').click();const closingAfter=frame();document.querySelector('#color-format-edit').click();return{before,after,closingBefore,closingAfter,open:d.open};});console.log('Dialog continuity',continuity);assert.equal(continuity.open,true);assert.ok(continuity.before.opacity>.05);for(const [before,after]of [[continuity.before,continuity.after],[continuity.closingBefore,continuity.closingAfter]]){assert.ok(Math.abs(after.opacity-before.opacity)<.05,'Interrupted motion must preserve opacity');assert.equal(after.transform,before.transform);assert.equal(after.backdrop,before.backdrop);assert.equal(after.filter,before.filter);}
  await formats.evaluate(async d=>{await Promise.all(d.getAnimations().map(a=>a.finished.catch(()=>{})));});await page.keyboard.press('Escape');await expect(formats).not.toBeVisible();await expect(page.locator('#color-format-edit')).toBeFocused();
  await page.locator('#color-format-edit').click();await page.evaluate(()=>{document.querySelector('#color-formats-close').click();document.querySelector('#color-format-edit').click();});await page.waitForTimeout(180);await expect(formats).toBeVisible();await page.locator('#color-formats-close').click();await expect(formats).not.toBeVisible();
  // Existing export/import dialog keeps errors inside its body, preserving settings on invalid input.
  await page.locator('[data-page=search]').click();await page.locator('#search-tab-menu').click();await page.locator('#menu-export').click();const exported=await page.locator('#menu-json').inputValue();JSON.parse(exported);await page.keyboard.press('Escape');await expect(page.locator('#menu-export')).toBeFocused();await page.locator('#menu-import').click();await expect(page.locator('#menu-json')).toBeFocused();await page.keyboard.insertText('{');await page.locator('#menu-json-apply').click();await expect(page.locator('#menu-json-dialog .one-dialog-body .dialog-error')).toBeVisible();assert.deepEqual((await page.evaluate(()=>window.one.settings())).search.menu,JSON.parse(exported));await page.locator('#menu-json').fill(exported);await page.locator('#menu-json-apply').click();await expect(page.locator('#menu-json-dialog')).not.toBeVisible();
  await page.locator('[data-edit="default-2"]').click();await page.locator('#menu-icon').click();const icons=page.getByRole('dialog',{name:'选择图标'});await expect(icons).toBeVisible();await page.locator('#icon-picker-query').fill('code');await page.getByRole('option',{name:'code',exact:true}).click();await expect(icons).toHaveCount(0);await expect(page.locator('#menu-icon')).toBeFocused();await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).search.menu.find(i=>i.id==='default-2').icon)).toBe('lucide:code');
  // Real text comparison now shares the same modal layout and scrolling body.
  await page.locator('[data-page=tools]').click();await page.locator('#tool-tab-diff').click();await page.locator('#file-diff-ignore-space').check();await page.locator('[data-page=text]').click();await page.locator('#source .cm-content').fill(' alpha\nbeta ');await page.locator('#result .cm-content').fill('alpha\nbeta');await page.locator('#text-compare').click();await expect(page.getByRole('dialog',{name:'文本差异'})).toBeVisible();await expect(page.locator('#diff-content')).not.toHaveText('');await page.locator('#diff-ignore-space').check();await page.locator('#text-diff-refresh').click();await expect(page.locator('#diff-position')).toHaveText('没有差异');assert.equal(await page.locator('#file-diff-ignore-space').isChecked(),true);await page.locator('#text-diff-close').click();await expect(page.locator('#text-diff-dialog')).not.toBeVisible();
  // Only this test instance receives fictitious maintenance reports/actions.
  await app.evaluate(({ipcMain})=>{globalThis.fixtureMaintenanceCalls=0;for(const name of ['maintenance-scan','maintenance-apply','maintenance-receipts'])ipcMain.removeHandler('one:'+name);ipcMain.handle('one:maintenance-scan',(_,kind)=>({id:'fixture',kind,created:Date.now(),entries:Array.from({length:70},(_,i)=>({id:String(i),name:'测试项目 '+i,source:'fixture',status:'目标存在',command:'测试命令',location:'测试位置 '+i,category:'测试',detail:'测试详情',action:kind==='startup'?'disable':'clean'}))}));ipcMain.handle('one:maintenance-apply',()=>{globalThis.fixtureMaintenanceCalls++;return{succeeded:70,failed:[],bytes:0};});ipcMain.handle('one:maintenance-receipts',()=>Array.from({length:70},(_,i)=>({id:String(i),created:Date.now(),name:'测试记录 '+i,restorable:false,restored:false,items:1})));});
  await page.locator('[data-page=system]').click();await expect(page.locator('#maintenance-rows')).toHaveAttribute('aria-rowcount','70');await expect(page.locator('.maintenance-item').first()).toBeVisible();assert.ok(await page.locator('.maintenance-item').count()<70);await page.locator('#maintenance-select-all').check();await expect(page.locator('#maintenance-count')).toHaveText('70');await page.locator('#maintenance-apply').click();const maintenance=page.getByRole('dialog',{name:'禁用 70 项启动内容'});await expect(maintenance.locator('#maintenance-confirm-cancel')).toBeFocused();await page.keyboard.press('Escape');await expect(maintenance).not.toBeVisible();assert.equal(await app.evaluate(()=>globalThis.fixtureMaintenanceCalls),0);await page.locator('#maintenance-apply').click();await page.evaluate(()=>{const b=document.querySelector('#maintenance-confirm-run');b.click();b.click();});await expect.poll(()=>app.evaluate(()=>globalThis.fixtureMaintenanceCalls)).toBe(1);await expect(maintenance).not.toBeVisible();
  await page.locator('#maintenance-history').click();const history=page.getByRole('dialog',{name:'操作记录'});await expect(history).toBeVisible();assert.equal(await history.evaluate(d=>{const body=d.querySelector('.one-dialog-body'),receipts=d.querySelector('#maintenance-receipts');return body.scrollHeight>body.clientHeight&&getComputedStyle(receipts).overflowY==='visible';}),true);await page.locator('#maintenance-history-close').click();await expect(history).not.toBeVisible();
  // Cancel an actual overwrite prompt for a fresh test file; Escape must keep the picker open.
  await fs.writeFile(path.join(profile,'overwrite.txt'),'before');await page.locator('[data-page=text]').click();await page.locator('#save-text').click();await expect.poll(()=>app.windows().some(p=>p.url().includes('view=picker'))).toBe(true);const picker=app.windows().find(p=>p.url().includes('view=picker'));await picker.waitForSelector('#picker-path');await picker.locator('#picker-path').fill(profile);await picker.locator('#picker-go').click();await expect(picker.locator('#picker-status')).toContainText('项');await picker.locator('#picker-name').fill('overwrite.txt');await picker.locator('#picker-confirm').click();await expect(picker.getByRole('dialog',{name:'文件已存在'})).toBeVisible();await picker.keyboard.press('Escape');await expect(picker.locator('#overwrite-dialog')).not.toBeVisible();assert.equal(picker.isClosed(),false);assert.equal(await fs.readFile(path.join(profile,'overwrite.txt'),'utf8'),'before');await picker.locator('#picker-cancel').click();await expect.poll(()=>picker.isClosed()).toBe(true);
  // Exercise reusable confirmation semantics in the real renderer without altering user files.
  await app.evaluate(({BrowserWindow},code)=>BrowserWindow.getAllWindows().find(w=>!w.isDestroyed()&&!w.webContents.isDestroyed()&&w.webContents.getURL().includes('view=main')).webContents.executeJavaScript(code),await fs.readFile(harness,'utf8'));await page.locator('#text-compare').focus();
  await page.evaluate(()=>{const holder=document.createElement('template');holder.innerHTML=window.dialogHarness.dialogMarkup({id:'focus-fields-test',title:'输入内容',body:'<input hidden autofocus><fieldset disabled><input></fieldset><input readonly value="只读"><textarea id="focus-fields-input"></textarea>'});const d=holder.content.firstElementChild;d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);window.dialogHarness.openDialog(d);});await expect(page.locator('#focus-fields-input')).toBeFocused();await page.keyboard.insertText('直接输入');await expect(page.locator('#focus-fields-input')).toHaveValue('直接输入');await page.keyboard.press('Escape');await expect(page.locator('#focus-fields-test')).toHaveCount(0);await expect(page.locator('#text-compare')).toBeFocused();
  await page.evaluate(()=>{window.answers=[];window.dialogHarness.confirmDialog({title:'确认 <文件>',message:'测试消息',confirm:'执行',danger:true}).then(answer=>window.answers.push(answer));});const confirmation=page.getByRole('dialog',{name:'确认 <文件>'});await expect(confirmation).toBeVisible();await expect(confirmation.locator('[data-dialog-cancel]')).toBeFocused();await page.keyboard.press('Escape');await expect.poll(()=>page.evaluate(()=>window.answers)).toEqual([false]);await expect(page.locator('#text-compare')).toBeFocused();
  await page.evaluate(()=>{window.dialogHarness.confirmDialog({title:'只执行一次',message:'测试消息'}).then(answer=>window.answers.push(answer));});await page.evaluate(()=>{const b=document.querySelector('[data-dialog-confirm]');b.click();b.click();});await expect.poll(()=>page.evaluate(()=>window.answers)).toEqual([false,true]);
  // A long confirmation must expose one scroll area and keep the actions within the viewport.
  await page.evaluate(()=>{window.dialogHarness.confirmDialog({title:'长内容',message:Array.from({length:500},(_,i)=>'第 '+i+' 行内容').join('\n')}).then(answer=>window.answers.push(answer));});const long=page.getByRole('dialog',{name:'长内容'});await expect(long).toBeVisible();
  await long.evaluate(async d=>{await Promise.all(d.getAnimations().map(a=>a.finished.catch(()=>{})));});const geometry=await long.evaluate(d=>{const body=d.querySelector('.one-dialog-body'),footer=d.querySelector('.one-dialog-actions');return{bodyScroll:body.scrollHeight>body.clientHeight,dialogScroll:d.scrollHeight>d.clientHeight,footerBottom:footer.getBoundingClientRect().bottom,height:innerHeight,wide:d.scrollWidth>d.clientWidth,modal:d.matches(':modal')};});assert.ok(geometry.bodyScroll);assert.equal(geometry.dialogScroll,false);assert.equal(geometry.wide,false);assert.ok(geometry.footerBottom<geometry.height-12);assert.equal(geometry.modal,true);await page.screenshot({path:path.join(out,'long-light.png')});await page.mouse.click(4,4);await expect(long).not.toBeVisible();await expect.poll(()=>page.evaluate(()=>window.answers)).toEqual([false,true,false]);
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>window.one.patchSettings({appearance:{mode:'dark'}}));await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.evaluate(()=>{window.dialogHarness.confirmDialog({title:'减少动态效果',message:'测试消息'}).then(answer=>window.answers.push(answer));});const reduced=page.getByRole('dialog',{name:'减少动态效果'});await expect(reduced).toBeVisible();assert.equal(await reduced.evaluate(d=>getComputedStyle(d).animationName),'none');await page.screenshot({path:path.join(out,'reduced-dark.png')});await page.keyboard.press('Escape');await expect(reduced).not.toBeVisible();assert.deepEqual(errors,[]);
  const result={result:'PASS',sharedModalLayout:true,uniqueIds:true,escapedTitle:true,focusReturn:true,editableFieldFocus:true,explicitAutofocusPreserved:true,escapeCancel:true,backdropCancel:true,reopenDuringClose:true,interruptedMotionContinuous:continuity,confirmationOnce:true,invalidImportPreservesSettings:true,iconPickerAndFocus:true,textDiff:true,diffOptionsIndependent:true,maintenanceCancelAndOnce:true,historyOneScroller:true,overwriteCancelKeepsPicker:true,oneScrollBody:true,actionsVisible:true,reducedMotion:true,errors};await fs.writeFile(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await app.close();}
}
run().catch(e=>{console.error(e);process.exitCode=1;});
