const {test}=require('node:test'),assert=require('node:assert/strict'),{build}=require('esbuild'),{EventEmitter}=require('node:events');
async function moduleFor(file,loader=require,plugins=[]){const bundle=await build({entryPoints:[file],bundle:true,platform:'node',format:'cjs',write:false,external:['electron'],plugins});const m={exports:{}};new Function('module','exports','require',bundle.outputFiles[0].text)(m,m.exports,loader);return m.exports;}
test('文件对话框操作栏优先向下展开，并适配屏幕边缘和负坐标',async()=>{
 const {dialogBarBounds}=await moduleFor('src/shared/dialog-bar.ts'),area={x:-1920,y:-100,width:1920,height:1080},owner={x:-1500,y:20,width:900,height:600};const idle=dialogBarBounds(owner,area),results=dialogBarBounds(owner,area,2,true);assert.equal(idle.height,70);assert.equal(results.y,idle.y);assert.equal(results.height,70+2*58+10);assert.equal(results.x,idle.x);
 for(const a of [area,{x:0,y:0,width:350,height:180},{x:1200,y:-900,width:1800,height:900}])for(const o of [owner,{x:1800,y:800,width:900,height:600}])for(const rows of [0,2,200,NaN,-1]){const r=dialogBarBounds(o,a,rows,true);assert.ok(Object.values(r).every(Number.isFinite));assert.ok(r.x>=a.x&&r.y>=a.y);assert.ok(r.x+r.width<=a.x+a.width&&r.y+r.height<=a.y+a.height);}
});
test('操作栏先附着，再异步读取目录；过期窗口的结果不会覆盖当前窗口',async()=>{
 const calls=[],pending=[],windows=[],config={dialogSwitch:true,bookmarks:[]};class Overlay{constructor(window,hwnd){this.hwnd=hwnd;this.window=window;}attach(){calls.push(['attach',this.hwnd]);return true;}detach(){calls.push(['detach',this.hwnd]);}interactive(){return true;}resize(){}focusOwner(){}}
 const plugin={name:'overlay-fixture',setup(b){b.onResolve({filter:/dialog-overlay$/},args=>({path:args.path,external:true}));}},loader=id=>id==='electron'?{BrowserWindow:{}}:id.endsWith('dialog-overlay')?{DialogOverlay:Overlay,dialogProcess:()=>42}:require(id);
 const {DialogBar}=await moduleFor('src/main/dialog-bar.ts',loader,[plugin]),create=()=>{const w=new EventEmitter();w.destroyed=false;w.isDestroyed=()=>w.destroyed;w.hide=()=>{};w.destroy=()=>{w.destroyed=true;w.emit('closed');};w.webContents={id:windows.length+1,isLoading:()=>false,send:(...args)=>calls.push(args)};windows.push(w);return w;},bridge={context:hwnd=>new Promise(resolve=>pending.push({hwnd,resolve}))},history={recentFolders:async()=>['C:/recent']};
 const bar=new DialogBar(create,bridge,()=>config,history);bar.warm();assert.equal(windows.length,1);const first=bar.show(1);assert.deepEqual(calls[1],['attach',1]);assert.equal(pending.length,1);const second=bar.show(2);assert.ok(calls.some(c=>c[0]==='attach'&&c[1]===2));
 pending[1].resolve({kind:'dialog',hwnd:2,pid:42,created:'second',folders:[{path:'C:/new',active:true},{path:'c:/NEW',active:true}]});await second;pending[0].resolve({kind:'dialog',hwnd:1,pid:42,created:'old',folders:[{path:'C:/old',active:true}]});await first;assert.equal(bar.context.hwnd,2);assert.deepEqual((await bar.data()).opened,['C:/new']);await bar.show(2);assert.equal(pending.length,2,'immediate focus transitions do not re-enumerate Explorer');
 const third=bar.show(3);bar.stop();pending[2].resolve({kind:'dialog',hwnd:3,pid:42,created:'third',folders:[]});await third;assert.equal(bar.context,undefined);assert.equal(windows[0].destroyed,true);config.dialogSwitch=false;bar.warm();assert.equal(windows.length,1);
});
