const {test}=require('node:test'),assert=require('node:assert/strict'),{buildSync}=require('esbuild'),path=require('node:path');
// Load the two public models independently to preserve their module exports.
function load(file){const value={exports:{}};new Function('module','exports','require',buildSync({entryPoints:[file],bundle:true,platform:'node',write:false}).outputFiles[0].text)(value,value.exports,require);return value.exports;}
const {DirectoryIndex}=load('src/shared/directory.ts'),{directoryRowCount:count,directoryRowAt:at,directoryPositionOf:position,invalidateDirectory:invalidate}=load('src/shared/directory-tree.ts');
test('complete directory indices use natural sorting, directories first, and bounded pages',()=>{const root=path.resolve('large'),names=Array.from({length:30000},(_,i)=>({name:'item-'+i+'.txt',directory:false}));names.push({name:'folder',directory:true});const index=new DirectoryIndex(root,names);assert.equal(index.count,30001);assert.equal(index.page(0,2).entries[0].name,'folder');assert.equal(index.page(0,256).entries.length,256);assert.equal(index.page(30000,128).entries[0].name,'item-29999.txt');assert.equal(index.find(path.join(root,'item-29999.txt')),30000);assert.equal(index.find(path.resolve('elsewhere','item-29999.txt')),-1);});
test('directory filtering covers the end, Unicode and case, without changing original positions',()=>{const root=path.resolve('files'),index=new DirectoryIndex(root,[{name:'Project10.txt',directory:false},{name:'Project2.txt',directory:false},{name:'中文 README.md',directory:false}]);const page=index.page(0,128,'PROJECT');assert.deepEqual(page.entries.map(e=>e.name),['Project2.txt','Project10.txt']);assert.equal(index.page(0,128,'README').total,1);assert.equal(index.page(0,128,'中文').entries[0].name,'中文 README.md');assert.equal(index.page(0,128,'absent').total,0);assert.equal(index.page(0,128).total,3);assert.equal(index.find(path.join(root,'project10.txt')),page.entries[1].index);});
test('empty directories and range validation do not invent entries',()=>{const index=new DirectoryIndex(path.resolve('empty'),[]);assert.equal(index.page(0,128).total,0);assert.deepEqual(index.page(100,128).entries,[]);for(const args of [[-1,128],[0,0],[0,257],[.1,1],[0,1,'x'.repeat(1001)]])assert.throws(()=>index.page(...args));});
const node=(id,count,parent,parentIndex)=>({info:{id,path:id,count,position:-1},children:new Map(),parent,parentIndex});
test('flattening expanded folders preserves sibling positions and nested parent navigation',()=>{const root=node('root',10),child=node('child',4,root,2),nested=node('nested',3,child,1);root.children.set(2,{node:child});child.children.set(1,{node:nested});assert.equal(count(root),17);assert.equal(position(child,0),3);assert.equal(position(nested,2),7);assert.equal(at(root,7).node,nested);assert.equal(at(root,7).index,2);assert.equal(at(root,10).node,root);assert.equal(at(root,10).index,3);root.children.delete(2);invalidate(root);assert.equal(count(root),10);assert.equal(at(root,9).index,9);});
test('loading and error rows remain visible, while empty children stay inline with their parent',()=>{const root=node('root',3),branch={};root.children.set(0,branch);assert.equal(count(root),4);assert.equal(at(root,1).note,'正在读取…');branch.error='读取失败';invalidate(root);assert.equal(at(root,1).note,'读取失败');branch.node=node('empty',0,root,0);invalidate(root);assert.equal(count(root),3);assert.equal(at(root,1).index,1);assert.equal(count(node('empty-root',0)),1);assert.equal(at(node('empty-root',0),0).note,'空文件夹');});
test('large expanded-tree lookup reuses its layout and reaches all five million root rows',()=>{const root=node('root',5000000);for(let i=0;i<2500;i++)root.children.set(i*1000,{node:node('child-'+i,100,root,i*1000)});assert.equal(count(root),5250000);const layout=root.layout;assert.equal(at(root,5249999).index,4999999);assert.equal(root.layout,layout);assert.equal(position(root,4999999),5249999);root.children.delete(0);invalidate(root);assert.equal(count(root),5249900);assert.equal(at(root,5249899).index,4999999);});
