const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),JSZip=require('jszip'),{buildSync}=require('esbuild');
const base=path.resolve(process.env.ONE_UNIT_OUTPUT_DIR||'work','document-search-tests');let root,service;const signals=[];
test.before(async()=>{await fs.mkdir(base,{recursive:true});root=await fs.mkdtemp(path.join(base,'transaction-'));const module=path.join(base,'service.cjs');buildSync({entryPoints:['src/main/file-tools-service.ts'],outfile:module,bundle:true,platform:'node',target:'node22'});await fs.copyFile('dist/main/file-tools-worker.cjs',path.join(base,'file-tools-worker.cjs'));const {FileToolsService}=require(module);service=new FileToolsService(path.join(root,'cache'),(_,p)=>signals.push(p));});
test.after(async()=>service?.stop());
const run=task=>service.run(7,task),index=folder=>run({kind:'document-index',roots:[folder],recursive:true,extensions:''});
async function hits(folder,query){const report=await run({kind:'document-search',roots:[folder],query});return service.page(report.id,0);}
async function word(file,text){const z=new JSZip();z.file('word/document.xml','<w:document xmlns:w="urn:w"><w:body>'+text+'</w:body></w:document>');await fs.writeFile(file,await z.generateAsync({type:'nodebuffer',compression:'DEFLATE',compressionOptions:{level:1}}));}
function pdf(marker,pages=1){let text='%PDF-1.4\n',offsets=[0];const obj=(id,body)=>{offsets[id]=Buffer.byteLength(text);text+=`${id} 0 obj\n${body}\nendobj\n`;};obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,`<< /Type /Pages /Kids [${Array.from({length:pages},(_,i)=>`${4+2*i} 0 R`).join(' ')}] /Count ${pages} >>`);obj(3,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');for(let i=0;i<pages;i++){obj(4+2*i,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${5+2*i} 0 R >>`);const content=`BT /F1 12 Tf 30 700 Td (${marker}_${i+1}) Tj ET\n`;obj(5+2*i,`<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}endstream`);}const xref=Buffer.byteLength(text);return text+`xref\n0 ${offsets.length}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;}
async function cancelWhen(folder,phase){const start=signals.length,result=index(folder).then(report=>({report}),error=>({error:String(error)}));const deadline=Date.now()+10000;while(!signals.slice(start).some(p=>p.phase.includes(phase))){assert.ok(Date.now()<deadline,'expected extraction progress');await new Promise(r=>setTimeout(r,5));}const at=performance.now();service.cancel(7,'document-index');const stopped=await result;assert.match(stopped.error,/任务已停止/);while(service.pendingTasks)await new Promise(r=>setTimeout(r,5));assert.ok(performance.now()-at<1000,'cancellation and worker cleanup exceeded one second');}
test('Cancelling Word extraction rolls back the old index and a retry completes correctly',async()=>{
 const folder=path.join(root,'word');await fs.mkdir(folder);const file=path.join(folder,'document.docx');await word(file,'<w:p><w:r><w:t>OLD_WORD_CONTENT</w:t></w:r></w:p>');assert.equal((await index(folder)).stats.indexed,1);
 await word(file,Array.from({length:70000},(_,i)=>`<w:p><w:r><w:t>paragraph ${i} ${'document content '.repeat(5)} ${i===69999?'NEW_WORD_CONTENT':''}</w:t></w:r></w:p>`).join(''));await cancelWhen(folder,'提取 Office 正文');assert.equal((await hits(folder,'OLD_WORD_CONTENT')).length,1);assert.equal((await hits(folder,'NEW_WORD_CONTENT')).length,0);assert.equal((await index(folder)).stats.indexed,1);assert.equal((await hits(folder,'NEW_WORD_CONTENT'))[0].line,70000);assert.equal((await hits(folder,'OLD_WORD_CONTENT')).length,0);
});
test('Cancelling PDF extraction preserves the previous version and frees resources for a complete retry',async()=>{
 const folder=path.join(root,'pdf');await fs.mkdir(folder);const file=path.join(folder,'document.pdf');await fs.writeFile(file,pdf('OLD_PDF'));assert.equal((await index(folder)).stats.indexed,1);await fs.writeFile(file,pdf('NEW_PDF',600));await cancelWhen(folder,'提取 PDF 正文');const moved=file+'.moved';await fs.rename(file,moved);await fs.rename(moved,file);assert.equal((await hits(folder,'OLD_PDF')).length,1);assert.equal((await hits(folder,'NEW_PDF_600')).length,0);assert.equal((await index(folder)).stats.indexed,1);assert.equal((await hits(folder,'NEW_PDF_600'))[0].page,600);
});
test('Malformed and textless PDF files are reported while valid neighbors remain searchable',async()=>{
 const folder=path.join(root,'invalid');await fs.mkdir(folder);await fs.writeFile(path.join(folder,'broken.pdf'),'%PDF-1.4\nnot a valid document');await fs.writeFile(path.join(folder,'empty.pdf'),pdf('').replace(/\(_1\)/,'(  )'));await fs.writeFile(path.join(folder,'valid.pdf'),pdf('VALID_NEIGHBOR'));const report=await index(folder);assert.equal(report.stats.indexed,1);assert.equal(report.issueCount,2);assert.ok(report.issues.some(i=>i.error.includes('OCR')));assert.equal((await hits(folder,'VALID_NEIGHBOR')).length,1);for(const name of ['broken.pdf','empty.pdf']){const file=path.join(folder,name);await fs.rename(file,file+'.moved');await fs.rename(file+'.moved',file);}assert.equal((await index(folder)).stats.cached,1);
});
test('Updating a legacy index refreshes unchanged files once and then reuses the new extraction cache',async()=>{
 const folder=path.join(root,'legacy');await fs.mkdir(folder);const file=path.join(folder,'document.docx');await word(file,'<w:p><w:r><w:t>CURRENT_EXTRACTOR_TEXT</w:t></w:r></w:p>');await index(folder);
 const {DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(path.join(root,'cache','documents.sqlite'));try{db.prepare('UPDATE chunks SET text=? WHERE path=?').run('STALE_EXTRACTOR_TEXT',file);db.exec('ALTER TABLE files DROP COLUMN extractor');}finally{db.close();}
 assert.equal((await hits(folder,'STALE_EXTRACTOR_TEXT')).length,1);const updated=await index(folder);assert.equal(updated.stats.indexed,1);assert.equal(updated.stats.cached,0);assert.equal((await hits(folder,'CURRENT_EXTRACTOR_TEXT')).length,1);assert.equal((await hits(folder,'STALE_EXTRACTOR_TEXT')).length,0);const cached=await index(folder);assert.equal(cached.stats.indexed,0);assert.equal(cached.stats.cached,1);
});
