const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),JSZip=require('jszip'),iconv=require('iconv-lite'),{buildSync}=require('esbuild');
const base=path.resolve(process.env.ONE_UNIT_OUTPUT_DIR||'work','document-text-tests');let root,extractDocument;
test.before(async()=>{await fs.mkdir(base,{recursive:true});root=await fs.mkdtemp(path.join(base,'formats-'));const module=path.join(base,'extract.cjs');buildSync({entryPoints:['src/main/document-text.ts'],outfile:module,bundle:true,platform:'node',target:'node22',external:['pdfjs-dist/legacy/build/pdf.mjs','pdfjs-dist/package.json']});({extractDocument}=require(module));});
async function zip(name,entries){const z=new JSZip();for(const [key,value]of Object.entries(entries))z.file(key,value);const file=path.join(root,name);await fs.writeFile(file,await z.generateAsync({type:'nodebuffer',compression:'DEFLATE'}));return file;}
async function parts(file,options){const stamp={path:file,size:(await fs.stat(file)).size},result=[];for await(const part of extractDocument(stamp,options))result.push(part);return result;}
const document=body=>'<w:document xmlns:w="urn:word"><w:body>'+body+'</w:body></w:document>';
test('Office extraction preserves entities, run breaks, tabs, CDATA and Unicode across chunk boundaries',async()=>{
 const paragraph='<w:p><w:r><w:t>银河 &amp; 探险 😀</w:t><w:tab/><w:t><![CDATA[<内容>]]></w:t><w:br/><w:t>第二行</w:t></w:r></w:p>',body=paragraph.repeat(2000),file=await zip('runs.docx',{'word/document.xml':document(body)}),result=await parts(file),text=result.map(p=>p.text).join('');assert.equal(text,'银河 & 探险 😀\t<内容>\n第二行\n'.repeat(2000));let line=1;for(const p of result){assert.equal(p.line,line);assert.ok(p.text.length<=16000);assert.ok(!/[\uD800-\uDBFF]$/.test(p.text));line+=(p.text.match(/\n/g)||[]).length;}
});
test('Word UTF16 XML BOMs are decoded without damaged text',async()=>{for(const encoding of ['utf16le','utf16be']){const xml=document('<w:p><w:r><w:t>编码银河 😀</w:t></w:r></w:p>'),file=await zip(encoding+'.docx',{'word/document.xml':Buffer.concat([Buffer.from(encoding==='utf16le'?[255,254]:[254,255]),iconv.encode(xml,encoding)])});assert.equal((await parts(file)).map(p=>p.text).join(''),'编码银河 😀\n');}});
test('Excel shared rich strings, inline strings, cached values and formulas exclude phonetic hints',async()=>{
 const file=await zip('cells.xlsx',{'xl/sharedStrings.xml':'<sst><si><r><t>银河</t></r><rPh><t>hint</t></rPh><r><t>探险</t></r></si></sst>','xl/worksheets/sheet1.xml':'<worksheet><sheetData><row><c t="s"><v>0</v></c><c t="inlineStr"><is><r><t>inline</t></r><r><t> 文本</t></r></is></c><c><f>1+2</f><v>3</v></c><c><f>NOW()</f></c></row></sheetData></worksheet>'}),store=new Map();let clears=0;const result=await parts(file,{sharedStrings:{clear(){store.clear();clears++;},put(i,text){store.set(i,text);},get(i){return store.get(i)||'';}}});assert.equal(result.map(p=>p.text).join(''),'银河探险\ninline 文本\n3\nNOW()\n');assert.equal(store.size,0);assert.equal(clears,2);
});
test('PPT pages are numeric ordered and OpenDocument text keeps spaces and line breaks',async()=>{
 const slide=text=>'<p:sld xmlns:p="urn:p" xmlns:a="urn:a"><a:p><a:r><a:t>'+text+'</a:t></a:r></a:p></p:sld>',file=await zip('slides.pptx',{'ppt/slides/slide10.xml':slide('十'),'ppt/slides/slide2.xml':slide('二'),'ppt/slides/slide1.xml':slide('一')});assert.deepEqual((await parts(file)).map(p=>[p.page,p.text]),[[1,'一\n'],[2,'二\n'],[3,'十\n']]);
 for(const ext of ['odt','ods']){const od=await zip('text.'+ext,{'content.xml':'<office:document xmlns:office="urn:o" xmlns:text="urn:t"><text:h>标题</text:h><text:p>银河<text:s text:c="3"/>探险<text:line-break/>第二行<text:tab/>正文</text:p></office:document>'});assert.equal((await parts(od)).map(p=>p.text).join(''),'标题\n银河   探险\n第二行\t正文\n');}
});
test('EPUB chapters preserve text while omitting script/style',async()=>{const file=await zip('chapters.epub',{'OEBPS/chapter10.xhtml':'<p>ten</p>','OEBPS/chapter2.xhtml':'<p>银河 &amp; 探险</p><script>hidden</script><style>hidden</style>'});const result=await parts(file);assert.match(result[0].text,/银河 & 探险/);assert.doesNotMatch(result[0].text,/hidden/);assert.match(result[1].text,/ten/);});
test('Malformed XML rejects instead of silently indexing partial content and releases the file',async()=>{const file=await zip('broken.docx',{'word/document.xml':'<document><p>visible</wrong>'});await assert.rejects(parts(file),/XML 无效/);const renamed=file+'.moved';await fs.rename(file,renamed);await fs.rename(renamed,file);});
test('Office body size limits are kept before decompression',async()=>{const file=await zip('oversize.docx',{'word/document.xml':' '.repeat(32*1024*1024+1)});await assert.rejects(parts(file),/超过 64 MB/);await fs.unlink(file);});
