const { _electron: electron, expect } = require('@playwright/test');
const fs = require('node:fs/promises');
const path = process.getBuiltinModule('node:path');
const assert = require('node:assert/strict');
async function main() {
  const output = path.resolve('work/electron-smoke'); await fs.mkdir(output,{recursive:true});
  const profile = await fs.mkdtemp(path.join(output,'profile-')); const samples = await fs.mkdtemp(path.join(output,'files-'));
  await fs.mkdir(path.join(samples,'child')); await fs.writeFile(path.join(samples,'sample.txt'),'文字预览 <script>不可执行</script>'); await fs.writeFile(path.join(samples,'child','large.bin'),Buffer.alloc(8192));
  await fs.writeFile(path.join(samples,'image.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1XkAAAAASUVORK5CYII=','base64'));
  const stream='BT /F1 24 Tf 70 700 Td (One PDF Preview) Tj ET\n';
  const objects = ['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}endstream`];
  let pdf = '%PDF-1.4\n'; const offsets = [0]; objects.forEach((object,index) => { offsets.push(Buffer.byteLength(pdf)); pdf += `${index+1} 0 obj\n${object}\nendobj\n`; }); const xref=Buffer.byteLength(pdf); pdf += `xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map(offset => String(offset).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; await fs.writeFile(path.join(samples,'sample.pdf'),pdf);
  const env={...process.env,ONE_TEST_MODE:'1',ONE_DATA_DIR:profile}; delete env.ELECTRON_RUN_AS_NODE;
  const packaged = process.env.ONE_PACKAGED_EXE;
  const application = await electron.launch(packaged ? { executablePath:path.resolve(packaged), args:[], env } : { args:[path.resolve('.')], env });
  const errors=[]; application.on('window', page => page.on('pageerror', error => errors.push(String(error))));
  try {
    const page = await application.firstWindow(); await page.waitForSelector('[data-page=text]');await page.locator('[data-page=text]').click();await page.waitForSelector('#source');
    const mainWindow = await application.browserWindow(page);
    await expect.poll(()=>mainWindow.evaluate(w=>w.isVisible())).toBe(true);
    await mainWindow.evaluate(w=>w.focus());
    assert.equal(await page.locator('select').count(),0);
    await page.locator('#encoding').click(); await expect(page.locator('#encoding-options')).toBeVisible(); await page.locator('#encoding').press('ArrowDown'); await page.locator('#encoding').press('Enter'); await expect(page.locator('#encoding')).toHaveText('UTF-8');
    await page.locator('#encoding').click(); await page.screenshot({path:path.join(output,'custom-dropdown.png')}); await page.locator('#encoding').press('Escape'); await expect(page.locator('.select-popup')).toHaveCount(0);
    await page.locator('#source .cm-content').fill('  臺灣軟體  \n\n  臺灣軟體  '); await page.locator('[data-operation=clean]').click(); await expect.poll(()=>page.locator('#result').evaluate(e=>e.value)).toBe('臺灣軟體\r\n臺灣軟體');
    await page.locator('#use-result').click(); await page.locator('[data-operation=unique]').click(); await expect.poll(()=>page.locator('#result').evaluate(e=>e.value)).toBe('臺灣軟體');
    await page.locator('#use-result').click(); await page.locator('[data-operation=simple]').click(); await expect.poll(()=>page.locator('#result').evaluate(e=>e.value)).toBe('台湾软件');
    await page.screenshot({path:path.join(output,'text-workspace.png')});
    let fileDialog=application.waitForEvent('window'); await page.locator('#open-text').click(); let picker=await fileDialog; await picker.waitForSelector('#picker-list .picker-entry'); await picker.locator('#picker-path').fill(samples); await picker.locator('#picker-go').click(); await expect(picker.locator('[role=option][aria-label="sample.txt"]')).toBeVisible(); await picker.locator('[role=option][aria-label="sample.txt"]').click(); await picker.screenshot({path:path.join(output,'custom-file-picker.png')}); await picker.locator('#picker-confirm').click(); await expect.poll(()=>page.locator('#source').evaluate(e=>e.value)).toMatch(/文字预览/);
    fileDialog=application.waitForEvent('window'); await page.locator('#save-text').click(); picker=await fileDialog; await picker.waitForSelector('#picker-list .picker-entry'); await picker.locator('#picker-path').fill(samples); await picker.locator('#picker-go').click(); await expect(picker.locator('[aria-label="sample.txt"]')).toBeVisible(); await picker.locator('#picker-name').fill('saved-output.txt'); await picker.locator('#picker-confirm').click(); await expect(page.locator('#toast')).toHaveText('已保存处理结果'); assert.equal(await fs.readFile(path.join(samples,'saved-output.txt'),'utf8'),'台湾软件');
    // Reject overwriting an existing file until the custom confirmation is accepted.
    fileDialog=application.waitForEvent('window'); await page.locator('#save-text').click(); picker=await fileDialog; await picker.waitForSelector('#picker-list .picker-entry'); await picker.locator('#picker-path').fill(samples); await picker.locator('#picker-go').click(); await expect(picker.locator('[aria-label="sample.txt"]')).toBeVisible(); await picker.locator('#picker-name').fill('sample.txt'); await picker.locator('#picker-confirm').click(); await expect(picker.locator('#overwrite-dialog')).toBeVisible(); await picker.locator('#overwrite-cancel').click(); await picker.locator('#picker-cancel').click().catch(error=>{if(!picker.isClosed())throw error;}); await expect.poll(()=>picker.isClosed()).toBe(true);assert.equal(page.isClosed(),false); assert.match(await fs.readFile(path.join(samples,'sample.txt'),'utf8'),/文字预览/);
    const secure = await mainWindow.evaluate(window => { const preferences=window.webContents.getLastWebPreferences(); return { sandbox:preferences.sandbox,nodeIntegration:preferences.nodeIntegration,contextIsolation:preferences.contextIsolation }; }); assert.deepEqual(secure,{sandbox:true,nodeIntegration:false,contextIsolation:true});
    const volume = await application.evaluate(async ({ app }) => { const { execFile }=process.getBuiltinModule('node:child_process');const { promisify }=process.getBuiltinModule('node:util');const { join }=process.getBuiltinModule('node:path');const helper=join(app.getAppPath(),'node_modules/loudness/impl/windows/adjust_get_current_system_volume_vista_plus.exe').replace('app.asar\\','app.asar.unpacked\\');return Number.parseInt((await promisify(execFile)(helper,[],{windowsHide:true,timeout:3000})).stdout,10); }); assert.ok(volume>=0&&volume<=100);
    await page.locator('[data-page=disk]').first().click(); await page.locator('#disk-path').evaluate((e,p)=>e.value=p,samples); await page.locator('#scan').click(); await expect(page.locator('#disk-results')).toBeVisible(); await expect(page.locator('#disk-files')).toHaveText('5'); await page.locator('#toggle-list').click(); await expect(page.locator('#disk-rows .disk-row')).toHaveCount(5);
    await expect(page.locator('#disk-empty')).toBeHidden(); await page.screenshot({path:path.join(output,'disk-space.png')});
    // Cancellation really terminates the worker and leaves the completed result intact.
    const cancelled = await page.evaluate(async samples => { const pending=window.one.scan(samples).catch(error=>String(error)); await window.one.cancelScan(); return pending; },samples); assert.match(cancelled,/取消/);
    const invalid = await page.evaluate(async () => window.one.scan('relative-path').catch(error=>String(error))); assert.match(invalid,/无效/);
    let opened=application.waitForEvent('window'); await page.evaluate(file=>window.one.preview(file),path.join(samples,'sample.txt')); let preview=await opened; await expect(preview.locator('#preview-body .cm-content')).toContainText('<script>不可执行</script>'); await preview.screenshot({path:path.join(output,'text-preview.png')}); await preview.close();
    opened=application.waitForEvent('window'); await page.evaluate(file=>window.one.preview(file),path.join(samples,'image.png')); preview=await opened; await expect(preview.locator('#preview-body img')).toBeVisible(); await expect.poll(()=>preview.locator('#preview-body img').evaluate(img=>img.complete && img.naturalWidth===1)).toBe(true); await preview.close();
    opened=application.waitForEvent('window'); await page.evaluate(file=>window.one.preview(file),path.join(samples,'sample.pdf')); preview=await opened; await expect(preview.locator('.pdf-sheet canvas')).toBeVisible(); await expect(preview.locator('.textLayer')).toContainText('One PDF Preview'); const assetURL=await preview.evaluate(async()=>(await window.one.previewData()).url); const response=await preview.evaluate(async url=>{const response=await fetch(url);return {status:response.status,mime:response.headers.get('content-type'),text:(await response.text()).slice(0,8)};},assetURL); assert.equal(response.status,200); assert.equal(response.mime,'application/pdf'); assert.match(response.text,/%PDF/); await preview.waitForTimeout(1400); await preview.screenshot({path:path.join(output,'pdf-preview.png')}); await preview.close();
await page.locator('[data-page=input]').first().click(); await page.locator('#enhancement-tab-edges').click(); await page.locator('#dwellMs').fill('800'); await page.locator('#enhancement-tab-echo').click();await page.locator('#keyEcho').check(); await page.locator('#page-name').click();await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).dwellMs)).toBe(Number(await page.locator('#dwellMs').inputValue())); await expect.poll(()=>page.evaluate(async()=>(await window.one.inputStatus()).hook)).toBe(true); const inputStatus=await page.evaluate(()=>window.one.inputStatus()); assert.equal(inputStatus.native,true,inputStatus.error); assert.equal(inputStatus.hook,true); assert.equal(inputStatus.error,''); await page.locator('#keyEcho').uncheck(); await page.locator('#page-name').click();await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).dwellMs)).toBe(Number(await page.locator('#dwellMs').inputValue())); await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).keyEcho)).toBe(false); const saved=JSON.parse(await fs.readFile(path.join(profile,'settings.json'),'utf8')); assert.equal(saved.dwellMs,800); assert.equal(saved.keyEcho,false); await page.screenshot({path:path.join(output,'desktop-actions.png')});
    const timeout=await page.evaluate(async()=>window.one.transform({operation:'replace',text:'a'.repeat(100000)+'!',pattern:'(a+)+$',regex:true}).catch(error=>String(error))); assert.match(timeout,/超时/); await expect(page.locator('#keyEcho')).toBeEnabled();
    await page.locator('[data-page=system]').first().click(); await page.locator('#scan-maintenance').click(); await expect(page.locator('#maintenance-status')).toHaveText(/\d+ 项/,{timeout:130000}); await page.screenshot({path:path.join(output,'system-check.png')}); const startupCount=await page.locator('.maintenance-item').count(); assert.ok(startupCount>0);
    await page.locator('#registry-tab').click(); await page.locator('#scan-maintenance').click(); await expect(page.locator('#maintenance-status')).toHaveText(/\d+ 项/,{timeout:130000});
    await page.locator('[data-page=preview]').first().click(); await page.screenshot({path:path.join(output,'quick-preview.png')});
    assert.deepEqual(errors,[]); console.log(JSON.stringify({result:'PASS',packaged:!!packaged,customControls:true,customFilePicker:true,startupRows:startupCount,output},null,2));
  } finally { await application.close(); }
}
main().catch(error=>{console.error(error);process.exitCode=1});


