const {_electron:electron,expect}=require('@playwright/test');const fs=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
async function main(){const output=path.resolve('work/experience-smoke');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),files=await fs.mkdtemp(path.join(output,'files-'));await require('./preview-fixtures.cjs')(files);
 const env={...process.env,ONE_TEST_MODE:'1',ONE_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;const app=await electron.launch(process.env.ONE_PACKAGED_EXE?{executablePath:path.resolve(process.env.ONE_PACKAGED_EXE),args:[],env}:{args:[path.resolve('.')],env});const errors=[];app.on('window',p=>p.on('pageerror',e=>errors.push(String(e))));
 try{const page=await app.firstWindow();await page.waitForSelector('[data-page=text]');await page.locator('[data-page=text]').click();await page.waitForSelector('#source');assert.equal(await page.locator('svg:not(.lucide):not(.window-glyph)').count(),0);assert.equal(await page.evaluate(()=>navigator.windowControlsOverlay?.visible),false);await page.locator('#encoding').click();assert.equal(await page.locator('.select-popup svg:not(.lucide)').count(),0);await page.locator('#encoding').press('Escape');
 const shot=(p,name)=>p.screenshot({path:path.join(output,name+'.png'),animations:'disabled'});
 const mainFocus=()=>app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>!w.isDestroyed()&&!w.webContents.isDestroyed()&&w.webContents.getURL().includes('view=main'));w.show();w.focus();});
 const open=async(name)=>{await page.evaluate(()=>window.one.patchSettings({preview:{files:false,held:false,pinned:false,wrap:true,leftTab:'files'}}));const event=app.waitForEvent('window');await page.evaluate(file=>window.one.preview(file),path.join(files,name));const preview=await event;await expect(preview.locator('#preview-name')).toHaveText(name);return preview;};
 const overflow=async(p)=>{const result=await p.evaluate(()=>({root:document.documentElement.scrollWidth-innerWidth,body:document.getElementById('preview-body').getBoundingClientRect().right,footer:document.querySelector('.preview-footer').getBoundingClientRect().bottom,width:innerWidth,height:innerHeight}));assert.ok(result.root<=1,JSON.stringify(result));assert.ok(result.body<=result.width+1&&result.footer<=result.height+1,JSON.stringify(result));};
 await page.locator('[data-page=settings]').click();await page.locator('[data-settings-tab=appearance]').click();await page.locator('[data-mode=light]').click();await expect.poll(()=>page.evaluate(async()=>JSON.stringify((await window.one.settings()).appearance))).toBe(await page.evaluate(async()=>JSON.stringify(await window.one.appearance())));await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.querySelector('.sidebar')).backgroundColor)).toBe('rgb(246, 246, 246)');await shot(page,'外观-浅色');
 await page.locator('[data-mode=dark]').click();await expect.poll(()=>page.evaluate(async()=>JSON.stringify((await window.one.settings()).appearance))).toBe(await page.evaluate(async()=>JSON.stringify(await window.one.appearance())));await expect.poll(()=>page.evaluate(()=>getComputedStyle(document.querySelector('.sidebar')).backgroundColor)).toBe('rgb(20, 20, 20)');assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).backgroundColor),'rgb(24, 24, 24)');assert.equal(await page.locator('.workspace').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(24, 24, 24)');await shot(page,'外观-深色');
 await page.locator('[data-mode=light]').click();await expect.poll(()=>page.evaluate(async()=>JSON.stringify((await window.one.settings()).appearance))).toBe(await page.evaluate(async()=>JSON.stringify(await window.one.appearance())));
 await page.locator('[data-page=input]').click();await page.locator('#corner-TL').click();await page.getByRole('option',{name:'自定义快捷键',exact:true}).click();await expect(page.locator('#shortcut-TL')).toBeVisible();await page.locator('#shortcut-TL').focus();await page.keyboard.press('Control+Shift+S');await page.locator('#corner-TR').click();await page.getByRole('option',{name:'执行命令',exact:true}).click();await page.locator('#command-TR').fill('notepad.exe');await page.locator('#args-TR').fill('["file with spaces.txt"]');await page.locator('#page-name').click();await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).dwellMs)).toBe(Number(await page.locator('#dwellMs').inputValue()));await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).cornerBindings.TR.args)).toEqual(['file with spaces.txt']);const settings=await page.evaluate(()=>window.one.settings());assert.equal(settings.cornerBindings.TL.shortcut,'Ctrl+Shift+S');assert.deepEqual(settings.cornerBindings.TR.args,['file with spaces.txt']);await page.evaluate(async()=>{const s=await window.one.settings();s.corners.TL=s.corners.TR='off';await window.one.saveSettings(s);});
 let preview=await open('long.txt');await expect(preview.locator('#preview-open')).toHaveText('');await expect(preview.locator('#preview-open svg.lucide')).toHaveCount(1);assert.equal(await preview.locator('svg:not(.lucide):not(.window-glyph)').count(),0);await overflow(preview);await expect(preview.locator('.cm-editor')).toBeVisible();const wrapMetrics=await preview.locator('.cm-scroller').evaluate(e=>({scroll:e.scrollWidth,client:e.clientWidth}));assert.ok(wrapMetrics.scroll<=wrapMetrics.client+1,JSON.stringify(wrapMetrics));await expect(preview.locator('#preview-file-panel')).toBeHidden();await preview.locator('#preview-hold').click();await preview.locator('#preview-pin').click();const flags=await preview.evaluate(()=>window.one.previewFlags());assert.deepEqual(flags,{held:true,pinned:true});await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=preview')).isAlwaysOnTop())).toBe(true);await mainFocus();await page.waitForTimeout(300);assert.equal(preview.isClosed(),false);assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=preview')).isAlwaysOnTop()),true);await preview.locator('#preview-pin').click();await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=preview')).isAlwaysOnTop())).toBe(false);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=preview')).focus());await preview.locator('#preview-hold').click();await mainFocus();await expect.poll(()=>preview.isClosed()).toBe(true);
 preview=await open('readme.md');await expect(preview.frameLocator('iframe').locator('h1')).toHaveText('One 阅读器');await expect(preview.frameLocator('iframe').locator('table')).toBeVisible();await expect.poll(()=>preview.frameLocator('iframe').locator('img').evaluate(e=>e.naturalWidth)).toBe(1);await preview.locator('#preview-files').click();if(await preview.locator('#preview-files').getAttribute('aria-pressed')!=='true')await preview.locator('#preview-files').click();await preview.locator('#side-details').click();await overflow(preview);await shot(preview,'Markdown-双侧面板');await preview.locator('#side-files').click();await preview.locator('#preview-file-list').getByText('data.json',{exact:true}).click();await expect(preview.locator('.cm-editor')).toBeVisible();await preview.locator('#toggle-render').click();await expect(preview.locator('.data-tree')).toContainText('One');await shot(preview,'JSON-结构');await preview.close();
 preview=await open('page.html');await expect(preview.frameLocator('iframe').locator('h1')).toHaveText('HTML preview');assert.equal(await preview.frameLocator('iframe').locator('h1').evaluate(e=>getComputedStyle(e).color),'rgb(12, 34, 56)');assert.equal(await preview.evaluate(()=>window.compromised),undefined);assert.equal(await preview.frameLocator('iframe').locator('script').count(),0);assert.equal(await preview.frameLocator('iframe').locator('a').getAttribute('href'),null);await shot(preview,'HTML');await preview.close();
 preview=await open('config.yaml');await expect(preview.locator('.cm-content')).toContainText('name: One');await preview.locator('#toggle-render').click();await expect(preview.locator('.data-tree')).toContainText('One');await preview.close();
 preview=await open('data.csv');await expect(preview.locator('.csv-table tr')).toHaveCount(3);await expect(preview.locator('td').first()).toHaveText('hello,world');await preview.close();
 preview=await open('folder');await preview.locator('.file-tree-row').filter({hasText:'nested'}).click();await expect(preview.locator('.file-tree-row').filter({hasText:'inside.txt'})).toBeVisible();await shot(preview,'文件夹树');const root=path.parse(files).root;await preview.evaluate(root=>window.one.selectPreview(root),root);await expect.poll(()=>preview.evaluate(async()=>(await window.one.previewData()).path)).toBe(root);await preview.locator('#preview-files').click();await expect(preview.locator('#files-path')).toHaveText(root);await preview.locator('#preview-files-up').click();await expect(preview.locator('#files-path')).toHaveText(root);await preview.close();
 preview=await open('archive.zip');await preview.locator('.file-tree-row').filter({hasText:'folder'}).click();await expect(preview.locator('.file-tree')).toContainText('readme.txt');await shot(preview,'ZIP');await preview.close();
 preview=await open('app.apk');if(await preview.locator('#preview-files').getAttribute('aria-pressed')!=='true')await preview.locator('#preview-files').click();await preview.locator('#side-details').click();await expect(preview.locator('#preview-details-list')).toContainText('com.one.example');await expect(preview.locator('#preview-details-list')).toContainText('1.2.3');await shot(preview,'APK');await preview.close();
 preview=await open('document.docx');await expect(preview.frameLocator('iframe').locator('section.docx')).toBeVisible({timeout:15000});await expect(preview.frameLocator('iframe').locator('body')).toContainText('One DOCX 文档');await overflow(preview);await shot(preview,'DOCX');await preview.close();
 preview=await open('slides.pptx');await expect(preview.locator('.slide-pages .slide-stage').first()).toContainText('One · 幻灯片 1');await preview.locator('#slide-next').click();await expect(preview.locator('.slide-pages .slide-stage').last()).toContainText('One · 幻灯片 2');await shot(preview,'PPTX');await preview.close();
 preview=await open('oversize.docx');await expect(preview.locator('.preview-unsupported')).toContainText('文档解压后过大');await preview.close();
 preview=await open('document.pdf');await expect(preview.locator('.textLayer').first()).toContainText('One custom PDF');await preview.locator('#pdf-next').click();await expect(preview.locator('#pdf-page')).toHaveValue('2');await preview.locator('#pdf-search').fill('custom');await preview.locator('#pdf-find').click();await expect(preview.locator('#pdf-found')).toHaveText('1/2 页');await expect.poll(()=>preview.locator('.pdf-hit').count()).toBeGreaterThan(0);await preview.locator('#pdf-rotate').click();await expect.poll(()=>preview.locator('.pdf-hit').first().evaluate(e=>{const b=e.getBoundingClientRect();return b.height>b.width*3;})).toBe(true);await overflow(preview);await shot(preview,'PDF-自定义阅读器');await preview.close();
 // Exercise the real HUD window, then inspect alpha of a native capture rather than CSS alone.
 await page.evaluate(async()=>{const s=await window.one.settings();s.keyEcho=true;await window.one.saveSettings(s);});await mainFocus();await expect.poll(()=>app.evaluate(({BrowserWindow})=>BrowserWindow.getFocusedWindow()?.webContents.getURL().includes('view=main'))).toBe(true);await page.waitForTimeout(100);const existingHud=app.windows().find(p=>p.url().includes('view=echo'));const hudOpening=existingHud?Promise.resolve(existingHud):app.waitForEvent('window');await app.evaluate(({app})=>{const {createRequire}=process.getBuiltinModule('node:module');const req=createRequire(app.getAppPath()+'/package.json');const {uIOhook,UiohookKey}=req('uiohook-napi');uIOhook.emit('keydown',{keycode:UiohookKey.K,ctrlKey:true,altKey:false,shiftKey:false,metaKey:false});uIOhook.emit('keyup',{keycode:UiohookKey.K});});const hud=await hudOpening;await expect(hud.locator('#echo-label')).toContainText('Ctrl');const alpha=await app.evaluate(async({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=echo'));w.webContents.send('one:echo','音量 42%');await new Promise(r=>setTimeout(r,180));const image=await w.webContents.capturePage();const bitmap=image.toBitmap();return {corner:bitmap[3],center:bitmap[Math.floor(image.getSize().height/2)*image.getSize().width*4+Math.floor(image.getSize().width/2)*4+3]};});assert.equal(alpha.corner,0);assert.ok(alpha.center>0);await shot(hud,'音量浮层');await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=echo'));w.webContents.send('one:echo','Ctrl + Shift + S');w.showInactive();});await shot(hud,'按键浮层');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',packaged:!!process.env.ONE_PACKAGED_EXE,formats:['txt','md','html','json','yaml','csv','folder','zip','apk','docx','pptx','pdf'],holdAndPin:true,hudAlpha:alpha,output},null,2));
 }catch(error){for(const [i,p] of app.windows().entries()){if(!p.isClosed()){await p.screenshot({path:path.join(output,'failure-'+i+'.png')}).catch(()=>{});console.error('WINDOW',p.url(),await p.locator('body').innerText().catch(()=>''));}}throw error;}finally{await app.close();}}
main().catch(error=>{console.error(error);process.exitCode=1});
