const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{buildSync}=require('esbuild'),{fixtures}=require('./file-tools-fixtures.cjs');
const out=path.resolve(process.env.ONE_UNIT_OUTPUT_DIR||'work','file-tools-tests');
const bundle=path.join(out,'backend.cjs');
test('file tools: real Windows files, formats, conflicts and undo',async t=>{
 await fs.mkdir(out,{recursive:true});buildSync({stdin:{contents:"export {FileToolsService} from './src/main/file-tools-service';export {renameName,defaultRename} from './src/shared/file-tools';",resolveDir:path.resolve('.')},outfile:bundle,bundle:true,platform:'node',target:'node22',external:['koffi','pdfjs-dist/legacy/build/pdf.mjs']});
 const {FileToolsService,renameName,defaultRename}=require(bundle),f=await fixtures(out),profile=await fs.mkdtemp(path.join(out,'profile-'));await fs.copyFile('dist/main/file-tools-worker.cjs',path.join(out,'file-tools-worker.cjs'));const progress=[],service=new FileToolsService(profile,(owner,p)=>progress.push(p));
 const run=task=>service.run(1,task),page=r=>service.page(r.id,0),options={...defaultRename(),search:'old',replace:'new'};
 await t.test('complete hashing distinguishes same-sized content, handles empty files and hardlinks',async()=>{const r=await run({kind:'duplicates',roots:[f.dupes,f.dupes],recursive:true,minBytes:0,extensions:''});assert.equal(r.count,2);assert.equal(r.stats.duplicateFiles,4);const groups=await page(r),large=groups.find(g=>g.size>0);assert.equal((await service.page(r.id,0,large.id)).length,2);assert.ok(r.stats.wasted>0);assert.equal(r.issueCount,0);});
 await t.test('small-file sampling is a complete hash at the 768 KiB boundary',async()=>{const root=path.join(f.files,'small-hashes'),size=768*1024,content=Buffer.alloc(size,7),changed=Buffer.from(content);changed[Math.floor(size/2)]=8;await fs.mkdir(root);await Promise.all([fs.writeFile(path.join(root,'a.bin'),content),fs.writeFile(path.join(root,'b.bin'),content),fs.writeFile(path.join(root,'c.bin'),changed)]);const r=await run({kind:'duplicates',roots:[root],recursive:false,minBytes:0,extensions:''});assert.equal(r.count,1);assert.equal(r.stats.duplicateFiles,2);assert.equal(r.stats.bytesRead,3*size);assert.equal(r.issueCount,0);});
 await t.test('sample hashes are never treated as proof of equality',async()=>{const a=Buffer.alloc(2*1024*1024,7),b=Buffer.from(a);b[400000]=8;const root=path.join(f.files,'collision');await fs.mkdir(root);await fs.writeFile(path.join(root,'a.bin'),a);await fs.writeFile(path.join(root,'b.bin'),b);const r=await run({kind:'duplicates',roots:[root],recursive:true,minBytes:0,extensions:''});assert.equal(r.count,0);assert.equal(r.issueCount,0);assert.ok(r.stats.bytesRead>4*1024*1024);});
 await t.test('dense duplicate groups stream summaries into result pages',async()=>{
  const root=path.join(f.files,'dense-duplicates');await fs.mkdir(root);const writes=[];
  for(let index=0;index<205;index++){const content=`group-${index}`;writes.push(fs.writeFile(path.join(root,`left-${String(index).padStart(3,'0')}.txt`),content),fs.writeFile(path.join(root,`right-${String(index).padStart(3,'0')}.txt`),content));}await Promise.all(writes);
  const report=await run({kind:'duplicates',roots:[root],recursive:false,minBytes:0,extensions:''});assert.equal(report.count,205);assert.equal(report.stats.streamed,1);assert.equal((await page(report)).length,100);assert.equal((await service.page(report.id,2)).length,5);assert.equal((await service.page(report.id,0,204)).length,2);
 });
 await t.test('file and folder diff',async()=>{const r=await run({kind:'diff',left:path.join(f.left,'change.txt'),right:path.join(f.right,'change.txt'),mode:'file',ignoreWhitespace:false,encoding:'自动'}),rows=await page(r);assert.equal(r.stats.addedLines,1);assert.equal(r.stats.removedLines,1);assert.ok(rows.every(r=>r.count>0&&r.leftText.length<=16000&&r.rightText.length<=16000));const dirs=await run({kind:'diff',left:f.left,right:f.right,mode:'folder',ignoreWhitespace:false,encoding:'自动'});assert.deepEqual(dirs.stats,{same:1,added:1,removed:1,modified:1,streamed:1});});
 await t.test('dense folder differences stream summary pages',async()=>{
  const left=path.join(f.files,'dense-folder-left'),right=path.join(f.files,'dense-folder-right');await Promise.all([fs.mkdir(left),fs.mkdir(right)]);const writes=[];
  for(let index=0;index<205;index++)writes.push(fs.writeFile(path.join(left,`entry-${String(index).padStart(3,'0')}.txt`),'left'));await Promise.all(writes);
  const report=await run({kind:'diff',left,right,mode:'folder',ignoreWhitespace:false,encoding:'自动'});assert.equal(report.count,205);assert.equal(report.stats.streamed,1);assert.equal((await page(report)).length,100);assert.equal((await service.page(report.id,2)).length,5);
 });
 await t.test('folder diff preserves results across concurrent small files and a large file',async()=>{
  const left=path.join(f.files,'parallel-diff-left'),right=path.join(f.files,'parallel-diff-right');await Promise.all([fs.mkdir(left),fs.mkdir(right)]);
  const writes=[];for(let i=0;i<40;i++){
   const name=`item-${String(i).padStart(2,'0')}.txt`,content=`content ${i}`;
   if(i<35)writes.push(fs.writeFile(path.join(left,name),content));
   if(i<25||i>=35)writes.push(fs.writeFile(path.join(right,name),i>=20&&i<25?`changed ${i}`:content));
  }
  const large=Buffer.alloc(1024*1024+1,17);writes.push(fs.writeFile(path.join(left,'large.bin'),large));writes.push(fs.writeFile(path.join(right,'large.bin'),large));await Promise.all(writes);
  const report=await run({kind:'diff',left,right,mode:'folder',ignoreWhitespace:false,encoding:'自动'}),rows=await page(report);
  assert.deepEqual(report.stats,{same:21,added:5,removed:10,modified:5,streamed:1});
  assert.equal(report.issueCount,0);assert.equal(report.count,20);
  assert.deepEqual(rows.reduce((groups,row)=>{groups[row.status]=(groups[row.status]||0)+1;return groups;},{}),{'修改':5,'删除':10,'新增':5});
 });
 await t.test('rename rules, Windows reserved names and literal replacements',()=>{assert.equal(renameName('old.txt',{...options,replace:'$&'},0,Date.now()),'$&.txt');assert.equal(renameName('photo_45.JPG',{...options,search:'photo_(\\d+)',replace:'image_$1_${n}',regex:true},2,Date.now()),'image_45_003.JPG');assert.throws(()=>renameName('old.txt',{...options,replace:'CON'},0,0));});
 await t.test('recursive rename, case-only rename and undo persist identities',async()=>{const preview=await run({kind:'rename-preview',paths:[f.rename],recursive:true,files:true,folders:true,options});assert.equal(preview.stats.changes,4);const applied=await run({kind:'rename-apply',report:preview.id});assert.ok(applied.receipt);assert.equal(await fs.readFile(path.join(f.rename,'new-dir','new-03.txt'),'utf8'),'third');await run({kind:'rename-undo',receipt:applied.id});assert.equal(await fs.readFile(path.join(f.rename,'old-dir','old-03.txt'),'utf8'),'third');assert.equal((await service.report(applied.id)).receipt,undefined);
 const upper=await run({kind:'rename-preview',paths:[path.join(f.rename,'old-01.txt')],recursive:false,files:true,folders:false,options:{...defaultRename(),caseMode:'upper'}});const caseOnly=await run({kind:'rename-apply',report:upper.id});assert.ok((await fs.readdir(f.rename)).includes('OLD-01.txt'));await run({kind:'rename-undo',receipt:caseOnly.id});});
 await t.test('sibling folder rename chain keeps receipt paths attached to their original ancestors',async()=>{
  const root=path.join(f.files,'rename-sibling-chain');await fs.mkdir(path.join(root,'aaa'),{recursive:true});await fs.mkdir(path.join(root,'aa'));await fs.writeFile(path.join(root,'aaa','aaa.txt'),'original aaa');await fs.writeFile(path.join(root,'aa','aa.txt'),'original aa');
  const preview=await run({kind:'rename-preview',paths:[root],recursive:true,files:true,folders:true,options:{...defaultRename(),search:'aa',replace:'a'}});assert.equal(preview.stats.changes,4);
  const applied=await run({kind:'rename-apply',report:preview.id});assert.equal(await fs.readFile(path.join(root,'aa','aa.txt'),'utf8'),'original aaa');assert.equal(await fs.readFile(path.join(root,'a','a.txt'),'utf8'),'original aa');
  const journal=(await fs.readFile(path.join(profile,applied.id,'journal.ndjson'),'utf8')).trim().split('\n').map(JSON.parse);assert.equal(journal.length,preview.stats.changes*4);for(let i=0;i<journal.length;i+=2)assert.deepEqual(journal[i].intent,journal[i+1].done);
  await run({kind:'rename-undo',receipt:applied.id});assert.equal(await fs.readFile(path.join(root,'aaa','aaa.txt'),'utf8'),'original aaa');assert.equal(await fs.readFile(path.join(root,'aa','aa.txt'),'utf8'),'original aa');
 });
 await t.test('Explorer selection renames folder itself without walking its children',async()=>{
  const parent=path.join(f.files,'shell-selection'),folder=path.join(parent,'old-dir'),file=path.join(parent,'old-file.txt');await fs.mkdir(folder,{recursive:true});await fs.writeFile(file,'selected');await fs.writeFile(path.join(folder,'old-child.txt'),'child');
  const task={kind:'rename-preview',paths:[folder,file],recursive:true,selectedOnly:true,files:true,folders:true,options};const preview=await run(task),rows=await page(preview);assert.equal(preview.stats.changes,2);assert.deepEqual(rows.map(r=>r.newName).sort(),['new-dir','new-file.txt']);assert.deepEqual(new Set(rows.map(r=>r.path)),new Set([folder,file]));
  const applied=await run({kind:'rename-apply',report:preview.id});assert.equal(await fs.readFile(path.join(parent,'new-dir','old-child.txt'),'utf8'),'child');assert.equal(await fs.readFile(path.join(parent,'new-file.txt'),'utf8'),'selected');await run({kind:'rename-undo',receipt:applied.id});assert.equal(await fs.readFile(path.join(folder,'old-child.txt'),'utf8'),'child');
  const children=await page(await run({...task,paths:[folder],selectedOnly:false}));assert.deepEqual(children.map(r=>r.path),[path.join(folder,'old-child.txt')]);await assert.rejects(run({...task,selectedOnly:'yes'}),/类型/);
 });
 await t.test('stale preview, occupied destinations and excluded selection',async()=>{const file=path.join(f.rename,'old-01.txt'),pre=()=>run({kind:'rename-preview',paths:[f.rename],recursive:false,files:true,folders:false,options});let r=await pre();await fs.appendFile(file,'changed');await assert.rejects(run({kind:'rename-apply',report:r.id}),/发生变化/);r=await pre();await fs.writeFile(path.join(f.rename,'new-01.txt'),'untouched');await assert.rejects(run({kind:'rename-apply',report:r.id}),/名称已存在/);assert.equal(await fs.readFile(path.join(f.rename,'new-01.txt'),'utf8'),'untouched');r=await pre();const rows=await page(r);assert.equal(rows.find(r=>r.name==='old-01.txt').status,'目标名称已存在');const keep=rows.find(r=>r.name==='old-02.txt');const applied=await run({kind:'rename-apply',report:r.id,excluded:rows.filter(r=>r.id!==keep.id).map(r=>r.id)});assert.equal(applied.stats.renamed,1);await run({kind:'rename-undo',receipt:applied.id});});
 await t.test('integrity verification pages dense changes without retaining result rows in the worker',async()=>{
  const root=path.join(f.files,'integrity-stream');await fs.mkdir(root);const entries=[];
  for(let index=0;index<205;index++){const name=`entry-${String(index).padStart(3,'0')}.txt`;entries.push({path:name,size:1,sha256:'0'.repeat(64)});await fs.writeFile(path.join(root,name),'');}
  const manifest=path.join(root,'one-integrity-stream.sha256.json');await fs.writeFile(manifest,JSON.stringify({format:'one-integrity',version:1,algorithm:'sha256',created:Date.now(),entries}));
  const report=await run({kind:'integrity-verify',manifest});assert.equal(report.count,205);assert.equal(report.stats.streamed,1);assert.equal((await page(report)).length,100);assert.equal((await service.page(report.id,2)).length,5);
 });
 await t.test('document body indexing: UTF8, GBK, UTF16, Word, PPT, Excel, EPUB and PDF',async()=>{const r=await run({kind:'document-index',roots:[f.docs],recursive:true,extensions:''});assert.equal(r.issueCount,0,JSON.stringify(r.issues));assert.equal(r.stats.indexed,8);const chinese=await run({kind:'document-search',roots:[f.docs],query:'银河探险'});assert.equal(chinese.stats.files,7);const short=await run({kind:'document-search',roots:[f.docs],query:'银河'});assert.equal(short.stats.files,7);const pdf=await run({kind:'document-search',roots:[f.docs],query:'galaxy exploration'});assert.equal(pdf.stats.files,1);assert.equal((await page(pdf))[0].page,1);const cached=await run({kind:'document-index',roots:[f.docs],recursive:true,extensions:''});assert.equal(cached.stats.cached,8);assert.equal(cached.stats.indexed,0);await fs.writeFile(path.join(f.docs,'utf8.txt'),'新的正文 唯一标记');await run({kind:'document-index',roots:[f.docs],recursive:true,extensions:''});assert.equal((await run({kind:'document-search',roots:[f.docs],query:'唯一标记'})).stats.files,1);assert.equal((await run({kind:'document-search',roots:[f.docs],query:'银河'})).stats.files,6);await fs.unlink(path.join(f.docs,'gbk.txt'));await run({kind:'document-index',roots:[f.docs],recursive:true,extensions:''});assert.equal((await run({kind:'document-search',roots:[f.docs],query:'银河'})).stats.files,5);});
 await t.test('saving a rename cannot be terminated; stop drains its transaction',async()=>{const preview=await run({kind:'rename-preview',paths:[path.join(f.rename,'old-02.txt')],recursive:false,files:true,folders:false,options});const pending=run({kind:'rename-apply',report:preview.id});while(!service.busyTransactions)await new Promise(r=>setTimeout(r,1));assert.throws(()=>service.cancel(1,'rename-apply'),/等待完成/);await service.stop();const applied=await pending;assert.equal(await fs.readFile(path.join(f.rename,'new-02.txt'),'utf8'),'second');assert.ok(applied.receipt);});
 assert.ok(progress.some(p=>p.phase==='已完成'));await service.stop();await fs.writeFile(path.join(out,'last-fixtures.json'),JSON.stringify(f));
});
