const {spawn,execFile}=require('node:child_process'),{promisify}=require('node:util'),path=require('node:path'),assert=require('node:assert/strict'),fs=require('node:fs/promises');
const exe=process.env.ONE_LEVELS_EXE||path.resolve('dist/native/One.Levels.exe');
async function run(){const commands=['u 1 0 0 150 200','u 1 0 149 150 200','u 1 0 150 150 200','u 1 0 1000 150 200','u 1 -1 1001 150 200','u 1 0 1002 150 200','suppress','u 1 0 1300 150 200','u 1 -1 1301 150 200','u 2 3 1302 150 200','u 2 3 1452 150 200','reset','u 2 3 1460 150 200','u 2 3 1610 150 200','u 2 3 1660 150 200','reset','suppress','u 3 0 1800 150 200','u 3 0 2000 150 200','u 3 -1 2001 150 200','u 3 0 2002 150 200','u 3 0 2152 150 200'];const corners=await new Promise((resolve,reject)=>{const child=spawn(exe,['--test-corners'],{windowsHide:true});let result='';child.stdout.on('data',data=>result+=data);child.on('error',reject);child.on('exit',code=>code?reject(Error('corner test exited '+code)):resolve(result.trim().split(/\s+/).map(Number)));child.stdin.end(commands.join('\n')+'\n');});assert.deepEqual(corners,[0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1]);
 const child=spawn(exe,[],{windowsHide:true});let buffer='',seq=0;const pending=new Map();child.stdout.on('data',part=>{buffer+=part;let at;while((at=buffer.indexOf('\n'))>=0){const message=JSON.parse(buffer.slice(0,at));buffer=buffer.slice(at+1);const item=pending.get(message.id);if(item){clearTimeout(item.timer);pending.delete(message.id);item.done(message);}}});const request=(action,read=1)=>new Promise(done=>{const id=++seq,timer=setTimeout(()=>{pending.delete(id);done({error:'timeout'});},12000);pending.set(id,{done,timer});child.stdin.write(`${action} ${id} 100 100 0 ${read}\n`);});
 try{const t=performance.now(),first=await request('volume'),cold=performance.now()-t;assert.ok(first.result?.supported,JSON.stringify(first));const times=[];for(let i=0;i<20;i++){const t=performance.now(),value=await request('volume');assert.ok(value.result.brightness>=0&&value.result.brightness<=100);times.push(performance.now()-t);}const start=performance.now(),panel=await request('brightness'),probeMs=performance.now()-start;assert.ok(panel.result?.supported,JSON.stringify(panel));const cachedStart=performance.now(),cached=await request('brightness',0),cachedMs=performance.now()-cachedStart;assert.equal(cached.result.brightness,panel.result.brightness);
  const output={result:'PASS',cornerDwellCooldownSuppression:true,physicalMonitorRead:panel.result,volumeColdMs:Math.round(cold),volumeMeanMs:+(times.reduce((a,b)=>a+b)/times.length).toFixed(2),brightnessProbeMs:+probeMs.toFixed(2),brightnessCachedMs:+cachedMs.toFixed(2),systemValuesChanged:false};await fs.mkdir('work/search-presentation',{recursive:true});await fs.writeFile('work/search-presentation/levels-native.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));
 }finally{child.stdin.end('stop\n');const timer=setTimeout(()=>child.kill(),2500);timer.unref();for(const item of pending.values())clearTimeout(item.timer);}
}
run().catch(error=>{console.error(error);process.exitCode=1;});
