const {test}=require('node:test'),assert=require('node:assert/strict'),{build}=require('esbuild');
async function moduleFor(file,loader=require){const bundle=await build({entryPoints:[file],bundle:true,platform:'node',format:'cjs',write:false,external:['electron']});const m={exports:{}};new Function('module','exports','require','__dirname',bundle.outputFiles[0].text)(m,m.exports,loader,process.cwd());return m.exports;}
const item=(id,target,kind='builtin',parent='')=>({id,target,kind,parent,label:id,args:[],cwd:'',icon:'star',enabled:true});
test('收藏从隐式项目迁移一次，保留用户顺序，删除或隐藏后不再注入',async()=>{
 const {defaultSearch,validateSearch,bookmarkMenuItem}=await moduleFor('src/shared/search.ts');let settings=defaultSearch();settings.bookmarks=['C:\\Users','D:\\Projects'];settings.menu=[item('custom','copy-path'),item('default-bookmarks','','group')];delete settings.menuVersion;
 settings=validateSearch(settings);assert.deepEqual(settings.menu.map(item=>item.id),['custom','default-bookmarks','default-bookmarks-1']);assert.equal(settings.menu.at(-1).target,'bookmarks');assert.deepEqual(validateSearch(settings),settings);
 settings.menu=settings.menu.filter(item=>item.target!=='bookmarks');assert.equal(validateSearch(settings).menu.length,2);
 const hidden=bookmarkMenuItem('hidden-favorites');hidden.enabled=false;delete settings.menuVersion;settings.menu.push(hidden);assert.equal(validateSearch(settings).menu.filter(item=>item.target==='bookmarks').length,1);assert.equal(validateSearch(settings).menu.at(-1).enabled,false);
 assert.throws(()=>validateSearch({...settings,menuBar:{position:'left',actions:[]}}));assert.throws(()=>validateSearch({...settings,menuBar:{position:'top',actions:['builtin:unknown']}}));assert.throws(()=>validateSearch({...settings,menuBar:{position:'bottom',actions:Array(8).fill('favorite')}}));
 assert.deepEqual(validateSearch({...settings,menuBar:{position:'top',actions:['favorite','favorite','item:deleted','builtin:copy-path']}}).menuBar,{top:{actions:['favorite','builtin:copy-path'],right:[]},bottom:{actions:[],right:[]}});
 const both={top:{actions:['favorite','item:deleted'],right:[]},bottom:{actions:['favorite','builtin:settings'],right:['builtin:settings']}};assert.deepEqual(validateSearch({...settings,menuBar:both}).menuBar,{top:{actions:['favorite'],right:[]},bottom:{actions:['builtin:settings'],right:['builtin:settings']}});
 assert.throws(()=>validateSearch({...settings,menuBar:{top:{actions:[],right:['favorite']},bottom:{actions:[],right:[]}}}));
});
test('收藏由管理位置生成，操作栏复用菜单、上下文与危险动作确认',async()=>{
 const copied=[],launched=[],prompts=[],loader=id=>id==='electron'?{shell:{},clipboard:{writeText:path=>copied.push(path)}}:require(id);
 const {SearchMenu}=await moduleFor('src/main/search-menu.ts',loader),{defaultSearch}=await moduleFor('src/shared/search.ts');let config=defaultSearch();config.bookmarks=['C:\\Users','D:\\Projects'];config.menu=[item('first','copy-path'),item('group','','group'),item('favorites','bookmarks','builtin','group'),item('last','search'),{...item('sep','','separator'),label:''}];config.menuBar={top:{actions:['favorite','builtin:copy-path','item:group','builtin:shutdown'],right:['builtin:shutdown']},bottom:{actions:['item:sep','builtin:settings'],right:[]}};let confirmed=false;
 const menu=new SearchMenu('work/current/unit/nonexistent-bookmarks-history.json',()=>config,{},()=>{},()=>{},async(...args)=>launched.push(args),async command=>{prompts.push(command.id);return confirmed;});
 const context={kind:'menu',hwnd:0,pid:0,created:'',folders:[],currentFolder:'D:\\工作目录 & $()'};let nodes=await menu.open(context);assert.deepEqual(nodes.map(item=>item.label),['first','last']);
 const bar=menu.toolbar();assert.equal(bar.top.length,4);assert.equal(bar.top[3].align,'right');assert.equal(bar.bottom.length,2);assert.equal(bar.bottom[0].kind,'separator');await assert.rejects(()=>menu.execute(bar.bottom[0].id));assert.deepEqual((await menu.children(bar.top[2].children[0].id)).map(item=>item.path),config.bookmarks);await menu.execute(bar.top[1].id);assert.deepEqual(copied,[context.currentFolder]);await menu.execute(bar.top[3].id);assert.equal(launched.length,0);confirmed=true;await menu.execute(bar.top[3].id);assert.deepEqual(prompts,['shutdown','shutdown']);assert.deepEqual(launched[0][1],['/s','/t','0']);
 config.menu[1].enabled=false;nodes=await menu.open(context);assert.deepEqual(nodes.map(item=>item.label),['first','last']);assert.equal(menu.toolbar().top.length,3);
 config.menu=config.menu.filter(item=>item.target!=='bookmarks');nodes=await menu.open(context);assert.equal(nodes.some(item=>item.label==='收藏文件夹'),false);
});
