const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict'),{execFile}=require('node:child_process'),{promisify}=require('node:util');
async function run(){
 const out=path.resolve(process.env.ONE_TEST_OUTPUT_DIR||'work/current/picker-smoke');await fs.mkdir(out,{recursive:true});const profile=await fs.mkdtemp(path.join(out,'profile-')),files=await fs.mkdtemp(path.join(out,'files-')),many=path.join(files,'many'),child=path.join(files,'子目录');
 await fs.mkdir(many);await fs.mkdir(child);for(const name of ['file2.txt','file10.txt','.visible.txt','hidden.txt'])await fs.writeFile(path.join(files,name),name);await promisify(execFile)('attrib',['+h',path.join(files,'hidden.txt')],{windowsHide:true});
 for(let start=0;start<10000;start+=100)await Promise.all(Array.from({length:100},(_,i)=>fs.mkdir(path.join(many,'folder'+String(start+i).padStart(5,'0')))));
 const env={...process.env,ONE_TEST_MODE:'1',ONE_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;let app,errors=[],timings={},nativeOpened;
 async function launch(){
  app=await electron.launch({args:[path.resolve('.')],env});app.process().stderr?.on('data',chunk=>console.error(String(chunk)));app.process().once('exit',(code,signal)=>console.log('isolated app exit',code,signal));app.on('window',p=>{p.on('pageerror',e=>errors.push(String(e)));p.on('crash',()=>console.error('renderer crash',p.url()));p.on('close',()=>console.log('window closed',p.url()));});const page=await app.firstWindow();await page.waitForSelector('#overview-index');
  // Offscreen windows are occluded by Windows. Disable test-only background
  // throttling to measure active UI response without moving focus on the desktop.
  await app.evaluate(({BrowserWindow})=>{global.createdPickerBounds=[];BrowserWindow.prototype.focus=function(){};BrowserWindow.prototype.show=function(){if(this.webContents.getURL().includes('view=picker'))global.createdPickerBounds.push(this.getBounds());this.webContents.setBackgroundThrottling(false);this.setPosition(-10000,-10000);this.showInactive();};const main=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=main'));main.webContents.setBackgroundThrottling(false);main.setBounds({x:-10000,y:-10000,width:1250,height:900});main.showInactive();});return page;
 }
 let page=await launch();
 async function open(mode,initial){const opening=app.waitForEvent('window');await page.evaluate(({mode,initial})=>{window.pickerResult='pending';const result=mode==='save'?window.one.saveText('replacement','UTF-8'):mode==='file'?window.one.pickFile(initial):window.one.pickDirectory(initial);result.then(value=>window.pickerResult=value).catch(error=>window.pickerResult='error:'+error);},{mode,initial});const picker=await opening;await picker.waitForSelector('#picker-list');await expect(picker.locator('#picker-list')).toHaveAttribute('aria-busy','false');return picker;}
 async function goto(picker,location){await picker.locator('#picker-path').fill(location);await picker.locator('#picker-go').click();await expect(picker.locator('#picker-list')).toHaveAttribute('aria-busy','false');await expect(picker.locator('#picker-path')).toHaveValue(location);}
 async function options(picker,id){await picker.locator('#picker-options-button').click();await picker.locator('#'+id).click();await expect(picker.locator('#picker-list')).toHaveAttribute('aria-busy','false');}
 try{
  await page.locator('[data-page=tools]').click();await page.locator('#duplicates-root').fill(files);await expect(page.locator('#duplicates-root')).toHaveValue(files);await page.screenshot({path:path.join(out,'path-field.png')});
  const dimensions=await page.locator('#duplicates-root').evaluate(input=>{const wrapper=input.closest('.one-path-field'),icon=wrapper.querySelector('.one-path-field-icon'),button=wrapper.querySelector('.one-path-field-action'),r=wrapper.getBoundingClientRect(),b=button.getBoundingClientRect(),s=icon.getBoundingClientRect();return{left:s.left-r.left,right:r.right-b.right,inputBorder:getComputedStyle(input).borderWidth,buttonHeight:b.height,fieldHeight:r.height};});assert.ok(dimensions.left<=13);assert.ok(dimensions.right<=2);assert.equal(dimensions.inputBorder,'0px');assert.ok(Math.abs(dimensions.fieldHeight-dimensions.buttonHeight)<=2);
  const opening=app.waitForEvent('window'),at=Date.now();await page.locator('[data-tool-folder=duplicates-root]').click();let picker=await opening;await expect(picker.locator('#picker-list')).toHaveAttribute('aria-busy','false');await expect(picker.locator('#picker-path')).toHaveValue(files);await expect(picker.getByRole('option')).toHaveCount(2);timings.folderFirstPaint=Date.now()-at;
  await expect(picker.locator('#picker-common [data-place]')).toHaveCount(6);await expect(picker.locator('#picker-opened')).not.toContainText('正在获取',{timeout:10000});nativeOpened=await picker.evaluate(()=>window.one.pickerOpened());assert.equal(nativeOpened.error,'');assert.ok(nativeOpened.places.every(item=>path.isAbsolute(item.path)));
  await expect(picker.locator('.windows-file-icon').first()).toBeVisible();await picker.screenshot({path:path.join(out,'directory-picker.png')});await picker.getByRole('option',{name:'子目录',exact:true}).click();await picker.locator('#picker-confirm').click();
  await expect(page.locator('#duplicates-root')).toHaveValue(child);
  picker=await open('file',files);await expect(picker.getByRole('option',{name:'hidden.txt',exact:true})).toHaveCount(0);await expect(picker.getByRole('option',{name:'.visible.txt',exact:true})).toBeVisible();
  await options(picker,'picker-hidden');await expect(picker.getByRole('option',{name:'hidden.txt',exact:true})).toBeVisible();await options(picker,'picker-extensions');await expect(picker.getByRole('option',{name:'file2.txt',exact:true}).locator('.picker-entry-name')).toHaveText('file2');
  await picker.getByRole('option',{name:'file2.txt',exact:true}).click();await expect(picker.locator('#picker-name')).toHaveValue('file2.txt');await expect(picker.locator('#picker-list')).toHaveAttribute('aria-activedescendant',/picker-option-/);
  await picker.locator('#picker-options-button').click();await picker.keyboard.press('Escape');await expect(picker.locator('#picker-options')).toBeHidden();await expect(picker.locator('#picker-list')).toBeVisible();
  await picker.locator('#picker-confirm').click();await expect.poll(()=>page.evaluate(()=>window.pickerResult)).toBe(path.join(files,'file2.txt'));
  picker=await open('directory',files);await expect(picker.locator('#picker-recent [data-place]')).toHaveCount(2);const before=await picker.evaluate(()=>document.querySelector('#picker-path').value);await picker.locator('#picker-recent-clear').click();await expect(picker.locator('#picker-recent [data-place]')).toHaveCount(0);assert.equal(await picker.locator('#picker-path').inputValue(),before);
  // Actual native resizing is kept offscreen; restoration must clamp that old position.
  const resized=await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=picker'));w.setBounds({x:-10000,y:-10000,width:940,height:680});return w.getBounds();});await picker.locator('#picker-cancel').click();await expect.poll(()=>page.evaluate(()=>window.pickerResult)).toBe(null);
  const saved=JSON.parse(await fs.readFile(path.join(profile,'picker-state.json'),'utf8'));assert.deepEqual(saved.recent,[]);assert.deepEqual(saved.bounds,resized);
  await app.close();page=await launch();picker=await open('file',files);const created=await app.evaluate(()=>global.createdPickerBounds.at(-1));assert.equal(created.width,saved.bounds.width);assert.equal(created.height,saved.bounds.height);assert.ok(created.x>=-3000&&created.y>=-1000,'disconnected/offscreen coordinates are clamped');await expect(picker.getByRole('option',{name:'hidden.txt',exact:true})).toBeVisible();await expect(picker.getByRole('option',{name:'file2.txt',exact:true}).locator('.picker-entry-name')).toHaveText('file2');
  await picker.locator('#picker-options-button').click();await picker.screenshot({path:path.join(out,'display-options.png')});await picker.keyboard.press('Escape');
  await picker.getByRole('option',{name:'子目录',exact:true}).dblclick();await expect(picker.locator('#picker-path')).toHaveValue(child);await picker.locator('#picker-back').click();await expect(picker.locator('#picker-path')).toHaveValue(files);await picker.locator('#picker-forward').click();await expect(picker.locator('#picker-path')).toHaveValue(child);await picker.locator('#picker-up').click();await expect(picker.locator('#picker-path')).toHaveValue(files);
  await picker.locator('#picker-path').fill(path.join(files,'missing'));await picker.locator('#picker-go').click();await expect(picker.locator('#picker-status')).toHaveText('无法读取目录');await expect(picker.locator('#picker-path')).toHaveValue(files);await expect(picker.getByRole('option',{name:'file2.txt',exact:true})).toBeVisible();
  await picker.locator('#picker-cancel').click();picker=await open('directory',many);await expect(picker.locator('#picker-list')).toHaveAttribute('data-count','10000');assert.ok(await picker.getByRole('option').count()<45);await picker.locator('#picker-list').focus();const end=Date.now();await picker.keyboard.press('End');await expect(picker.getByRole('option',{name:'folder09999',exact:true})).toHaveAttribute('aria-selected','true');timings.end=Date.now()-end;
  await picker.locator('#picker-filter').fill('folder05001');await expect(picker.getByRole('option')).toHaveCount(1);await expect(picker.getByRole('option')).toHaveAttribute('aria-label','folder05001');await picker.locator('#picker-filter').fill('');await expect(picker.locator('#picker-list')).toHaveAttribute('data-count','10000');
  for(const [theme,width,height]of [['light',620,500],['dark',860,640]]){await app.evaluate(({BrowserWindow},size)=>{BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('view=picker')).setBounds({x:-10000,y:-10000,...size});},{width,height});await page.evaluate(mode=>window.one.patchSettings({appearance:{mode}}),theme);await expect(picker.locator('html')).toHaveAttribute('data-theme',theme);const layout=await picker.evaluate(()=>[...document.querySelectorAll('.picker-toolbar,.picker-footer,.picker-content,.picker-browser')].map(node=>({width:node.clientWidth,scroll:node.scrollWidth,height:node.clientHeight})));assert.ok(layout.every(x=>x.width>=x.scroll&&x.height>0));await picker.screenshot({path:path.join(out,'large-'+theme+'.png')});}
  await picker.locator('#picker-cancel').click();picker=await open('save');await goto(picker,files);await picker.locator('#picker-name').fill('file2.txt');await picker.locator('#picker-confirm').click();await expect(picker.locator('#overwrite-dialog')).toBeVisible();await picker.keyboard.press('Escape');await expect(picker.locator('#overwrite-dialog')).not.toBeVisible();assert.equal(await fs.readFile(path.join(files,'file2.txt'),'utf8'),'file2.txt');await picker.locator('#picker-confirm').click();await picker.locator('#overwrite-confirm').click();await expect.poll(()=>page.evaluate(()=>window.pickerResult)).toBe(path.join(files,'file2.txt'));assert.equal(await fs.readFile(path.join(files,'file2.txt'),'utf8'),'replacement');
  assert.deepEqual(errors,[]);const result={result:'PASS',timings,nativeExplorerDirectories:nativeOpened.places.length,recentLimit:20,clearRecent:true,geometryRestore:true,hiddenWindowsAttributes:true,extensions:true,largeDirectoryItems:10000,keyboardFiltering:true,overwriteAndCancel:true,errors};await fs.writeFile(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{if(app)await app.close();}
}
run().catch(error=>{console.error(error);process.exitCode=1});
