const {_electron:electron,expect}=require('@playwright/test'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
async function run(){const output=path.resolve('work/preferences-smoke');await fs.mkdir(output,{recursive:true});const profile=await fs.mkdtemp(path.join(output,'profile-')),env={...process.env,ONE_TEST_MODE:'1',ONE_DATA_DIR:profile};delete env.ELECTRON_RUN_AS_NODE;
 const launch=()=>electron.launch(process.env.ONE_PACKAGED_EXE?{executablePath:process.env.ONE_PACKAGED_EXE,args:[],env}:{args:[path.resolve('.')],env});let app=await launch();const errors=[];
 try{let page=await app.firstWindow();page.on('pageerror',e=>errors.push(String(e)));await page.waitForSelector('[data-page=text]');await page.locator('[data-page=text]').click();await page.waitForSelector('#source');
  const widths=[];for(const id of ['text','disk','system','input','preview','color','search','settings']){await page.locator(`[data-page=${id}]`).click();widths.push(await page.locator(`#page-${id}`).evaluate(e=>e.getBoundingClientRect().width));assert.equal(await page.getByRole('button',{name:/^保存设置$|^保存外观$/}).count(),0);}assert.equal(new Set(widths).size,1);assert.equal(await page.locator('.sidebar-bottom').count(),0);
  await page.locator('[data-settings-tab=appearance]').click();await page.locator('[data-mode=dark]').click();await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).appearance.mode)).toBe('dark');await page.screenshot({path:path.join(output,'settings-dark.png'),animations:'disabled'});await page.locator('[data-mode=light]').click();await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).appearance.mode)).toBe('light');await page.screenshot({path:path.join(output,'settings-light.png'),animations:'disabled'});
  await page.evaluate(()=>Promise.all([{general:{closeToTray:false}},{appearance:{radius:12}},{colorFormat:'rgb'},{search:{pinyin:false}},{utilities:{topmost:{border:false}}}].map(p=>window.one.patchSettings(p))));const merged=await page.evaluate(()=>window.one.settings());assert.equal(merged.general.closeToTray,false);assert.equal(merged.appearance.mode,'light');assert.equal(merged.appearance.radius,12);assert.equal(merged.colorFormat,'rgb');assert.equal(merged.search.pinyin,false);assert.equal(merged.utilities.topmost.border,false);
  const rejected=await page.evaluate(()=>window.one.patchSettings(JSON.parse('{"__proto__":{"polluted":true}}')).then(()=>false,()=>true));assert.equal(rejected,true);assert.equal((await page.evaluate(()=>window.one.settings())).appearance.radius,12);
  await page.locator('[data-page=input]').click();await page.locator('#dwellMs').fill('820');await page.locator('#dwellMs').blur();await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).dwellMs)).toBe(820);await page.locator('#excludedApps').fill('sample.exe');await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).excludedApps)).toBe('sample.exe');await page.locator('#dwellMs').focus();assert.equal(await page.locator('#dwellMs').evaluate(e=>getComputedStyle(e).outlineStyle),'none');assert.equal(await page.locator('#dwellMs').evaluate(e=>getComputedStyle(e.parentElement).outlineStyle),'none');
  await page.locator('[data-page=search]').click();await page.locator('#search-pinyin').uncheck();await page.locator('#search-pinyin').check();await expect.poll(()=>page.evaluate(async()=>(await window.one.settings()).search.pinyin)).toBe(true);await page.screenshot({path:path.join(output,'search-settings.png'),animations:'disabled'});
  await page.locator('#search-tab-menu').click();await page.locator('#menu-add').click();await page.locator('#menu-label').fill('开发工具');await page.locator('#menu-icon').click();await expect(page.locator('.icon-picker-dialog')).toBeVisible();await page.locator('#icon-picker-query').fill('code');await page.getByRole('option',{name:'code',exact:true}).click();await expect(page.locator('.icon-picker-dialog')).toHaveCount(0);await page.locator('#menu-create').click();await expect(page.getByRole('button',{name:'开发工具',exact:true})).toBeVisible();
  let settings=await page.evaluate(()=>window.one.settings());const group=settings.search.menu.find(i=>i.label==='开发工具');assert.equal(group.icon,'lucide:code');await page.locator(`[data-child="${group.id}"]`).click();await page.locator('#menu-label').fill('常用目录');await page.locator('#menu-create').click();await expect(page.getByRole('button',{name:'常用目录',exact:true})).toBeVisible();settings=await page.evaluate(()=>window.one.settings());const child=settings.search.menu.find(i=>i.label==='常用目录');assert.equal(child.parent,group.id);
  await page.locator('#menu-label').fill('本地目录');await page.locator('#menu-label').blur();await expect.poll(()=>page.evaluate(id=>window.one.settings().then(s=>s.search.menu.find(i=>i.id===id).label),child.id)).toBe('本地目录');await page.locator('[data-enabled="'+child.id+'"]').click();await expect.poll(()=>page.evaluate(id=>window.one.settings().then(s=>s.search.menu.find(i=>i.id===id).enabled),child.id)).toBe(false);
  await page.locator(`[data-collapse="${group.id}"]`).click();await expect(page.locator(`[data-menu-id="${child.id}"]`)).toHaveCount(0);await page.locator(`[data-collapse="${group.id}"]`).click();await expect(page.locator(`[data-menu-id="${child.id}"]`)).toBeVisible();await page.screenshot({path:path.join(output,'nested-menu.png'),animations:'disabled'});await page.locator('#menu-icon').click();await page.locator('#icon-picker-query').fill('文件夹');await expect(page.locator('.icon-choice')).not.toHaveCount(0);await page.screenshot({path:path.join(output,'icon-picker.png'),animations:'disabled'});await page.locator('#icon-picker-close').click();
  await page.locator('#sidebar-toggle').click();await expect.poll(()=>page.locator('.sidebar').evaluate(e=>Math.round(e.getBoundingClientRect().width))).toBe(60);assert.notEqual(await page.locator('.shell').evaluate(e=>getComputedStyle(e).transitionDuration),'0s');await page.locator('#sidebar-toggle').click();
  const saved=JSON.parse(await fs.readFile(path.join(profile,'settings.json'),'utf8'));assert.equal(saved.dwellMs,820);assert.equal(saved.search.menu.find(i=>i.id===child.id).label,'本地目录');await app.close();app=await launch();page=await app.firstWindow();await page.waitForSelector('[data-page=text]');await page.locator('[data-page=text]').click();await page.waitForSelector('#source');const restored=await page.evaluate(()=>window.one.settings());assert.equal(restored.general.closeToTray,false);assert.equal(restored.dwellMs,820);assert.equal(restored.search.menu.find(i=>i.id===group.id).icon,'lucide:code');assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',equalPageWidths:true,autosave:true,concurrentPatches:true,restartPersistence:true,nestedMenu:true,lucidePicker:true,restrainedFocus:true,animatedSidebar:true,output}));
 }finally{await app.close();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
