const {test}=require('node:test'),assert=require('node:assert/strict');
const {buildSync}=require('esbuild');
const code=buildSync({entryPoints:['src/shared/preview.ts'],bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;
const moduleValue={exports:{}};new Function('module','exports',code)(moduleValue,moduleValue.exports);const {defaultPreview,validatePreview,parseLyrics,textExtensions,decodePreviewText}=moduleValue.exports;
test('old preferences migrate; preview widths and boolean flags are bounded',()=>{assert.deepEqual(validatePreview(undefined),defaultPreview());assert.throws(()=>validatePreview({...defaultPreview(),held:'true'}));assert.throws(()=>validatePreview({...defaultPreview(),leftWidth:90000}));assert.throws(()=>validatePreview({...defaultPreview(),leftTab:'unknown'}));assert.equal(validatePreview({...defaultPreview(),pinned:true,leftWidth:320}).pinned,true);});
test('former right details pane migrates into the unified sidebar',()=>{const next=validatePreview({...defaultPreview(),files:false,details:true,rightWidth:276});assert.equal(next.files,true);assert.equal(next.leftTab,'details');assert.equal('details'in next,false);for(const leftTab of ['files','details','outline','overview'])assert.equal(validatePreview({...defaultPreview(),leftTab}).leftTab,leftTab);});
test('LRC handles repeated timestamps and offset; plain lyrics remain readable',()=>{assert.deepEqual(parseLyrics('[offset:100]\n[00:01.00][00:03.00]副歌\n[00:02.00]正文'),[{time:1.1,text:'副歌'},{time:2.1,text:'正文'},{time:3.1,text:'副歌'}]);assert.deepEqual(parseLyrics('一行\n二行'),[{time:-1,text:'一行'},{time:-1,text:'二行'}]);});
test('code extensions include common languages and configuration formats',()=>{for(const ext of ['toml','ini','py','go','rs','tsx','vue','ps1','tf','nix','jsonc','yml','kt','swift','lua','sql','graphql','proto','tex','diff'])assert.equal(textExtensions.test(ext),true,ext);assert.equal(textExtensions.test('exe'),false);});
test('preview byte decoding preserves UTF-16 BOM text and rejects invalid or oversized input',()=>{assert.equal(decodePreviewText(Buffer.from('中文\n代码')),'中文\n代码');const little=Buffer.concat([Buffer.from([255,254]),Buffer.from('中文\n代码','utf16le')]);assert.equal(decodePreviewText(little),'中文\n代码');const big=Buffer.from(little);big.swap16();assert.equal(decodePreviewText(big),'中文\n代码');assert.throws(()=>decodePreviewText(Buffer.from([255,255])));assert.throws(()=>decodePreviewText(new Uint8Array(50*1024*1024+1)),/50 MB/);});
