#define NOMINMAX
#include <windows.h>
#include <ole2.h>
#include <wrl/client.h>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
#include <memory>
#include <algorithm>
using Microsoft::WRL::ComPtr;
HWND host,edit,secret,custom,nonText;int copyCommands=0;WNDPROC nonTextProc;std::wstring customText=L"Custom rendered selection fixture";int customFirst=0,customLast=0;bool customDragging=false;WNDPROC editProc,secretProc;int wheel=0,horizontal=0,middle=0,right=0,pastes=0;
std::string json(std::wstring value){int n=WideCharToMultiByte(CP_UTF8,0,value.data(),(int)value.size(),nullptr,0,nullptr,nullptr);std::string bytes(n,0);WideCharToMultiByte(CP_UTF8,0,value.data(),(int)value.size(),bytes.data(),n,nullptr,nullptr);std::string out="\"";for(auto c:bytes){if(c=='\\'||c=='"')out+='\\';if(c=='\r')out+="\\r";else if(c=='\n')out+="\\n";else out+=c;}return out+'"';}
void count(UINT m,WPARAM wp){if(m==WM_KEYDOWN&&wp=='C'&&(GetKeyState(VK_CONTROL)&0x8000))copyCommands++;if(m==WM_MOUSEWHEEL)wheel+=(SHORT)HIWORD(wp);if(m==WM_MOUSEHWHEEL)horizontal+=(SHORT)HIWORD(wp);if(m==WM_MBUTTONDOWN)middle++;if(m==WM_RBUTTONDOWN)right++;if(m==WM_PASTE)pastes++;}
LRESULT CALLBACK control(HWND w,UINT m,WPARAM wp,LPARAM lp){count(m,wp);if(m==WM_MOUSEWHEEL||m==WM_MOUSEHWHEEL)return 0;return CallWindowProcW(w==edit?editProc:w==secret?secretProc:nonTextProc,w,m,wp,lp);}
LRESULT CALLBACK customProc(HWND w,UINT m,WPARAM wp,LPARAM lp){count(m,wp);if(m==WM_PAINT){PAINTSTRUCT p{};auto dc=BeginPaint(w,&p);TextOutW(dc,5,5,customText.c_str(),(int)customText.size());EndPaint(w,&p);return 0;}if(m==WM_LBUTTONDOWN){SetFocus(w);customFirst=customLast=std::clamp(((int)(short)LOWORD(lp)-5)/8,0,(int)customText.size());customDragging=true;SetCapture(w);return 0;}if(m==WM_MOUSEMOVE&&customDragging){customLast=std::clamp(((int)(short)LOWORD(lp)-5)/8,0,(int)customText.size());return 0;}if(m==WM_LBUTTONUP){customDragging=false;ReleaseCapture();return 0;}if(m==WM_LBUTTONDBLCLK){customFirst=0;customLast=(int)customText.size();return 0;}if(m==WM_KEYDOWN&&wp=='C'&&(GetKeyState(VK_CONTROL)&0x8000)&&customFirst!=customLast){auto value=customText.substr(std::min(customFirst,customLast),std::abs(customLast-customFirst));auto memory=GlobalAlloc(GMEM_MOVEABLE,(value.size()+1)*sizeof(wchar_t));auto data=GlobalLock(memory);memcpy(data,value.c_str(),(value.size()+1)*sizeof(wchar_t));GlobalUnlock(memory);if(OpenClipboard(w)){EmptyClipboard();SetClipboardData(CF_UNICODETEXT,memory);CloseClipboard();}else GlobalFree(memory);return 0;}return DefWindowProcW(w,m,wp,lp);}
void state(){RECT r{},e{},s{},c{},n{};GetWindowRect(custom,&c);GetWindowRect(nonText,&n);GetWindowRect(host,&r);GetWindowRect(edit,&e);GetWindowRect(secret,&s);wchar_t text[4096]{};GetWindowTextW(edit,text,4096);DWORD first=0,last=0;SendMessageW(edit,EM_GETSEL,(WPARAM)&first,(LPARAM)&last);std::wstring selected=std::wstring(text).substr(std::min<DWORD>(first,wcslen(text)),std::min<DWORD>(last,wcslen(text))-std::min<DWORD>(first,wcslen(text)));std::cout<<"{\"nonTextX\":"<<n.left<<",\"nonTextY\":"<<n.top<<",\"copyCommands\":"<<copyCommands<<",\"customX\":"<<c.left<<",\"customY\":"<<c.top<<",\"customSelected\":"<<json(customText.substr(std::min(customFirst,customLast),std::abs(customLast-customFirst)))<<",\"window\":"<<(uintptr_t)host<<",\"edit\":"<<(uintptr_t)edit<<",\"password\":"<<(uintptr_t)secret<<",\"x\":"<<r.left<<",\"y\":"<<r.top<<",\"width\":"<<r.right-r.left<<",\"height\":"<<r.bottom-r.top<<",\"editX\":"<<e.left<<",\"editY\":"<<e.top<<",\"passwordX\":"<<s.left<<",\"passwordY\":"<<s.top<<",\"wheel\":"<<wheel<<",\"horizontal\":"<<horizontal<<",\"middle\":"<<middle<<",\"right\":"<<right<<",\"pastes\":"<<pastes<<",\"caps\":"<<((GetKeyState(VK_CAPITAL)&1)?"true":"false")<<",\"text\":"<<json(text)<<",\"selected\":"<<json(selected)<<"}"<<std::endl;}
LRESULT CALLBACK windowProc(HWND w,UINT m,WPARAM wp,LPARAM lp){if(m==WM_APP){std::unique_ptr<std::string> command((std::string*)lp);std::istringstream in(*command);std::string op;in>>op;if(op=="focus")SetFocus(edit);else if(op=="password")SetFocus(secret);else if(op=="select"){int a=0,b=0;in>>a>>b;SendMessageW(edit,EM_SETSEL,a,b);}else if(op=="reset"){SetWindowTextW(edit,L"One selection testing text\r\nSecond line");SendMessageW(edit,EM_SETSEL,0,0);}else if(op=="clear")SetWindowTextW(edit,L"");else if(op=="quit"){DestroyWindow(w);return 0;}state();return 0;}count(m,wp);if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(w,m,wp,lp);}
int main(){wchar_t env[8]{};if(!GetEnvironmentVariableW(L"ONE_TEST_MODE",env,8)||wcscmp(env,L"1"))return 3;SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);OleInitialize(nullptr);std::vector<std::pair<UINT,HANDLE>> clipboard;HWND clipboardOwner=CreateWindowW(L"STATIC",L"Fixture clipboard",0,0,0,0,0,HWND_MESSAGE,nullptr,GetModuleHandleW(nullptr),nullptr);if(OpenClipboard(clipboardOwner)){UINT format=0;while((format=EnumClipboardFormats(format))!=0){HANDLE data=GetClipboardData(format);if(data){HANDLE duplicate=OleDuplicateData(data,(CLIPFORMAT)format,GMEM_MOVEABLE);if(duplicate)clipboard.push_back({format,duplicate});}}CloseClipboard();}bool caps=(GetKeyState(VK_CAPITAL)&1)!=0;
 WNDCLASSW type{};type.lpfnWndProc=windowProc;type.hInstance=GetModuleHandleW(nullptr);type.lpszClassName=L"OneQuickActionsFixture";type.hCursor=LoadCursorW(nullptr,IDC_ARROW);type.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&type);host=CreateWindowW(type.lpszClassName,L"One input verification",WS_OVERLAPPEDWINDOW,150,150,760,500,nullptr,nullptr,type.hInstance,nullptr);
 edit=CreateWindowW(L"Edit",L"One selection testing text\r\nSecond line",WS_CHILD|WS_VISIBLE|WS_BORDER|ES_MULTILINE|ES_AUTOVSCROLL,70,80,570,160,host,nullptr,type.hInstance,nullptr);secret=CreateWindowW(L"Edit",L"Password fixture",WS_CHILD|WS_VISIBLE|WS_BORDER|ES_PASSWORD,70,280,570,40,host,nullptr,type.hInstance,nullptr);auto font=CreateFontW(-22,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,0,0,0,0,L"Segoe UI");SendMessageW(edit,WM_SETFONT,(WPARAM)font,TRUE);SendMessageW(secret,WM_SETFONT,(WPARAM)font,TRUE);editProc=(WNDPROC)SetWindowLongPtrW(edit,GWLP_WNDPROC,(LONG_PTR)control);secretProc=(WNDPROC)SetWindowLongPtrW(secret,GWLP_WNDPROC,(LONG_PTR)control);
 WNDCLASSW customClass{};customClass.lpfnWndProc=customProc;customClass.hInstance=type.hInstance;customClass.lpszClassName=L"OneCustomSelectionFixture";customClass.style=CS_DBLCLKS;customClass.hCursor=LoadCursorW(nullptr,IDC_ARROW);customClass.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);RegisterClassW(&customClass);custom=CreateWindowW(customClass.lpszClassName,L"",WS_CHILD|WS_VISIBLE,70,350,570,45,host,nullptr,type.hInstance,nullptr);
 nonText=CreateWindowW(L"ListBox",L"",WS_CHILD|WS_VISIBLE|WS_BORDER|LBS_NOTIFY,70,405,570,42,host,nullptr,type.hInstance,nullptr);SendMessageW(nonText,LB_ADDSTRING,0,(LPARAM)L"Non-text list item");nonTextProc=(WNDPROC)SetWindowLongPtrW(nonText,GWLP_WNDPROC,(LONG_PTR)control);
 ShowWindow(host,SW_SHOWNORMAL);SetWindowPos(host,nullptr,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOZORDER|SWP_SHOWWINDOW);SetForegroundWindow(host);SetFocus(edit);state();
 std::thread input([]{std::string line;while(std::getline(std::cin,line)){auto command=new std::string(line);if(!PostMessageW(host,WM_APP,0,(LPARAM)command)){delete command;break;}if(line=="quit")break;}});MSG message{};while(GetMessageW(&message,nullptr,0,0)>0){TranslateMessage(&message);DispatchMessageW(&message);}
 if(OpenClipboard(clipboardOwner)){EmptyClipboard();for(auto [format,data]:clipboard)SetClipboardData(format,data);CloseClipboard();}DestroyWindow(clipboardOwner);if(caps!=((GetKeyState(VK_CAPITAL)&1)!=0)){INPUT keys[2]{};for(auto& k:keys){k.type=INPUT_KEYBOARD;k.ki.wVk=VK_CAPITAL;}keys[1].ki.dwFlags=KEYEVENTF_KEYUP;SendInput(2,keys,sizeof(INPUT));}DeleteObject(font);input.join();OleUninitialize();return 0;
}
