const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{randomUUID}=require('node:crypto'),{buildSync}=require('esbuild');
test('system menu requests consume only fresh, bounded selections in the owning profile',async t=>{
 const out=path.resolve(process.env.ONE_UNIT_OUTPUT_DIR||'work','shell-request-tests');await fs.mkdir(out,{recursive:true});const bundle=path.join(out,'request.cjs');buildSync({entryPoints:['src/main/shell-request.ts'],outfile:bundle,bundle:true,platform:'node',target:'node22'});const {readShellRequest}=require(bundle),profile=await fs.mkdtemp(path.join(out,'profile-')),root=path.join(profile,'shell-requests');await fs.mkdir(root);
 const file=path.join(profile,'中文 文件.txt'),folder=path.join(profile,'选中目录'),invoke=p=>readShellRequest(['--one-shell-request='+p],profile),request=async(value,dir=root,name=randomUUID()+'.json')=>{const p=path.join(dir,name);await fs.writeFile(p,JSON.stringify(value));return p;};
 await t.test('Unicode selections and duplicates are consumed once',async()=>{const p=await request({tool:'rename',paths:[file,folder,file]});assert.deepEqual(await invoke(p),{tool:'rename',paths:[file,folder]});await assert.rejects(fs.stat(p),{code:'ENOENT'});await assert.rejects(invoke(p),{code:'ENOENT'});assert.equal(await readShellRequest([],profile),undefined);});
 await t.test('foreign paths and invalid request names are left untouched',async()=>{for(const p of [await request({tool:'rename',paths:[file]},profile),await request({tool:'rename',paths:[file]},root,'-'.repeat(36)+'.json')]){await assert.rejects(invoke(p),/路径无效/);assert.ok((await fs.stat(p)).isFile());}});
 await t.test('invalid selection limits, types and path data are rejected',async()=>{for(const value of [{tool:'delete',paths:[file]},{tool:'rename',paths:[]},{tool:'locksmith',paths:Array(33).fill(file)},{tool:'rename',paths:Array(4097).fill(file)},{tool:'rename',paths:['relative.txt']},{tool:'rename',paths:[file+'\n']},{tool:'rename',paths:[17]}]){const p=await request(value);await assert.rejects(invoke(p),/选择无效/);assert.ok((await fs.stat(p)).isFile());}});
 await t.test('expired and oversized requests do not run',async()=>{const stale=await request({tool:'rename',paths:[file]});await fs.utimes(stale,new Date(0),new Date(0));await assert.rejects(invoke(stale),/失效/);const large=await request({tool:'rename',paths:[file]});await fs.writeFile(large,' '.repeat(4*1024*1024+1));await assert.rejects(invoke(large),/失效/);});
});
