const test=require('node:test'),assert=require('node:assert/strict'),{buildSync}=require('esbuild');
buildSync({entryPoints:['src/shared/disk-monitor.ts','src/main/disk-monitor.ts','src/main/system-info-service.ts'],outdir:'work/test-system-monitor',bundle:true,platform:'node',outExtension:{'.js':'.cjs'}});
const {DiskAlertPolicy,validateDiskMonitor}=require('../work/test-system-monitor/shared/disk-monitor.cjs'),{WriterSampler}=require('../work/test-system-monitor/main/disk-monitor.cjs'),{formatInformationValue}=require('../work/test-system-monitor/main/system-info-service.cjs');
const settings={enabled:true,notify:true,intervalSeconds:2,rules:[{drive:'C:\\',enabled:true,unit:'percent',threshold:10}]};
const volume=free=>[{drive:'C:\\',free,total:100,type:3,label:'',filesystem:'NTFS'}];
test('disk warnings alert once per episode and recover with hysteresis',()=>{const p=new DiskAlertPolicy();assert.deepEqual(p.evaluate(volume(9),settings),{entered:['C:\\'],active:['C:\\']});assert.deepEqual(p.evaluate(volume(8),settings).entered,[]);assert.deepEqual(p.evaluate(volume(10.5),settings).active,['C:\\']);assert.deepEqual(p.evaluate(volume(12),settings).active,[]);assert.deepEqual(p.evaluate(volume(9),settings).entered,['C:\\']);});
test('disabled, inaccessible, and removed volumes do not alert',()=>{const p=new DiskAlertPolicy();assert.deepEqual(p.evaluate(volume(1),{...settings,enabled:false}).entered,[]);assert.deepEqual(p.evaluate([{...volume(1)[0],error:5}],settings).entered,[]);p.evaluate(volume(1),settings);p.evaluate([],settings);assert.deepEqual(p.evaluate(volume(1),settings).entered,['C:\\']);});
test('disk rule validation rejects duplicate drives and malformed thresholds',()=>{assert.throws(()=>validateDiskMonitor({...settings,rules:[settings.rules[0],settings.rules[0]]}));assert.throws(()=>validateDiskMonitor({...settings,rules:[{...settings.rules[0],threshold:100}]}));assert.throws(()=>validateDiskMonitor({...settings,intervalSeconds:0}));assert.equal(validateDiskMonitor(undefined).enabled,false);assert.equal(validateDiskMonitor({...settings,rules:[{...settings.rules[0],drive:'c:\\'}]}).rules[0].drive,'C:\\');});
const raw=(time,bytes,started='100',extra={})=>({created:time,trace:'off',processes:[{pid:12,started,name:'writer.exe',path:'C:\\writer.exe',bytes,operations:bytes/10}],fileWrites:[],...extra});
test('writer rates use deltas, reset on PID reuse, and require consecutive active intervals',()=>{const s=new WriterSampler();assert.deepEqual(s.sample(raw(1000,100)),[]);assert.equal(s.sample(raw(3000,300))[0].bytesPerSecond,100);assert.equal(s.sample(raw(5000,500))[0].activeSeconds,4);s.sample(raw(7000,500));assert.equal(s.sample(raw(9000,700))[0].activeSeconds,2);assert.deepEqual(s.sample(raw(11000,900,'101')),[]);assert.equal(s.sample(raw(13000,1100,'101'))[0].activeSeconds,2);});
test('file tracing excludes network/device writes and exposes paths',()=>{const s=new WriterSampler();s.sample(raw(1000,100));assert.deepEqual(s.sample(raw(3000,10000,'100',{trace:'active'})),[]);const w=s.sample(raw(5000,20000,'100',{trace:'active',fileWrites:[{pid:12,bytes:200,operations:2,files:[{path:'C:\\sample.txt',bytes:200}]}]}))[0];assert.equal(w.bytesPerSecond,100);assert.equal(w.files[0].path,'C:\\sample.txt');});
test('system information formats 64-bit capacities, EDID names, memory types, and absent values',()=>{assert.equal(formatInformationValue(16*1024**3,'bytes'),'16 GB');assert.equal(formatInformationValue([65,66,0],'edid'),'AB');assert.equal(formatInformationValue(34,'memory'),'DDR5');assert.equal(formatInformationValue(32768,'kb'),'32 MB');assert.equal(formatInformationValue(null),'未报告');assert.equal(formatInformationValue(1000000000,'bps'),'1.00 Gbps');});

test('classified write rates and totals are independent, consecutive, and do not relabel unknown I/O',()=>{const s=new WriterSampler();s.sample(raw(1000,0));const traced=(created,kinds)=>raw(created,9999,'100',{trace:'active',fileWrites:[{pid:12,bytes:Object.values(kinds).reduce((a,b)=>a+b,0),operations:4,files:[],kinds}]});let w=s.sample(traced(3000,{file:200,network:600,device:100,unknown:100}))[0];assert.equal(w.bytesPerSecond,500);assert.equal(w.breakdown.network.bytesPerSecond,300);assert.equal(w.breakdown.file.totalBytes,200);w=s.sample(traced(5000,{network:400}))[0];assert.equal(w.breakdown.network.activeSeconds,4);assert.equal(w.breakdown.file.activeSeconds,0);assert.equal(w.breakdown.network.totalBytes,1000);s.sample(traced(7000,{}));w=s.sample(traced(9000,{file:100}))[0];assert.equal(w.breakdown.file.activeSeconds,2);assert.equal(w.breakdown.network.bytesPerSecond,0);const fallback=new WriterSampler();fallback.sample(raw(1000,0));const total=fallback.sample(raw(3000,200))[0];assert.equal(total.breakdown.unknown.bytesPerSecond,100);assert.equal(total.breakdown.file.bytesPerSecond,0);});
