export interface MenuBuiltin {id:string;label:string;category:string;icon:string;systemIcon?:boolean;keywords?:string;confirm?:string}
export const menuBuiltins:readonly MenuBuiltin[]=[
 {id:'opened',label:'已打开的文件夹',category:'文件操作',icon:'folder'},
 {id:'recent',label:'最近访问',category:'文件操作',icon:'history'},
 {id:'copy-path',label:'复制当前路径',category:'文件操作',icon:'copy'},
 {id:'search',label:'文件搜索',category:'文件操作',icon:'search'},
 {id:'terminal',label:'在此打开 PowerShell',category:'终端与开发',icon:'terminal',systemIcon:true},
 {id:'ip-info',label:'详细 IP 信息',category:'网络',icon:'network',systemIcon:true,keywords:'ipconfig 网络 地址'},
 {id:'network-connections',label:'管理网络连接',category:'网络',icon:'network',systemIcon:true},
 {id:'hosts',label:'编辑 Hosts',category:'网络',icon:'file',systemIcon:true,keywords:'域名 主机'},
 {id:'apps',label:'卸载应用',category:'系统管理',icon:'window',systemIcon:true},
 {id:'environment',label:'环境变量',category:'系统管理',icon:'settings',systemIcon:true,keywords:'PATH'},
 {id:'registry',label:'注册表编辑器',category:'系统管理',icon:'settings',systemIcon:true,keywords:'regedit'},
 {id:'group-policy',label:'组策略编辑器',category:'系统管理',icon:'settings',systemIcon:true,keywords:'gpedit'},
 {id:'task-manager',label:'任务管理器',category:'系统管理',icon:'activity',systemIcon:true},
 {id:'services',label:'服务',category:'系统管理',icon:'settings',systemIcon:true},
 {id:'computer-management',label:'计算机管理',category:'系统管理',icon:'window',systemIcon:true},
 {id:'device-manager',label:'设备管理器',category:'系统管理',icon:'settings',systemIcon:true},
 {id:'disk-management',label:'磁盘管理',category:'系统管理',icon:'disk',systemIcon:true},
 {id:'event-viewer',label:'事件查看器',category:'系统管理',icon:'list',systemIcon:true},
 {id:'control-panel',label:'控制面板',category:'系统管理',icon:'settings',systemIcon:true},
 {id:'windows-settings',label:'Windows 设置',category:'系统管理',icon:'settings',systemIcon:true},
 {id:'character-map',label:'特殊字符表',category:'辅助工具',icon:'text',systemIcon:true,keywords:'charmap 字符映射'},
 {id:'steps-recorder',label:'步骤记录器',category:'辅助工具',icon:'history',systemIcon:true,keywords:'psr'},
 {id:'lock',label:'锁定电脑',category:'电源',icon:'lock'},
 {id:'hibernate',label:'休眠',category:'电源',icon:'power',confirm:'将电脑置于休眠状态？'},
 {id:'sign-out',label:'注销',category:'电源',icon:'power',confirm:'将注销当前账户，请先保存正在编辑的文件。'},
 {id:'restart',label:'重启电脑',category:'电源',icon:'power',confirm:'将立即重启电脑，请先保存正在编辑的文件。'},
 {id:'shutdown',label:'关机',category:'电源',icon:'power',confirm:'将立即关闭电脑，请先保存正在编辑的文件。'},
 {id:'settings',label:'自定义菜单',category:'One',icon:'settings'},
];
export const builtinById=(id:string)=>menuBuiltins.find(command=>command.id===id);
