import type {Operation,TextRequest} from './types';
export type TextStep=Omit<TextRequest,'text'>;
export const operationNames:Record<Operation,string>={clean:'整理空白',unique:'按行去重',sort:'按行排序',simple:'繁 → 简',traditional:'简 → 繁',half:'转半角',full:'转全角',replace:'查找替换',trim:'删除行首尾空白',trimEnd:'删除行末空白',empty:'删除空行',paragraphSpace:'段间空一行',joinParagraph:'合并段内换行',indent:'段首缩进两格',layout:'中文简单排版',punctuation:'半角标点转中文',vertical:'竖排符号横转',upper:'转大写',lower:'转小写',reverse:'倒序排列行',natural:'自然排序',removeLetters:'删除英文字母',removeDigits:'删除数字',removePunctuation:'删除标点',normalize:'Unicode 规范化',wrap:'控制行宽',brackets:'检查括号配对'};
export function validateSteps(value:unknown):TextStep[]{if(!Array.isArray(value)||!value.length||value.length>64)throw new Error('处理流程需要 1–64 个步骤');return value.map(step=>{if(!step||!Object.hasOwn(operationNames,step.operation))throw new Error('处理步骤无效');if(step.pattern!==undefined&&(typeof step.pattern!=='string'||step.pattern.length>10000)||step.replacement!==undefined&&(typeof step.replacement!=='string'||step.replacement.length>100000)||step.regex!==undefined&&typeof step.regex!=='boolean'||step.ignoreCase!==undefined&&typeof step.ignoreCase!=='boolean')throw new Error('查找替换参数无效');if(step.operation==='replace'&&!step.pattern)throw new Error('查找内容不能为空');if(step.operation==='wrap'&&(!Number.isInteger(step.width)||step.width<10||step.width>1000))throw new Error('行宽应为 10–1000');return {operation:step.operation,pattern:step.pattern,replacement:step.replacement,regex:step.regex,ignoreCase:step.ignoreCase,width:step.width};});}
export interface TextProgress {phase:string;completed:number;total:number;path?:string;output?:string;error?:string}
export interface TextBatchRequest {paths:string[];steps:TextStep[];inputEncoding:string;outputEncoding:string;output:string;extensions:string;recursive:boolean;merge:boolean;separator:string}
export interface TextBatchResult {output:string;completed:number;failed:{path:string;error:string}[];files:number}
export interface TextDifference {id:number;status:string;oldLine:number;newLine:number;leftText:string;rightText:string;count:number}
export interface TextComparison {id:string;count:number;pageSize:number;grouped:boolean;stats:{addedLines:number;removedLines:number;leftLines:number;rightLines:number}}
