import {spawn,type ChildProcessWithoutNullStreams} from 'node:child_process';
import {join} from 'node:path';
import {DiskAlertPolicy,defaultDiskMonitor,type DiskMonitorSettings,type DiskMonitorState,type ProcessWriting,type WriteKind,type WriteMetrics} from '../shared/disk-monitor';
interface RawProcess {pid:number;started:string;name:string;path:string;bytes:number;operations:number}
interface RawSnapshot extends Omit<DiskMonitorState,'writers'|'alerts'> {samplingWriters?:boolean;samplingEpoch?:number;processes:RawProcess[];fileWrites:{pid:number;bytes:number;operations:number;files:ProcessWriting['files'];kinds?:Partial<Record<WriteKind,number>>}[];traceCode:number}
export class WriterSampler {
 private previous=new Map<number,RawProcess>();private history=new Map<number,{started:string;activeSeconds:number;totalBytes:number;last:number;files:ProcessWriting['files'];breakdown:Partial<Record<WriteKind,WriteMetrics>>}>();private at=0;
 reset(){this.previous.clear();this.history.clear();this.at=0;}
 get ready(){return this.at!==0;}
 sample(raw:RawSnapshot):ProcessWriting[]{const seconds=this.at?Math.max(.1,(raw.created-this.at)/1000):0;this.at=raw.created;const next=new Map<number,RawProcess>(),writers:ProcessWriting[]=[];
  for(const p of raw.processes){next.set(p.pid,p);const previous=this.previous.get(p.pid);if(!seconds||!previous||previous.started!==p.started){this.history.delete(p.pid);continue;}const trace=raw.fileWrites.find(w=>w.pid===p.pid);const bytes=raw.trace==='active'?trace?.bytes||0:Math.max(0,p.bytes-previous.bytes),operations=raw.trace==='active'?trace?.operations||0:Math.max(0,p.operations-previous.operations);
   if(bytes>0){const h=this.history.get(p.pid)||{started:p.started,activeSeconds:0,totalBytes:0,last:raw.created,files:[],breakdown:{}};if(raw.created-h.last>10000)h.activeSeconds=0;h.activeSeconds+=seconds;h.totalBytes+=bytes;h.last=raw.created;h.files=trace?.files||[];const amounts:Partial<Record<WriteKind,number>>=raw.trace==='active'?(trace?.kinds||{file:bytes}):{unknown:bytes};for(const kind of ['file','network','device','unknown'] as WriteKind[]){const n=amounts[kind]||0,previous=h.breakdown[kind]||{bytesPerSecond:0,totalBytes:0,activeSeconds:0};h.breakdown[kind]={bytesPerSecond:n/seconds,totalBytes:previous.totalBytes+n,activeSeconds:n>0?previous.activeSeconds+seconds:0};}this.history.set(p.pid,h);writers.push({pid:p.pid,started:p.started,name:p.name,path:p.path,bytesPerSecond:bytes/seconds,operationsPerSecond:operations/seconds,activeSeconds:h.activeSeconds,totalBytes:h.totalBytes,files:h.files,breakdown:{...h.breakdown}});}else {const h=this.history.get(p.pid);if(h){h.activeSeconds=0;for(const k of Object.values(h.breakdown)){k.activeSeconds=0;k.bytesPerSecond=0;}}}
  }
  this.previous=next;for(const [pid,h] of this.history)if(!next.has(pid)||raw.created-h.last>60000)this.history.delete(pid);return writers.sort((a,b)=>b.bytesPerSecond-a.bytesPerSecond).slice(0,100);
 }
}
export class DiskMonitorService {
 private child:ChildProcessWithoutNullStreams|null=null;private sampler=new WriterSampler();private policy=new DiskAlertPolicy();private settings=defaultDiskMonitor();private subscribers=new Set<string>();private tracing=false;private samplingWriters=false;private samplingEpoch=0;private stopped=false;private revision=0;
 state:DiskMonitorState={created:0,volumes:[],writers:[],trace:'off',alerts:[],cpuPercent:0,memoryTotal:0,memoryFree:0,uptimeSeconds:0};
 constructor(private changed:(s:DiskMonitorState)=>void,private alert:(drive:string,state:DiskMonitorState)=>void){}
 configure(settings:DiskMonitorSettings){const restart=settings.intervalSeconds!==this.settings.intervalSeconds;this.settings=settings;const result=this.policy.evaluate(this.state.volumes,settings);this.state={...this.state,alerts:result.active};for(const drive of result.entered)if(settings.notify)this.alert(drive,this.state);this.changed(this.state);if(restart)this.restart();else this.ensure();}
 subscribe(active:boolean,source:string){if(active)this.subscribers.add(source);else this.subscribers.delete(source);this.ensure();return this.state;}
 trace(enabled:boolean){if(this.tracing!==enabled){this.tracing=enabled;this.state={...this.state,trace:'off',traceError:undefined,writers:[]};this.changed(this.state);this.restart();}return this.state;}
 private wantsWriters(){return this.tracing||this.subscribers.has('maintenance');}
 private ensure(){if(this.stopped)return;if(this.settings.enabled||this.subscribers.size>0||this.tracing){if(!this.child)this.start();else if(this.samplingWriters!==this.wantsWriters()){this.samplingWriters=this.wantsWriters();this.samplingEpoch++;this.sampler.reset();this.state={...this.state,writers:[],writersReady:false};this.changed(this.state);if(this.child.stdin.writable)this.child.stdin.write(`writers ${Number(this.samplingWriters)} ${this.samplingEpoch}\n`);}}else this.halt();}
 private restart(){this.halt();this.ensure();}
 private start(){const revision=++this.revision;this.sampler.reset();this.samplingWriters=this.wantsWriters();this.samplingEpoch=0;this.state={...this.state,writers:[],writersReady:false,error:undefined};let buffer='';const child=spawn(join(__dirname,'../native/One.Monitor.exe').replace('app.asar\\','app.asar.unpacked\\'),[this.tracing?'trace':this.samplingWriters?'sample':'capacity',String(this.settings.intervalSeconds*1000)],{windowsHide:true,stdio:'pipe'});this.child=child;child.stdout.setEncoding('utf8');child.stdout.on('data',chunk=>{if(revision!==this.revision)return;buffer+=chunk;if(buffer.length>8*1024*1024){child.kill();this.failure('磁盘监控响应超过限制');return;}let end;while((end=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,end);buffer=buffer.slice(end+1);try{const raw=JSON.parse(line) as RawSnapshot;const result=this.policy.evaluate(raw.volumes,this.settings);const active=this.samplingWriters&&raw.samplingWriters!==false&&(raw.samplingEpoch===undefined||raw.samplingEpoch===this.samplingEpoch),writersReady=active&&this.sampler.ready;const writers=active?this.sampler.sample(raw):[];this.state={created:raw.created,volumes:raw.volumes,writers,writersReady,trace:raw.trace,traceError:raw.traceCode?`Windows 错误 ${raw.traceCode}`:undefined,alerts:result.active,cpuPercent:raw.cpuPercent,memoryTotal:raw.memoryTotal,memoryFree:raw.memoryFree,uptimeSeconds:raw.uptimeSeconds};this.changed(this.state);for(const drive of result.entered)if(this.settings.notify)this.alert(drive,this.state);}catch{this.failure('磁盘监控返回了无效数据');}}});child.stderr.resume();child.stdin.on('error',()=>{});child.on('error',error=>{if(revision===this.revision)this.failure(error.message);});child.on('exit',code=>{if(revision===this.revision){this.child=null;this.failure(`磁盘监控已退出 (${code})`);}});}
 private failure(error:string){this.state={...this.state,error};this.changed(this.state);}
 private halt(){this.revision++;const child=this.child;this.child=null;if(child){child.stdin.end('stop\n');const timer=setTimeout(()=>child.kill(),2500);timer.unref();child.once('exit',()=>clearTimeout(timer));}}
 stop(){this.stopped=true;this.halt();}
}
