import {execFile} from 'node:child_process';
import {join} from 'node:path';
import {promisify} from 'node:util';
import {session} from 'electron';
import {proxySites,type ProxyAdapter,type ProxyConfiguration,type ProxyDiagnostics,type ProxyDiagnosticsProgress,type ProxyEnvironment,type ProxyExit,type ProxyMode,type ProxyProcess,type ProxySiteResult} from '../shared/proxy-info';
import type {InformationGroup} from '../shared/system-info';

const run=promisify(execFile);
const powershell=join(process.env.SystemRoot||'C:\\Windows','System32/WindowsPowerShell/v1.0/powershell.exe');
const cleanEnv=()=>Object.fromEntries(Object.entries(process.env).filter(([key])=>!/^(?:all|https?|no)_proxy$/i.test(key)));
const short=(value:unknown,limit=250)=>String(value??'').trim().slice(0,limit);
export function safeProxyValue(value:string){try{const url=new URL(value);if(url.username||url.password){url.username='';url.password='';}url.search='';url.hash='';return url.toString();}catch{return value.replace(/(https?:\/\/|socks\d?h?:\/\/|(?:https?|socks)=)[^@;\s]+@/gi,'$1').slice(0,300);}}
function endpoint(value:string){const raw=value.trim();if(!raw)return null;const url=new URL(/^[a-z][\w+.-]*:\/\//i.test(raw)?raw:`http://${raw}`);if(url.username||url.password||!url.hostname||!url.port&&url.protocol!=='http:'&&url.protocol!=='https:')return null;if(!['http:','https:','socks4:','socks4a:','socks5:','socks5h:'].includes(url.protocol))return null;url.pathname='/';url.search='';url.hash='';if(url.protocol==='socks5:')url.protocol='socks5h:';return url.toString().replace(/\/$/,'');}
export function manualProxy(server:string){const entries=server.split(';').map(v=>v.trim()).filter(Boolean);const pick=(name:string)=>entries.find(v=>v.toLowerCase().startsWith(name+'='))?.split('=').slice(1).join('=');const value=pick('https')||pick('http');if(value)return endpoint(value);const socks=pick('socks');if(socks)return endpoint(`socks5h://${socks}`);const single=entries.find(v=>!v.includes('='));return single?endpoint(single):null;}
function routeFromElectron(value:string){for(const item of value.split(';')){const [kind,host]=item.trim().split(/\s+/,2);if(!host)continue;const scheme=kind==='SOCKS5'?'socks5h':kind==='SOCKS'?'socks4':kind==='HTTPS'?'https':kind==='PROXY'?'http':'';if(scheme){try{return endpoint(`${scheme}://${host}`);}catch{}}}return null;}
export async function readProxyConfiguration():Promise<ProxyConfiguration>{
 try{const result=await run(powershell,['-NoProfile','-NonInteractive','-File',join(__dirname,'proxy-info.ps1').replace('app.asar\\','app.asar.unpacked\\')],{windowsHide:true,timeout:20000,maxBuffer:2*1024*1024,encoding:'utf8'});const raw=JSON.parse(result.stdout);
  const scopes:Record<string,ProxyEnvironment['scope']>={Process:'进程',User:'用户',Machine:'系统'};
  return {environment:(Array.isArray(raw.environment)?raw.environment:[]).slice(0,40).map((item:any)=>({scope:scopes[item.scope]||'进程',name:short(item.name,40),value:safeProxyValue(short(item.value,500))})),windows:{enabled:!!raw.windows?.enabled,server:safeProxyValue(short(raw.windows?.server,500)),pac:safeProxyValue(short(raw.windows?.pac,500)),autoDetect:!!raw.windows?.autoDetect,bypass:short(raw.windows?.bypass,500),winHttp:safeProxyValue(short(raw.windows?.winHttp,1000))},processes:(Array.isArray(raw.processes)?raw.processes:[]).slice(0,80).map((item:any):ProxyProcess=>({name:short(item.name,120),pid:Number(item.pid)||0,path:short(item.path,500)})),adapters:(Array.isArray(raw.adapters)?raw.adapters:[]).slice(0,80).map((item:any):ProxyAdapter=>({name:short(item.name,120),description:short(item.description,250),status:short(item.status,80),mac:short(item.mac,80),index:Number(item.index)||0,addresses:Array.isArray(item.addresses)?item.addresses.map((v:unknown)=>short(v,100)):[],gateways:Array.isArray(item.gateways)?item.gateways.map((v:unknown)=>short(v,100)):[],dns:Array.isArray(item.dns)?item.dns.map((v:unknown)=>short(v,100)):[],virtual:!!item.virtual}))};
 }catch(error){return {environment:[],windows:{enabled:false,server:'',pac:'',autoDetect:false,bypass:'',winHttp:''},processes:[],adapters:[],error:short((error as Error).message,300)};}
}
export function proxyInformationGroups(config:ProxyConfiguration):InformationGroup[]{const field=(key:string,label:string,value:unknown)=>({key,label,value:short(value)||'未报告'});return [
 {id:'proxy-settings',title:'系统代理',records:[{title:'Windows 代理设置',fields:[field('enabled','手动代理',config.windows.enabled?'已开启':'未开启'),field('server','代理服务器',config.windows.server),field('pac','PAC 地址',config.windows.pac),field('autoDetect','自动检测',config.windows.autoDetect?'已开启':'未开启'),field('bypass','绕过地址',config.windows.bypass),field('winHttp','WinHTTP',config.windows.winHttp)]}],error:config.error},
 {id:'proxy-environment',title:'代理环境变量',records:config.environment.map(item=>({title:`${item.name} · ${item.scope}`,fields:[field('scope','作用域',item.scope),field('value','值',item.value)]}))},
 {id:'proxy-processes',title:'检测到的相关进程',records:config.processes.map(item=>({title:item.name,fields:[field('pid','PID',item.pid),field('path','程序路径',item.path)]}))},
 {id:'proxy-adapters',title:'虚拟网卡',records:config.adapters.map(item=>({title:item.name,fields:[field('status','状态',item.status),field('description','适配器',item.description),field('addresses','IP / 前缀',item.addresses.join(' · ')),field('gateways','默认网关',item.gateways.join(' · ')),field('dns','DNS',item.dns.join(' · ')),field('mac','MAC',item.mac),field('index','接口索引',item.index)]}))}
 ];}

async function curl(url:string,mode:ProxyMode,proxy:string|null,body=false){const args=['--disable','--silent','--show-error','--location','--max-redirs','2','--connect-timeout','3','--max-time','7','--proto','=https','--proto-redir','=https'];if(mode==='direct')args.push('--proxy','','--noproxy','*');else if(proxy)args.push('--proxy',proxy,'--noproxy','');else throw new Error('未检测到可用于该网站的显式代理');if(body)args.push('--output','-');else args.push('--range','0-0','--output','NUL','--write-out','%{http_code} %{time_total}');args.push(url);return run(join(process.env.SystemRoot||'C:\\Windows','System32/curl.exe'),args,{windowsHide:true,timeout:8500,maxBuffer:body?128*1024:4096,encoding:'utf8',env:cleanEnv()});}
function errorText(error:unknown){const e=error as Error&{stderr?:string};return short(e.stderr||e.message,160).replace(/\s+/g,' ');}
async function geo(mode:ProxyMode,proxy:string|null):Promise<ProxyExit>{if(mode==='proxy'&&!proxy)return {mode,status:'unavailable',detail:'未检测到显式代理；TUN / VPN 路由无法与直连隔离'};
 for(const [url,source] of [['https://ipapi.co/json/','ipapi.co'],['https://ipinfo.io/json','ipinfo.io']] as const){try{const {stdout}=await curl(url,mode,proxy,true),raw=JSON.parse(stdout);if(!raw.ip||raw.error)throw Error(raw.reason||raw.error||'未返回公网 IP');const [latitude,longitude]=typeof raw.loc==='string'?raw.loc.split(',').map(Number):[Number(raw.latitude),Number(raw.longitude)];return {mode,status:'ok',ip:short(raw.ip,80),country:short(raw.country_name||raw.country,100),region:short(raw.region,100),city:short(raw.city,100),latitude:Number.isFinite(latitude)?latitude:undefined,longitude:Number.isFinite(longitude)?longitude:undefined,asn:short(raw.asn||raw.org?.match(/AS\d+/)?.[0],50),organization:short(raw.org,150),source};}catch(error){if(source==='ipinfo.io')return {mode,status:'failed',detail:errorText(error)};}}
 return {mode,status:'failed',detail:'IP 信息服务不可用'};}
async function checkSite(site:(typeof proxySites)[number],mode:ProxyMode,proxy:string|null):Promise<ProxySiteResult>{if(mode==='proxy'&&!proxy)return {site:site.id,mode,status:'unavailable',detail:'该网站没有可用的显式代理'};try{const {stdout}=await curl(site.url,mode,proxy),[code,seconds]=stdout.trim().split(/\s+/),http=Number(code),latencyMs=Math.round(Number(seconds)*1000);if(!http)throw Error('没有收到 HTTP 响应');return {site:site.id,mode,status:http<400?'ok':'restricted',http,latencyMs,detail:http>=400?`服务器返回 HTTP ${http}`:undefined,route:mode==='proxy'?'代理':'直连'};}catch(error){return {site:site.id,mode,status:'failed',detail:errorText(error),route:mode==='proxy'?'代理':'直连'};}}
export class ProxyDiagnosticsService {
 private pending?:Promise<ProxyDiagnostics>;private cached?:ProxyDiagnostics;private stopped=false;
 constructor(private progress:(value:ProxyDiagnosticsProgress)=>void){}
 async read(refresh=false):Promise<ProxyDiagnostics>{if(this.stopped)throw Error('代理检测服务已关闭');if(this.pending)return this.pending;if(!refresh&&this.cached&&Date.now()-this.cached.created<120000)return this.cached;const work=this.run();this.pending=work;try{const report=await work;this.cached=report;return report;}finally{this.pending=undefined;}}
 private async route(url:string,config:ProxyConfiguration){const env=process.env.HTTPS_PROXY||process.env.https_proxy||process.env.ALL_PROXY||process.env.all_proxy;if(env){try{return endpoint(env);}catch{return null;}}
  try{const resolved=routeFromElectron(await session.defaultSession.resolveProxy(url));if(resolved)return resolved;}catch{}
  if(config.windows.enabled){try{return manualProxy(config.windows.server);}catch{}}return null;
 }
 private async run():Promise<ProxyDiagnostics>{const configuration=await readProxyConfiguration(),sites:ProxySiteResult[]=[],exits:ProxyExit[]=[];const geoProxy=await this.route('https://ipapi.co/json/',configuration);
  const geoWork=Promise.all((['direct','proxy'] as ProxyMode[]).map(async mode=>{const result=await geo(mode,mode==='proxy'?geoProxy:null);exits.push(result);if(!this.stopped)this.progress({kind:'exit',value:result});}));
  const tasks=proxySites.flatMap(site=>(['direct','proxy'] as ProxyMode[]).map(mode=>({site,mode})));let cursor=0;
  const workers=Array.from({length:6},async()=>{while(cursor<tasks.length&&!this.stopped){const {site,mode}=tasks[cursor++],proxy=mode==='proxy'?await this.route(site.url,configuration):null,result=await checkSite(site,mode,proxy);sites.push(result);if(!this.stopped)this.progress({kind:'site',value:result});}});
  await Promise.all([...workers,geoWork]);if(this.stopped)throw Error('代理检测服务已关闭');return {created:Date.now(),configuration,exits,sites,proxyAvailable:!!geoProxy||sites.some(item=>item.mode==='proxy'&&item.status!=='unavailable')};
 }
 stop(){this.stopped=true;}
}
