import {parentPort,workerData} from 'node:worker_threads';
import {opendir,stat,lstat,readFile,rename,mkdir,open,unlink} from 'node:fs/promises';
import {watch,type FSWatcher,createReadStream} from 'node:fs';
import {createInterface} from 'node:readline';
import {join,dirname,resolve,relative,isAbsolute,basename} from 'node:path';
import {setImmediate as yieldTick} from 'node:timers/promises';
import {searchMatcher,type SearchEntry,type SearchSettings,type SearchState} from '../shared/search';
const entries=new Map<string,SearchEntry>(),watchers:FSWatcher[]=[];let settings:SearchSettings=workerData.settings,generation=0,queryGeneration=0,flushTimer:NodeJS.Timeout|undefined,watchTimer:NodeJS.Timeout|undefined;const pending=new Set<string>();
let state:SearchState={running:false,count:0,scanned:0,issues:0,root:'',updated:0,error:'',watching:false};let last=0;
const key=(path:string)=>resolve(path).toLowerCase();const under=(path:string,root:string)=>{const r=relative(root,path);return !r||r!=='..'&&!r.startsWith('..\\')&&!isAbsolute(r);};
const excluded=(path:string)=>settings.excluded.some(p=>under(path,p));const send=(force=false)=>{state.count=entries.size;if(force||Date.now()-last>150){last=Date.now();parentPort!.postMessage({state:{...state}});}};
async function walk(root:string,revision:number){const stack=[root];while(stack.length&&generation===revision){const path=stack.pop()!;if(excluded(path))continue;try{const info=await lstat(path);if(info.isSymbolicLink())continue;entries.set(key(path),{path,name:basename(path)||path,directory:info.isDirectory(),modified:info.mtimeMs,size:info.isDirectory()?0:info.size});state.scanned++;if(entries.size>=1_000_000){state.error='索引达到 100 万项上限，请缩小范围';return;}if(info.isDirectory()){const dir=await opendir(path);for await(const child of dir){if(generation!==revision)return;const full=join(path,child.name);if(excluded(full)||child.isSymbolicLink())continue;if(child.isDirectory())stack.push(full);else if(child.isFile()){entries.set(key(full),{path:full,name:child.name,directory:false,modified:0,size:0});state.scanned++;if(entries.size>=1_000_000){state.error='索引达到 100 万项上限，请缩小范围';return;}if(state.scanned%1024===0){send();await yieldTick();}}}}}catch{state.issues++;}send();await yieldTick();}}
async function persist(){const temp=workerData.cache+'.tmp',revision=generation,config=settings;let file;try{await mkdir(dirname(temp),{recursive:true});file=await open(temp,'w');await file.write(JSON.stringify({version:1,roots:config.roots,excluded:config.excluded,updated:state.updated})+'\n');let chunk='';for(const entry of entries.values()){if(revision!==generation)return;chunk+=JSON.stringify(entry)+'\n';if(chunk.length>256000){await file.write(chunk);chunk='';}}if(chunk)await file.write(chunk);await file.close();file=undefined;if(revision===generation)await rename(temp,workerData.cache);}catch{}finally{await file?.close();await unlink(temp).catch(()=>{});}}
let persisting=false,persistAgain=false;function schedulePersist(){clearTimeout(flushTimer);flushTimer=setTimeout(async()=>{if(persisting){persistAgain=true;return;}persisting=true;try{await persist();}finally{persisting=false;if(persistAgain){persistAgain=false;schedulePersist();}}},2000);}
function stopWatch(){for(const w of watchers)w.close();watchers.length=0;state.watching=false;clearTimeout(watchTimer);pending.clear();}
function startWatch(){stopWatch();for(const root of settings.roots)try{const w=watch(root,{recursive:true},(_event,name)=>{if(!name)return;pending.add(join(root,name.toString()));clearTimeout(watchTimer);watchTimer=setTimeout(()=>void refreshChanges(),600);});w.on('error',()=>{state.watching=false;state.error='目录监听已中断，请重新扫描';send(true);});watchers.push(w);}catch{state.error='部分目录无法监听，请手动刷新';}state.watching=watchers.length===settings.roots.length&&!!watchers.length;}
let refreshing=false;
async function refreshChanges(){if(state.running||refreshing)return;refreshing=true;const revision=generation;try{while(pending.size&&generation===revision){const paths=[...pending];pending.clear();for(const path of paths){if(generation!==revision)return;if(excluded(path))continue;for(const [id,item]of entries)if(under(item.path,path))entries.delete(id);try{await lstat(path);}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')continue;state.issues++;continue;}await walk(path,revision);}}if(generation===revision){state.updated=Date.now();send(true);schedulePersist();}}finally{refreshing=false;}}
async function rebuild(config:SearchSettings){generation++;stopWatch();settings=config;const revision=generation;entries.clear();state={...state,running:true,scanned:0,issues:0,error:'',updated:0};send(true);for(const root of config.roots){if(generation!==revision)return;state.root=root;await walk(root,revision);if(state.error)break;}if(generation!==revision)return;state.running=false;state.root='';state.updated=Date.now();startWatch();send(true);schedulePersist();}
async function load(){try{const info=await stat(workerData.cache);if(info.size>350*1024*1024)throw new Error('cache too large');const stream=createReadStream(workerData.cache,{encoding:'utf8'}),lines=createInterface({input:stream,crlfDelay:Infinity});let first=true;try{for await(const line of lines){const row=JSON.parse(line);if(first){first=false;if(row.version!==1||JSON.stringify(row.roots)!==JSON.stringify(settings.roots)||JSON.stringify(row.excluded)!==JSON.stringify(settings.excluded))break;state.updated=row.updated;continue;}if(typeof row.path!=='string'||!settings.roots.some(p=>under(row.path,p))||excluded(row.path))continue;entries.set(key(row.path),row);if(entries.size>=1_000_000)break;}}finally{lines.close();stream.destroy();}}catch{}startWatch();send(true);}
// Display cached hits immediately, then reconcile changes made while One was closed.
const ready=load();void ready.then(()=>{if(settings.roots.length)void rebuild(settings);});
parentPort!.on('message',async message=>{await ready;try{if(message.type==='rebuild'){void rebuild(message.settings);return;}if(message.type==='cancel'){generation++;state.running=false;state.root='';state.error='已停止，保留部分索引';startWatch();send(true);schedulePersist();return;}if(message.type==='query'){const revision=++queryGeneration,start=performance.now(),match=searchMatcher(message.query,message.foldersOnly),items:{item:SearchEntry;score:number}[]=[];let total=0,seen=0;for(const item of entries.values()){if(revision!==queryGeneration){parentPort!.postMessage({id:message.id,result:{items:[],total:0,elapsed:0}});return;}const score=match(item);if(score>=0){total++;if(items.length<100||score>items[items.length-1].score){items.push({item,score});items.sort((a,b)=>b.score-a.score||a.item.path.localeCompare(b.item.path,'zh-CN'));if(items.length>100)items.pop();}}if(++seen%10000===0)await yieldTick();}parentPort!.postMessage({id:message.id,result:{items:items.map(x=>x.item),total,elapsed:Math.round(performance.now()-start)}});}}catch(error){parentPort!.postMessage({id:message.id,error:(error as Error).message});}});
