import type {InformationKind} from '../shared/system-info';
export interface InformationSource { id:string;title:string;class:string;namespace?:string;filter?:string;name?:string;fields:string;limit?:number }
// Field syntax: provider property | user-facing label | optional presentation unit.
const sources:Record<string,InformationSource>={
 computer:{id:'computer',title:'计算机',class:'Win32_ComputerSystem',name:'Model',fields:'Name|计算机名;Manufacturer|制造商;Model|型号;SystemFamily|产品系列;SystemSKUNumber|SKU;SystemType|系统类型;TotalPhysicalMemory|物理内存|bytes;NumberOfProcessors|处理器插槽;NumberOfLogicalProcessors|逻辑处理器;Domain|域 / 工作组;PartOfDomain|加入域;HypervisorPresent|虚拟机监控器;BootupState|启动状态'},
 product:{id:'product',title:'产品标识',class:'Win32_ComputerSystemProduct',name:'Name',fields:'Vendor|厂商;Name|产品;Version|版本;IdentifyingNumber|序列号;UUID|UUID'},
 cpu:{id:'cpu',title:'处理器',class:'Win32_Processor',name:'Name',fields:'Name|型号;Manufacturer|制造商;SocketDesignation|插槽;ProcessorId|处理器 ID;Architecture|架构|architecture;AddressWidth|地址宽度|bits;DataWidth|数据宽度|bits;NumberOfCores|核心数;NumberOfEnabledCore|已启用核心;NumberOfLogicalProcessors|线程数;MaxClockSpeed|固件报告频率上限|mhz;CurrentClockSpeed|当前报告频率|mhz;ExtClock|外部时钟|mhz;L2CacheSize|L2 缓存|kb;L3CacheSize|L3 缓存|kb;Family|家族编码;Stepping|步进;Revision|修订;Version|版本;VirtualizationFirmwareEnabled|固件虚拟化;VMMonitorModeExtensions|虚拟化扩展;SecondLevelAddressTranslationExtensions|二级地址转换;Status|状态'},
 memory:{id:'memory',title:'内存条',class:'Win32_PhysicalMemory',name:'DeviceLocator',fields:'DeviceLocator|插槽;BankLabel|存储体;Manufacturer|制造商;PartNumber|部件型号;SerialNumber|序列号;Capacity|容量|bytes;Speed|标称速率|mts;ConfiguredClockSpeed|配置速率|mts;SMBIOSMemoryType|类型|memory;FormFactor|形态|form;DataWidth|数据位宽|bits;TotalWidth|总位宽|bits;ConfiguredVoltage|配置电压|mv;MinVoltage|最小电压|mv;MaxVoltage|最大电压|mv;Attributes|Rank 数;TypeDetail|类型标志'},
 array:{id:'array',title:'内存阵列',class:'Win32_PhysicalMemoryArray',name:'Tag',fields:'MemoryDevices|插槽数;MaxCapacityEx|最大支持容量|kb;MaxCapacity|最大支持容量（旧接口）|kb;MemoryErrorCorrection|纠错类型|ecc;Location|位置编码;Use|用途编码'},
 board:{id:'board',title:'主板',class:'Win32_BaseBoard',name:'Product',fields:'Manufacturer|制造商;Product|型号;Version|版本;SerialNumber|序列号;HostingBoard|主板;Removable|可移除;Replaceable|可替换;Status|状态'},
 bios:{id:'bios',title:'BIOS / UEFI',class:'Win32_BIOS',name:'SMBIOSBIOSVersion',fields:'Manufacturer|制造商;Name|名称;SMBIOSBIOSVersion|固件版本;Version|版本标识;ReleaseDate|发布日期|date;SMBIOSMajorVersion|SMBIOS 主版本;SMBIOSMinorVersion|SMBIOS 次版本;SystemBiosMajorVersion|系统 BIOS 主版本;SystemBiosMinorVersion|系统 BIOS 次版本;EmbeddedControllerMajorVersion|EC 主版本;EmbeddedControllerMinorVersion|EC 次版本;SerialNumber|序列号;BIOSCharacteristics|功能标志'},
 chassis:{id:'chassis',title:'机箱',class:'Win32_SystemEnclosure',name:'Manufacturer',fields:'Manufacturer|制造商;Model|型号;SerialNumber|序列号;SMBIOSAssetTag|资产标签;ChassisTypes|机箱类型编码;Version|版本;SecurityStatus|安全状态编码;LockPresent|机箱锁'},
 gpu:{id:'gpu',title:'显卡',class:'Win32_VideoController',name:'Name',fields:'Name|型号;AdapterCompatibility|制造商;VideoProcessor|图形处理器;PNPDeviceID|硬件 ID;DriverVersion|驱动版本;DriverDate|驱动日期|date;AdapterRAM|WMI 显存（32 位接口）|bytes;CurrentHorizontalResolution|当前宽度|px;CurrentVerticalResolution|当前高度|px;CurrentRefreshRate|当前刷新率|hz;CurrentBitsPerPixel|色深|bits;VideoModeDescription|显示模式;VideoArchitecture|架构编码;Availability|可用状态编码;Status|状态'},
 monitor:{id:'monitor',title:'显示器标识',class:'WmiMonitorID',namespace:'root/wmi',name:'UserFriendlyName',fields:'UserFriendlyName|名称|edid;ManufacturerName|制造商|edid;ProductCodeID|产品代码|edid;SerialNumberID|序列号|edid;WeekOfManufacture|生产周;YearOfManufacture|生产年份;Active|已连接;InstanceName|设备实例'},
 monitorSize:{id:'monitor-size',title:'显示面板',class:'WmiMonitorBasicDisplayParams',namespace:'root/wmi',name:'InstanceName',fields:'InstanceName|设备实例;MaxHorizontalImageSize|物理宽度|cm;MaxVerticalImageSize|物理高度|cm;VideoInputType|输入类型编码;DisplayTransferCharacteristic|Gamma 编码;Active|已连接'},
 disk:{id:'disk',title:'磁盘设备',class:'Win32_DiskDrive',name:'Model',fields:'Model|型号;Manufacturer|制造商;SerialNumber|序列号;FirmwareRevision|固件;Size|容量|bytes;InterfaceType|接口;MediaType|介质;BytesPerSector|扇区大小|bytes;Partitions|分区数;Index|磁盘编号;DeviceID|设备路径;PNPDeviceID|硬件 ID;SCSIBus|总线编号;SCSIPort|端口;Status|状态'},
 physical:{id:'physical',title:'存储健康',class:'MSFT_PhysicalDisk',namespace:'root/Microsoft/Windows/Storage',name:'FriendlyName',fields:'FriendlyName|名称;SerialNumber|序列号;BusType|总线|bus;MediaType|介质|media;Size|容量|bytes;HealthStatus|健康|health;OperationalStatus|运行状态编码;FirmwareVersion|固件;LogicalSectorSize|逻辑扇区|bytes;PhysicalSectorSize|物理扇区|bytes;SpindleSpeed|转速|rpm;UniqueId|唯一 ID'},
 reliability:{id:'reliability',title:'磁盘可靠性计数器',class:'MSFT_StorageReliabilityCounter',namespace:'root/Microsoft/Windows/Storage',name:'DeviceId',fields:'DeviceId|设备编号;Temperature|温度|celsius;TemperatureMax|最高温度|celsius;Wear|磨损|percent;PowerOnHours|通电时长|hours;ReadErrorsTotal|读取错误;WriteErrorsTotal|写入错误;ReadErrorsUncorrected|不可纠正读取错误;WriteErrorsUncorrected|不可纠正写入错误;ReadLatencyMax|最大读取延迟|ms;WriteLatencyMax|最大写入延迟|ms'},
 volume:{id:'volume',title:'卷与盘符',class:'Win32_LogicalDisk',filter:'DriveType=2 OR DriveType=3',name:'DeviceID',fields:'DeviceID|盘符;VolumeName|卷标;FileSystem|文件系统;Size|容量|bytes;FreeSpace|剩余|bytes;VolumeSerialNumber|卷序列号;Compressed|压缩;SupportsFileBasedCompression|支持文件压缩;SupportsDiskQuotas|支持配额;DriveType|类型编码'},
 partition:{id:'partition',title:'分区',class:'MSFT_Partition',namespace:'root/Microsoft/Windows/Storage',name:'AccessPaths',fields:'DiskNumber|磁盘编号;PartitionNumber|分区编号;DriveLetter|盘符;AccessPaths|挂载点;Size|容量|bytes;Offset|偏移|bytes;GptType|GPT 类型;Guid|GUID;IsBoot|启动分区;IsSystem|系统分区;IsReadOnly|只读;IsHidden|隐藏'},
 adapter:{id:'adapter',title:'网络适配器',class:'MSFT_NetAdapter',namespace:'root/StandardCimv2',name:'Name',fields:'Name|名称;InterfaceDescription|型号;InterfaceIndex|接口索引;MacAddress|MAC;PermanentAddress|永久地址;LinkSpeed|链路速率|bps;MediaConnectState|连接状态编码;InterfaceOperationalStatus|运行状态编码;DriverVersionString|驱动版本;DriverDate|驱动日期;DriverProvider|驱动提供者;Virtual|虚拟接口;HardwareInterface|硬件接口;NdisVersion|NDIS 版本'},
 ip:{id:'ip',title:'IP / DNS 配置',class:'Win32_NetworkAdapterConfiguration',filter:'IPEnabled=TRUE',name:'Description',fields:'Description|接口;MACAddress|MAC;IPAddress|IP 地址;IPSubnet|子网;DefaultIPGateway|网关;DNSServerSearchOrder|DNS 服务器;DNSDomain|DNS 域;DNSHostName|DNS 主机名;DHCPEnabled|DHCP;DHCPServer|DHCP 服务器;DHCPLeaseObtained|租约开始|date;DHCPLeaseExpires|租约结束|date;MTU|MTU;IPConnectionMetric|接口跃点'},
 routes:{id:'routes',title:'默认路由',class:'MSFT_NetRoute',namespace:'root/StandardCimv2',filter:"DestinationPrefix='0.0.0.0/0' OR DestinationPrefix='::/0'",name:'InterfaceAlias',fields:'InterfaceAlias|接口;DestinationPrefix|目标;NextHop|下一跳;RouteMetric|路由跃点;InterfaceIndex|接口索引;Protocol|协议编码;State|状态编码'},
 bluetooth:{id:'bluetooth',title:'蓝牙无线电与设备',class:'Win32_PnPEntity',filter:"PNPClass='Bluetooth'",name:'Name',fields:'Name|名称;Manufacturer|制造商;Service|驱动服务;DeviceID|设备 ID;HardwareID|硬件 ID;CompatibleID|兼容 ID;Status|状态;ConfigManagerErrorCode|设备错误|device-error;Present|在场;ClassGuid|设备类别 GUID'},
 audio:{id:'audio',title:'音频设备',class:'Win32_SoundDevice',name:'Name',fields:'Name|名称;Manufacturer|制造商;ProductName|产品;PNPDeviceID|硬件 ID;Status|状态;ConfigManagerErrorCode|设备错误|device-error'},
 usb:{id:'usb',title:'USB 设备',class:'Win32_PnPEntity',filter:"PNPClass='USB'",name:'Name',fields:'Name|名称;Manufacturer|制造商;DeviceID|硬件 ID;Service|服务;Status|状态;ConfigManagerErrorCode|设备错误|device-error'},
 input:{id:'input',title:'键盘 / 鼠标 / HID',class:'Win32_PnPEntity',filter:"PNPClass='Keyboard' OR PNPClass='Mouse' OR PNPClass='HIDClass'",name:'Name',fields:'Name|名称;Manufacturer|制造商;PNPClass|类型;DeviceID|设备 ID;Service|驱动服务;Status|状态;ConfigManagerErrorCode|设备错误|device-error'},
 battery:{id:'battery',title:'电池',class:'Win32_Battery',name:'Name',fields:'Name|名称;DeviceID|设备 ID;BatteryStatus|状态编码;EstimatedChargeRemaining|剩余电量|percent;EstimatedRunTime|预估续航|minutes;DesignCapacity|设计容量|mwh;FullChargeCapacity|满充容量|mwh;DesignVoltage|设计电压|mv;Chemistry|化学类型编码;Status|状态'},
 batteryStatic:{id:'battery-static',title:'电池制造信息',class:'BatteryStaticData',namespace:'root/wmi',name:'DeviceName',fields:'DeviceName|名称;ManufactureName|制造商;SerialNumber|序列号;DesignedCapacity|设计容量|mwh;ManufactureDate|生产日期编码;UniqueID|唯一 ID'},
 batteryFull:{id:'battery-full',title:'电池健康',class:'BatteryFullChargedCapacity',namespace:'root/wmi',name:'InstanceName',fields:'InstanceName|设备实例;FullChargedCapacity|满充容量|mwh'},
 batteryCycles:{id:'battery-cycles',title:'充放电循环',class:'BatteryCycleCount',namespace:'root/wmi',name:'InstanceName',fields:'InstanceName|设备实例;CycleCount|循环次数'},
 batteryStatus:{id:'battery-status',title:'实时供电',class:'BatteryStatus',namespace:'root/wmi',name:'InstanceName',fields:'InstanceName|设备实例;PowerOnline|交流电;Charging|正在充电;Discharging|正在放电;RemainingCapacity|剩余容量|mwh;Voltage|电压|mv;ChargeRate|充电功率|mw;DischargeRate|放电功率|mw'},
 power:{id:'power',title:'电源计划',class:'Win32_PowerPlan',namespace:'root/cimv2/power',filter:'IsActive=TRUE',name:'ElementName',fields:'ElementName|计划;InstanceID|计划 ID;IsActive|当前计划'},
 os:{id:'os',title:'Windows',class:'Win32_OperatingSystem',name:'Caption',fields:'Caption|版本名称;Version|版本;BuildNumber|内部版本;OSArchitecture|架构;InstallDate|安装日期|date;LastBootUpTime|启动时间|date;LocalDateTime|系统时间|date;WindowsDirectory|Windows 目录;SystemDirectory|系统目录;BootDevice|启动设备;Locale|地区编码;MUILanguages|界面语言;TotalVisibleMemorySize|可用物理内存总量|kb;FreePhysicalMemory|空闲物理内存|kb;TotalVirtualMemorySize|虚拟内存总量|kb;FreeVirtualMemory|空闲虚拟内存|kb;NumberOfProcesses|进程数;NumberOfUsers|登录用户数;DataExecutionPrevention_Available|DEP;DataExecutionPrevention_SupportPolicy|DEP 策略编码;EncryptionLevel|加密等级|bits'},
 timezone:{id:'timezone',title:'时区',class:'Win32_TimeZone',name:'Caption',fields:'Caption|时区;StandardName|标准时间;DaylightName|夏令时间;Bias|UTC 偏移分钟'},
 tpm:{id:'tpm',title:'TPM',class:'Win32_Tpm',namespace:'root/cimv2/security/microsofttpm',name:'SpecVersion',fields:'SpecVersion|规范版本;ManufacturerIdTxt|制造商;ManufacturerVersion|固件版本;IsActivated_InitialValue|已激活;IsEnabled_InitialValue|已启用;IsOwned_InitialValue|所有权'},
 pagefile:{id:'pagefile',title:'分页文件',class:'Win32_PageFileUsage',name:'Name',fields:'Name|位置;AllocatedBaseSize|已分配|mb;CurrentUsage|当前使用|mb;PeakUsage|峰值使用|mb;TempPageFile|临时分页文件'},
 drivers:{id:'drivers',title:'已签名驱动',class:'Win32_PnPSignedDriver',name:'DeviceName',limit:2000,fields:'DeviceName|设备;DeviceClass|类型;Manufacturer|制造商;DriverProviderName|提供者;DriverVersion|版本;DriverDate|日期|date;IsSigned|已签名;Signer|签名者;InfName|INF;DeviceID|硬件 ID;FriendlyName|友好名称'},
 issues:{id:'issues',title:'设备异常',class:'Win32_PnPEntity',filter:'ConfigManagerErrorCode<>0',name:'Name',fields:'Name|设备;PNPClass|类型;DeviceID|设备 ID;ConfigManagerErrorCode|设备错误|device-error;Status|状态'}
};
const categories:Record<InformationKind,string[]>={overview:['computer','cpu','board','gpu','memory','volume','os'],cpu:['cpu'],memory:['memory','array'],board:['board','bios','chassis','product','tpm'],display:['gpu','monitor','monitorSize'],storage:['disk','physical','reliability','volume','partition'],network:['adapter','ip','routes'],bluetooth:['bluetooth'],devices:['audio','usb','input','issues'],battery:['battery','batteryStatic','batteryFull','batteryCycles','batteryStatus','power'],os:['os','computer','timezone','pagefile','tpm'],drivers:['drivers']};
export function informationSources(kind:InformationKind){return categories[kind].map(key=>sources[key]);}
