import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {mkdir,writeFile,copyFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
const run=promisify(execFile);
await mkdir('dist/native',{recursive:true});await mkdir('work',{recursive:true});
const vswhere=join(process.env['ProgramFiles(x86)']||'C:\\Program Files (x86)','Microsoft Visual Studio/Installer/vswhere.exe');
const {stdout}=await run(vswhere,['-latest','-products','*','-requires','Microsoft.VisualStudio.Component.VC.Tools.x86.x64','-property','installationPath'],{windowsHide:true});
const installation=stdout.trim();if(!installation)throw new Error('需要 Visual Studio C++ x64 工具链构建原生辅助程序');
const script=resolve('work/build-native.cmd');
await writeFile(script,`@echo off\r\ncall "${installation}\\VC\\Auxiliary\\Build\\vcvars64.bat" >nul\r\nif errorlevel 1 exit /b 1\r\ncl /nologo /std:c++20 /EHsc /MT /O2 /DUNICODE /D_UNICODE native\\open-with.cpp /Fe:dist\\native\\One.OpenWith.exe /Fo:work\\open-with.obj /link user32.lib ole32.lib shell32.lib shlwapi.lib uuid.lib gdiplus.lib gdi32.lib crypt32.lib\r\nif errorlevel 1 exit /b 1\r\ncl /nologo /std:c++20 /EHsc /MT /O2 /DUNICODE /D_UNICODE native\\system-tools.cpp /Fe:dist\\native\\One.Native.exe /Fo:work\\system-tools.obj /link psapi.lib\r\nif errorlevel 1 exit /b 1\r\ncl /nologo /std:c++20 /EHsc /MT /O2 /DUNICODE /D_UNICODE native\\search-bridge.cpp /Fe:dist\\native\\One.Search.exe /Fo:work\\search-bridge.obj /link user32.lib ole32.lib oleaut32.lib uuid.lib shell32.lib uiautomationcore.lib imm32.lib\r\n`, 'utf8');
await writeFile('work/build-window-tools.cmd',`@echo off\r\ncall "${installation}\\VC\\Auxiliary\\Build\\vcvars64.bat" >nul\r\ncl /nologo /std:c++20 /EHsc /MT /O2 /utf-8 /DUNICODE /D_UNICODE native\\window-tools.cpp /Fe:dist\\native\\One.Windows.exe /Fo:work\\window-tools.obj /link user32.lib gdi32.lib dwmapi.lib\r\n`);
await writeFile('work/build-monitor.cmd',`@echo off\r\ncall "${installation}\\VC\\Auxiliary\\Build\\vcvars64.bat" >nul\r\ncl /nologo /std:c++20 /EHsc /MT /O2 /utf-8 /DUNICODE /D_UNICODE native\\disk-monitor.cpp /Fe:dist\\native\\One.Monitor.exe /Fo:work\\disk-monitor.obj /link ole32.lib user32.lib advapi32.lib tdh.lib dxgi.lib wlanapi.lib Bthprops.lib\r\n`);
await writeFile('work/build-levels.cmd',`@echo off\r\ncall "${installation}\\VC\\Auxiliary\\Build\\vcvars64.bat" >nul\r\ncl /nologo /std:c++20 /EHsc /MT /O2 /utf-8 /DUNICODE /D_UNICODE native\\levels.cpp /Fe:dist\\native\\One.Levels.exe /Fo:work\\levels.obj /link user32.lib ole32.lib oleaut32.lib uuid.lib dxva2.lib wbemuuid.lib\r\n`);
const levelsBuild=await run('cmd.exe',['/d','/c',resolve('work/build-levels.cmd')],{cwd:resolve('.'),windowsHide:true});process.stdout.write(levelsBuild.stdout);
const monitorBuild=await run('cmd.exe',['/d','/c',resolve('work/build-monitor.cmd')],{cwd:resolve('.'),windowsHide:true});process.stdout.write(monitorBuild.stdout);
const windowBuild=await run('cmd.exe',['/d','/c',resolve('work/build-window-tools.cmd')],{cwd:resolve('.'),windowsHide:true});process.stdout.write(windowBuild.stdout);
const result=await run('cmd.exe',['/d','/c',script],{cwd:resolve('.'),windowsHide:true});process.stdout.write(result.stdout);process.stderr.write(result.stderr);
await run('cargo',['build','--release','--locked','--manifest-path','native/search-engine/Cargo.toml'],{cwd:resolve('.'),windowsHide:true,env:{...process.env,RUSTFLAGS:'-C target-feature=+crt-static'},maxBuffer:4*1024*1024});
await copyFile(resolve(process.env.CARGO_TARGET_DIR||'native/search-engine/target','release/one-index.exe'),'dist/native/One.Index.exe');
