import './build-native.mjs';
import { build as bundle } from 'esbuild';
import { build } from 'vite';
import { mkdir, readFile, writeFile, readdir, copyFile, cp } from 'node:fs/promises';
import './notices.mjs';
import {mainOptions,preloadOptions} from './bundle-options.mjs';
await mkdir('dist/main', { recursive: true });
await mkdir('dist/icons', { recursive: true });
for (const name of await readdir('assets/icons')) if (/^one-(?:taskbar-)?\d+\.png$/.test(name) || name === 'one.ico') await copyFile('assets/icons/'+name,'dist/icons/'+name);
await bundle(mainOptions);
await bundle(preloadOptions);
await writeFile('dist/main/system-info.ps1',Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),await readFile('src/main/system-info.ps1')]));
await writeFile('dist/main/proxy-info.ps1',Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),await readFile('src/main/proxy-info.ps1')]));
await writeFile('dist/main/maintenance-actions.ps1',Buffer.concat([Buffer.from([0xef,0xbb,0xbf]),await readFile('src/main/maintenance-actions.ps1')]));
await writeFile('dist/main/maintenance.ps1', Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), await readFile('src/main/maintenance.ps1')]));
await writeFile('dist/main/brightness.ps1', Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), await readFile('src/main/brightness.ps1')]));
await build({ root: 'src/renderer', base: './', build: { outDir: '../../dist/renderer', emptyOutDir: true }, logLevel: 'warn' });
for(const folder of ['cmaps','standard_fonts','wasm'])await cp('node_modules/pdfjs-dist/'+folder,'dist/renderer/pdf/'+folder,{recursive:true});
await cp('assets/file-icons','dist/renderer/file-icons',{recursive:true});
console.log('Electron build complete.');

