// Owned native helper for protocol/lifecycle verification. Never attaches to
// the live app or kills a process it did not spawn.
const {spawn}=require('node:child_process'),assert=require('node:assert/strict'),koffi=require('koffi');
const Memory=koffi.struct('OneCatalogClientMemory',{cb:'uint32',PageFaultCount:'uint32',PeakWorkingSetSize:'size_t',WorkingSetSize:'size_t',QuotaPeakPagedPoolUsage:'size_t',QuotaPagedPoolUsage:'size_t',QuotaPeakNonPagedPoolUsage:'size_t',QuotaNonPagedPoolUsage:'size_t',PagefileUsage:'size_t',PeakPagefileUsage:'size_t',PrivateUsage:'size_t'}),kernel=koffi.load('kernel32.dll'),psapi=koffi.load('psapi.dll'),open=kernel.func('void * __stdcall OpenProcess(uint32,int,uint32)'),close=kernel.func('int __stdcall CloseHandle(void *)'),getMemory=psapi.func('int __stdcall GetProcessMemoryInfo(void *, _Out_ OneCatalogClientMemory *, uint32)');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(check,timeout=30000){const end=performance.now()+timeout;while(performance.now()<end){if(await check())return;await delay(20);}throw Error('Native condition timed out');}
async function client(exe,args,init){
 const start=performance.now(),child=spawn(exe,args,{windowsHide:true,stdio:'pipe'}),handle=open(0x410,0,child.pid);assert.ok(handle);let buffer='',serial=0,ready,started=false,state,failure,closed=false;const pending=new Map(),states=[],events=[],errors=[];
 const listeners=new Set();const fail=error=>{failure=error;for(const p of pending.values()){clearTimeout(p.timer);p.reject(error);}pending.clear();};
 const exit=new Promise(resolve=>{child.once('error',fail);child.once('exit',(code,signal)=>{if(pending.size)fail(Error('Native helper exited during request'));resolve({code,signal});});});
 child.stderr.on('data',chunk=>errors.push(chunk.toString()));child.stdin.on('error',fail);child.stdout.setEncoding('utf8');
 child.stdout.on('data',chunk=>{try{buffer+=chunk;assert.ok(buffer.length<12*1024**2);let at;while((at=buffer.indexOf('\n'))>=0){const message=JSON.parse(buffer.slice(0,at));buffer=buffer.slice(at+1);if(message.state){state=message.state;states.push({...state,at:performance.now()});started ||= state.running;if(started&&!state.running)ready??={count:state.count,readyMs:performance.now()-start};for(const listener of listeners)listener(state);continue;}if(message.ready){ready={...message,readyMs:performance.now()-start};continue;}if(message.merge){events.push(message.merge);continue;}const p=pending.get(message.id);if(!p)continue;if(message.result?.partial){p.partial=message.result;p.onPartial?.({result:message.result,wallMs:performance.now()-p.start});continue;}pending.delete(message.id);clearTimeout(p.timer);message.error?p.reject(Error(message.error)):p.resolve({result:message.result,partial:p.partial,wallMs:performance.now()-p.start});}}catch(error){fail(error);}});
 const send=value=>{if(failure)throw failure;child.stdin.write(JSON.stringify(value)+'\n');};
 const request=(value,onPartial)=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject,onPartial,start:performance.now(),timer:setTimeout(()=>{pending.delete(id);reject(Error('Native request timeout: '+value.type));},30000)});try{send({id,...value});}catch(error){clearTimeout(pending.get(id).timer);pending.delete(id);reject(error);}});
 const memory=()=>{const value={cb:koffi.sizeof(Memory)};assert.ok(getMemory(handle,value,value.cb));return{resident:value.WorkingSetSize,private:value.PrivateUsage,peakPrivate:value.PeakPagefileUsage,peakResident:value.PeakWorkingSetSize};};
 async function stop(){if(closed)return;closed=true;const timer=setTimeout(()=>child.kill(),10000);try{if(child.exitCode===null)child.stdin.end(JSON.stringify({type:'stop'})+'\n');const result=await exit;assert.equal(result.code,0,errors.join(''));assert.deepEqual(errors,[]);if(failure)throw failure;}finally{clearTimeout(timer);for(const p of pending.values())clearTimeout(p.timer);close(handle);}}
 try{if(init)send({type:'init',settings:init});await until(()=>{if(failure)throw failure;assert.equal(child.exitCode,null,errors.join(''));return ready;});return{...ready,pid:child.pid,states,events,send,request,memory,stop,state:()=>state,observeState:listener=>{listeners.add(listener);return()=>listeners.delete(listener);}};}catch(error){await stop().catch(()=>{});throw error;}
}
module.exports={client,until,delay};
