import './system-information.css';
import './text.css';
import './search.css';
import './styles.css';
import './disk.css';
import './preview.css';
import './preview-chrome.css';
import './refinement.css';
import './color.css';
import './hud.css';
import './echo.css';
import './preview-redesign.css';
import './selection.css';
import './interface-refinement.css';
import './components.css';
import {setupAppearance} from './appearance';
import {setupTextSelection} from './selection';
import {setupTooltips} from './tooltip';
import {setupSegments} from './segments';
import {setupWindowVisibility} from './window-visibility';
setupAppearance();setupTextSelection();setupTooltips();setupSegments();
const view=new URLSearchParams(location.search).get('view')||'main';
if(['main','file-action','preview','picker','search','color-editor','dialog-bar'].includes(view))setupWindowVisibility();
const render=async()=>{
 if(view==='echo')(await import('./hud')).renderHUD();
 else if(view==='color-picker')await (await import('./color-view')).renderColorPicker();
 else if(view==='color-editor')(await import('./color-editor-view')).renderColorEditor();
 else if(view==='command-confirm')await (await import('./menu-confirmation-view')).renderMenuConfirmation();
 else if(view==='preview')await (await import('./preview-view')).renderPreview();
 else if(view==='picker')(await import('./picker-view')).renderPicker();
 else if(view==='file-action')await (await import('./file-action-view')).renderFileAction();
 else if(view==='search-menu')await (await import('./search-menu')).renderSearchMenu();
 else if(view==='file-context')await (await import('./file-context-view')).renderFileContextMenu();
 else if(view==='dialog-bar')await (await import('./dialog-bar-view')).renderDialogBar();
 else if(view==='search')await (await import('./search-view')).renderSearch();
 else (await import('./main-view')).renderMain();
};
void render().catch(console.error);
