import './clicker.css';
import {api,button,icon,q,switchControl,toast} from './ui';
import {bindPreference} from './preferences';
import {setupShortcut} from './shortcut';
import type {ClickerState} from '../shared/utilities';

export function clickerPage(){return `<div data-enhancement-panel="clicker" hidden><div class="clicker-layout"><section class="settings-card clicker-card"><div class="setting-row clicker-heading"><span class="setting-icon">${icon('mouse')}</span><div class="setting-copy"><h2>鼠标连点</h2></div>${switchControl('clicker-enabled','开启鼠标连点')}</div><div class="clicker-settings">
<div class="preference-row"><label for="clicker-button">按键</label><select id="clicker-button" aria-label="鼠标按键"><option value="left">左键</option><option value="right">右键</option><option value="middle">中键</option></select></div>
<div class="preference-row"><label for="clicker-double">点击方式</label><select id="clicker-double" aria-label="点击方式"><option value="single">单击</option><option value="double">双击</option></select></div>
<div class="preference-row"><label for="clicker-method">模拟方式</label><select id="clicker-method" aria-label="模拟方式"><option value="mouseEvent">鼠标事件</option><option value="sendInput">输入注入</option></select></div>
<div class="preference-row"><label for="clicker-interval">间隔</label><div class="field-group"><input type="number" id="clicker-interval" min="10" max="3600000" step="10" aria-label="点击间隔"><span>毫秒</span></div></div>
<div class="preference-row"><label for="clicker-repeat-mode">次数</label><div class="clicker-inline-fields"><select id="clicker-repeat-mode" aria-label="点击次数模式"><option value="until">直到停止</option><option value="count">指定次数</option></select><div class="field-group" id="clicker-repeat-field" hidden><input type="number" id="clicker-repeat" min="1" max="1000000" aria-label="点击次数"><span>次</span></div></div></div>
<div class="preference-row"><label for="clicker-target">位置</label><select id="clicker-target" aria-label="点击位置"><option value="cursor">当前鼠标位置</option><option value="fixed">固定屏幕坐标</option></select></div>
<div class="clicker-fixed" id="clicker-fixed" hidden><div class="field-group"><label for="clicker-x">X</label><input id="clicker-x" type="number" min="-100000" max="100000" aria-label="固定位置 X"><label for="clicker-y">Y</label><input id="clicker-y" type="number" min="-100000" max="100000" aria-label="固定位置 Y">${button('clicker-capture','获取当前位置','crosshair')}</div><label class="clicker-restore"><input id="clicker-restore" type="checkbox">点击后恢复鼠标位置</label></div>
<div class="preference-row"><label for="clicker-shortcut">快捷键</label><input id="clicker-shortcut" aria-label="鼠标连点快捷键"></div></div></section>
<aside class="settings-card clicker-status-card" id="clicker-status-card"><div class="clicker-status-icon">${icon('mouse')}</div><strong id="clicker-status-title">准备就绪</strong><span id="clicker-status-detail">按 F6 开始连点</span><div class="clicker-metrics"><div><b id="clicker-count">0</b><span>已点击</span></div><div><b id="clicker-remaining">—</b><span>剩余次数</span></div></div><p class="clicker-message" id="clicker-message" role="status"></p><div class="clicker-actions">${button('clicker-stop','停止')}${button('clicker-start','开始','play',true)}</div></aside></div></div>`;}

export function setupClicker(){
  setupShortcut(q<HTMLInputElement>('clicker-shortcut'));
  let state:ClickerState={running:false,clicks:0,remaining:0,error:''};
  const controls=['clicker-enabled','clicker-button','clicker-double','clicker-method','clicker-interval','clicker-repeat-mode','clicker-repeat','clicker-target','clicker-x','clicker-y','clicker-restore','clicker-shortcut'];
  const fields=()=>{const count=q<HTMLSelectElement>('clicker-repeat-mode').value==='count',fixed=q<HTMLSelectElement>('clicker-target').value==='fixed';q('clicker-repeat-field').hidden=!count;q('clicker-fixed').hidden=!fixed;q<HTMLInputElement>('clicker-repeat').disabled=!count;for(const id of controls)if(id!=='clicker-enabled')q<HTMLInputElement|HTMLSelectElement>(id).disabled=state.running;};
  const render=(next:ClickerState)=>{state=next;fields();q('clicker-status-title').textContent=next.running?'正在连点':next.error?'已停止':'准备就绪';q('clicker-status-detail').textContent=next.running?'按快捷键可立即停止':`按 ${q<HTMLInputElement>('clicker-shortcut').value||'快捷键'} 开始连点`;q('clicker-count').textContent=String(next.clicks);q('clicker-remaining').textContent=next.remaining?String(next.remaining):'—';q('clicker-message').textContent=next.error||'';q<HTMLButtonElement>('clicker-start').disabled=next.running;q<HTMLButtonElement>('clicker-stop').disabled=!next.running;q('clicker-status-card').classList.toggle('running',next.running);};
  const load=async()=>{const config=(await api.settings()).utilities.clicker;q<HTMLInputElement>('clicker-enabled').checked=config.enabled;q<HTMLSelectElement>('clicker-button').value=config.button;q<HTMLSelectElement>('clicker-double').value=config.double?'double':'single';q<HTMLSelectElement>('clicker-method').value=config.method;q<HTMLInputElement>('clicker-interval').value=String(config.intervalMs);q<HTMLSelectElement>('clicker-repeat-mode').value=config.repeat?'count':'until';q<HTMLInputElement>('clicker-repeat').value=String(config.repeat||1);q<HTMLSelectElement>('clicker-target').value=config.target;q<HTMLInputElement>('clicker-x').value=String(config.x);q<HTMLInputElement>('clicker-y').value=String(config.y);q<HTMLInputElement>('clicker-restore').checked=config.restore;q<HTMLInputElement>('clicker-shortcut').value=config.shortcut;render(await api.clickerState());};
  const patch=()=>({utilities:{clicker:{enabled:q<HTMLInputElement>('clicker-enabled').checked,button:q<HTMLSelectElement>('clicker-button').value as 'left'|'right'|'middle',double:q<HTMLSelectElement>('clicker-double').value==='double',method:q<HTMLSelectElement>('clicker-method').value as 'mouseEvent'|'sendInput',intervalMs:Number(q<HTMLInputElement>('clicker-interval').value),repeat:q<HTMLSelectElement>('clicker-repeat-mode').value==='count'?Number(q<HTMLInputElement>('clicker-repeat').value):0,target:q<HTMLSelectElement>('clicker-target').value as 'cursor'|'fixed',x:Number(q<HTMLInputElement>('clicker-x').value),y:Number(q<HTMLInputElement>('clicker-y').value),restore:q<HTMLInputElement>('clicker-restore').checked,shortcut:q<HTMLInputElement>('clicker-shortcut').value.trim()}}});
  for(const id of controls)bindPreference(q(id),patch,load);
  q('clicker-repeat-mode').addEventListener('change',fields);q('clicker-target').addEventListener('change',fields);
  q('clicker-capture').onclick=()=>void api.clickerCapture().then(point=>{q<HTMLInputElement>('clicker-x').value=String(point.x);q<HTMLInputElement>('clicker-y').value=String(point.y);return api.patchSettings(patch());}).catch(toast);
  q('clicker-start').onclick=()=>void (async()=>{if(!q<HTMLInputElement>('clicker-enabled').checked){q<HTMLInputElement>('clicker-enabled').checked=true;await api.patchSettings(patch());}render(await api.clickerStart());})().catch(toast);
  q('clicker-stop').onclick=()=>void api.clickerStop().then(render).catch(toast);
  api.onUtilityState(value=>render(value.clicker));
  void load().catch(toast);
}
