import {esc,icon} from './ui';
import {hydrateFileIcons} from './shell-icons';
import {closeControls,openControl,releaseControl} from './controls';
export interface CommandChoice {id:string;label:string;category:string;icon?:string;path?:string;keywords?:string;detail?:string}
let current:HTMLElement|undefined;
/** Searchable grouped selection; keyboard navigation, viewport limits and dismissal. */
export function chooseCommand(anchor:HTMLElement,choices:readonly CommandChoice[],selected:string,onChoose:(choice:CommandChoice)=>void,title='选择内置命令') {
 closeControls();current?.remove();const popup=current=document.createElement('div');popup.className='command-picker';popup.popover='auto';popup.setAttribute('aria-label',title);
 const groups=['全部',...new Set(choices.map(c=>c.category))];let category='全部',scrollingCategory:string|undefined;
 popup.innerHTML=`<div class="command-picker-query">${icon('search')}<input placeholder="搜索命令" aria-label="搜索命令"></div><div class="command-picker-body"><nav class="command-picker-categories" aria-label="命令分类">${groups.map(group=>`<button type="button" class="quiet" data-command-category="${esc(group)}" aria-pressed="${group===category}">${esc(group)}</button>`).join('')}</nav><div class="command-picker-list" role="listbox" aria-label="${esc(title)}"></div></div>`;
 document.body.append(popup);popup.showPopover();
 const position=()=>{const box=anchor.getBoundingClientRect(),width=Math.min(430,innerWidth-16),below=Math.max(0,innerHeight-box.bottom-13),above=Math.max(0,box.top-13),down=below>=360||below>=above,room=down?below:above;
  popup.dataset.side=down?'bottom':'top';popup.style.width=width+'px';popup.style.left=Math.max(8,Math.min(box.left,innerWidth-width-8))+'px';popup.style.maxHeight=Math.min(520,room)+'px';popup.style.top=Math.max(8,Math.min(down?box.bottom+5:box.top-popup.offsetHeight-5,innerHeight-popup.offsetHeight-8))+'px';
 };position();
 const query=popup.querySelector<HTMLInputElement>('input')!,list=popup.querySelector<HTMLElement>('[role=listbox]')!;
 const scroll=(event:Event)=>{if(event.target instanceof Element&&event.target.contains(anchor))position();};
 const close=()=>{window.removeEventListener('resize',position);document.removeEventListener('scroll',scroll,true);releaseControl(close);popup.remove();if(current!==popup)return;current=undefined;if(anchor.isConnected)anchor.focus();};
 window.addEventListener('resize',position);document.addEventListener('scroll',scroll,true);openControl(close);
 const highlight=()=>popup.querySelectorAll<HTMLElement>('[data-command-category]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.commandCategory===category)));
 const draw=()=>{const term=query.value.trim().toLowerCase(),matches=choices.filter(c=>(c.label+' '+c.category+' '+(c.keywords||'')).toLowerCase().includes(term)),categories=[...new Set(matches.map(c=>c.category))];highlight();
  list.innerHTML=categories.map(category=>`<div class="command-picker-category" data-category-heading="${esc(category)}">${esc(category)}</div>`+matches.filter(c=>c.category===category).map(c=>`<button type="button" role="option" aria-selected="${c.id===selected}" data-command="${esc(c.id)}" class="quiet">${c.path?`<span class="menu-file-icon" data-file-icon="${esc(c.path)}">${icon(c.icon||'window')}</span>`:icon(c.icon||'window')}<span>${esc(c.label)}</span>${c.detail?`<small>${esc(c.detail)}</small>`:''}${c.id===selected?icon('check'):''}</button>`).join('')).join('')||'<p class="muted">没有匹配的命令</p>';list.scrollTop=0;hydrateFileIcons(list);
  list.querySelectorAll<HTMLButtonElement>('[data-command]').forEach(button=>button.onclick=()=>{const choice=choices.find(c=>c.id===button.dataset.command);close();if(choice)onChoose(choice);});position();
 };query.oninput=()=>{scrollingCategory=undefined;category='全部';draw();};popup.querySelectorAll<HTMLButtonElement>('[data-command-category]').forEach(button=>button.onclick=()=>{const next=button.dataset.commandCategory!;if(query.value){query.value='';draw();}category=next;highlight();const heading=[...list.querySelectorAll<HTMLElement>('[data-category-heading]')].find(node=>node.dataset.categoryHeading===next),top=heading?list.scrollTop+heading.getBoundingClientRect().top-list.getBoundingClientRect().top:0,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;scrollingCategory=reduced?undefined:next;list.scrollTo({top,behavior:reduced?'instant':'smooth'});});
 list.onscroll=()=>{if(query.value||scrollingCategory)return;const top=list.getBoundingClientRect().top,headings=[...list.querySelectorAll<HTMLElement>('[data-category-heading]')],heading=headings.filter(node=>node.getBoundingClientRect().top<=top+4).at(-1);category=list.scrollTop<=1?'全部':heading?.dataset.categoryHeading||'全部';highlight();};list.onscrollend=()=>{scrollingCategory=undefined;};for(const event of ['wheel','touchstart','pointerdown','keydown'])list.addEventListener(event,()=>{scrollingCategory=undefined;},{passive:true});
 popup.onkeydown=event=>{const categoryFocus=(document.activeElement as HTMLElement)?.closest('.command-picker-categories'),buttons=[...(categoryFocus?popup.querySelectorAll<HTMLButtonElement>('[data-command-category]'):list.querySelectorAll<HTMLButtonElement>('button'))],at=buttons.indexOf(document.activeElement as HTMLButtonElement);if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();const to=event.key==='Home'?0:event.key==='End'?buttons.length-1:at<0?event.key==='ArrowDown'?0:buttons.length-1:Math.max(0,Math.min(buttons.length-1,at+(event.key==='ArrowDown'?1:-1)));buttons[to]?.focus();buttons[to]?.scrollIntoView({block:'nearest'});}else if(event.key==='Escape'){event.preventDefault();event.stopPropagation();close();}};
 popup.addEventListener('toggle',event=>{if((event as ToggleEvent).newState==='closed')close();});draw();query.focus();return close;
}
