import {api,q,icon,esc,button} from './ui';
import {hydrateFileIcons} from './shell-icons';
import type {FileMenuTarget,FileMenuAction} from '../shared/file-menu';
export async function renderFileContextMenu(){
 document.body.classList.add('file-context-window');q('app').innerHTML='<div class="file-context-shell"><div id="file-context-content"></div><p id="file-context-error" role="alert" hidden></p></div>';
 let target:FileMenuTarget|null=null,page:'root'|'apps'|'rename'='root',busy=false,request=0,expanded=false,hover:ReturnType<typeof setTimeout>|undefined;
 const shell=document.querySelector('.file-context-shell')!;
 shell.addEventListener('pointermove',()=>shell.classList.remove('keyboard-mode'));
 document.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key))shell.classList.add('keyboard-mode');});
 const outerHeight=(element:Element)=>{const style=getComputedStyle(element);return element.getBoundingClientRect().height+parseFloat(style.marginTop)+parseFloat(style.marginBottom);};
 const resize=()=>{if(!target)return;const content=q('file-context-content'),notice=q('file-context-error');
  // A flex list fills the old window height. Measure its rows so empty and shorter menus can shrink.
  const contentHeight=[...content.children].reduce((sum,element)=>sum+(element.classList.contains('file-context-list')?[...element.children].reduce((height,row)=>height+outerHeight(row),0):outerHeight(element)),0);
  const style=getComputedStyle(shell);void api.fileMenuSize(target.session,Math.ceil(contentHeight+parseFloat(style.paddingTop)+parseFloat(style.paddingBottom)+(notice.hidden?0:outerHeight(notice)))).catch(()=>{});
 };
 const error=(e:unknown)=>{q('file-context-error').textContent=String(e).replace(/^Error: /,'').replace(/^Error invoking remote method '[^']+': Error: /,'');q('file-context-error').hidden=false;resize();};
 const collapse=()=>{clearTimeout(hover);if(expanded)void api.fileMenuClose(true,true);};
 const run=async(action:FileMenuAction,value?:string)=>{if(!target||busy)return;const session=target.session;busy=true;try{await api.fileMenuAction(session,action,value);}catch(e){if(target.session===session)error(e);}finally{if(target.session===session)busy=false;}};
 const row=(action:string,label:string,glyph:string,key='',danger=false)=>`<button role="menuitem" data-file-action="${action}"${action==='apps'?' aria-haspopup="menu" aria-expanded="false"':''} class="file-context-item${danger?' danger':''}">${icon(glyph)}<span>${label}</span>${action==='apps'?icon('chevron'):key?`<kbd>${key}</kbd>`:''}</button>`;
 const openApps=(focus=false)=>{if(!target)return;clearTimeout(hover);const entry=q('file-context-content').querySelector<HTMLButtonElement>('[data-file-action=apps]');if(entry)void api.fileMenuSubmenu(target.session,entry.getBoundingClientRect().top,focus).catch(error);};
 const renderApps=async()=>{if(!target)return;page='apps';const session=target.session,revision=++request;q('file-context-content').innerHTML='<div id="file-context-apps" role="menu" class="file-context-list"><span class="file-context-loading">正在读取应用…</span></div>';resize();try{const items=await api.fileMenuApps(session);if(target?.session!==session||page!=='apps'||request!==revision)return;q('file-context-apps').innerHTML=items.map((item,i)=>`<button role="menuitem" data-open-app="${i}" class="file-context-item">${item.icon?`<img src="${esc(item.icon)}" alt="">`:icon('window')}<span>${esc(item.name)}</span></button>`).join('')+(items.length?'<hr>':'')+row('choose','选择其他应用','plus');q('file-context-apps').querySelectorAll<HTMLButtonElement>('[data-open-app]').forEach(b=>b.onclick=()=>void run('open-with',items[Number(b.dataset.openApp)].id));q('file-context-apps').querySelector<HTMLButtonElement>('[data-file-action=choose]')!.onclick=()=>void run('open-with',':choose');resize();q('file-context-apps').querySelector<HTMLButtonElement>('[role=menuitem]')?.focus();}catch(e){if(request===revision)error(e);}};
 const render=()=>{if(!target)return;clearTimeout(hover);expanded=false;q('file-context-error').hidden=true;if(target.submenu){void renderApps();return;}page='root';request++;const file=!target.launchKind;q('file-context-content').innerHTML=`<div class="file-context-heading"><span data-file-icon="${esc(target.path)}">${icon(target.launchKind==='setting'?'settings':target.directory?'folder':'file')}</span><strong>${esc(target.name)}</strong></div><div role="menu" class="file-context-list">${row('open','打开','open','Enter')}${file?row('preview','快速预览','preview','Alt+P'):''}${file&&!target.directory?row('apps','打开方式','window','›'):''}${file?row('reveal','在资源管理器中显示','folder'):''}<hr>${file?row('copy','复制','copy','Ctrl+C')+row('cut','剪切','cut','Ctrl+X')+row('copy-path','复制路径','link'):row('copy-name','复制名称','copy')}${file?'<hr>'+row('rename','重命名','rename','F2')+row('trash','移入回收站','trash','Delete',true)+'<hr>'+row('native','更多系统操作','ellipsis'):''}</div>`;hydrateFileIcons(q('file-context-content'));resize();q('file-context-content').querySelectorAll<HTMLButtonElement>('[data-file-action]').forEach(b=>{b.onclick=()=>{const action=b.dataset.fileAction!;if(action==='apps')openApps(true);else if(action==='rename')rename();else{collapse();void run(action as FileMenuAction);}};b.onpointerenter=()=>{clearTimeout(hover);if(b.dataset.fileAction==='apps')hover=setTimeout(()=>openApps(),100);else collapse();};b.onpointerleave=()=>clearTimeout(hover);});q('file-context-content').querySelector<HTMLButtonElement>('[role=menuitem]')?.focus();};
 const rename=()=>{if(!target)return;collapse();page='rename';request++;q('file-context-content').innerHTML=`<form id="file-rename-form"><label for="file-rename-name">重命名</label><input id="file-rename-name" value="${esc(target.name)}" maxlength="255" spellcheck="false"><div class="file-rename-actions">${button('file-rename-cancel','取消')}${button('file-rename-confirm','确定','',true)}</div></form>`;q<HTMLButtonElement>('file-rename-cancel').type='button';q('file-rename-cancel').onclick=render;q('file-rename-form').onsubmit=e=>{e.preventDefault();void run('rename',q<HTMLInputElement>('file-rename-name').value);};resize();const input=q<HTMLInputElement>('file-rename-name');input.focus();input.setSelectionRange(0,target.directory?input.value.length:Math.max(0,input.value.lastIndexOf('.'))||input.value.length);};
 api.onFileMenuExpanded(open=>{expanded=open;const entry=q('file-context-content').querySelector('[data-file-action=apps]');entry?.classList.toggle('submenu-open',open);entry?.setAttribute('aria-expanded',String(open));});
 let received=false;api.onFileMenu(value=>{received=true;target=value;busy=false;render();});const initial=await api.fileMenuData();if(initial&&!received){target=initial;render();}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();if(page==='rename')render();else void api.fileMenuClose(true);return;}if(e.target instanceof HTMLInputElement)return;const buttons=[...q('file-context-content').querySelectorAll<HTMLButtonElement>('[role=menuitem]:not(:disabled)')];if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const at=buttons.indexOf(document.activeElement as HTMLButtonElement),next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(at+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus();if(page==='root'&&buttons[next]?.dataset.fileAction!=='apps')collapse();}else if(e.key==='ArrowRight'&&page==='root'&&(document.activeElement as HTMLElement)?.dataset.fileAction==='apps'){e.preventDefault();openApps(true);}else if(e.key==='ArrowLeft'&&target?.submenu){e.preventDefault();void api.fileMenuClose(true);}else if(e.key==='Tab'){e.preventDefault();void api.fileMenuClose(true);}else if(page==='root'&&target&&!target.launchKind){if(e.key==='F2'){e.preventDefault();rename();}else if(e.key==='Delete'){e.preventDefault();collapse();void run('trash');}else if(e.ctrlKey&&['c','x'].includes(e.key.toLowerCase())){e.preventDefault();collapse();void run(e.key.toLowerCase()==='c'?'copy':'cut');}}});
}
