import catalogURL from '../../assets/lucide-catalog.json?url';
import {icon,iconButton,esc,q,registerIcons} from './ui';
import type {IconNode} from 'lucide';
import {dialogMarkup,openDialog,closeDialog} from './dialog';
let pending:Promise<string[]>|undefined;
export function loadMenuIcons(){return pending??=fetch(catalogURL).then(r=>{if(!r.ok)throw new Error('图标读取失败');return r.json() as Promise<Record<string,IconNode>>;}).then(catalog=>{registerIcons(catalog);return Object.keys(catalog).sort();});}
const aliases:Record<string,string>={folder:'文件夹 目录',file:'文件 文档',terminal:'终端 命令',settings:'设置 齿轮',star:'星 收藏',bookmark:'书签 收藏',heart:'爱心 喜欢',search:'搜索 查找',music:'音乐 音频',image:'图片 图像',video:'视频',code:'代码 开发',globe:'网页 浏览器',palette:'颜色 调色',coffee:'咖啡 唤醒',house:'首页 主页',layers:'图层 层级',list:'列表 菜单',panel:'侧边栏 面板',pin:'置顶 固定',arrow:'箭头 方向',download:'下载',upload:'上传',archive:'压缩 归档',app:'应用 程序',game:'游戏',mail:'邮件',clock:'时间 时钟',history:'历史',power:'电源 开关',lock:'锁 安全'};
export async function chooseIcon(current:string,onChoose:(name:string)=>void){
 const names=await loadMenuIcons(),holder=document.createElement('template');holder.innerHTML=dialogMarkup({id:'icon-picker-dialog',title:'选择图标',closeId:'icon-picker-close',className:'icon-picker-dialog',body:`<div class="icon-picker-search">${icon('search')}<input id="icon-picker-query" placeholder="搜索图标" aria-label="搜索 Lucide 图标" autocomplete="off"></div><div class="icon-picker-grid" role="listbox" aria-label="Lucide 图标"></div>`,actions:'<span id="icon-picker-count"></span><button class="quiet" id="icon-picker-more">显示更多</button>'});const dialog=holder.content.firstElementChild as HTMLDialogElement;
 document.body.append(dialog);let limit=120,filtered=names;const query=dialog.querySelector<HTMLInputElement>('#icon-picker-query')!,grid=dialog.querySelector<HTMLElement>('.icon-picker-grid')!;
 const draw=()=>{grid.innerHTML=filtered.slice(0,limit).map(name=>`<button class="icon-choice quiet" role="option" aria-selected="${'lucide:'+name===current}" aria-label="${name}" title="${name}" data-icon="${name}">${icon('lucide:'+name)}</button>`).join('')||'<p class="icon-picker-empty">没有匹配的图标</p>';q('icon-picker-count').textContent=`${filtered.length} 个图标`;q('icon-picker-more').hidden=limit>=filtered.length;grid.querySelectorAll<HTMLButtonElement>('[data-icon]').forEach(b=>b.onclick=()=>{onChoose('lucide:'+b.dataset.icon);void closeDialog(dialog);});};
 query.oninput=()=>{const term=query.value.trim().toLowerCase();filtered=names.filter(name=>name.includes(term)||Object.entries(aliases).some(([key,words])=>name.includes(key)&&words.includes(term)));limit=120;grid.scrollTop=0;draw();};q('icon-picker-more').onclick=()=>{limit+=120;draw();};q('icon-picker-close').onclick=()=>void closeDialog(dialog);
 grid.onkeydown=e=>{const buttons=[...grid.querySelectorAll<HTMLButtonElement>('button')],at=buttons.indexOf(document.activeElement as HTMLButtonElement),columns=Math.max(1,Math.floor(grid.clientWidth/44));const delta=({ArrowRight:1,ArrowLeft:-1,ArrowDown:columns,ArrowUp:-columns} as Record<string,number>)[e.key];if(delta){e.preventDefault();buttons[Math.max(0,Math.min(buttons.length-1,at+delta))]?.focus();}};
 dialog.addEventListener('close',()=>dialog.remove(),{once:true});draw();openDialog(dialog);query.focus();
}
