import {hydrateFileIcons} from './shell-icons';
import {dialogMarkup,openDialog,closeDialog} from './dialog';
import {api,q,button,iconButton,icon,esc,toast} from './ui';
import type {LocksmithState} from '../shared/locksmith';
import {isWindowVisible,onWindowVisibility} from './window-visibility';
export function locksmithCard(){return `<div class="settings-card" id="file-lock-card"><div class="setting-row"><span class="setting-icon">${icon('locksmith')}</span><div class="setting-copy"><h2>检查占用</h2><p>查找正在使用文件或目录的进程。</p></div>${iconButton('lock-open-window','独立窗口','open')}${iconButton('lock-refresh','重新扫描','refresh')}</div><div class="utility-fields lock-target-input"><input id="lock-path" aria-label="检查占用的文件或目录" placeholder="输入文件或目录路径">${button('lock-add','添加')}${button('lock-pick-file','文件','file')}${button('lock-pick-folder','目录','folder')}</div><div class="lock-targets" id="lock-targets"></div><div class="utility-fields"><span id="lock-status" role="status">尚未检查</span><div class="spacer"></div>${button('lock-cancel','停止')}${button('lock-scan','检查占用','search',true)}</div><p class="utility-message" id="lock-summary"></p><div class="lock-results" id="lock-results"></div></div>${dialogMarkup({id:"lock-end-dialog",title:"结束进程",closeId:"lock-end-close",body:`<p id="lock-end-name"></p><p class="footnote">此进程中未保存的内容可能丢失。结束后会释放它占用的文件。</p>`,actions:`<button id="lock-end-cancel" autofocus>取消</button>${button('lock-end-confirm','结束进程','',true)}`})}`;}
export function setupLocksmith(){
  let paths:string[]=[],state:LocksmithState|undefined,pending='',active=false,targetsTouched=false,targetRevision=0,scanTimer:ReturnType<typeof setTimeout>|undefined;let inspectTask=Promise.resolve();const dialog=q<HTMLDialogElement>('lock-end-dialog');
  q('lock-open-window').hidden=document.body.classList.contains('file-action-window');q('lock-open-window').onclick=()=>{cancelQueued();void api.cancelLocks().then(()=>api.openFileAction('locksmith',paths)).catch(toast);};
  const showing=()=>active&&isWindowVisible();
  const targets=()=>{if(!showing())return;q('lock-targets').innerHTML=paths.map((path,i)=>`<div><span class="lock-target-icon" data-file-icon="${esc(path)}">${icon('file')}</span><span title="${esc(path)}"><strong>${esc(path.split(/[\\/]/).filter(Boolean).at(-1)||path)}</strong><small>${esc(path)}</small></span><button class="icon-button quiet" data-remove="${i}" aria-label="移除 ${esc(path)}">${icon('close')}</button></div>`).join('');q('lock-targets').querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.onclick=()=>{targetsTouched=true;paths.splice(Number(b.dataset.remove),1);targets();autoScan();});hydrateFileIcons(q('lock-targets'),showing);};
  const add=(path:string,automatic=true)=>{path=path.trim();if(!path||paths.some(p=>p.toLowerCase()===path.toLowerCase()))return;if(paths.length>=32)return toast('一次最多检查 32 个目标');targetsTouched=true;paths.push(path);targets();if(automatic)autoScan();};
  const render=(s:LocksmithState)=>{state=s;if(!showing())return;if(!targetsTouched){paths=[...s.targets];targets();}q('lock-status').textContent=s.running?`正在检查 ${s.checked} / ${s.total} 个进程`:s.error?'检查未完成':s.cancelled?'已停止':s.checked?`找到 ${s.processes.length} 个占用进程`:'尚未检查';q('lock-summary').textContent=s.error||[s.denied?`${s.denied} 个进程不可访问`:'',s.timedOut?`${s.timedOut} 个进程查询未完成`:'',s.modulesUnavailable?`${s.modulesUnavailable} 个进程未能检查全部模块`:'',!s.running&&s.checked&&!s.processes.length?'未在已检查范围内发现占用':''].filter(Boolean).join(' · ');for(const id of ['lock-scan','lock-refresh'])q<HTMLButtonElement>(id).disabled=s.running;q<HTMLButtonElement>('lock-cancel').disabled=!s.running;
    const empty=q('lock-empty');if(empty){empty.hidden=s.processes.length>0;q('lock-empty-title').textContent=s.running?'正在检查占用':s.error?'检查未完成':s.cancelled?'检查已停止':s.checked?'未发现占用进程':'添加文件或文件夹';}
    const open=new Set([...q('lock-results').querySelectorAll<HTMLDetailsElement>('details[open]')].map(e=>e.dataset.token));q('lock-results').innerHTML=s.processes.map(p=>`<div class="lock-process"><div class="lock-process-head"><span class="lock-process-icon" data-file-icon="${esc(p.process)}">${icon('file')}</span><div><strong>${esc(p.process.split('\\').pop()||'进程')}</strong><span>PID ${p.pid} · ${p.files.length} 个文件</span></div><button data-end="${p.token}" ${s.running?'disabled':''}>结束进程…</button></div><details data-token="${p.token}" ${open.has(p.token)?'open':''}><summary>占用文件</summary><ul>${p.files.map(f=>`<li title="${esc(f)}">${esc(f)}</li>`).join('')}</ul></details></div>`).join('');hydrateFileIcons(q('lock-results'),showing);q('lock-results').querySelectorAll<HTMLButtonElement>('[data-end]').forEach(b=>b.onclick=()=>{const p=state?.processes.find(p=>p.token===b.dataset.end);if(!p)return;pending=p.token;q('lock-end-name').textContent=`${p.process.split('\\').pop()} · PID ${p.pid}`;openDialog(dialog);});};
  const scan=()=>{if(!paths.length)add(q<HTMLInputElement>('lock-path').value.trim(),false);return api.scanLocks(paths).then(render);};
  q('lock-add').onclick=()=>{add(q<HTMLInputElement>('lock-path').value.trim());q<HTMLInputElement>('lock-path').value='';};q('lock-path').onkeydown=e=>{if(e.key==='Enter')q('lock-add').click();};q('lock-pick-file').onclick=()=>void api.pickFile().then(p=>p&&add(p)).catch(toast);q('lock-pick-folder').onclick=()=>void api.pickDirectory().then(p=>p&&add(p)).catch(toast);q('lock-scan').onclick=q('lock-refresh').onclick=()=>{cancelQueued();void scan().catch(toast);};q('lock-cancel').onclick=()=>{cancelQueued();void api.cancelLocks().catch(toast);};
  q('lock-end-cancel').onclick=q('lock-end-close').onclick=()=>closeDialog(dialog);q('lock-end-confirm').onclick=()=>{const b=q<HTMLButtonElement>('lock-end-confirm');b.disabled=true;void api.endLockProcess(pending).then(()=>closeDialog(dialog)).catch(toast).finally(()=>b.disabled=false);};
  const cancelQueued=()=>{clearTimeout(scanTimer);scanTimer=undefined;targetRevision++;};
  const inspect=(targets:string[])=>{
    clearTimeout(scanTimer);scanTimer=undefined;const revision=++targetRevision;
    return inspectTask=inspectTask.catch(()=>{}).then(async()=>{
      if(revision!==targetRevision)return;await api.cancelLocks();if(revision!==targetRevision)return;
      targetsTouched=true;paths=[];for(const path of targets)add(path,false);q<HTMLInputElement>('lock-path').value='';if(paths.length)await scan();else render({running:false,targets:[],processes:[],checked:0,total:0,denied:0,timedOut:0,modulesUnavailable:0,error:'',cancelled:false});
    });
  };
  const autoScan=()=>{clearTimeout(scanTimer);const revision=++targetRevision;scanTimer=setTimeout(()=>{scanTimer=undefined;if(revision===targetRevision)void inspect([...paths]).catch(toast);},120);};
  api.onLockTarget(path=>{void inspect([path]).catch(toast);});
  api.onLocks(render);void api.lockState().then(s=>{if(!targetsTouched)render(s);}).catch(toast);
  const drop=q('lock-targets');drop.addEventListener('dragover',e=>e.preventDefault());drop.addEventListener('drop',e=>{e.preventDefault();for(const file of e.dataTransfer?.files||[]){const path=api.droppedFile(file);if(path)add(path);}});
  const resume=()=>{if(showing()){targets();if(state)render(state);}};
  onWindowVisibility(resume);
  return{activate(value:boolean){active=value;resume();},inspect};
}
