import {dialogMarkup,openDialog,closeDialog} from './dialog';
import {api,q,button,iconButton,icon,esc,toast} from './ui';
import type {LocksmithState} from '../shared/locksmith';
export function locksmithCard(){return `<div class="settings-card" id="file-lock-card"><div class="setting-row"><span class="setting-icon">${icon('locksmith')}</span><div class="setting-copy"><h2>文件占用</h2><p>查找正在使用文件或目录的进程。</p></div>${iconButton('lock-refresh','重新扫描','refresh')}</div><div class="utility-fields lock-target-input"><input id="lock-path" aria-label="检查占用的文件或目录" placeholder="输入文件或目录路径">${button('lock-add','添加')}${button('lock-pick-file','文件','file')}${button('lock-pick-folder','目录','folder')}</div><div class="lock-targets" id="lock-targets"></div><div class="utility-fields"><span id="lock-status" role="status">尚未检查</span><div class="spacer"></div>${button('lock-cancel','停止')}${button('lock-scan','检查占用','search',true)}</div><p class="utility-message" id="lock-summary"></p><div class="lock-results" id="lock-results"></div></div>${dialogMarkup({id:"lock-end-dialog",title:"结束进程",closeId:"lock-end-close",body:`<p id="lock-end-name"></p><p class="footnote">此进程中未保存的内容可能丢失。结束后会释放它占用的文件。</p>`,actions:`<button id="lock-end-cancel" autofocus>取消</button>${button('lock-end-confirm','结束进程','',true)}`})}`;}
export function setupLocksmith(){
  let paths:string[]=[],state:LocksmithState|undefined,pending='';const dialog=q<HTMLDialogElement>('lock-end-dialog');
  const targets=()=>{q('lock-targets').innerHTML=paths.map((path,i)=>`<div><span title="${esc(path)}">${esc(path)}</span><button class="icon-button quiet" data-remove="${i}" aria-label="移除 ${esc(path)}">${icon('close')}</button></div>`).join('');q('lock-targets').querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.onclick=()=>{paths.splice(Number(b.dataset.remove),1);targets();});};
  const add=(path:string)=>{if(!path.trim())return;if(paths.length>=32)return toast('一次最多检查 32 个目标');if(!paths.some(p=>p.toLowerCase()===path.toLowerCase()))paths.push(path);targets();};
  const render=(s:LocksmithState)=>{state=s;if(!paths.length){paths=[...s.targets];targets();}q('lock-status').textContent=s.running?`正在检查 ${s.checked} / ${s.total} 个进程`:s.error?'检查未完成':s.cancelled?'已停止':s.checked?`找到 ${s.processes.length} 个占用进程`:'尚未检查';q('lock-summary').textContent=s.error||[s.denied?`${s.denied} 个进程不可访问`:'',s.timedOut?`${s.timedOut} 个进程查询未完成`:'',s.modulesUnavailable?`${s.modulesUnavailable} 个进程未能检查全部模块`:'',!s.running&&s.checked&&!s.processes.length?'未在已检查范围内发现占用':''].filter(Boolean).join(' · ');for(const id of ['lock-scan','lock-refresh'])q<HTMLButtonElement>(id).disabled=s.running;q<HTMLButtonElement>('lock-cancel').disabled=!s.running;
    const open=new Set([...q('lock-results').querySelectorAll<HTMLDetailsElement>('details[open]')].map(e=>e.dataset.token));q('lock-results').innerHTML=s.processes.map(p=>`<div class="lock-process"><div class="lock-process-head">${icon('window')}<div><strong>${esc(p.process.split('\\').pop()||'进程')}</strong><span>PID ${p.pid} · ${p.files.length} 个文件</span></div><button data-end="${p.token}" ${s.running?'disabled':''}>结束进程…</button></div><details data-token="${p.token}" ${open.has(p.token)?'open':''}><summary>占用文件</summary><ul>${p.files.map(f=>`<li title="${esc(f)}">${esc(f)}</li>`).join('')}</ul></details></div>`).join('');q('lock-results').querySelectorAll<HTMLButtonElement>('[data-end]').forEach(b=>b.onclick=()=>{const p=state?.processes.find(p=>p.token===b.dataset.end);if(!p)return;pending=p.token;q('lock-end-name').textContent=`${p.process.split('\\').pop()} · PID ${p.pid}`;openDialog(dialog);});};
  const scan=()=>{if(!paths.length)add(q<HTMLInputElement>('lock-path').value.trim());return api.scanLocks(paths).then(render);};
  q('lock-add').onclick=()=>{add(q<HTMLInputElement>('lock-path').value.trim());q<HTMLInputElement>('lock-path').value='';};q('lock-path').onkeydown=e=>{if(e.key==='Enter')q('lock-add').click();};q('lock-pick-file').onclick=()=>void api.pickFile().then(p=>p&&add(p)).catch(toast);q('lock-pick-folder').onclick=()=>void api.pickDirectory().then(p=>p&&add(p)).catch(toast);q('lock-scan').onclick=q('lock-refresh').onclick=()=>void scan().catch(toast);q('lock-cancel').onclick=()=>void api.cancelLocks().catch(toast);
  q('lock-end-cancel').onclick=q('lock-end-close').onclick=()=>closeDialog(dialog);q('lock-end-confirm').onclick=()=>{const b=q<HTMLButtonElement>('lock-end-confirm');b.disabled=true;void api.endLockProcess(pending).then(()=>closeDialog(dialog)).catch(toast).finally(()=>b.disabled=false);};
  api.onLockTarget(path=>{paths=[];add(path);void scan().catch(toast);});
  api.onLocks(render);void api.lockState().then(render).catch(toast);
  const drop=q('lock-targets');drop.addEventListener('dragover',e=>e.preventDefault());drop.addEventListener('drop',e=>{e.preventDefault();for(const file of e.dataTransfer?.files||[]){const path=api.droppedFile(file);if(path)add(path);}});
}
