import {dialogMarkup,openDialog,closeDialog} from './dialog';
import {api,q,esc,icon,button,iconButton,action,toast,size} from './ui';
import {diskWarningPage,setupDiskWarning} from './disk-warning-view';
import type {MaintenanceKind,MaintenanceReport,MaintenanceEntry} from '../shared/maintenance';
import {isWindowVisible,onWindowVisibility} from './window-visibility';
const names={startup:'启动项',registry:'注册表',disk:'磁盘清理',alerts:'磁盘告警'};
const compactStatus=(v:string)=>v.startsWith('目标未找到')?'目标不存在':v.startsWith('目标存在')?'正常':v.startsWith('相对路径')?'间接命令':v.startsWith('网络路径')?'网络路径':v.startsWith('磁盘离线')?'磁盘离线':v.startsWith('无访问权限')?'无访问权限':v;
export function maintenancePage(){return `<div class="maintenance-page"><div class="toolbar module-toolbar"><div class="tabs" role="tablist" aria-label="系统维护">${Object.entries(names).map(([id,name])=>`<button id="${id}-tab" data-maintenance-tab="${id}" role="tab" aria-selected="${id==='startup'}" class="${id==='startup'?'selected':''}">${name}</button>`).join('')}</div><div class="spacer"></div><div id="maintenance-actions" class="toolbar">${iconButton('maintenance-export','导出报告','download')}${iconButton('maintenance-history','操作记录','history')}${button('cancel-maintenance','停止扫描','stop')}${button('scan-maintenance','重新扫描','refresh')}</div></div><div id="maintenance-scan-panel"><div class="maintenance-tools"><div class="filter-field">${icon('search')}<input id="maintenance-query" placeholder="筛选名称、来源或路径" aria-label="筛选维护结果"></div><select id="maintenance-filter" aria-label="维护结果过滤"><option value="all">全部项目</option><option value="actionable">可处理</option><option value="missing">目标不存在</option></select><span id="maintenance-status" role="status">尚未扫描</span></div><div class="maintenance-layout"><div class="maintenance-results"><div class="maintenance-list-head"><label><input type="checkbox" id="maintenance-select-all" aria-label="选择当前列表可处理项目">名称</label><span>状态</span></div><div id="maintenance-rows"></div>${button('maintenance-more','显示更多')}</div><aside class="maintenance-selection"><div class="selection-count"><strong id="maintenance-count">0</strong><span>项已选</span></div><div id="maintenance-bytes"></div><div id="maintenance-selected-names"></div>${button('maintenance-apply','处理所选','',true)}<span id="maintenance-outcome" role="status"></span></aside></div></div><div id="maintenance-alert-panel" hidden>${diskWarningPage()}</div></div>${dialogMarkup({id:"maintenance-confirm",title:"确认操作",closeId:"maintenance-confirm-close",titleId:"maintenance-confirm-title",className:"dialog-wide",body:`<p id="maintenance-confirm-detail"></p><div id="maintenance-confirm-list" class="confirm-items"></div>`,actions:`<button id="maintenance-confirm-cancel" autofocus>取消</button>${button('maintenance-confirm-run','确认','',true)}`})}${dialogMarkup({id:"maintenance-history-dialog",title:"操作记录",closeId:"maintenance-history-close",className:"dialog-wide",body:`<div id="maintenance-receipts"></div>`})}`;}
interface TabState {report?:MaintenanceReport;scanning:boolean;cancelling:boolean;restoreFocus:boolean;applying:boolean;selected:Set<string>;limit:number;query:string;filter:string;status:string;outcome:string;failures:string}
export function setupMaintenance(){
 const states=Object.fromEntries(['startup','registry','disk'].map(k=>[k,{scanning:false,cancelling:false,restoreFocus:false,applying:false,selected:new Set<string>(),limit:200,query:'',filter:'all',status:'尚未扫描',outcome:'',failures:''}])) as Record<MaintenanceKind,TabState>;
 let kind:MaintenanceKind|'alerts'='startup',mutation=false,moduleActive=false,statusFrame=0;const warning=setupDiskWarning();
 const showing=()=>moduleActive&&isWindowVisible();q('cancel-maintenance').hidden=true;
 const state=()=>states[kind as MaintenanceKind],entries=()=>state()?.report?.entries||[];
 const filtered=()=>{const s=state(),query=s.query.toLowerCase();return entries().filter(e=>(!query||[e.name,e.command,e.source,e.location].join(' ').toLowerCase().includes(query))&&(s.filter==='all'||s.filter==='actionable'&&!!e.action&&e.action!=='manage'||s.filter==='missing'&&e.status.includes('目标未找到')));};
 const selection=()=>{if(!showing()||kind==='alerts')return;const s=state(),list=entries().filter(e=>s.selected.has(e.id));q('maintenance-count').textContent=String(list.length);q('maintenance-bytes').textContent=kind==='disk'?size(list.reduce((sum,e)=>sum+(e.bytes||0),0)):'';q('maintenance-selected-names').innerHTML=list.slice(0,5).map(e=>`<span>${esc(e.name)}</span>`).join('')+(list.length>5?`<span>以及 ${list.length-5} 项</span>`:'');q<HTMLButtonElement>('maintenance-apply').disabled=mutation||s.scanning||!list.length;q('maintenance-apply').textContent=kind==='startup'?'禁用所选':'清理所选';const selectable=filtered().filter(e=>['clean','disable'].includes(e.action));q<HTMLInputElement>('maintenance-select-all').checked=!!selectable.length&&selectable.every(e=>s.selected.has(e.id));q<HTMLInputElement>('maintenance-select-all').indeterminate=selectable.some(e=>s.selected.has(e.id))&&!q<HTMLInputElement>('maintenance-select-all').checked;};
 const status=()=>{
  if(!showing()||kind==='alerts')return;const s=state(),restore=!s.scanning&&s.restoreFocus&&(document.activeElement===q('cancel-maintenance')||document.activeElement===document.body);if(!s.scanning)s.restoreFocus=false;
  q('maintenance-status').textContent=s.status;q('maintenance-status').classList.toggle('task-running',s.scanning||s.applying);
  q<HTMLButtonElement>('scan-maintenance').disabled=s.scanning||s.applying;
  q<HTMLButtonElement>('cancel-maintenance').hidden=!s.scanning;q<HTMLButtonElement>('cancel-maintenance').disabled=s.cancelling;
  const cancel=q<HTMLButtonElement>('cancel-maintenance'),label=s.cancelling?'正在停止…':'停止扫描';if(cancel.textContent!==label)cancel.innerHTML=icon('stop')+label;if(restore)q('scan-maintenance').focus({preventScroll:true});
  q<HTMLButtonElement>('maintenance-apply').disabled=mutation||s.scanning||s.applying||!s.selected.size;
  q('maintenance-outcome').textContent=s.outcome;q('maintenance-outcome').title=s.failures;
 };
 const draw=()=>{if(!showing()||kind==='alerts')return;const s=state(),list=filtered();q('maintenance-rows').innerHTML=list.length?list.slice(0,s.limit).map(e=>`<div class="maintenance-item ${s.selected.has(e.id)?'chosen':''}"><label class="maintenance-check"><input type="checkbox" data-maintain-id="${e.id}" aria-label="选择 ${esc(e.name)}" ${s.selected.has(e.id)?'checked':''} ${!e.action||e.action==='manage'?'disabled':''}></label><div class="maintenance-item-main"><div><strong>${esc(e.name)}</strong><span class="maintenance-category">${esc(e.category)}</span></div><span class="maintenance-path" title="${esc(e.location)}">${esc(e.command||e.source)}</span><details><summary>详情</summary><p>${esc(e.status)}${e.detail?' · '+esc(e.detail):''}</p><code>${esc(e.location)}</code></details></div><div class="maintenance-item-end"><span class="${e.status.includes('未找到')?'missing':''}">${e.bytes!==undefined?size(e.bytes):esc(compactStatus(e.status))}</span>${e.count!==undefined?`<small>${e.count.toLocaleString()} 个文件</small>`:''}${e.action==='manage'?'<button class="quiet" data-manage="pagefile">管理</button>':e.action==='hibernate'?'<small>关闭休眠</small>':''}</div></div>`).join(''):`<div class="maintenance-empty ${s.scanning?'loading':''}">${icon(s.scanning?'refresh':'check')}<span>${s.scanning?'正在扫描'+names[kind]:s.report?'没有符合条件的项目':s.status}</span></div>`;
  q<HTMLButtonElement>('maintenance-more').hidden=list.length<=s.limit;q('maintenance-more').textContent=`显示更多 · ${Math.min(s.limit,list.length)} / ${list.length}`;q('maintenance-rows').querySelectorAll<HTMLInputElement>('[data-maintain-id]').forEach(c=>c.onchange=()=>{if(c.checked)s.selected.add(c.dataset.maintainId!);else s.selected.delete(c.dataset.maintainId!);c.closest('.maintenance-item')?.classList.toggle('chosen',c.checked);selection();});q('maintenance-rows').querySelectorAll<HTMLElement>('[data-manage]').forEach(b=>b.onclick=()=>void api.maintenanceManage('pagefile').catch(toast));status();selection();
 };
 const scan=async(target:MaintenanceKind)=>{const s=states[target],previous=s.report;if(s.scanning||s.applying)return;s.scanning=true;s.status='正在扫描…';if(kind===target){if(!s.report)draw();else status();}try{s.report=await api.maintenanceScan(target);s.limit=200;s.selected.clear();s.status=`${s.report.entries.length.toLocaleString()} 项 · ${new Date(s.report.created).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`;}catch(error){if(String(error).includes('扫描已停止'))s.status=s.report?'已停止 · 保留上次结果':'扫描已停止';else{s.status='扫描失败';toast(error);}}finally{s.scanning=false;s.cancelling=false;if(kind===target){if(s.report!==previous||!s.report)draw();else status();}}};
 api.onMaintenanceProgress(p=>{const s=states[p.kind];if(!s.scanning&&!s.applying||s.cancelling)return;s.status=(p.phase==='scan'?'扫描':'处理')+'中'+(p.total?` · ${p.completed} / ${p.total}`:'')+(p.label&&p.label!=='完成'?' · '+p.label:'');if(kind===p.kind&&showing()&&!statusFrame)statusFrame=requestAnimationFrame(()=>{statusFrame=0;status();});});
 document.querySelectorAll<HTMLButtonElement>('[data-maintenance-tab]').forEach(b=>b.onclick=()=>{const target=b.dataset.maintenanceTab as typeof kind;if(kind!=='alerts'){state().query=q<HTMLInputElement>('maintenance-query').value;state().filter=q<HTMLSelectElement>('maintenance-filter').value;}kind=target;document.querySelectorAll<HTMLElement>('[data-maintenance-tab]').forEach(t=>{const active=t===b;t.classList.toggle('selected',active);t.setAttribute('aria-selected',String(active));});q('maintenance-scan-panel').hidden=kind==='alerts';q('maintenance-actions').hidden=kind==='alerts';q('maintenance-alert-panel').hidden=kind!=='alerts';warning.activate(kind==='alerts');if(kind!=='alerts'){q<HTMLInputElement>('maintenance-query').value=state().query;q<HTMLSelectElement>('maintenance-filter').value=state().filter;draw();void scan(kind);}});
 action('cancel-maintenance',async()=>{if(kind==='alerts')return;const target=kind,s=states[target];if(!s.scanning||s.cancelling)return;s.restoreFocus=document.activeElement===q('cancel-maintenance');s.cancelling=true;s.status='正在停止扫描…';status();try{await api.maintenanceCancel(target);}catch(error){s.cancelling=false;status();throw error;}});
 action('scan-maintenance',()=>kind!=='alerts'&&scan(kind));action('maintenance-export',async()=>{if(state()?.report)await api.exportMaintenance(state().report!.entries);});q('maintenance-query').oninput=()=>{state().query=q<HTMLInputElement>('maintenance-query').value;state().limit=200;draw();};q('maintenance-filter').onchange=()=>{state().filter=q<HTMLSelectElement>('maintenance-filter').value;state().limit=200;draw();};action('maintenance-more',()=>{state().limit+=200;draw();});q<HTMLInputElement>('maintenance-select-all').onchange=()=>{const s=state();for(const e of filtered())if(['clean','disable'].includes(e.action)){if(q<HTMLInputElement>('maintenance-select-all').checked)s.selected.add(e.id);else s.selected.delete(e.id);}draw();};
 const dialog=q<HTMLDialogElement>('maintenance-confirm');let actionPending:(()=>Promise<void>)|undefined;
 action('maintenance-apply',()=>{if(kind==='alerts')return;const target=kind,s=states[target],report=s.report,list=report?.entries.filter(e=>s.selected.has(e.id))||[];if(!report||!list.length)return;q('maintenance-confirm-title').textContent=target==='startup'?`禁用 ${list.length} 项启动内容`:`清理 ${list.length} 项`;q('maintenance-confirm-detail').textContent=target!=='disk'?'将备份所选项目，可从操作记录恢复。':[list.some(e=>e.action==='recycle')?'回收站将永久清空。':'',list.some(e=>e.action==='hibernate')?'关闭休眠和快速启动，需要管理员权限。':'',list.some(e=>e.action==='clean')?'所选缓存文件将永久删除，正在使用或已变化的文件会跳过。':''].filter(Boolean).join(' ');q('maintenance-confirm-list').innerHTML=list.slice(0,50).map(e=>`<div><strong>${esc(e.name)}</strong><span>${esc(e.location)}</span></div>`).join('');actionPending=async()=>{mutation=true;s.applying=true;s.status='正在处理…';status();try{const result=await api.maintenanceApply(report.id,list.map(e=>e.id));s.selected.clear();s.outcome=`已处理 ${result.succeeded} 项${result.bytes?' · '+size(result.bytes):''}${result.failedCount||result.failed.length?' · '+(result.failedCount||result.failed.length)+' 项跳过':''}`;s.failures=result.failed.map(e=>e.name+'：'+e.error).join('\n');s.applying=false;await scan(target);}catch(error){s.status='处理失败';throw error;}finally{mutation=false;s.applying=false;status();}};openDialog(dialog);});
 action('maintenance-confirm-run',async()=>{closeDialog(dialog);const work=actionPending;actionPending=undefined;await work?.();});for(const id of ['maintenance-confirm-close','maintenance-confirm-cancel'])action(id,()=>closeDialog(dialog));
 const history=q<HTMLDialogElement>('maintenance-history-dialog');const loadHistory=async()=>{const receipts=await api.maintenanceReceipts();q('maintenance-receipts').innerHTML=receipts.length?receipts.map(r=>`<div class="receipt-row"><div><strong>${esc(r.name)}</strong><span>${new Date(r.created).toLocaleString()} · ${r.items} 项</span></div>${r.restorable&&!r.restored?`<button data-restore="${r.id}">恢复</button>`:`<span>${r.restored?'已恢复':'已处理'}</span>`}</div>`).join(''):'<div class="table-empty">暂无记录</div>';q('maintenance-receipts').querySelectorAll<HTMLButtonElement>('[data-restore]').forEach(b=>b.onclick=()=>{b.disabled=true;void api.maintenanceRestore(b.dataset.restore!).then(async()=>{await loadHistory();if(kind!=='alerts')await scan(kind);}).catch(e=>{b.disabled=false;toast(e);});});};action('maintenance-history',async()=>{await loadHistory();openDialog(history);});action('maintenance-history-close',()=>closeDialog(history));draw();
 const syncVisibility=()=>{warning.activate(showing()&&kind==='alerts');if(showing())draw();else{cancelAnimationFrame(statusFrame);statusFrame=0;}};
 onWindowVisibility(syncVisibility);
 return {activate(active:boolean){moduleActive=active;syncVisibility();if(active&&kind!=='alerts'&&(!state().report||Date.now()-state().report!.created>30000))void scan(kind);}};
}
