import {dialogMarkup,openDialog,closeDialog} from './dialog';
import {api,q,esc,icon,button,iconButton,action,toast,size} from './ui';
import {diskWarningPage,setupDiskWarning} from './disk-warning-view';
import type {MaintenanceKind,MaintenanceReport,MaintenanceEntry} from '../shared/maintenance';
import {isWindowVisible,onWindowVisibility} from './window-visibility';
import {MaintenanceList,MaintenanceConfirmation,maintenanceListState,maintenanceEntryKey,type MaintenanceListState} from './maintenance-list';
import './maintenance-list.css';
import {applyMaintenanceBatches} from '../shared/maintenance-batches';
const names={startup:'启动项',registry:'注册表',disk:'磁盘清理',alerts:'磁盘告警'};
export function maintenancePage(){return `<div class="maintenance-page"><div class="toolbar module-toolbar"><div class="tabs" role="tablist" aria-label="系统维护">${Object.entries(names).map(([id,name])=>`<button id="${id}-tab" data-maintenance-tab="${id}" role="tab" aria-selected="${id==='startup'}" class="${id==='startup'?'selected':''}">${name}</button>`).join('')}</div><div class="spacer"></div><div id="maintenance-actions" class="toolbar">${iconButton('maintenance-export','导出报告','download')}${iconButton('maintenance-history','操作记录','history')}${button('cancel-maintenance','停止扫描','stop')}${button('scan-maintenance','重新扫描','refresh')}</div></div><div id="maintenance-scan-panel"><div class="maintenance-tools"><div class="filter-field">${icon('search')}<input id="maintenance-query" placeholder="筛选名称、来源或路径" aria-label="筛选维护结果"></div><select id="maintenance-filter" aria-label="维护结果过滤"><option value="all">全部项目</option><option value="actionable">可处理</option><option value="missing">目标不存在</option></select><span id="maintenance-status" role="status">尚未扫描</span></div><div class="maintenance-layout"><div class="maintenance-results"><div class="maintenance-list-head"><label><input type="checkbox" id="maintenance-select-all" aria-label="选择当前列表可处理项目">名称</label><span>状态</span></div><div id="maintenance-rows"></div><div class="maintenance-list-footer"><span id="maintenance-filtered-count"></span><span class="maintenance-list-shortcuts">↑↓ 浏览 · 空格选择 · Enter 详情</span></div></div><aside class="maintenance-selection"><div class="selection-count"><strong id="maintenance-count">0</strong><span>项已选</span></div><div id="maintenance-bytes"></div><div id="maintenance-selected-names"></div>${button('maintenance-apply','处理所选','',true)}<span id="maintenance-outcome" role="status"></span></aside></div></div><div id="maintenance-alert-panel" hidden>${diskWarningPage()}</div></div>${dialogMarkup({id:"maintenance-confirm",title:"确认操作",closeId:"maintenance-confirm-close",titleId:"maintenance-confirm-title",className:"dialog-wide",body:`<p id="maintenance-confirm-detail"></p><div id="maintenance-confirm-list" class="confirm-items"></div>`,actions:`<button id="maintenance-confirm-cancel" autofocus>取消</button>${button('maintenance-confirm-run','确认','',true)}`})}${dialogMarkup({id:"maintenance-history-dialog",title:"操作记录",closeId:"maintenance-history-close",className:"dialog-wide",body:`<div id="maintenance-receipts"></div>`})}`;}
interface TabState {report?:MaintenanceReport;scanning:boolean;cancelling:boolean;restoreFocus:boolean;applying:boolean;selected:Map<string,MaintenanceEntry>;view:MaintenanceListState;matches?:{report?:MaintenanceReport;query:string;filter:string;entries:MaintenanceEntry[]};query:string;filter:string;status:string;outcome:string;failures:string}
export function setupMaintenance(){
 const states=Object.fromEntries(['startup','registry','disk'].map(k=>[k,{scanning:false,cancelling:false,restoreFocus:false,applying:false,selected:new Map<string,MaintenanceEntry>(),view:maintenanceListState(),query:'',filter:'all',status:'尚未扫描',outcome:'',failures:''}])) as Record<MaintenanceKind,TabState>;
 let kind:MaintenanceKind|'alerts'='startup',mutation=false,moduleActive=false,statusFrame=0;const warning=setupDiskWarning();
 const showing=()=>moduleActive&&isWindowVisible();q('cancel-maintenance').hidden=true;
 const state=()=>states[kind as MaintenanceKind],entries=()=>state()?.report?.entries||[];
 const filtered=()=>{const s=state();if(s.matches&&s.matches.report===s.report&&s.matches.query===s.query&&s.matches.filter===s.filter)return s.matches.entries;const query=s.query.toLowerCase(),all=entries(),list=!query&&s.filter==='all'?all:all.filter(e=>(!query||[e.name,e.command,e.source,e.location].join(' ').toLowerCase().includes(query))&&(s.filter==='all'||s.filter==='actionable'&&!!e.action&&e.action!=='manage'||s.filter==='missing'&&e.status.includes('目标未找到')));s.matches={report:s.report,query:s.query,filter:s.filter,entries:list};return list;};
 const selection=()=>{if(!showing()||kind==='alerts')return;const s=state(),list=[...s.selected.values()];q('maintenance-count').textContent=String(list.length);q('maintenance-bytes').textContent=kind==='disk'?size(list.reduce((sum,e)=>sum+(e.bytes||0),0)):'';q('maintenance-selected-names').innerHTML=list.slice(0,5).map(e=>`<span>${esc(e.name)}</span>`).join('')+(list.length>5?`<span>以及 ${list.length-5} 项</span>`:'');q<HTMLButtonElement>('maintenance-apply').disabled=mutation||s.scanning||!list.length;q('maintenance-apply').textContent=kind==='startup'?'禁用所选':'清理所选';const selectable=filtered().filter(e=>['clean','disable'].includes(e.action));q<HTMLInputElement>('maintenance-select-all').checked=!!selectable.length&&selectable.every(e=>s.selected.has(e.id));q<HTMLInputElement>('maintenance-select-all').indeterminate=selectable.some(e=>s.selected.has(e.id))&&!q<HTMLInputElement>('maintenance-select-all').checked;};
 const status=()=>{
  if(!showing()||kind==='alerts')return;const s=state(),restore=!s.scanning&&s.restoreFocus&&(document.activeElement===q('cancel-maintenance')||document.activeElement===document.body);if(!s.scanning)s.restoreFocus=false;
  q('maintenance-status').textContent=s.status;q('maintenance-status').classList.toggle('task-running',s.scanning||s.applying);
  q<HTMLButtonElement>('scan-maintenance').disabled=s.scanning||s.applying;
  q<HTMLButtonElement>('cancel-maintenance').hidden=!s.scanning;q<HTMLButtonElement>('cancel-maintenance').disabled=s.cancelling;
  const cancel=q<HTMLButtonElement>('cancel-maintenance'),label=s.cancelling?'正在停止…':'停止扫描';if(cancel.textContent!==label)cancel.innerHTML=icon('stop')+label;if(restore)q('scan-maintenance').focus({preventScroll:true});
  q<HTMLButtonElement>('maintenance-apply').disabled=mutation||s.scanning||s.applying||!s.selected.size;
  if(!filtered().length)list.setEmpty(s.scanning?'正在扫描'+names[kind]:s.report?'没有符合条件的项目':s.status,s.scanning);q('maintenance-outcome').textContent=s.outcome;q('maintenance-outcome').title=s.failures;
 };
 const list=new MaintenanceList(q('maintenance-rows'),(entry,checked)=>{if(checked)state().selected.set(entry.id,entry);else state().selected.delete(entry.id);draw();},()=>void api.maintenanceManage('pagefile').catch(toast),()=>selectAll(true));
 const draw=()=>{if(!showing()||kind==='alerts')return;const s=state(),matches=filtered();list.setActive(true);list.update(matches,s.selected,s.view,[kind,s.query,s.filter].join('\0'));q('maintenance-filtered-count').textContent=matches.length.toLocaleString()+' 项'+(matches.length!==entries().length?' / '+entries().length.toLocaleString():'');status();selection();};
 const selectAll=(checked:boolean)=>{const s=state();for(const e of filtered())if(['clean','disable'].includes(e.action)){if(checked)s.selected.set(e.id,e);else s.selected.delete(e.id);}draw();};
 const scan=async(target:MaintenanceKind)=>{const s=states[target],previous=s.report;if(s.scanning||s.applying)return;s.scanning=true;s.status='正在扫描…';if(kind===target){if(!s.report)draw();else status();}try{s.report=await api.maintenanceScan(target);s.matches=undefined;s.selected.clear();if(s.view.expanded.size){const retained=new Set(s.report.entries.map(maintenanceEntryKey).filter(key=>s.view.expanded.has(key)));for(const key of s.view.expanded.keys())if(!retained.has(key))s.view.expanded.delete(key);}s.status=`${s.report.entries.length.toLocaleString()} 项 · ${new Date(s.report.created).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`;}catch(error){if(String(error).includes('扫描已停止'))s.status=s.report?'已停止 · 保留上次结果':'扫描已停止';else{s.status='扫描失败';toast(error);}}finally{s.scanning=false;s.cancelling=false;if(kind===target){if(s.report!==previous||!s.report)draw();else status();}}};
 api.onMaintenanceProgress(p=>{const s=states[p.kind];if(!s.scanning&&!s.applying||s.cancelling)return;s.status=(p.phase==='scan'?'扫描':'处理')+'中'+(p.total?` · ${p.completed} / ${p.total}`:'')+(p.label&&p.label!=='完成'?' · '+p.label:'');if(kind===p.kind&&showing()&&!statusFrame)statusFrame=requestAnimationFrame(()=>{statusFrame=0;status();});});
 document.querySelectorAll<HTMLButtonElement>('[data-maintenance-tab]').forEach(b=>b.onclick=()=>{const target=b.dataset.maintenanceTab as typeof kind;if(kind!=='alerts'){state().query=q<HTMLInputElement>('maintenance-query').value;state().filter=q<HTMLSelectElement>('maintenance-filter').value;}kind=target;document.querySelectorAll<HTMLElement>('[data-maintenance-tab]').forEach(t=>{const active=t===b;t.classList.toggle('selected',active);t.setAttribute('aria-selected',String(active));});q('maintenance-scan-panel').hidden=kind==='alerts';q('maintenance-actions').hidden=kind==='alerts';q('maintenance-alert-panel').hidden=kind!=='alerts';warning.activate(showing()&&kind==='alerts');if(kind==='alerts')list.setActive(false);if(kind!=='alerts'){q<HTMLInputElement>('maintenance-query').value=state().query;q<HTMLSelectElement>('maintenance-filter').value=state().filter;draw();void scan(kind);}});
 action('cancel-maintenance',async()=>{if(kind==='alerts')return;const target=kind,s=states[target];if(!s.scanning||s.cancelling)return;s.restoreFocus=document.activeElement===q('cancel-maintenance');s.cancelling=true;s.status='正在停止扫描…';status();try{await api.maintenanceCancel(target);}catch(error){s.cancelling=false;status();throw error;}});
 action('scan-maintenance',()=>kind!=='alerts'&&scan(kind));action('maintenance-export',async()=>{if(state()?.report)await api.exportMaintenance(state().report!.entries);});q('maintenance-query').oninput=()=>{state().query=q<HTMLInputElement>('maintenance-query').value;draw();};q('maintenance-filter').onchange=()=>{state().filter=q<HTMLSelectElement>('maintenance-filter').value;draw();};q<HTMLInputElement>('maintenance-select-all').onchange=()=>selectAll(q<HTMLInputElement>('maintenance-select-all').checked);
 const dialog=q<HTMLDialogElement>('maintenance-confirm'),confirmation=new MaintenanceConfirmation(q('maintenance-confirm-list'));dialog.addEventListener('close',()=>{actionPending=undefined;confirmation.clear();});let actionPending:(()=>Promise<void>)|undefined;
 action('maintenance-apply',()=>{if(kind==='alerts')return;const target=kind,s=states[target],report=s.report,list=[...s.selected.values()];if(!report||!list.length)return;q('maintenance-confirm-title').textContent=target==='startup'?`禁用 ${list.length} 项启动内容`:`清理 ${list.length} 项`;q('maintenance-confirm-detail').textContent=target!=='disk'?'将备份所选项目，可从操作记录恢复。':[list.some(e=>e.action==='recycle')?'回收站将永久清空。':'',list.some(e=>e.action==='hibernate')?'关闭休眠和快速启动，需要管理员权限。':'',list.some(e=>e.action==='clean')?'所选缓存文件将永久删除，正在使用或已变化的文件会跳过。':''].filter(Boolean).join(' ');confirmation.set(list);actionPending=async()=>{mutation=true;s.applying=true;s.status='正在处理…';status();try{const result=await applyMaintenanceBatches(list.map(e=>e.id),ids=>api.maintenanceApply(report.id,ids),result=>{s.outcome='已处理 '+result.succeeded.toLocaleString()+' 项';status();});s.selected.clear();s.outcome=`已处理 ${result.succeeded} 项${result.bytes?' · '+size(result.bytes):''}${result.failedCount||result.failed.length?' · '+(result.failedCount||result.failed.length)+' 项跳过':''}`;s.failures=result.failed.map(e=>e.name+'：'+e.error).join('\n');s.applying=false;await scan(target);}catch(error){s.status='处理失败';throw error;}finally{mutation=false;s.applying=false;status();}};openDialog(dialog);});
 action('maintenance-confirm-run',async()=>{const work=actionPending;actionPending=undefined;closeDialog(dialog);await work?.();});for(const id of ['maintenance-confirm-close','maintenance-confirm-cancel'])action(id,()=>{actionPending=undefined;closeDialog(dialog);});
 const history=q<HTMLDialogElement>('maintenance-history-dialog');const loadHistory=async()=>{const receipts=await api.maintenanceReceipts();q('maintenance-receipts').innerHTML=receipts.length?receipts.map(r=>`<div class="receipt-row"><div><strong>${esc(r.name)}</strong><span>${new Date(r.created).toLocaleString()} · ${r.items} 项</span></div>${r.restorable&&!r.restored?`<button data-restore="${r.id}">恢复</button>`:`<span>${r.restored?'已恢复':'已处理'}</span>`}</div>`).join(''):'<div class="table-empty">暂无记录</div>';q('maintenance-receipts').querySelectorAll<HTMLButtonElement>('[data-restore]').forEach(b=>b.onclick=()=>{b.disabled=true;void api.maintenanceRestore(b.dataset.restore!).then(async()=>{await loadHistory();if(kind!=='alerts')await scan(kind);}).catch(e=>{b.disabled=false;toast(e);});});};action('maintenance-history',async()=>{await loadHistory();openDialog(history);});action('maintenance-history-close',()=>closeDialog(history));draw();
 const syncVisibility=()=>{warning.activate(showing()&&kind==='alerts');if(showing())draw();else{list.setActive(false);cancelAnimationFrame(statusFrame);statusFrame=0;}};
 onWindowVisibility(syncVisibility);
 return {activate(active:boolean){moduleActive=active;syncVisibility();if(active&&kind!=='alerts'&&(!state().report||Date.now()-state().report!.created>30000))void scan(kind);}};
}
