import {dialogMarkup,openDialog,closeDialog} from './dialog';
import {api,q,icon,iconButton,button,esc,toast,action} from './ui';
import {customControls,closeControls} from './controls';
import {chooseIcon,loadMenuIcons} from './icon-picker';
import {hydrateFileIcons} from './shell-icons';
import {menuIconPath} from '../shared/menu-icons';
import type {MenuPreset} from '../shared/menu-presets';
import {menuBuiltins,builtinById} from '../shared/menu-builtins';
import {chooseCommand,type CommandChoice} from './command-picker';
import {confirmPopover} from './confirm-popover';
import {moveMenuItem,type MenuDropPosition} from '../shared/menu-tree';
import {validateMenu,validateMenuBar,type SearchMenuItem,type MenuKind,type MenuShell} from '../shared/search';
import {menuPreviewMarkup,setupMenuBarEditor} from './menu-bar-editor';
import {placeInMenu,barKeys,type MenuLayout} from '../shared/menu-layout';
const labels:Record<MenuKind,string>={folder:'文件夹',file:'文件',command:'运行命令',shell:'运行命令',url:'网址',group:'子菜单',separator:'分隔线',builtin:'内置动作'};
const symbols:Record<MenuKind,string>={folder:'folder',file:'file',command:'window',shell:'terminal',url:'open',group:'folder',separator:'minus',builtin:'settings'};
const menuGlyph=(item:SearchMenuItem)=>{const path=menuIconPath(item),fallback=icon(item.kind==='separator'?'minus':item.icon==='auto'?symbols[item.kind]:item.icon||symbols[item.kind]);return path?`<span class="menu-file-icon" data-file-icon="${esc(path)}">${fallback}</span>`:fallback;};
const kinds=()=>Object.entries(labels).filter(([kind])=>kind!=='shell');
export function menuEditorCard(){return `<div id="menu-editor"><div class="menu-editor-toolbar"><span id="menu-count" class="muted"></span><div class="spacer"></div>${button('menu-import','导入')}${button('menu-export','导出')}${button('menu-add','添加','plus',true)}</div><div class="menu-designer">${menuPreviewMarkup()}<aside class="menu-inspector"><div class="section-heading"><h2 id="menu-edit-title">项目设置</h2><div class="menu-inspector-actions">${iconButton('menu-item-visibility','隐藏项目','preview')}${iconButton('menu-item-copy','复制项目','copy')}${iconButton('menu-item-delete','删除项目及子项目','trash')}</div></div><div id="menu-edit-fields"><p class="inspector-empty">选择一个项目进行编辑</p></div><p id="menu-edit-error" role="status"></p><div class="dialog-actions"><button id="menu-create" class="primary" hidden>添加项目</button></div></aside></div></div>${dialogMarkup({id:"menu-json-dialog",title:"菜单配置",closeId:"menu-json-close",titleId:"menu-json-title",body:`<textarea id="menu-json" aria-label="菜单 JSON" spellcheck="false"></textarea>`,actions:`${button('menu-json-apply','导入','',true)}`})}`;}
export function setupMenuEditor(getLayout:()=>MenuLayout,save:(patch:MenuLayout)=>Promise<void>){
 const get=()=>getLayout().menu;let barController:ReturnType<typeof setupMenuBarEditor>;
 let editing='',draft:SearchMenuItem|undefined,dragged='',chain=Promise.resolve(),editRevision=0,flush:(()=>void)|undefined,addPopup:HTMLElement|undefined;
 const collapsed=new Set<string>();let drop:{id:string;position:MenuDropPosition}|undefined;
 const descendants=(id:string,items=get())=>{const ids=new Set<string>();if(id)ids.add(id);let previous=-1;while(previous!==ids.size){previous=ids.size;for(const item of items)if(ids.has(item.parent))ids.add(item.id);}return ids;};
 const report=(error:unknown)=>q('menu-edit-error').textContent=String(error).replace('Error: ','');
 const transact=(mutate:(layout:MenuLayout)=>MenuLayout)=>{const task=chain.catch(()=>{}).then(async()=>{const before=structuredClone(getLayout()),next=mutate(structuredClone(before));next.menu=validateMenu(next.menu);next.menuBar=validateMenuBar(next.menuBar,next.menu);if(JSON.stringify(next)===JSON.stringify(before)){draw();return;}await save(next);draw();});chain=task;return task;};
 const commit=(change:(items:SearchMenuItem[])=>SearchMenuItem[])=>transact(layout=>({...layout,menu:change(layout.menu)}));
 const empty=()=>{editRevision++;flush=undefined;editing='';draft=undefined;q('menu-edit-fields').innerHTML='<p class="inspector-empty">选择一个项目进行编辑</p>';q('menu-item-delete').hidden=true;q('menu-item-copy').hidden=true;q('menu-item-visibility').hidden=true;q('menu-create').hidden=true;q('menu-edit-error').textContent='';draw();};
 const remove=(id:string,anchor:HTMLElement)=>{const item=get().find(i=>i.id===id);if(!item)return;const count=descendants(id).size;confirmPopover(anchor,'删除“'+(item.label||'分隔线')+'”？',count>1?'包含 '+(count-1)+' 个子项目。':'',()=>{flush=undefined;void commit(items=>{const ids=descendants(id,items);return items.filter(item=>!ids.has(item.id));}).then(()=>{if(editing&&!get().some(i=>i.id===editing)){empty();q('menu-add').focus();}}).catch(toast);});};
 const toggle=(id:string)=>{flush?.();void commit(items=>items.map(item=>item.id===id?{...item,enabled:!item.enabled}:item)).catch(toast);};
 const clearDrop=()=>{drop=undefined;barController?.clear();delete q('menu-editor-list').dataset.rootDrop;q('menu-editor-list').querySelectorAll<HTMLElement>('[data-drop-position]').forEach(row=>delete row.dataset.dropPosition);};
 const move=(id:string,direction:number)=>commit(items=>{const at=items.findIndex(i=>i.id===id);if(at<0)return items;const siblings=items.filter(i=>i.parent===items[at].parent),target=siblings[siblings.findIndex(i=>i.id===id)+direction];if(target){const to=items.findIndex(i=>i.id===target.id);[items[at],items[to]]=[items[to],items[at]];}return items;});
 const duplicate=async()=>{flush?.();const source=editing;if(!source)return;let id='';await commit(items=>{const ids=descendants(source,items),copies=new Map([...ids].map(key=>[key,crypto.randomUUID()]));id=copies.get(source)!;return [...items,...items.filter(i=>ids.has(i.id)).map(i=>({...i,id:copies.get(i.id)!,parent:i.id===source?i.parent:copies.get(i.parent)!,label:i.id===source?i.label+' 副本':i.label}))];});edit(id);};
 const seenGroups=new Set<string>();
 const sourceId=()=>dragged.startsWith('bar:item:')?dragged.slice(9):dragged.startsWith('bar:')?'':dragged;
 const finishDrag=()=>{dragged='';clearDrop();draw();};
 const draw=()=>{if(dragged)return;const items=get(),host=q('menu-editor-list'),scroll=host.scrollTop,inBar=new Set(barKeys(getLayout().menuBar).filter(key=>key.startsWith('item:')).map(key=>key.slice(5)));q('menu-count').textContent=`${items.length} 项`;
  for(const item of items)if(item.kind==='group'&&!seenGroups.has(item.id)){seenGroups.add(item.id);collapsed.add(item.id);}
  let ancestor=items.find(item=>item.id===editing);while(ancestor?.parent){collapsed.delete(ancestor.parent);ancestor=items.find(item=>item.id===ancestor!.parent);}
  const rows=(parent:string,level:number):string=>items.filter(i=>i.parent===parent&&!inBar.has(i.id)).map(i=>`<div class="menu-tree-node"><div class="menu-editor-row ${i.kind==='separator'?'separator':''} ${i.enabled?'':'disabled'} ${editing===i.id?'selected':''}" data-menu-id="${i.id}" draggable="true" role="treeitem" aria-selected="${editing===i.id}" aria-level="${level+1}" ${i.kind==='group'?`aria-expanded="${!collapsed.has(i.id)}"`:''}><button class="quiet menu-item-label" draggable="true" data-edit="${i.id}" aria-label="编辑 ${esc(i.label||'分隔线')}">${i.kind==='separator'?'<hr aria-hidden="true">':menuGlyph(i)+`<span>${esc(i.label)}</span>`}${i.kind==='group'?icon(collapsed.has(i.id)?'chevron':'chevron-down'):''}</button><div class="tree-row-actions"><button class="icon-button quiet menu-visibility" data-enabled="${i.id}" aria-label="${i.enabled?'隐藏':'显示'} ${esc(i.label||'分隔线')}" title="${i.enabled?'隐藏':'显示'}此项目" aria-pressed="${i.enabled}">${icon(i.enabled?'preview':'hidden')}</button><button class="icon-button quiet" data-delete="${i.id}" aria-label="删除 ${esc(i.label||'分隔线')}">${icon('trash')}</button></div></div>${i.kind==='group'&&!collapsed.has(i.id)?`<div class="menu-preview-submenu" role="group">${rows(i.id,level+1)||'<p class="menu-submenu-empty">空子菜单</p>'}</div>`:''}</div>`).join('');
  host.innerHTML=rows('',0)||'<div class="menu-tree-empty">'+icon('list')+'<span>添加菜单或拖入图标</span></div>';host.scrollTop=scroll;hydrateFileIcons(host);barController?.draw();
  const selected=items.find(item=>item.id===editing),visibility=q<HTMLButtonElement>('menu-item-visibility');visibility.hidden=!selected;if(selected){visibility.innerHTML=icon(selected.enabled?'preview':'hidden');visibility.setAttribute('aria-label',selected.enabled?'隐藏项目':'显示项目');visibility.setAttribute('title',selected.enabled?'隐藏项目':'显示项目');visibility.setAttribute('aria-pressed',String(selected.enabled));}
  host.querySelectorAll<HTMLElement>('[data-edit]').forEach(b=>{b.onclick=()=>{const id=b.dataset.edit!,item=items.find(item=>item.id===id);if(item?.kind==='group'){if(collapsed.has(id))collapsed.delete(id);else collapsed.add(id);}edit(id);};b.onkeydown=e=>{if(e.key==='Delete'){e.preventDefault();remove(b.dataset.edit!,b);}if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();void move(b.dataset.edit!,e.key==='ArrowUp'?-1:1).catch(toast);}};});
  host.querySelectorAll<HTMLElement>('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete!,b));host.querySelectorAll<HTMLElement>('[data-enabled]').forEach(b=>b.onclick=()=>toggle(b.dataset.enabled!));
  host.querySelectorAll<HTMLElement>('[data-menu-id]').forEach(row=>{
   row.ondragstart=e=>{flush?.();dragged=row.dataset.menuId!;barController.reveal();row.classList.add('dragging');e.dataTransfer!.setData('text/plain',dragged);e.dataTransfer!.effectAllowed='move';};row.ondragend=finishDrag;
   row.ondragover=e=>{const target=items.find(item=>item.id===row.dataset.menuId),source=sourceId();if(!target||!dragged||source&&descendants(source,items).has(target.id)){clearDrop();return;}e.preventDefault();e.stopPropagation();e.dataTransfer!.dropEffect='move';const box=row.getBoundingClientRect(),ratio=(e.clientY-box.top)/box.height,position:MenuDropPosition=target.kind==='group'&&ratio>=.25&&ratio<=.75?'inside':ratio<.5?'before':'after';if(drop?.id!==target.id||drop.position!==position){clearDrop();drop={id:target.id,position};row.dataset.dropPosition=position;}};
   row.ondragleave=e=>{if(!row.contains(e.relatedTarget as Node)&&drop?.id===row.dataset.menuId)clearDrop();};row.ondrop=e=>{e.preventDefault();e.stopPropagation();const source=dragged,target=drop;dragged='';clearDrop();if(!source||!target)return;void (source.startsWith('bar:')?transact(layout=>placeInMenu(layout,source.slice(4),crypto.randomUUID(),target.id,target.position)):commit(list=>moveMenuItem(list,source,target.id,target.position))).then(()=>{if(target.position==='inside')collapsed.delete(target.id);if(editing)edit(editing);else draw();}).catch(toast);};
  });
  host.ondragover=e=>{if(!dragged||(e.target as Element).closest('[data-menu-id]'))return;e.preventDefault();e.dataTransfer!.dropEffect='move';host.dataset.rootDrop='true';};host.ondragleave=e=>{if(!host.contains(e.relatedTarget as Node))delete host.dataset.rootDrop;};host.ondrop=e=>{if(!dragged||(e.target as Element).closest('[data-menu-id]'))return;e.preventDefault();const source=dragged;dragged='';clearDrop();void transact(layout=>source.startsWith('bar:')?placeInMenu(layout,source.slice(4),crypto.randomUUID()):({...layout,menu:[...layout.menu.filter(item=>item.id!==source),{...layout.menu.find(item=>item.id===source)!,parent:''}]})).catch(toast);};
 };
 const read=():SearchMenuItem=>{const kind=q<HTMLSelectElement>('menu-kind').value as MenuKind,runtime=q<HTMLSelectElement>('menu-shell').value,isShell=kind==='command'&&runtime!=='program',shell=runtime as MenuShell;return{id:editing||draft!.id,parent:q<HTMLSelectElement>('menu-parent').value,kind,label:kind==='separator'?'':q<HTMLInputElement>('menu-label').value.trim(),icon:(q('menu-icon') as any).value,...(q('menu-icon').dataset.iconMode?{iconMode:q('menu-icon').dataset.iconMode as 'auto'|'custom'}:{}),target:kind==='builtin'?q<HTMLInputElement>('menu-builtin').value:isShell?q<HTMLTextAreaElement>('menu-script').value:q<HTMLInputElement>('menu-target').value.trim(),args:kind==='command'&&(!isShell||shell==='custom')?q<HTMLTextAreaElement>('menu-args').value.split(/\r?\n/).filter(Boolean):[],cwd:['command','shell','file'].includes(kind)?q<HTMLInputElement>('menu-cwd').value.trim():'',enabled:get().find(item=>item.id===editing)?.enabled??draft?.enabled??true,...(kind==='command'&&!isShell&&q<HTMLInputElement>('menu-console').checked?{console:true}:{}),...(isShell?{shell,shellPath:q<HTMLInputElement>('menu-shell-path').value.trim()}:{})};};
 const edit=(id='',parent='',kind:MenuKind='command',target='',preset?:MenuPreset)=>{flush?.();flush=undefined;closeControls();editRevision++;editing=id;draft=id?undefined:{id:crypto.randomUUID(),parent,kind,label:'',target,args:[],cwd:'',icon:['command','file','shell'].includes(kind)?'auto':'lucide:'+symbols[kind],enabled:true,...(preset?{label:preset.label,target:preset.target,args:preset.args,cwd:preset.cwd,console:preset.console}: {})};const item=get().find(i=>i.id===id)||draft!;if(!item)return empty();q('menu-edit-title').textContent=id?'项目设置':'添加'+labels[kind];q('menu-item-delete').hidden=!id;q('menu-item-copy').hidden=!id;q('menu-create').hidden=!!id;q('menu-edit-error').textContent='';const excluded=descendants(id);const itemPath=(i:SearchMenuItem):string=>{const parent=get().find(p=>p.id===i.parent);return parent?itemPath(parent)+' / '+i.label:i.label;};
  q('menu-edit-fields').innerHTML=`<div class="menu-name-field"><label>名称<input id="menu-label" value="${esc(item.label)}" maxlength="200" placeholder="菜单名称"></label><label>图标<button type="button" id="menu-icon" class="menu-icon-select" aria-label="选择菜单图标">${menuGlyph(item)}${icon('chevron-down')}</button></label></div><div class="menu-field-pair"><label>类型<select id="menu-kind" aria-label="菜单类型">${kinds().map(([key,label])=>`<option value="${key}" ${key===(item.kind==='shell'?'command':item.kind)?'selected':''}>${label}</option>`).join('')}</select></label><label>上级菜单<select id="menu-parent" aria-label="上级菜单"><option value="">主菜单</option>${get().filter(i=>i.kind==='group'&&!excluded.has(i.id)).map(i=>`<option value="${i.id}" ${i.id===item.parent?'selected':''}>${esc(itemPath(i))}</option>`).join('')}</select></label></div><div id="menu-target-field"><label><span id="menu-target-label">目标</span><div class="menu-path-field"><input id="menu-target" value="${esc(item.kind==='shell'||item.kind==='command'&&item.shell?'':item.target)}" placeholder="文件路径">${iconButton('menu-pick-target','选择目标文件','folder')}</div></label></div><label id="menu-builtin-field">内置命令<input id="menu-builtin" type="hidden" value="${esc(item.kind==='builtin'?item.target:'opened')}"><button type="button" id="menu-builtin-button" class="menu-command-select" aria-label="选择内置命令" aria-haspopup="listbox"><span>${esc(builtinById(item.kind==='builtin'?item.target:'opened')?.label||'选择命令')}</span>${icon('chevron-down')}</button></label><label id="menu-runtime-field">运行方式<select id="menu-shell" aria-label="运行方式">${[['program','程序'],['powershell','Windows PowerShell'],['pwsh','PowerShell 7'],['cmd','命令提示符'],['custom','其他 Shell']].map(([key,label])=>`<option value="${key}" ${key===(item.kind==='shell'?item.shell??'powershell':item.shell??'program')?'selected':''}>${label}</option>`).join('')}</select></label><div id="menu-shell-fields"><label id="menu-shell-path-field">Shell 程序<div class="menu-path-field"><input id="menu-shell-path" value="${esc(item.shellPath||'')}" placeholder="选择 bash.exe 等程序">${iconButton('menu-pick-shell','选择 Shell 程序','folder')}</div></label><label>命令<textarea id="menu-script" spellcheck="false" placeholder="Get-ChildItem">${esc(item.kind==='shell'||item.kind==='command'&&item.shell?item.target:'')}</textarea></label><p id="menu-shell-context" class="menu-field-hint"></p></div><div id="menu-command-fields"><label>参数 · 每行一个<textarea id="menu-args" spellcheck="false" placeholder="{selected}">${esc(item.args.join('\n'))}</textarea></label><p id="menu-args-hint" class="menu-field-hint"></p><label id="menu-console-field" class="menu-console"><input id="menu-console" type="checkbox" ${item.console?'checked':''}>在终端中运行</label></div><label id="menu-cwd-field">工作目录<div class="menu-path-field"><input id="menu-cwd" value="${esc(item.cwd)}" placeholder="当前文件夹">${iconButton('menu-pick-dir','选择工作目录','folder')}</div></label>`;
  customControls(q('menu-edit-fields'));(q('menu-icon') as any).value=item.icon;if(item.iconMode)q('menu-icon').dataset.iconMode=item.iconMode;
  let previousKind:MenuKind=item.kind==='shell'?'command':item.kind,timer:ReturnType<typeof setTimeout>|undefined;const revision=editRevision;
  const fields=()=>{const kind=q<HTMLSelectElement>('menu-kind').value as MenuKind,shell=q<HTMLSelectElement>('menu-shell').value,isShell=kind==='command'&&shell!=='program';if(kind!==previousKind){q<HTMLInputElement>('menu-target').value='';q<HTMLTextAreaElement>('menu-script').value='';q<HTMLTextAreaElement>('menu-args').value='';previousKind=kind;}
   q('menu-target-field').hidden=isShell||!['folder','file','url','command'].includes(kind);q('menu-runtime-field').hidden=kind!=='command';q('menu-shell-fields').hidden=!isShell;q('menu-shell-path-field').hidden=shell!=='custom';q('menu-command-fields').hidden=kind!=='command'||isShell&&shell!=='custom';q('menu-builtin-field').hidden=kind!=='builtin';q('menu-console-field').hidden=kind!=='command'||isShell;q('menu-cwd-field').hidden=!['file','command','shell'].includes(kind);q('menu-pick-target').hidden=kind==='url';q<HTMLInputElement>('menu-label').disabled=kind==='separator';q('menu-target-label').textContent=kind==='command'?'程序':kind==='url'?'网址':kind==='folder'?'文件夹':'文件';q<HTMLInputElement>('menu-target').placeholder=kind==='url'?'https://':kind==='command'?'程序路径或名称':'选择路径';q('menu-shell-context').textContent=shell==='cmd'?'当前目录：%ONE_FOLDER% · 选中文件：%ONE_SELECTED%':shell==='powershell'||shell==='pwsh'?'当前目录：$env:ONE_FOLDER · 选中文件：$env:ONE_SELECTED':'当前目录和选中文件通过 ONE_FOLDER、ONE_SELECTED 环境变量提供';q('menu-args-hint').textContent=isShell?'使用 {command} 传入上面的整段命令。':'{folder} 当前目录 · {selected} 选中文件 · {selection} 所有选中文件';};fields();
  const refreshIcon=()=>{q('menu-icon').innerHTML=menuGlyph(read())+icon('chevron-down');hydrateFileIcons(q('menu-icon'));};refreshIcon();
  const apply=()=>{clearTimeout(timer);timer=undefined;fields();refreshIcon();if(!editing)return;const value=read(),selected=editing;try{validateMenu(get().map(i=>i.id===selected?value:i));q('menu-edit-error').textContent='';}catch(error){report(error);return;}if(JSON.stringify(get().find(i=>i.id===selected))===JSON.stringify(value))return;void commit(items=>items.map(i=>i.id===selected?value:i)).catch(error=>{if(revision===editRevision)report(error);});};flush=()=>{if(timer)apply();};q('menu-edit-fields').onchange=apply;q('menu-edit-fields').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(editRevision===revision)apply();},300);};
  q('menu-icon').onclick=()=>void chooseIcon((q('menu-icon') as any).value,name=>{if(editRevision!==revision)return;(q('menu-icon') as any).value=name;q('menu-icon').dataset.iconMode=name==='auto'?'auto':'custom';apply();},true).catch(toast);
  q('menu-pick-target').onclick=()=>void (q<HTMLSelectElement>('menu-kind').value==='folder'?api.pickDirectory():api.pickFile()).then(path=>{if(path&&revision===editRevision){q<HTMLInputElement>('menu-target').value=path;if(!q<HTMLInputElement>('menu-label').value)q<HTMLInputElement>('menu-label').value=path.split(/[\\/]/).pop()||path;apply();}}).catch(toast);
  for(const [id,input,pick]of [['menu-pick-dir','menu-cwd',()=>api.pickDirectory()],['menu-pick-shell','menu-shell-path',()=>api.pickFile()]] as const)q(id).onclick=()=>void pick().then(path=>{if(path&&revision===editRevision){q<HTMLInputElement>(input).value=path;apply();}}).catch(toast);
  q('menu-builtin-button').onclick=()=>void (async()=>{
   flush?.();const presets=await api.menuPresets();if(revision!==editRevision)return;
   const choices:CommandChoice[]=[...menuBuiltins.map(c=>({...c,id:'builtin:'+c.id,...(c.systemIcon?{path:'one-builtin:'+c.id}: {})})),...presets.filter(p=>p.kind==='command').map(p=>({id:'preset:'+p.id,label:p.label,category:'终端与开发',icon:'window',path:p.program,detail:p.available?'':'选择程序'}))];
   chooseCommand(q('menu-builtin-button'),choices,'builtin:'+q<HTMLInputElement>('menu-builtin').value,choice=>void (async()=>{
    if(revision!==editRevision)return;
    if(choice.id.startsWith('builtin:')){const command=builtinById(choice.id.slice(8))!,old=builtinById(q<HTMLInputElement>('menu-builtin').value);q<HTMLInputElement>('menu-builtin').value=command.id;q('menu-builtin-button').querySelector('span')!.textContent=command.label;const label=q<HTMLInputElement>('menu-label');if(!label.value||label.value===old?.label)label.value=command.label;(q('menu-icon') as any).value='lucide:'+command.icon;delete q('menu-icon').dataset.iconMode;apply();}
    else {const preset={...presets.find(p=>p.id===choice.id.slice(7))!};if(!preset.available){const file=await api.pickFile();if(!file||revision!==editRevision)return;preset.target=file;}
     const value={...read(),kind:'command' as const,label:preset.label,target:preset.target,args:preset.args,cwd:preset.cwd,icon:'auto',iconMode:'auto' as const,console:preset.console};delete value.shell;delete value.shellPath;
     if(editing){const id=editing;await commit(items=>items.map(i=>i.id===id?value:i));if(revision===editRevision)edit(id);}else edit('',value.parent,'command',preset.target,preset);
    }
   })().catch(toast));
  })().catch(toast);
  draw();q<HTMLInputElement>('menu-label').focus();
 };
 const add=(anchor:HTMLElement,parent?:string)=>{closeControls();addPopup?.remove();const selected=get().find(i=>i.id===editing);parent??=selected?.kind==='group'?selected.id:'';const popup=addPopup=document.createElement('div');popup.className='menu-add-popup';popup.popover='auto';popup.innerHTML=kinds().map(([kind,label])=>`<button class="quiet" data-add-kind="${kind}">${icon(symbols[kind as MenuKind])}<span>${label}</span></button>`).join('');document.body.append(popup);popup.showPopover();const box=anchor.getBoundingClientRect();popup.style.left=Math.max(8,Math.min(box.right-190,innerWidth-198))+'px';popup.style.top=Math.max(8,Math.min(box.bottom+5,innerHeight-305))+'px';popup.querySelectorAll<HTMLButtonElement>('[data-add-kind]').forEach(b=>b.onclick=()=>{const kind=b.dataset.addKind as MenuKind;popup.remove();addPopup=undefined;if(['group','separator','builtin'].includes(kind)){const id=crypto.randomUUID(),item:SearchMenuItem={id,parent:parent!,kind,label:kind==='group'?'新子菜单':kind==='builtin'?'已打开的文件夹':'',icon:'lucide:'+symbols[kind],target:kind==='builtin'?'opened':'',args:[],cwd:'',enabled:true};void commit(items=>[...items,item]).then(()=>{collapsed.delete(parent!);edit(id);q<HTMLInputElement>('menu-label').select();}).catch(toast);}else edit('',parent,kind);});};
 action('menu-add',()=>add(q('menu-add')));action('menu-item-visibility',()=>toggle(editing));action('menu-item-delete',()=>remove(editing,q('menu-item-delete')));action('menu-item-copy',duplicate);
 action('menu-create',async()=>{const value=read();await commit(items=>[...items,value]);if(value.parent)collapsed.delete(value.parent);edit(value.id);});
 action('menu-export',()=>{flush?.();q('menu-json-title').textContent='导出菜单';q<HTMLTextAreaElement>('menu-json').value=JSON.stringify(get(),null,2);q('menu-json-apply').hidden=true;openDialog(q<HTMLDialogElement>('menu-json-dialog'));q<HTMLTextAreaElement>('menu-json').select();});action('menu-import',()=>{q('menu-json-title').textContent='导入并替换菜单';q<HTMLTextAreaElement>('menu-json').value='';q('menu-json-apply').hidden=false;openDialog(q<HTMLDialogElement>('menu-json-dialog'));});action('menu-json-close',()=>closeDialog(q<HTMLDialogElement>('menu-json-dialog')));action('menu-json-apply',async()=>{const next=validateMenu(JSON.parse(q<HTMLTextAreaElement>('menu-json').value));await commit(()=>next);empty();closeDialog(q<HTMLDialogElement>('menu-json-dialog'));});
 barController=setupMenuBarEditor({get:getLayout,change:transact,dragged:()=>dragged,setDragged:key=>{flush?.();dragged=key;},finish:finishDrag,edit:id=>edit(id),selected:()=>editing,remove});
 q('search-tab-menu').addEventListener('click',()=>void loadMenuIcons().then(draw).catch(toast));q('menu-item-delete').hidden=true;q('menu-item-copy').hidden=true;q('menu-item-visibility').hidden=true;return draw;
}
