import {dialogMarkup,openDialog,closeDialog} from './dialog';
import {api,q,icon,iconButton,button,esc,toast,action} from './ui';
import {customControls,closeControls} from './controls';
import {chooseIcon,loadMenuIcons} from './icon-picker';
import {validateMenu,type SearchMenuItem,type MenuKind,type MenuShell} from '../shared/search';
const labels:Record<MenuKind,string>={folder:'文件夹',file:'文件',command:'程序与参数',shell:'Shell 命令',url:'网址',group:'子菜单',separator:'分隔线',builtin:'内置动作'};
const symbols:Record<MenuKind,string>={folder:'folder',file:'file',command:'window',shell:'terminal',url:'open',group:'folder',separator:'minus',builtin:'settings'};
const builtins=[['opened','已打开的文件夹'],['recent','最近访问'],['copy-path','复制当前路径'],['terminal','在此打开 PowerShell'],['search','文件搜索'],['settings','自定义菜单']];
export function menuEditorCard(){return `<div id="menu-editor"><div class="menu-editor-toolbar"><span id="menu-count" class="muted"></span><div class="spacer"></div>${iconButton('menu-undo','撤销上次修改','history')}${button('menu-import','导入')}${button('menu-export','导出')}${button('menu-add','添加','plus',true)}</div><div class="menu-designer"><div id="menu-editor-list" role="tree" aria-label="快捷菜单层级"></div><aside class="menu-inspector"><div class="section-heading"><h2 id="menu-edit-title">项目设置</h2><div class="menu-inspector-actions">${iconButton('menu-item-copy','复制项目','copy')}${iconButton('menu-item-delete','删除项目及子项目','trash')}</div></div><div id="menu-edit-fields"><p class="inspector-empty">选择一个项目进行编辑</p></div><p id="menu-edit-error" role="status"></p><div class="dialog-actions"><button id="menu-create" class="primary" hidden>添加项目</button></div></aside></div></div>${dialogMarkup({id:"menu-json-dialog",title:"菜单配置",closeId:"menu-json-close",titleId:"menu-json-title",body:`<textarea id="menu-json" aria-label="菜单 JSON" spellcheck="false"></textarea>`,actions:`${button('menu-json-apply','导入','',true)}`})}`;}
export function setupMenuEditor(get:()=>SearchMenuItem[],save:(items:SearchMenuItem[])=>Promise<void>){
 let editing='',draft:SearchMenuItem|undefined,dragged='',chain=Promise.resolve(),editRevision=0,flush:(()=>void)|undefined,addPopup:HTMLElement|undefined;
 const collapsed=new Set<string>(),history:SearchMenuItem[][]=[];
 const descendants=(id:string,items=get())=>{const ids=new Set<string>();if(id)ids.add(id);let previous=-1;while(previous!==ids.size){previous=ids.size;for(const item of items)if(ids.has(item.parent))ids.add(item.id);}return ids;};
 const report=(error:unknown)=>q('menu-edit-error').textContent=String(error).replace('Error: ','');
 const commit=(change:(items:SearchMenuItem[])=>SearchMenuItem[],remember=true)=>{const task=chain.catch(()=>{}).then(async()=>{const before=structuredClone(get()),next=validateMenu(change(structuredClone(before)));if(JSON.stringify(next)===JSON.stringify(before))return;await save(next);if(remember){history.push(before);if(history.length>20)history.shift();}draw();});chain=task;return task;};
 const empty=()=>{editRevision++;flush=undefined;editing='';draft=undefined;q('menu-edit-fields').innerHTML='<p class="inspector-empty">选择一个项目进行编辑</p>';q('menu-item-delete').hidden=true;q('menu-item-copy').hidden=true;q('menu-create').hidden=true;q('menu-edit-error').textContent='';draw();};
 const remove=(id=editing)=>{if(!id)return;flush=undefined;void commit(items=>{const ids=descendants(id,items);return items.filter(item=>!ids.has(item.id));}).then(()=>{if(descendants(id).has(editing)||editing===id||!get().some(i=>i.id===editing))empty();}).catch(toast);};
 const move=(id:string,direction:number)=>commit(items=>{const at=items.findIndex(i=>i.id===id);if(at<0)return items;const siblings=items.filter(i=>i.parent===items[at].parent),target=siblings[siblings.findIndex(i=>i.id===id)+direction];if(target){const to=items.findIndex(i=>i.id===target.id);[items[at],items[to]]=[items[to],items[at]];}return items;});
 const duplicate=async()=>{flush?.();const source=editing;if(!source)return;let id='';await commit(items=>{const ids=descendants(source,items),copies=new Map([...ids].map(key=>[key,crypto.randomUUID()]));id=copies.get(source)!;return [...items,...items.filter(i=>ids.has(i.id)).map(i=>({...i,id:copies.get(i.id)!,parent:i.id===source?i.parent:copies.get(i.parent)!,label:i.id===source?i.label+' 副本':i.label}))];});edit(id);};
 const draw=()=>{const items=get(),host=q('menu-editor-list'),scroll=host.scrollTop;q('menu-count').textContent=`${items.length} 项`;q<HTMLButtonElement>('menu-undo').disabled=!history.length;
  const rows=(parent:string,level:number):string=>items.filter(i=>i.parent===parent).map(i=>`<div class="menu-tree-node"><div class="menu-editor-row ${i.enabled?'':'disabled'} ${editing===i.id?'selected':''}" style="--indent:${level*16}px" data-menu-id="${i.id}" draggable="true" role="treeitem" aria-selected="${editing===i.id}" aria-level="${level+1}" ${i.kind==='group'?`aria-expanded="${!collapsed.has(i.id)}"`:''}><button class="icon-button quiet tree-toggle ${i.kind==='group'?'':'placeholder'}" data-collapse="${i.id}" aria-label="${collapsed.has(i.id)?'展开':'收起'} ${esc(i.label)}" ${i.kind==='group'?'':'tabindex="-1"'}>${icon(collapsed.has(i.id)?'chevron':'chevron-down')}</button><button class="quiet menu-item-label" data-edit="${i.id}" aria-label="编辑 ${esc(i.label||'分隔线')}">${icon(i.kind==='separator'?'minus':i.icon||symbols[i.kind])}<span>${i.kind==='separator'?'分隔线':esc(i.label)}</span></button><div class="tree-row-actions">${i.kind==='group'?`<button class="icon-button quiet" data-child="${i.id}" aria-label="添加到 ${esc(i.label)}" title="添加子项目">${icon('plus')}</button>`:''}<button class="icon-button quiet" data-up="${i.id}" aria-label="上移 ${esc(i.label)}">${icon('up')}</button><button class="icon-button quiet menu-down" data-down="${i.id}" aria-label="下移 ${esc(i.label)}">${icon('up')}</button><button class="icon-button quiet" data-delete="${i.id}" aria-label="删除 ${esc(i.label||'分隔线')}">${icon('trash')}</button></div></div>${i.kind==='group'&&!collapsed.has(i.id)?`<div role="group">${rows(i.id,level+1)}</div>`:''}</div>`).join('');host.innerHTML=rows('',0)||'<div class="menu-tree-empty">'+icon('list')+'<span>添加你的第一个快捷操作</span></div>';host.scrollTop=scroll;
  host.querySelectorAll<HTMLElement>('[data-edit]').forEach(b=>{b.onclick=()=>edit(b.dataset.edit!);b.onkeydown=e=>{if(e.key==='Delete'){e.preventDefault();remove(b.dataset.edit!);}if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();void move(b.dataset.edit!,e.key==='ArrowUp'?-1:1).catch(toast);}};});
  host.querySelectorAll<HTMLElement>('[data-child]').forEach(b=>b.onclick=()=>add(b,b.dataset.child!));host.querySelectorAll<HTMLElement>('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete!));host.querySelectorAll<HTMLElement>('[data-collapse]').forEach(b=>b.onclick=()=>{const id=b.dataset.collapse!;if(collapsed.has(id))collapsed.delete(id);else collapsed.add(id);draw();});
  for(const direction of ['up','down'] as const)host.querySelectorAll<HTMLElement>('[data-'+direction+']').forEach(b=>b.onclick=()=>void move(b.dataset[direction]!,direction==='up'?-1:1).catch(toast));
  host.querySelectorAll<HTMLElement>('[data-menu-id]').forEach(row=>{row.ondragstart=e=>{flush?.();dragged=row.dataset.menuId!;e.dataTransfer!.setData('text/plain',dragged);e.dataTransfer!.effectAllowed='move';};row.ondragover=e=>{e.preventDefault();row.classList.add('drop-target');};row.ondragleave=()=>row.classList.remove('drop-target');row.ondrop=e=>{e.preventDefault();row.classList.remove('drop-target');const target=items.find(i=>i.id===row.dataset.menuId),id=dragged;dragged='';if(!target||!id||id===target.id)return;void commit(list=>{const source=list.find(i=>i.id===id);if(!source)return list;if(target.kind==='group'){source.parent=target.id;collapsed.delete(target.id);}else{source.parent=target.parent;list=list.filter(i=>i.id!==id);list.splice(list.findIndex(i=>i.id===target.id),0,source);}return list;}).then(()=>{if(editing)edit(editing);}).catch(toast);};});
 };
 const read=():SearchMenuItem=>{const kind=q<HTMLSelectElement>('menu-kind').value as MenuKind,shell=q<HTMLSelectElement>('menu-shell').value as MenuShell;return{id:editing||draft!.id,parent:q<HTMLSelectElement>('menu-parent').value,kind,label:kind==='separator'?'':q<HTMLInputElement>('menu-label').value.trim(),icon:(q('menu-icon') as any).value,target:kind==='builtin'?q<HTMLSelectElement>('menu-builtin').value:kind==='shell'?q<HTMLTextAreaElement>('menu-script').value:q<HTMLInputElement>('menu-target').value.trim(),args:kind==='command'||kind==='shell'&&shell==='custom'?q<HTMLTextAreaElement>('menu-args').value.split(/\r?\n/).filter(Boolean):[],cwd:['command','shell','file'].includes(kind)?q<HTMLInputElement>('menu-cwd').value.trim():'',enabled:q<HTMLInputElement>('menu-enabled').checked,...(kind==='shell'?{shell,shellPath:q<HTMLInputElement>('menu-shell-path').value.trim()}:{})};};
 const edit=(id='',parent='',kind:MenuKind='command',target='')=>{flush?.();flush=undefined;closeControls();editRevision++;editing=id;draft=id?undefined:{id:crypto.randomUUID(),parent,kind,label:'',target,args:[],cwd:'',icon:'lucide:'+symbols[kind],enabled:true};const item=get().find(i=>i.id===id)||draft!;if(!item)return empty();q('menu-edit-title').textContent=id?'项目设置':'添加'+labels[kind];q('menu-item-delete').hidden=!id;q('menu-item-copy').hidden=!id;q('menu-create').hidden=!!id;q('menu-edit-error').textContent='';const excluded=descendants(id);const itemPath=(i:SearchMenuItem):string=>{const parent=get().find(p=>p.id===i.parent);return parent?itemPath(parent)+' / '+i.label:i.label;};
  q('menu-edit-fields').innerHTML=`<div class="menu-name-field"><label>名称<input id="menu-label" value="${esc(item.label)}" maxlength="200" placeholder="菜单名称"></label><label>图标<button type="button" id="menu-icon" class="menu-icon-select" aria-label="选择菜单图标">${icon(item.icon)}${icon('chevron-down')}</button></label></div><div class="menu-field-pair"><label>类型<select id="menu-kind" aria-label="菜单类型">${Object.entries(labels).map(([key,label])=>`<option value="${key}" ${key===item.kind?'selected':''}>${label}</option>`).join('')}</select></label><label>上级菜单<select id="menu-parent" aria-label="上级菜单"><option value="">主菜单</option>${get().filter(i=>i.kind==='group'&&!excluded.has(i.id)).map(i=>`<option value="${i.id}" ${i.id===item.parent?'selected':''}>${esc(itemPath(i))}</option>`).join('')}</select></label></div><div id="menu-target-field"><label><span id="menu-target-label">目标</span><div class="menu-path-field"><input id="menu-target" value="${esc(item.kind==='shell'?'':item.target)}" placeholder="文件路径">${iconButton('menu-pick-target','选择目标文件','folder')}</div></label></div><label id="menu-builtin-field">动作<select id="menu-builtin" aria-label="内置动作">${builtins.map(([key,label])=>`<option value="${key}" ${key===item.target?'selected':''}>${label}</option>`).join('')}</select></label><div id="menu-shell-fields"><label>Shell<select id="menu-shell" aria-label="运行命令的 Shell">${[['powershell','Windows PowerShell'],['pwsh','PowerShell 7'],['cmd','命令提示符'],['custom','其他 Shell']].map(([key,label])=>`<option value="${key}" ${key===(item.shell??'powershell')?'selected':''}>${label}</option>`).join('')}</select></label><label id="menu-shell-path-field">Shell 程序<div class="menu-path-field"><input id="menu-shell-path" value="${esc(item.shellPath||'')}" placeholder="选择 bash.exe 等程序">${iconButton('menu-pick-shell','选择 Shell 程序','folder')}</div></label><label>命令<textarea id="menu-script" spellcheck="false" placeholder="Get-ChildItem">${esc(item.kind==='shell'?item.target:'')}</textarea></label><p id="menu-shell-context" class="menu-field-hint"></p></div><div id="menu-command-fields"><label>参数 · 每行一个<textarea id="menu-args" spellcheck="false" placeholder="{selected}">${esc(item.args.join('\n'))}</textarea></label><p id="menu-args-hint" class="menu-field-hint"></p></div><label id="menu-cwd-field">工作目录<div class="menu-path-field"><input id="menu-cwd" value="${esc(item.cwd)}" placeholder="当前文件夹">${iconButton('menu-pick-dir','选择工作目录','folder')}</div></label><label class="menu-enabled"><input id="menu-enabled" type="checkbox" ${item.enabled?'checked':''}>显示此项目</label>`;
  customControls(q('menu-edit-fields'));(q('menu-icon') as any).value=item.icon;
  let previousKind=item.kind,timer:ReturnType<typeof setTimeout>|undefined;const revision=editRevision;
  const fields=()=>{const kind=q<HTMLSelectElement>('menu-kind').value as MenuKind,shell=q<HTMLSelectElement>('menu-shell').value as MenuShell;if(kind!==previousKind){q<HTMLInputElement>('menu-target').value='';q<HTMLTextAreaElement>('menu-script').value='';q<HTMLTextAreaElement>('menu-args').value='';previousKind=kind;}
   q('menu-target-field').hidden=!['folder','file','url','command'].includes(kind);q('menu-shell-fields').hidden=kind!=='shell';q('menu-shell-path-field').hidden=shell!=='custom';q('menu-command-fields').hidden=kind!=='command'&&!(kind==='shell'&&shell==='custom');q('menu-builtin-field').hidden=kind!=='builtin';q('menu-cwd-field').hidden=!['file','command','shell'].includes(kind);q('menu-pick-target').hidden=kind==='url';q<HTMLInputElement>('menu-label').disabled=kind==='separator';q('menu-target-label').textContent=kind==='command'?'程序':kind==='url'?'网址':kind==='folder'?'文件夹':'文件';q<HTMLInputElement>('menu-target').placeholder=kind==='url'?'https://':kind==='command'?'程序路径或名称':'选择路径';q('menu-shell-context').textContent=shell==='cmd'?'当前目录：%ONE_FOLDER% · 选中文件：%ONE_SELECTED%':shell==='powershell'||shell==='pwsh'?'当前目录：$env:ONE_FOLDER · 选中文件：$env:ONE_SELECTED':'当前目录和选中文件通过 ONE_FOLDER、ONE_SELECTED 环境变量提供';q('menu-args-hint').textContent=kind==='shell'?'使用 {command} 传入上面的整段命令。':'{folder} 当前目录 · {selected} 选中文件 · {selection} 所有选中文件';};fields();
  const apply=()=>{clearTimeout(timer);timer=undefined;fields();if(!editing)return;const value=read(),selected=editing;try{validateMenu(get().map(i=>i.id===selected?value:i));q('menu-edit-error').textContent='';}catch(error){report(error);return;}if(JSON.stringify(get().find(i=>i.id===selected))===JSON.stringify(value))return;void commit(items=>items.map(i=>i.id===selected?value:i)).catch(error=>{if(revision===editRevision)report(error);});};flush=()=>{if(timer)apply();};q('menu-edit-fields').onchange=apply;q('menu-edit-fields').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(editRevision===revision)apply();},300);};
  q('menu-icon').onclick=()=>void chooseIcon((q('menu-icon') as any).value,name=>{if(editRevision!==revision)return;(q('menu-icon') as any).value=name;q('menu-icon').innerHTML=icon(name)+icon('chevron-down');apply();}).catch(toast);
  q('menu-pick-target').onclick=()=>void (q<HTMLSelectElement>('menu-kind').value==='folder'?api.pickDirectory():api.pickFile()).then(path=>{if(path&&revision===editRevision){q<HTMLInputElement>('menu-target').value=path;if(!q<HTMLInputElement>('menu-label').value)q<HTMLInputElement>('menu-label').value=path.split(/[\\/]/).pop()||path;apply();}}).catch(toast);
  for(const [id,input,pick]of [['menu-pick-dir','menu-cwd',()=>api.pickDirectory()],['menu-pick-shell','menu-shell-path',()=>api.pickFile()]] as const)q(id).onclick=()=>void pick().then(path=>{if(path&&revision===editRevision){q<HTMLInputElement>(input).value=path;apply();}}).catch(toast);
  draw();q<HTMLInputElement>('menu-label').focus();
 };
 const add=(anchor:HTMLElement,parent?:string)=>{closeControls();addPopup?.remove();const selected=get().find(i=>i.id===editing);parent??=selected?.kind==='group'?selected.id:'';const popup=addPopup=document.createElement('div');popup.className='menu-add-popup';popup.popover='auto';popup.innerHTML=Object.entries(labels).map(([kind,label])=>`<button class="quiet" data-add-kind="${kind}">${icon(symbols[kind as MenuKind])}<span>${label}</span></button>`).join('');document.body.append(popup);popup.showPopover();const box=anchor.getBoundingClientRect();popup.style.left=Math.max(8,Math.min(box.right-190,innerWidth-198))+'px';popup.style.top=Math.max(8,Math.min(box.bottom+5,innerHeight-305))+'px';popup.querySelectorAll<HTMLButtonElement>('[data-add-kind]').forEach(b=>b.onclick=()=>{const kind=b.dataset.addKind as MenuKind;popup.remove();addPopup=undefined;if(['group','separator','builtin'].includes(kind)){const id=crypto.randomUUID(),item:SearchMenuItem={id,parent:parent!,kind,label:kind==='group'?'新子菜单':kind==='builtin'?'已打开的文件夹':'',icon:'lucide:'+symbols[kind],target:kind==='builtin'?'opened':'',args:[],cwd:'',enabled:true};void commit(items=>[...items,item]).then(()=>{collapsed.delete(parent!);edit(id);q<HTMLInputElement>('menu-label').select();}).catch(toast);}else edit('',parent,kind);});};
 action('menu-add',()=>add(q('menu-add')));action('menu-item-delete',()=>remove());action('menu-item-copy',duplicate);action('menu-undo',async()=>{flush=undefined;const previous=history[history.length-1];if(!previous)return;await commit(()=>previous,false);history.pop();empty();});
 action('menu-create',async()=>{const value=read();await commit(items=>[...items,value]);if(value.parent)collapsed.delete(value.parent);edit(value.id);});
 action('menu-export',()=>{flush?.();q('menu-json-title').textContent='导出菜单';q<HTMLTextAreaElement>('menu-json').value=JSON.stringify(get(),null,2);q('menu-json-apply').hidden=true;openDialog(q<HTMLDialogElement>('menu-json-dialog'));q<HTMLTextAreaElement>('menu-json').select();});action('menu-import',()=>{q('menu-json-title').textContent='导入并替换菜单';q<HTMLTextAreaElement>('menu-json').value='';q('menu-json-apply').hidden=false;openDialog(q<HTMLDialogElement>('menu-json-dialog'));});action('menu-json-close',()=>closeDialog(q<HTMLDialogElement>('menu-json-dialog')));action('menu-json-apply',async()=>{const next=validateMenu(JSON.parse(q<HTMLTextAreaElement>('menu-json').value));await commit(()=>next);empty();closeDialog(q<HTMLDialogElement>('menu-json-dialog'));});
 q('search-tab-menu').addEventListener('click',()=>void loadMenuIcons().then(draw).catch(toast));q('menu-item-delete').hidden=true;q('menu-item-copy').hidden=true;q<HTMLButtonElement>('menu-undo').disabled=true;return draw;
}
