import JSZip from 'jszip';
import {renderAsync} from 'docx-preview';
import {esc,iconButton} from './ui';
import type {SetOutline,SetOverview} from './preview-outline';
const all=(node:ParentNode,name:string)=>Array.from((node as Element).getElementsByTagNameNS('*',name));
const first=(node:ParentNode,name:string)=>all(node,name)[0];
const xml=(text:string)=>{const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw new Error('文档 XML 无法读取');return doc;};
const framePolicy="default-src 'none'; img-src data: blob: one-file:; style-src 'unsafe-inline' one-file:; font-src data: blob:; base-uri 'none'; form-action 'none'";
export function isolatedFrame(host:HTMLElement,html:string,styles=''){
  const frame=document.createElement('iframe');frame.className='document-frame';frame.setAttribute('sandbox','allow-same-origin');frame.setAttribute('title','文档内容');frame.srcdoc=`<!doctype html><html><head><meta charset="UTF-8"><meta http-equiv="Content-Security-Policy" content="${framePolicy}"><style>html,body{margin:0;min-height:100%;font-family:Segoe UI,Microsoft YaHei,sans-serif;color:#252525;background:#fff}*{box-sizing:border-box}body{overflow-wrap:anywhere}img,video,svg{max-width:100%;height:auto}pre{white-space:pre-wrap;overflow-wrap:anywhere}table{max-width:100%;border-collapse:collapse}a{color:inherit}::-webkit-scrollbar{width:8px;height:8px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:#9997;border:2px solid transparent;background-clip:padding-box;border-radius:8px}::-webkit-scrollbar-button{display:none} ${styles}</style></head><body>${html}</body></html>`;host.append(frame);return frame;
}
export async function renderDocx(host:HTMLElement,url:string,metadata:(v:Record<string,string>)=>void,outline:SetOutline=()=>{},overview:SetOverview=()=>{}){
 const soft=getComputedStyle(document.documentElement).getPropertyValue('--soft'),frame=isolatedFrame(host,'',`body{background:${soft}}.docx-wrapper{background:transparent!important;padding:28px!important}.docx-wrapper>section.docx{box-shadow:0 1px 8px #0001;margin-bottom:28px!important}section.docx{overflow:hidden}`);
 const controller=new AbortController();let cancelled=false,observer:ResizeObserver|undefined,removeScroll:(()=>void)|undefined;
 void(async()=>{await new Promise<void>(resolve=>frame.onload=()=>resolve());const bytes=await fetch(url,{signal:controller.signal}).then(r=>r.arrayBuffer());if(cancelled)return;const archive=await JSZip.loadAsync(bytes),source=xml(await archive.file('word/document.xml')!.async('string')),styleFile=archive.file('word/styles.xml'),styleDoc=styleFile?xml(await styleFile.async('string')):undefined,stylesMap=new Map<string,Element>();if(styleDoc)for(const style of all(styleDoc,'style'))stylesMap.set(style.getAttribute('w:styleId')||'',style);
  const attr=(node:Element|undefined)=>node?.getAttribute('w:val')??node?.getAttribute('val');const level=(id:string,seen=new Set<string>()):number|undefined=>{if(seen.has(id))return;seen.add(id);const style=stylesMap.get(id),value=attr(style&&first(style,'outlineLvl'));if(value!==undefined&&value!==null)return Number(value)<9?Number(value):undefined;const name=attr(style&&first(style,'name'))||id,m=/^(?:heading|标题)\s*([1-9])/i.exec(name);if(m)return Number(m[1])-1;const parent=attr(style&&first(style,'basedOn'));return parent?level(parent,seen):undefined;};
  const titles:{label:string;depth:number}[]=[];for(const p of all(source,'p')){const properties=Array.from(p.children).find(n=>n.localName==='pPr'),direct=attr(properties&&first(properties,'outlineLvl')),depth=direct!==undefined&&direct!==null?Number(direct):level(attr(properties&&first(properties,'pStyle'))||'');const label=all(p,'t').map(t=>t.textContent).join('').trim();if(depth!==undefined&&depth<9&&label)titles.push({label,depth});}
  const doc=frame.contentDocument!,content=doc.createElement('div'),styles=doc.createElement('div');doc.body.append(styles,content);await renderAsync(bytes,content,styles,{inWrapper:true,breakPages:true,ignoreLastRenderedPageBreak:false,ignoreWidth:false,ignoreHeight:false,useBase64URL:true,renderAltChunks:false,renderComments:false,ignoreFonts:true});if(cancelled)return;doc.querySelectorAll('a').forEach(a=>a.removeAttribute('href'));const pages=Array.from(doc.querySelectorAll<HTMLElement>('section.docx')),paragraphs=Array.from(doc.querySelectorAll<HTMLElement>('section.docx article p'));
  const normalize=(s:string)=>s.replace(/\s/g,'');let cursor=0;const entries=titles.flatMap(t=>{const at=paragraphs.findIndex((p,i)=>i>=cursor&&normalize(p.textContent||'')===normalize(t.label));if(at<0)return [];cursor=at+1;const p=paragraphs[at];p.dataset.outlineLevel=String(t.depth);return [{label:t.label,depth:t.depth,activate:()=>p.scrollIntoView({behavior:'smooth',block:'start'})}];});outline(entries);
  let active=0,scrollFrame=0;const scrollPage=()=>{cancelAnimationFrame(scrollFrame);scrollFrame=requestAnimationFrame(()=>{const middle=frame.clientHeight*.5;let page=0;for(let i=1;i<pages.length;i++){if(pages[i].getBoundingClientRect().top>middle)break;page=i;}if(page!==active){active=page;host.dispatchEvent(new CustomEvent('preview-page',{bubbles:true,detail:{page:page+1}}));}});};frame.contentWindow!.addEventListener('scroll',scrollPage,{passive:true});removeScroll=()=>{cancelAnimationFrame(scrollFrame);frame.contentWindow?.removeEventListener('scroll',scrollPage);};const fit=()=>{for(const page of pages){page.style.zoom='1';page.style.zoom=String(Math.min(1,Math.max(.1,(frame.clientWidth-56)/page.offsetWidth)));}};observer=new ResizeObserver(fit);observer.observe(frame);fit();metadata({'页面':String(pages.length),...(entries.length?{'目录来源':'Word 标题样式 / 大纲级别'}:{})});const css=Array.from(doc.querySelectorAll('style')).map(s=>s.textContent).join('\n');overview(pages.map((page,i)=>({label:'第 '+(i+1)+' 页',activate:()=>page.scrollIntoView({behavior:'smooth',block:'start'}),thumbnail:()=>{const wrapper=document.createElement('div');wrapper.className='docx-thumbnail';const ratio=160/page.offsetWidth;wrapper.style.width='160px';wrapper.style.height=Math.min(300,page.offsetHeight*ratio)+'px';const shadow=wrapper.attachShadow({mode:'open'}),style=document.createElement('style');style.textContent=css+' :host{display:block;overflow:hidden;background:#fff;font:16px Segoe UI,Microsoft YaHei,sans-serif;color:#252525;text-align:left;line-height:normal}*{box-sizing:border-box}section.docx{zoom:1!important;margin:0!important;box-shadow:none!important;transform-origin:0 0;transform:scale('+ratio+')}';const clone=page.cloneNode(true) as HTMLElement;clone.style.zoom='1';clone.style.width=page.offsetWidth+'px';shadow.append(style,clone);return wrapper;}})));
 })().catch(error=>{if(!cancelled)frame.srcdoc=`<p>${esc(error.message)}</p>`;});
 return()=>{cancelled=true;controller.abort();observer?.disconnect();removeScroll?.();frame.remove();};
}
// A small OOXML renderer for editable slide content: text, images, shapes, tables and layout placeholders.
// It intentionally does not execute animation, macros or embedded objects.
export async function renderPptx(host:HTMLElement,url:string,metadata:(v:Record<string,string>)=>void,outline:SetOutline=()=>{},overview:SetOverview=()=>{}){
  const controller=new AbortController();let disposed=false;const zip=await JSZip.loadAsync(await fetch(url,{signal:controller.signal}).then(r=>r.arrayBuffer()));
  const read=async(path:string)=>{const file=zip.file(path);return file?xml(await file.async('string')):undefined;};
  const presentation=await read('ppt/presentation.xml');if(!presentation)throw new Error('演示文稿缺少 presentation.xml');const size=first(presentation,'sldSz');const width=Number(size?.getAttribute('cx')||9144000),height=Number(size?.getAttribute('cy')||5143500);
  const resolvePath=(base:string,target:string)=>{const parts=base.split('/').slice(0,-1);for(const p of target.split('/')){if(p==='..')parts.pop();else if(p!=='.')parts.push(p);}return parts.join('/');};
  const relations=async(path:string)=>{const parent=path.slice(0,path.lastIndexOf('/')+1),name=path.slice(path.lastIndexOf('/')+1);const doc=await read(parent+'_rels/'+name+'.rels');const result=new Map<string,string>();if(doc)for(const rel of all(doc,'Relationship'))if(rel.getAttribute('TargetMode')!=='External')result.set(rel.getAttribute('Id')!,resolvePath(path,rel.getAttribute('Target')!));return result;};
  const presentationRels=await relations('ppt/presentation.xml');const slides=all(presentation,'sldId').map(n=>presentationRels.get(n.getAttribute('r:id')!)).filter(Boolean) as string[];
  if(slides.length>500)throw new Error('演示文稿超过 500 页');metadata({'幻灯片':String(slides.length),'比例':`${Math.round(width/height*100)/100}:1`});
  const theme=await read('ppt/theme/theme1.xml');const palette:Record<string,string>={dk1:'#000000',lt1:'#ffffff',dk2:'#333333',lt2:'#eeeeee',accent1:'#4472c4',accent2:'#ed7d31'};if(theme){const scheme=first(theme,'clrScheme');if(scheme)for(const c of Array.from(scheme.children)){const child=c.children[0];palette[c.localName]='#'+(child?.getAttribute('val')?.match(/^[a-f\d]{6}$/i)?.[0]||child?.getAttribute('lastClr')||'333333');}}
  const color=(node:Element|undefined,fallback:string)=>{if(!node)return fallback;const rgb=first(node,'srgbClr'),scheme=first(node,'schemeClr');return rgb?'#'+rgb.getAttribute('val'):scheme?palette[scheme.getAttribute('val')!]||fallback:fallback;};
  host.innerHTML=`<div class="reader-toolbar">${iconButton('slide-prev','上一张','back')}<span id="slide-position"></span>${iconButton('slide-next','下一张','arrow')}</div><div class="slide-scroll"><div class="slide-pages"></div></div>`;
  const scroll=host.querySelector<HTMLElement>('.slide-scroll')!,container=host.querySelector<HTMLElement>('.slide-pages')!,stages=slides.map((_,i)=>{const stage=document.createElement('div');stage.className='slide-stage';stage.style.aspectRatio=String(width/height);stage.dataset.page=String(i+1);stage.setAttribute('aria-label','幻灯片 '+(i+1));container.append(stage);return stage;});let index=0,revision=0;
  const draw=async(at:number,stage:HTMLElement)=>{const version=revision,slidePath=slides[at],slide=await read(slidePath);if(!slide)return;const rels=await relations(slidePath);let layout:Document|undefined;const layoutPath=Array.from(rels.values()).find(p=>p.includes('/slideLayouts/'));if(layoutPath)layout=await read(layoutPath);
    let master:Document|undefined,masterRels=new Map<string,string>();if(layoutPath){const layoutRels=await relations(layoutPath);const path=Array.from(layoutRels.values()).find(p=>p.includes('/slideMasters/'));if(path){master=await read(path);masterRels=await relations(path);}}
    if(disposed||version!==revision)return;stage.replaceChildren();stage.style.background=color(first(slide,'bg')||layout&&first(layout,'bg')||master&&first(master,'bg'),'#fff');
    const scale=(n:number,dimension=width)=>n/dimension*100+'%';
    const shape=async(node:Element,rels:Map<string,string>,isMaster=false)=>{
      const ph=first(node,'ph');if(isMaster&&ph)return;
      const layoutNode=ph&&layout?all(layout,'sp').find(sp=>{const target=first(sp,'ph');return target&&(target.getAttribute('idx')||'')===(ph.getAttribute('idx')||'')&&(target.getAttribute('type')||'')===(ph.getAttribute('type')||'');}):undefined;
      const xfrm=first(node,'xfrm')||(layoutNode&&first(layoutNode,'xfrm'));if(!xfrm)return;
      const off=first(xfrm,'off'),ext=first(xfrm,'ext');if(!off||!ext)return;
      const box=document.createElement('div');box.className='slide-shape';Object.assign(box.style,{left:scale(Number(off.getAttribute('x'))),top:scale(Number(off.getAttribute('y')),height),width:scale(Number(ext.getAttribute('cx'))),height:scale(Number(ext.getAttribute('cy')),height)});const rotate=Number(xfrm.getAttribute('rot')||0)/60000;if(rotate)box.style.transform=`rotate(${rotate}deg)`;
      if(node.localName==='pic'){const blip=first(node,'blip'),path=blip&&rels.get(blip.getAttribute('r:embed')!);if(path){const file=zip.file(path);if(file){const image=document.createElement('img');const ext=path.split('.').pop()?.toLowerCase();image.src=`data:image/${ext==='jpg'?'jpeg':ext};base64,${await file.async('base64')}`;box.append(image);}}}
      else if(node.localName==='graphicFrame'){const table=first(node,'tbl');if(table){const t=document.createElement('table');for(const row of all(table,'tr')){const tr=document.createElement('tr');for(const cell of Array.from(row.children).filter(n=>n.localName==='tc')){const td=document.createElement('td');td.textContent=all(cell,'t').map(n=>n.textContent).join(' ');tr.append(td);}t.append(tr);}box.append(t);}else{box.classList.add('slide-placeholder');box.textContent='嵌入对象';}}
      else {const properties=Array.from(node.children).find(n=>n.localName==='spPr');const fill=properties&&Array.from(properties.children).find(n=>n.localName==='solidFill');if(fill)box.style.background=color(fill,'transparent');const preset=properties&&first(properties,'prstGeom')?.getAttribute('prst');if(preset==='ellipse')box.style.borderRadius='50%';else if(preset==='roundRect')box.style.borderRadius='10px';const line=properties&&Array.from(properties.children).find(n=>n.localName==='ln');if(line&&!first(line,'noFill'))box.style.border=`1px solid ${color(line,'#888')}`;
        const body=first(node,'txBody');if(body){box.classList.add('slide-text');const bodyPr=first(body,'bodyPr');box.style.justifyContent=bodyPr?.getAttribute('anchor')==='ctr'?'center':bodyPr?.getAttribute('anchor')==='b'?'flex-end':'flex-start';for(const p of Array.from(body.children).filter(n=>n.localName==='p')){const para=document.createElement('p'),pPr=first(p,'pPr');para.style.textAlign=({ctr:'center',r:'right',just:'justify'} as Record<string,string>)[pPr?.getAttribute('algn')||'']||'left';if(first(p,'buChar'))para.append('• ');for(const run of Array.from(p.children)){if(run.localName==='br'){para.append(document.createElement('br'));continue;}if(!['r','fld'].includes(run.localName))continue;const rPr=first(run,'rPr')||pPr&&first(pPr,'defRPr'),span=document.createElement('span');span.textContent=first(run,'t')?.textContent||'';const points=Number(rPr?.getAttribute('sz')||pPr&&first(pPr,'defRPr')?.getAttribute('sz')||2000)/100;span.style.fontSize=`${points*12700/width*100}cqw`;span.style.color=color(rPr,'#202020');if(rPr?.getAttribute('b')==='1')span.style.fontWeight='700';if(rPr?.getAttribute('i')==='1')span.style.fontStyle='italic';if(rPr?.getAttribute('u')&&rPr.getAttribute('u')!=='none')span.style.textDecoration='underline';para.append(span);}box.append(para);}}
      }if(!disposed&&version===revision)stage.append(box);
    };
    for(const [doc,map,isMaster] of [[master,masterRels,true],[slide,rels,false]] as const){const tree=doc&&first(doc,'spTree');if(tree)for(const node of Array.from(tree.children))if(['sp','pic','graphicFrame'].includes(node.localName))await shape(node,map,isMaster);}
  };
  const controls=()=>{host.querySelector('#slide-position')!.textContent=`${index+1} / ${slides.length}`;host.querySelector<HTMLButtonElement>('#slide-prev')!.disabled=index===0;host.querySelector<HTMLButtonElement>('#slide-next')!.disabled=index===slides.length-1;host.dispatchEvent(new CustomEvent('preview-page',{bubbles:true,detail:{page:index+1}}));};
  const rendered=new Set<number>(),pending=new Set<number>(),queue:number[]=[];let working=false;const enqueue=(i:number)=>{if(!rendered.has(i)&&!pending.has(i)){pending.add(i);queue.push(i);}void pump();};async function pump(){if(working||disposed||!queue.length)return;working=true;const i=queue.shift()!;try{await draw(i,stages[i]);if(!disposed)rendered.add(i);}catch(error){if(!disposed)stages[i].textContent=String(error);}finally{pending.delete(i);working=false;for(const n of rendered){if(rendered.size<=8)break;if(Math.abs(n-index)>3){stages[n].replaceChildren();rendered.delete(n);}}void pump();}}
  const jump=(i:number)=>{index=Math.max(0,Math.min(slides.length-1,i));scroll.scrollTo({top:stages[index].offsetTop-container.offsetTop,behavior:'auto'});controls();enqueue(index);};
  host.querySelector<HTMLElement>('#slide-prev')!.onclick=()=>jump(index-1);host.querySelector<HTMLElement>('#slide-next')!.onclick=()=>jump(index+1);
  let scrollFrame=0;const onScroll=()=>{cancelAnimationFrame(scrollFrame);scrollFrame=requestAnimationFrame(()=>{let lo=0,hi=stages.length-1;while(lo<hi){const m=Math.floor((lo+hi+1)/2);if(stages[m].offsetTop-container.offsetTop<=scroll.scrollTop+scroll.clientHeight*.5)lo=m;else hi=m-1;}index=lo;controls();enqueue(index);});};scroll.addEventListener('scroll',onScroll,{passive:true});
  const fit=()=>{for(const stage of stages)stage.style.width=Math.max(100,Math.min(1600,scroll.clientWidth-56))+'px';};const resize=new ResizeObserver(fit);resize.observe(scroll);fit();controls();await draw(0,stages[0]);rendered.add(0);const visibility=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)enqueue(Number((e.target as HTMLElement).dataset.page)-1);},{root:scroll,rootMargin:'600px'});stages.forEach(stage=>visibility.observe(stage));
  const entries=[];for(const [i,path]of slides.entries()){if(disposed)break;const doc=await read(path);if(!doc)continue;const shapes=all(doc,'sp'),title=shapes.find(sp=>['title','ctrTitle'].includes(first(sp,'ph')?.getAttribute('type')||''))||shapes.find(sp=>all(sp,'t').some(t=>t.textContent?.trim()));const label=title?all(title,'p').map(p=>all(p,'t').map(t=>t.textContent).join('')).find(t=>t.trim())?.trim():undefined;if(label)entries.push({label,activate:()=>jump(i)});if(i%10===0)await new Promise(r=>setTimeout(r,0));}if(!disposed){outline(entries);overview(slides.map((_,i)=>({label:'幻灯片 '+(i+1),activate:()=>jump(i),thumbnail:async()=>{const stage=document.createElement('div');stage.className='slide-stage slide-thumbnail';stage.style.aspectRatio=String(width/height);stage.style.width='160px';await draw(i,stage);return stage;}})));}
  return()=>{disposed=true;revision++;controller.abort();resize.disconnect();visibility.disconnect();cancelAnimationFrame(scrollFrame);scroll.removeEventListener('scroll',onScroll);queue.length=0;};
}
