import {api,q,esc,icon,iconButton,toast} from './ui';
import type {PortEntry,PortSnapshot,ServiceEntry} from '../shared/ports';
import './ports.css';

const stateLabel:Record<string,string>={Listen:'监听中',Listening:'监听中',Established:'已连接',Bound:'已绑定',TimeWait:'等待关闭',CloseWait:'等待关闭',SynSent:'正在连接',SynReceived:'正在连接',Running:'运行中',Stopped:'已停止'};
const stateRank:Record<string,number>={Listen:0,Listening:0,Established:1,SynSent:2,SynReceived:2,TimeWait:3,CloseWait:3,Bound:4};
const endpoint=(address:string,port:number,remote=false)=>{if(!port)return '';const any=['::','0.0.0.0','*',''].includes(address);return any?(remote?'任意远端':'所有本地地址')+` · ${port}`:`${address.includes(':')?`[${address}]`:address} · ${port}`;};
const portText=(item:PortEntry)=>`${item.protocol} · ${endpoint(item.localAddress,item.localPort)}${item.remotePort?`  →  ${endpoint(item.remoteAddress,item.remotePort,true)}`:''}`;
const loading=()=>{q('ports-summary').innerHTML=Array.from({length:3},()=>'<article class="ports-metric-loading"><i></i><span>正在读取…</span></article>').join('');q('ports-table').innerHTML=`<div class="ports-loading" role="status"><div class="ports-loading-copy"><span class="ports-pulse"></span><strong>正在读取端口与服务</strong><small>首次读取可能需要几秒钟</small></div><div class="ports-loading-head"><span>进程</span><span>网络端点</span><span>状态</span></div>${Array.from({length:3},()=>'<div class="ports-loading-row"><i></i><i></i><i></i></div>').join('')}</div>`;q<HTMLInputElement>('ports-query').disabled=true;};
export function portsPage(){return `<div class="ports-page"><div class="toolbar module-toolbar"><div class="tabs" role="tablist" aria-label="端口与服务"><button class="selected" data-ports-tab="ports" aria-selected="true">网络端口</button><button data-ports-tab="services" aria-selected="false">系统服务</button></div><span class="ports-freshness" id="ports-freshness">正在准备检查…</span><div class="spacer"></div>${iconButton('ports-refresh','重新扫描','refresh')}</div><div class="ports-summary" id="ports-summary"></div><div class="ports-filter">${icon('search')}<input id="ports-query" aria-label="筛选端口与服务" placeholder="筛选进程、端口、地址或状态"></div><section class="ports-table" id="ports-table" aria-live="polite"></section></div>`;}
export function setupPorts(){
 let data:PortSnapshot|undefined,tab:'ports'|'services'='ports',active=true;
 const draw=()=>{if(!active||!data)return;const query=q<HTMLInputElement>('ports-query').value.trim().toLowerCase();const table=q('ports-table');q<HTMLInputElement>('ports-query').disabled=false;q('ports-freshness').textContent=`更新于 ${new Date(data.captured).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`;
  if(tab==='ports'){const all=[...data.ports].sort((a,b)=>(stateRank[a.state]??5)-(stateRank[b.state]??5)||(a.process||'').localeCompare(b.process||'')||a.localPort-b.localPort);const rows=all.filter(item=>!query||[item.process,item.protocol,item.state,item.localAddress,item.localPort,item.remoteAddress,item.remotePort,item.pid,stateLabel[item.state]].join(' ').toLowerCase().includes(query));const listening=data.ports.filter(item=>item.state==='Listen'||item.state==='Listening').length,connected=data.ports.filter(item=>item.state==='Established').length;q('ports-summary').innerHTML=`<article><span>监听端口</span><strong>${listening.toLocaleString()}</strong><small>等待外部连接</small></article><article><span>活动连接</span><strong>${connected.toLocaleString()}</strong><small>${data.ports.length.toLocaleString()} 个网络端点</small></article><article><span>关联进程</span><strong>${new Set(data.ports.map(item=>item.pid).filter(Boolean)).size.toLocaleString()}</strong><small>按连接状态排序</small></article>`;table.innerHTML=`<div class="ports-head"><span>进程</span><span>网络端点</span><span>状态</span></div>${rows.length?rows.map(item=>`<div class="ports-row"><div><strong>${esc(item.process||'系统进程')}</strong><small>PID ${item.pid||'—'}</small></div><div><strong>${esc(portText(item))}</strong><small>${item.remotePort?'远端已连接':item.localPort?`本地端口 ${item.localPort}`:'未分配端口'}</small></div><span class="ports-state" data-state="${esc(item.state)}">${esc(stateLabel[item.state]||item.state||'未知')}</span></div>`).join(''):'<p class="ports-empty">没有匹配的端口</p>'}`;}
  else {const rows=data.services.filter(item=>!query||[item.name,item.displayName,item.state,item.startMode,item.pid,item.path,stateLabel[item.state]].join(' ').toLowerCase().includes(query));q('ports-summary').innerHTML=`<article><span>正在运行</span><strong>${data.services.filter(item=>item.state==='Running').length.toLocaleString()}</strong><small>${data.services.length.toLocaleString()} 个系统服务</small></article><article><span>自动启动</span><strong>${data.services.filter(item=>item.startMode==='Auto').length.toLocaleString()}</strong><small>随系统启动</small></article><article><span>手动或已停止</span><strong>${data.services.filter(item=>item.state!=='Running').length.toLocaleString()}</strong><small>按需运行的服务</small></article>`;table.innerHTML=`<div class="ports-head"><span>服务</span><span>启动方式</span><span>状态</span></div>${rows.length?rows.map((item:ServiceEntry)=>`<div class="ports-row"><div><strong>${esc(item.displayName||item.name)}</strong><small>${esc(item.name)}${item.pid?` · PID ${item.pid}`:''}</small></div><div><strong>${esc(item.startMode||'—')}</strong><small>${esc(item.path||'系统服务')}</small></div><span class="ports-state" data-state="${esc(item.state)}">${esc(stateLabel[item.state]||item.state||'未知')}</span></div>`).join(''):'<p class="ports-empty">没有匹配的服务</p>'}`;}
 };
 const load=async(refresh=false)=>{const button=q<HTMLButtonElement>('ports-refresh');button.disabled=true;if(!data)loading();else q('ports-freshness').textContent='正在重新读取…';try{data=await api.portSnapshot(refresh);draw();}finally{button.disabled=false;}};
 document.querySelectorAll<HTMLButtonElement>('[data-ports-tab]').forEach(button=>button.onclick=()=>{tab=button.dataset.portsTab as typeof tab;document.querySelectorAll<HTMLButtonElement>('[data-ports-tab]').forEach(node=>{const selected=node===button;node.classList.toggle('selected',selected);node.setAttribute('aria-selected',String(selected));});draw();});
 q<HTMLInputElement>('ports-query').oninput=draw;q('ports-refresh').onclick=()=>void load(true).catch(toast);loading();void load().catch(toast);
 return {activate(value:boolean){active=value;if(value&&data)draw();}};
}
