import {DirectoryList} from './directory-list';
import {renderDirectoryTree} from './directory-tree';
import type {PreviewData,FileEntry} from '../shared/types';
import {defaultPreview,type PreviewPreferences} from '../shared/preview';
import {api,q,esc,icon,iconButton,size,toast,action} from './ui';
import {renderDocument,archiveTree,previewText} from './document-view';
import {codeText} from './code-view';
import {fileIcon,refreshFileIcons} from './file-icons';
import {renderPDF} from './pdf-view';
import {renderDocx,renderPptx} from './office-view';
import {renderMedia} from './media-view';
import {closeControls,openControl,releaseControl} from './controls';
import type {OutlineItem,OverviewItem} from './preview-outline';
import {windowControls,setupChrome} from './chrome';

function parent(path:string){const value=path.replace(/[\\/]+$/,'');if(/^[a-z]:$/i.test(value))return value+'\\';const i=value.lastIndexOf('\\');return i<0?path:/^[a-z]:$/i.test(value.slice(0,i))?value.slice(0,i)+'\\':value.slice(0,i)||path;}
const typeName:Record<string,string>={folder:'文件夹',archive:'压缩包',markdown:'Markdown',text:'源码',image:'图片',media:'媒体',workbook:'工作簿',notebook:'Notebook',font:'字体',epub:'电子书',unsupported:'文件'};

export async function renderPreview(){
 document.body.classList.add('preview-window','custom-preview-frame');
 q('app').innerHTML=`<div class="preview-shell">
  <header class="preview-head drag-region"><div class="preview-navigation-actions">${iconButton('preview-files','侧边栏','panel-left')}${iconButton('preview-pin','置顶','pin')}${iconButton('preview-hold','保持窗口（失去焦点仍保留）','hold')}<span id="preview-return-wrap" hidden>${iconButton('preview-return','返回文件夹','back')}</span></div><span class="toolbar-divider"></span><div class="preview-title"><span id="preview-title-icon"></span><div><h2 id="preview-name">预览</h2></div></div>
   <div class="preview-top-actions">${iconButton('preview-reveal','在文件资源管理器中显示','folder')}<div class="preview-open-split">${iconButton('preview-open','用默认程序打开','open')}<button id="preview-open-menu" class="icon-button quiet" title="打开方式" aria-label="打开方式" aria-expanded="false" aria-haspopup="menu" aria-controls="preview-open-popover">${icon('chevron-down')}</button></div><button id="preview-more" class="icon-button quiet" title="更多" aria-label="更多" aria-expanded="false" aria-haspopup="menu" aria-controls="preview-more-popover">${icon('ellipsis')}</button>${windowControls('preview')}</div>
  </header>
  <div class="preview-layout">
   <aside id="preview-file-panel" class="preview-pane preview-file-panel" aria-label="预览侧边栏"><div class="preview-pane-inner"><div class="preview-pane-heading"><div class="tabs preview-side-tabs" role="tablist" aria-label="预览侧边栏"><button id="side-files" role="tab">文件</button><button id="side-details" role="tab">详情</button><button id="side-outline" role="tab" hidden>目录</button><button id="side-overview" role="tab" hidden>概览</button></div></div><div id="files-browser"><div class="preview-files-location">${iconButton('preview-files-up','上一级目录','up')}<span id="files-path"></span></div><div class="preview-file-filter">${icon('search')}<input id="files-search" aria-label="筛选文件" placeholder="筛选文件"></div><div id="preview-file-list" class="preview-file-list"></div></div><nav id="preview-outline" class="preview-outline" aria-label="文档目录" hidden></nav><div id="preview-overview" class="preview-overview" aria-label="页面概览" hidden></div><div id="preview-information" class="preview-details" aria-label="文件详情" hidden><div class="preview-detail-identity"><div id="detail-cover" class="detail-cover"></div><h3 id="detail-name" data-selectable></h3></div><div id="preview-details-list"></div><div class="preview-detail-location"><span>位置</span><p id="preview-path" data-selectable></p></div></div></div></aside>
   <div id="preview-left-splitter" class="preview-splitter" role="separator" tabindex="0" aria-label="侧边栏宽度" aria-orientation="vertical"></div>
   <main class="preview-content"><div id="document-toolbar" class="document-toolbar" hidden><div class="tabs preview-view-tabs" role="tablist" aria-label="内容显示"><button id="toggle-source" role="tab">源码</button><button id="toggle-render" role="tab">预览</button></div><div class="spacer"></div>${iconButton('format-document','格式化','braces')}${iconButton('toggle-wrap','自动换行','wrap')}${iconButton('copy-document','复制全文','copy')}</div><div id="preview-body" class="preview-body"><div class="preview-loading">${icon('file')}<span>正在准备预览…</span></div></div></main>
  </div>
  <footer class="preview-footer"><div class="preview-file-status"><span id="preview-size"></span><span id="preview-status-kind"></span></div><div class="preview-paging">${iconButton('preview-previous','上一个文件','back')}<span id="preview-position"></span>${iconButton('preview-next','下一个文件','arrow')}</div><div id="preview-zoom" class="preview-zoom" hidden>${iconButton('zoom-out','缩小','minus')}<button id="zoom-reset" title="原始大小">100%</button>${iconButton('zoom-in','放大','plus')}${iconButton('zoom-fit','适应窗口','fit')}</div><span id="preview-shortcut" class="preview-shortcut">Esc 关闭</span></footer><div id="preview-open-popover" class="preview-open-popover" role="menu" hidden></div><div id="preview-more-popover" class="preview-open-popover preview-more-popover" role="menu" aria-label="更多" hidden><button id="copy-preview-path" role="menuitem">${icon("copy")}<span>复制路径</span></button><button id="preview-locks" role="menuitem">${icon("locksmith")}<span>查看占用</span></button></div>
 </div><div class="preview-toast-layer"><div id="toast" class="toast" hidden></div></div>`;
 setupChrome('preview');
 let prefs:PreviewPreferences=defaultPreview(),data:PreviewData|undefined,revision=0,dispose:(()=>void)|undefined,media:HTMLMediaElement|undefined,source=false,formatted=false,returnFolder='',outline:OutlineItem[]=[],overview:OverviewItem[]=[],overviewObserver:IntersectionObserver|undefined,fileDirectory='',fileList:DirectoryList|undefined,fileRevision=0;
 let zoom=1,fit=true,image:HTMLImageElement|undefined;
 const body=q('preview-body'),layout=q('preview-file-panel').parentElement!,filePanel=q('preview-file-panel');
 let currentPage=1;
 const markPage=()=>{for(const card of q('preview-overview').querySelectorAll<HTMLElement>('.preview-overview-card')){const selected=Number(card.dataset.page)+1===currentPage;card.classList.toggle('selected',selected);card.setAttribute('aria-current',selected?'page':'false');}};
 body.addEventListener('preview-page',event=>{currentPage=(event as CustomEvent<{page:number}>).detail.page;markPage();});
 const persist=(value:Partial<PreviewPreferences>)=>{Object.assign(prefs,value);void api.previewPreferences(value).catch(toast);};
 const stateButton=(id:string,state:boolean)=>q(id).setAttribute('aria-pressed',String(state));
 const renderOutline=()=>{const host=q('preview-outline');host.replaceChildren();if(!outline.length){host.innerHTML='<div class="preview-panel-empty">暂无目录</div>';return;}for(const item of outline){const b=document.createElement('button');b.className='preview-outline-item';b.style.setProperty('--outline-depth',String(Math.min(8,Math.max(0,item.depth||0))));b.innerHTML=icon(item.icon||'text')+'<span>'+esc(item.label)+'</span>';b.title=item.label;b.onclick=()=>{host.querySelector('.active')?.classList.remove('active');b.classList.add('active');item.activate();};host.append(b);}};
 const setOutline=(items:OutlineItem[])=>{outline=items;renderOutline();fitPanes();};
 function fitPanes(){const width=layout.clientWidth,left=prefs.files?Math.max(0,Math.min(prefs.leftWidth,width-285)):0;layout.style.setProperty('--preview-left',left+'px');layout.style.setProperty('--left-separator',left?'5px':'0px');filePanel.classList.toggle('is-open',prefs.files);filePanel.inert=!prefs.files;filePanel.setAttribute('aria-hidden',String(!prefs.files));const split=q('preview-left-splitter');split.tabIndex=prefs.files?0:-1;split.setAttribute('aria-valuenow',String(left));split.setAttribute('aria-valuemin','180');split.setAttribute('aria-valuemax','480');stateButton('preview-files',prefs.files);q('side-outline').hidden=!outline.length;q('side-overview').hidden=!overview.length;
  const tab=(prefs.leftTab==='outline'&&!outline.length||prefs.leftTab==='overview'&&!overview.length)?'files':prefs.leftTab;for(const name of ['files','details','outline','overview']){const b=q('side-'+name);b.setAttribute('aria-selected',String(tab===name));b.classList.toggle('selected',tab===name);b.tabIndex=tab===name?0:-1;}q('files-browser').hidden=tab!=='files';q('preview-information').hidden=tab!=='details';q('preview-outline').hidden=tab!=='outline';q('preview-overview').hidden=tab!=='overview';
 }
 const setOverview=(items:OverviewItem[])=>{overview=items;overviewObserver?.disconnect();const host=q('preview-overview');host.replaceChildren();const cache=new Map<HTMLElement,HTMLElement>();let queue=Promise.resolve();overviewObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const card=entry.target as HTMLElement,idx=Number(card.dataset.page);if(cache.has(card)||card.dataset.loading)continue;card.dataset.loading='true';queue=queue.then(async()=>{if(!card.isConnected)return;try{const thumbnail=await items[idx].thumbnail();if(!card.isConnected)return;card.querySelector('.overview-thumbnail')!.replaceChildren(thumbnail);cache.set(card,thumbnail);while(cache.size>40){const first=cache.keys().next().value!;cache.get(first)?.remove();cache.delete(first);delete first.dataset.loading;}}catch{delete card.dataset.loading;}});}}, {root:host,rootMargin:'160px'});for(const [i,item] of items.entries()){const b=document.createElement('button');b.className='preview-overview-card';b.dataset.page=String(i);b.innerHTML='<span class="overview-thumbnail" aria-hidden="true"></span><span class="overview-label">'+esc(item.label)+'</span>';b.onclick=()=>{host.querySelector('.selected')?.classList.remove('selected');b.classList.add('selected');item.activate();};host.append(b);overviewObserver.observe(b);}markPage();fitPanes();};
 const iconObserver=new MutationObserver(refreshFileIcons);iconObserver.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
 const imageObserver=new ResizeObserver(()=>{if(image&&fit)imageZoom();});imageObserver.observe(body);
 const paneObserver=new ResizeObserver(()=>{fitPanes();if(image&&fit)imageZoom();});paneObserver.observe(layout);
 for(const [id,key,sign] of [['preview-left-splitter','leftWidth',1]] as const){const separator=q(id);let start=0,initial=0;separator.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();start=e.clientX;initial=prefs[key];layout.classList.add('resizing');separator.setPointerCapture(e.pointerId);};separator.onpointermove=e=>{if(!separator.hasPointerCapture(e.pointerId))return;prefs[key]=Math.round(Math.max(180,Math.min(480,initial+(e.clientX-start)*sign)));fitPanes();};const end=(e:PointerEvent)=>{if(!separator.hasPointerCapture(e.pointerId))return;separator.releasePointerCapture(e.pointerId);layout.classList.remove('resizing');persist({[key]:prefs[key]});};separator.onpointerup=end;separator.onpointercancel=end;separator.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();persist({[key]:Math.max(180,Math.min(480,prefs[key]+(e.key==='ArrowRight'?12:-12)*sign))});fitPanes();}};}
 function detailRows(title:string,values:Record<string,string>){const section=document.createElement('section');section.className='preview-detail-section';section.innerHTML='<h4>'+esc(title)+'</h4><dl>'+Object.entries(values).map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v)+'</dd></div>').join('')+'</dl>';return section;}
 function details(){if(!data)return;const d=data,cover=q('detail-cover');q('preview-information').classList.toggle('has-visual-cover',!!(d.type==='image'&&d.url||d.cover));cover.className='detail-cover detail-cover-'+d.type;cover.innerHTML=d.type==='image'&&d.url?'<img src="'+esc(d.url)+'" alt="">':d.cover?'<img src="'+esc(d.cover)+'" alt="">':fileIcon(d.name,d.type==='folder');q('detail-name').textContent=d.name;q('preview-path').textContent=d.path;const meta={...d.metadata};delete meta['类型'];const preferred=d.type==='media'?['标题','艺术家','专辑','时长','编码','容器','比特率','采样率','声道','尺寸']:d.type==='image'?['尺寸','设备品牌','设备型号','镜头','拍摄时间','曝光时间','光圈','ISO','色彩空间','方向']:Object.keys(meta);const tailored:Record<string,string>={};for(const key of preferred)if(meta[key]!==undefined){tailored[key]=meta[key];delete meta[key];}const list=q('preview-details-list');list.replaceChildren();if(Object.keys(tailored).length)list.append(detailRows(d.type==='media'?'媒体':d.type==='image'?'图片信息':d.type==='archive'&&/\.apk$/i.test(d.name)?'应用信息':'内容',tailored));const file:Record<string,string>={'格式':d.type==='folder'?'文件夹':d.name.split('.').pop()?.toUpperCase()||'文件','大小':size(d.size),...meta};if(d.modified)file['修改时间']=new Date(d.modified).toLocaleString();if(d.created)file['创建时间']=new Date(d.created).toLocaleString();list.append(detailRows('文件',file));}
 const metadata=(values:Record<string,string>)=>{if(data){data.metadata={...data.metadata,...values};details();}};
 function showFiles(){void fileList?.filter(q<HTMLInputElement>('files-search').value).catch(toast);}
 async function loadFiles(path:string){
  const position=data?.navigation?.path===path?data.navigation.position:-1;
  if(path===fileDirectory&&fileList&&(!data?.navigation||data.navigation.path!==path||data.navigation.id===fileList.id)){fileList.setCurrent(data?.path||'',position);return;}
  const version=++fileRevision;if(fileDirectory&&path!==fileDirectory)q<HTMLInputElement>('files-search').value='';fileDirectory=path;q('files-path').textContent=path;q('files-path').title=path;fileList?.dispose();fileList=undefined;const host=q('preview-file-list');host.innerHTML='<div class="preview-panel-empty">正在读取…</div>';
  try{const info=await api.directoryOpen(path);if(version!==fileRevision){void api.directoryRelease(info.id).catch(()=>{});return;}fileList=new DirectoryList(host,info,path=>void select(path).catch(toast),path=>void loadFiles(path).catch(toast),toast);fileList.setCurrent(data?.path||'',position);await fileList.filter(q<HTMLInputElement>('files-search').value);}catch(error){if(version===fileRevision)host.innerHTML='<div class="preview-panel-empty">'+esc((error as Error).message)+'</div>';throw error;}
 }
 async function select(path:string){if(data?.type==='folder')returnFolder=data.path;loading();try{await api.selectPreview(path);}catch(error){scheduleRefresh();throw error;}}
 function stop(){dispose?.();dispose=undefined;media?.pause();media=undefined;image=undefined;}
 function loading(){stop();overviewObserver?.disconnect();revision++;body.className='preview-body';body.innerHTML='<div class="preview-loading">'+icon('file')+'<span>正在读取…</span></div>';q('document-toolbar').hidden=true;closeOpenMenu();closeMoreMenu();}
 function imageZoom(){if(!image)return;if(fit)zoom=Math.min(1,Math.max(.01,Math.min((body.clientWidth-40)/image.naturalWidth,(body.clientHeight-40)/image.naturalHeight)));image.style.width=Math.max(1,image.naturalWidth*zoom)+'px';image.style.height=Math.max(1,image.naturalHeight*zoom)+'px';q('zoom-reset').textContent=Math.round(zoom*100)+'%';body.classList.toggle('zoomed',!fit);}
 let pan:{x:number;y:number;left:number;top:number}|undefined;body.addEventListener('pointerdown',e=>{if(!image||fit||e.button!==0)return;pan={x:e.clientX,y:e.clientY,left:body.scrollLeft,top:body.scrollTop};body.setPointerCapture(e.pointerId);e.preventDefault();});body.addEventListener('pointermove',e=>{if(pan){body.scrollLeft=pan.left-e.clientX+pan.x;body.scrollTop=pan.top-e.clientY+pan.y;}});body.addEventListener('pointerup',()=>pan=undefined);body.addEventListener('pointercancel',()=>pan=undefined);body.addEventListener('wheel',e=>{if(image&&e.ctrlKey){e.preventDefault();fit=false;zoom=Math.min(16,Math.max(.05,zoom*(e.deltaY<0?1.1:.9)));imageZoom();}},{passive:false});
 async function paint(){if(!data)return;stop();closeControls();closeOpenMenu();closeMoreMenu();const generation=++revision,d=data;currentPage=1;outline=[];overview=[];renderOutline();setOverview([]);fitPanes();body.replaceChildren();body.className='preview-body type-'+d.type;document.body.classList.toggle('preview-immersive',['media','image'].includes(d.type));document.body.classList.toggle('preview-audio',d.type==='media'&&!/\.(mp4|m4v|mov|webm|mkv)$/i.test(d.name));refreshFileIcons();q('document-toolbar').hidden=!(d.text!==undefined||d.textURL);const renderable=['markdown','html','json','yaml','csv','notebook'].includes(d.type);q('toggle-render').hidden=!renderable;q<HTMLButtonElement>('toggle-render').disabled=!!d.textURL&&d.size>5*1024*1024;q('toggle-source').hidden=!renderable;q('toggle-wrap').hidden=!(source||d.type==='text');stateButton('toggle-source',source);stateButton('toggle-render',!source);for(const [id,active] of [['toggle-source',source],['toggle-render',!source]] as const){q(id).classList.toggle('selected',active);q(id).setAttribute('aria-selected',String(active));}stateButton('toggle-wrap',prefs.wrap);q('format-document').hidden=!source||!['json','yaml'].includes(d.type);q<HTMLButtonElement>('format-document').disabled=d.size>5*1024*1024;stateButton('format-document',formatted);q('preview-zoom').hidden=d.type!=='image';const meta=(v:Record<string,string>)=>{if(generation===revision)metadata(v);};const toc=(items:OutlineItem[])=>{if(generation===revision)setOutline(items);};const pages=(items:OverviewItem[])=>{if(generation===revision)setOverview(items);};
  try{let cleanup:(()=>void)|undefined;
   if(d.type==='workbook'||d.type==='epub'||d.type==='font'||d.type==='notebook'&&!source){const special=await import('./special-preview');if(generation!==revision)return;if(d.type==='workbook')cleanup=special.renderWorkbook(body,d.workbook!,toc);else if(d.type==='epub')cleanup=await special.renderEpub(body,d.url!,meta,toc);else if(d.type==='font')cleanup=await special.renderFont(body,d.url!,meta);else cleanup=await special.renderNotebook(body,d.text??(d.textURL?await previewText(d.textURL):''));}
   else if(d.text!==undefined||d.textURL)cleanup=await renderDocument(body,d,source,prefs.wrap,toc,meta,formatted);
   else if(d.type==='folder'&&d.directory)cleanup=renderDirectoryTree(body,d.directory,path=>void select(path).catch(toast));
   else if(d.type==='archive')body.append(archiveTree(d.entries||[]));
   else if(d.type==='image'){const stage=document.createElement('div');stage.className='image-stage';image=document.createElement('img');image.alt=d.name;image.draggable=false;image.src=d.url!;stage.append(image);body.append(stage);fit=true;zoom=1;image.onload=()=>{if(generation!==revision)return;meta({'尺寸':image!.naturalWidth+' × '+image!.naturalHeight});imageZoom();};}
   else if(d.type==='pdf')cleanup=await renderPDF(body,d.url!,meta,toc,pages);
   else if(d.type==='docx')cleanup=await renderDocx(body,d.url!,meta,toc,pages);
   else if(d.type==='pptx')cleanup=await renderPptx(body,d.url!,meta,toc,pages);
   else if(d.type==='media'){const player=renderMedia(body,d,meta);media=player.media;cleanup=player.dispose;}
   else body.innerHTML='<div class="preview-unsupported">'+fileIcon(d.name)+'<h2>'+(d.error?'无法预览':'暂不支持此格式')+'</h2>'+(d.error?'<p class="preview-error-detail">'+esc(d.error)+'</p>':'')+'<button id="fallback-open">'+icon('open')+'用默认程序打开</button></div>';
   if(generation!==revision){cleanup?.();return;}dispose=cleanup;const fallback=document.getElementById('fallback-open');if(fallback)fallback.onclick=()=>void api.openFile(d.path).catch(toast);
  }catch(error){if(generation===revision){body.innerHTML='<p class="render-error">'+esc((error as Error).message)+'</p>';toast(error);}}
 }
 let refreshQueue=Promise.resolve();function scheduleRefresh(){refreshQueue=refreshQueue.catch(()=>{}).then(refresh).catch(toast);}
 async function refresh(){let next:PreviewData;try{next=await api.previewData();}catch{return;}data=next;formatted=false;q('preview-return-wrap').hidden=!returnFolder||data.path===returnFolder;source=['json','yaml','text'].includes(data.type)||!!data.textURL&&(data.type==='notebook'||data.size>5*1024*1024);document.title=data.name+' — One';q('preview-name').textContent=data.name;q('preview-name').title=data.path;q('preview-title-icon').innerHTML=fileIcon(data.name,data.type==='folder');q('preview-size').textContent=data.type==='folder'?(data.directory?.count||0)+' 项':size(data.size);q('preview-status-kind').textContent=typeName[data.type]||data.type.toUpperCase();const index=data.navigation?.position??-1,count=data.navigation?.count??0;q('preview-position').textContent=index>=0?(index+1)+' / '+count:'';q<HTMLButtonElement>('preview-previous').disabled=index<=0;q<HTMLButtonElement>('preview-next').disabled=index<0||index>=count-1;details();if(prefs.files){const directory=fileDirectory===parent(data.path)||fileDirectory===data.path?fileDirectory:parent(data.path);void loadFiles(directory||parent(data.path)).catch(toast);}await paint();}
 function closeOpenMenu(){q('preview-open-popover').hidden=true;q('preview-open-menu').setAttribute('aria-expanded','false');releaseControl(closeOpenMenu);}
 async function openMenu(){const host=q('preview-open-popover');if(!host.hidden){closeOpenMenu();return;}closeControls();closeMoreMenu();openControl(closeOpenMenu);host.hidden=false;q('preview-open-menu').setAttribute('aria-expanded','true');host.innerHTML='<div class="preview-menu-label">打开方式</div><div class="preview-panel-empty">读取应用…</div>';const current=data?.path,apps=await api.previewOpenWith().catch(()=>[]);if(host.hidden||current!==data?.path)return;host.innerHTML='<div class="preview-menu-label">打开方式</div>';for(const app of apps){const b=document.createElement('button');b.setAttribute('role','menuitem');b.innerHTML=(app.icon?.startsWith('data:image/png;base64,')?'<img class="open-with-icon" src="'+esc(app.icon)+'" alt="">':icon('window'))+'<span>'+esc(app.name)+'</span>';b.onclick=()=>{closeOpenMenu();void api.previewOpenIn(app.id).catch(toast);};host.append(b);}const b=document.createElement('button');b.className='preview-menu-more';b.setAttribute('role','menuitem');b.innerHTML=icon('ellipsis')+'<span>选择其他应用</span>';b.onclick=()=>{closeOpenMenu();void api.previewOpenIn(':choose').catch(toast);};host.append(b);host.querySelector<HTMLButtonElement>('button')?.focus();}
 function closeMoreMenu(){q('preview-more-popover').hidden=true;q('preview-more').setAttribute('aria-expanded','false');releaseControl(closeMoreMenu);}
 function positionMoreMenu(){const rect=q('preview-more').getBoundingClientRect(),host=q('preview-more-popover');host.style.left=Math.max(8,Math.min(rect.right-host.offsetWidth,window.innerWidth-host.offsetWidth-8))+'px';host.style.right='auto';host.style.top=rect.bottom+8+'px';}
 action('preview-more',()=>{const host=q('preview-more-popover');if(!host.hidden){closeMoreMenu();return;}closeControls();closeOpenMenu();openControl(closeMoreMenu);host.hidden=false;q('preview-more').setAttribute('aria-expanded','true');positionMoreMenu();host.querySelector<HTMLButtonElement>('button')?.focus();});
 document.addEventListener('pointerdown',e=>{if(!(e.target as Element).closest('#preview-more,#preview-more-popover'))closeMoreMenu();});window.addEventListener('resize',closeMoreMenu);
 q('preview-more-popover').onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeMoreMenu();q('preview-more').focus();}else if(e.key==='Tab')closeMoreMenu();else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const buttons=Array.from(q('preview-more-popover').querySelectorAll<HTMLButtonElement>('button')),i=buttons.indexOf(document.activeElement as HTMLButtonElement),next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus();}};
 action('preview-open-menu',openMenu);document.addEventListener('pointerdown',e=>{if(!(e.target as Element).closest('.preview-open-split,.preview-open-popover'))closeOpenMenu();});q('preview-open-popover').onkeydown=e=>{const menu=q('preview-open-popover');if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeOpenMenu();q('preview-open-menu').focus();}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const buttons=Array.from(menu.querySelectorAll<HTMLButtonElement>('button')),i=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}};
 action('preview-files',async()=>{persist({files:!prefs.files});fitPanes();if(prefs.files&&data&&!fileDirectory)await loadFiles(parent(data.path));});for(const tab of ['files','details','outline','overview'] as const)action('side-'+tab,()=>{persist({leftTab:tab});fitPanes();});q('preview-file-panel').querySelector('[role=tablist]')!.addEventListener('keydown',event=>{const e=event as KeyboardEvent;if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const buttons=Array.from(filePanel.querySelectorAll<HTMLButtonElement>('[role=tab]')).filter(b=>!b.hidden),index=buttons.indexOf(document.activeElement as HTMLButtonElement),next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next]?.click();buttons[next]?.focus();});q('files-search').oninput=showFiles;action('preview-files-up',()=>loadFiles(parent(fileDirectory)));
 action('preview-return',()=>returnFolder&&select(returnFolder));action('preview-open',()=>data&&api.openFile(data.path));action('preview-reveal',()=>data&&api.revealFile(data.path));action('preview-locks',()=>{closeMoreMenu();return data&&api.inspectLocks(data.path);});action('copy-preview-path',async()=>{closeMoreMenu();if(data){await api.copyText(data.path);toast('已复制路径');}});
 action('preview-pin',async()=>{const state=await api.previewFlags({pinned:!prefs.pinned});Object.assign(prefs,state);stateButton('preview-pin',state.pinned);});action('preview-hold',async()=>{const state=await api.previewFlags({held:!prefs.held});Object.assign(prefs,state);stateButton('preview-hold',state.held);});
 action('toggle-source',async()=>{if(!source){source=true;await paint();}});action('toggle-render',async()=>{if(source){source=false;await paint();}});action('format-document',async()=>{formatted=!formatted;await paint();});action('toggle-wrap',async()=>{persist({wrap:!prefs.wrap});await paint();});action('copy-document',async()=>{if(!data)return;const text=codeText(body)??data.text??(data.textURL?await previewText(data.textURL):'');await api.copyText(text||'');toast('已复制');});for(const [id,step] of [['preview-previous',-1],['preview-next',1]] as const)action(id,()=>api.navigatePreview(step));
 action('zoom-fit',()=>{fit=true;imageZoom();});action('zoom-reset',()=>{fit=false;zoom=1;imageZoom();});action('zoom-in',()=>{fit=false;zoom=Math.min(16,zoom*1.2);imageZoom();});action('zoom-out',()=>{fit=false;zoom=Math.max(.05,zoom/1.2);imageZoom();});
 document.addEventListener('keydown',e=>{if(e.defaultPrevented||document.querySelector('dialog[open]'))return;const target=e.target as Element;if(e.key==='Escape'){e.preventDefault();if(!q('preview-more-popover').hidden){closeMoreMenu();q('preview-more').focus();}else if(!q('preview-open-popover').hidden){closeOpenMenu();q('preview-open-menu').focus();}else void api.closeWindow();return;}if(target.closest('input,textarea,[contenteditable=true],.cm-editor'))return;if(e.key===' '&&!target.closest('button')){e.preventDefault();if(media){if(media.paused)void media.play().catch(toast);else media.pause();}else void api.closeWindow();}else if((e.key==='ArrowLeft'||e.key==='ArrowRight')&&!target.closest('button,[role=separator]')){e.preventDefault();void api.navigatePreview(e.key==='ArrowLeft'?-1:1).catch(toast);}});
 api.onPreviewLoading(loading);api.onPreviewChanged(scheduleRefresh);api.onPreviewClosing(stop);window.addEventListener('pagehide',()=>{stop();fileRevision++;fileList?.dispose();fileList=undefined;});window.addEventListener('beforeunload',()=>{stop();overviewObserver?.disconnect();paneObserver.disconnect();imageObserver.disconnect();iconObserver.disconnect();});prefs=await api.previewPreferences();const flags=await api.previewFlags();Object.assign(prefs,flags);stateButton('preview-pin',prefs.pinned);stateButton('preview-hold',prefs.held);fitPanes();scheduleRefresh();
}
