import {menuEditorCard,setupMenuEditor} from './menu-editor';
import {api,q,icon,iconButton,button,esc,switchControl,toast,action} from './ui';
import {bindPreference} from './preferences';
import {setupShortcut} from './shortcut';
import {hydrateFileIcons} from './shell-icons';
import {isWindowVisible,onWindowVisibility} from './window-visibility';
import type {SearchSettings,SearchEntry,SearchContext,SearchState} from '../shared/search';
const searchSwitch=(key:string,title:string,description='')=>`<div class="setting-row"><div class="setting-copy"><h2>${title}</h2>${description?`<p>${description}</p>`:''}</div>${switchControl('search-'+key,title)}</div>`;
export function searchPage(){return `<div class="search-settings"><div class="toolbar search-page-toolbar"><div class="tabs" role="tablist" aria-label="文件搜索设置">${[['entry','搜索'],['index','索引'],['menu','快捷菜单']].map(([id,label])=>`<button id="search-tab-${id}" data-search-tab="${id}" role="tab" aria-selected="${id==='entry'}" class="${id==='entry'?'selected':''}">${label}</button>`).join('')}</div>${button('search-launch','打开搜索','search',true)}</div><div data-search-panel="entry"><div class="search-settings-grid"><div><h2 class="section-label">快捷入口</h2><div class="settings-card"><div class="setting-row"><div class="setting-copy"><h2>搜索窗口</h2></div><input id="search-shortcut" aria-label="文件搜索快捷键"></div>${searchSwitch('doubleCtrl','双按 Ctrl')}${searchSwitch('explorerTyping','直接输入搜索','资源管理器文件列表')}${searchSwitch('explorerMenu','双击空白处菜单','资源管理器文件列表')}${searchSwitch('dialogSwitch','文件对话框跳转','Ctrl+G')}</div></div><div><h2 class="section-label">匹配方式</h2><div class="settings-card">${searchSwitch('fuzzy','模糊搜索')}${searchSwitch('pinyin','拼音与首字母')}</div><h2 class="section-label">收藏文件夹</h2><div class="settings-card"><div class="section-heading"><span></span>${button('search-bookmark','添加','plus')}</div><div id="search-bookmarks" class="search-paths"></div></div></div></div><p class="utility-message" id="search-bridge-error" role="alert"></p></div><div data-search-panel="index" hidden><div class="settings-card index-limit"><div class="preference-row"><label for="index-limit">索引项上限</label><input type="number" id="index-limit" min="1000" max="10000000" step="1000" aria-label="索引项上限"></div></div><div class="index-status-bar"><span id="index-summary" role="status"></span><span id="index-detail"></span><div class="spacer"></div>${button('index-cancel','停止')}${button('index-refresh','重新扫描','refresh')}</div><div class="search-settings-grid"><div class="settings-card"><div class="section-heading"><h2>索引目录</h2>${button('index-add','添加','plus')}</div><div id="index-roots" class="search-paths"></div></div><div class="settings-card"><div class="section-heading"><h2>排除目录</h2>${button('index-exclude','添加','plus')}</div><div id="index-excluded" class="search-paths"></div></div></div></div><div data-search-panel="menu" hidden>${menuEditorCard()}</div></div>`;}
export function setupSearchPage(){let config:SearchSettings;setupShortcut(q<HTMLInputElement>('search-shortcut'));
 const tab=(id:string)=>{document.querySelectorAll<HTMLElement>('[data-search-panel]').forEach(p=>p.hidden=p.dataset.searchPanel!==id);document.querySelectorAll<HTMLElement>('[data-search-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.searchTab===id);b.setAttribute('aria-selected',String(b.dataset.searchTab===id));});};
 document.querySelectorAll<HTMLButtonElement>('[data-search-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.searchTab!));
 const update=async(patch:Partial<SearchSettings>)=>{const result=await api.patchSettings({search:patch});config=result.search;return result;};
 const drawPaths=(id:string,key:'roots'|'excluded'|'bookmarks')=>{q(id).innerHTML=config[key].length?config[key].map((p,i)=>`<div><span title="${esc(p)}">${icon('folder')}<span>${esc(p)}</span></span><button class="icon-button quiet" data-remove="${i}" aria-label="移除 ${esc(p)}">${icon('close')}</button></div>`).join(''):'<p class="path-empty">未添加</p>';q(id).querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.onclick=()=>{const path=config[key][Number(b.dataset.remove)];void update({[key]:config[key].filter(p=>p!==path)}).then(()=>drawPaths(id,key)).catch(toast);});};
 const draw=()=>{drawPaths('index-roots','roots');drawPaths('index-excluded','excluded');drawPaths('search-bookmarks','bookmarks');};
 const render=(s:SearchState&{bridgeError:string})=>{q('index-summary').textContent=`${s.running?'正在索引 · ':''}${s.count.toLocaleString()} 项`;q('index-detail').textContent=s.error||(s.issues?`${s.issues} 项未能读取`:s.running?s.root:s.updated?`更新于 ${new Date(s.updated).toLocaleTimeString()}`:'');q('index-detail').title=s.root;q('search-bridge-error').textContent=s.bridgeError;q<HTMLButtonElement>('index-cancel').hidden=!s.running;};
 const drawMenu=setupMenuEditor(()=>config?.menu||[],async menu=>{await update({menu});});
 const fill=()=>{q<HTMLInputElement>('index-limit').value=String(config.maxEntries);q<HTMLInputElement>('search-shortcut').value=config.shortcut;for(const key of ['doubleCtrl','explorerTyping','explorerMenu','dialogSwitch','fuzzy','pinyin'] as const)q<HTMLInputElement>('search-'+key).checked=config[key];};
 const load=()=>api.settings().then(s=>{config=s.search;draw();drawMenu();fill();});void load().catch(toast);document.querySelector('[data-page=search]')?.addEventListener('click',()=>void load().catch(toast));api.onSearchSettings(()=>void load().catch(toast));
 for(const key of ['shortcut','doubleCtrl','explorerTyping','explorerMenu','dialogSwitch','fuzzy','pinyin'] as const){const control=q<HTMLInputElement>('search-'+key);control.addEventListener('change',()=>void update({[key]:key==='shortcut'?control.value:control.checked}).catch(error=>{fill();toast(error);}));}
 for(const [id,list,key]of [['index-add','index-roots','roots'],['index-exclude','index-excluded','excluded'],['search-bookmark','search-bookmarks','bookmarks']] as const)action(id,async()=>{const path=await api.pickDirectory();if(path&&!config[key].includes(path)){await update({[key]:[...config[key],path]});drawPaths(list,key);}});
 bindPreference(q('index-limit'),()=>({search:{maxEntries:Number(q<HTMLInputElement>('index-limit').value)}}),load);
 action('index-refresh',()=>api.rebuildSearch());action('index-cancel',()=>api.cancelSearchIndex());action('search-launch',()=>api.showSearch());api.onSearchState(render);void api.searchState().then(render).catch(toast);
}
export async function renderSearch(){
 const embedded=new URLSearchParams(location.search).has('embedded');document.body.classList.add('search-window');if(embedded)document.body.classList.add('search-inline');document.querySelector('#app')!.innerHTML=`<div class="search-shell"><header class="search-input-row drag-region">${icon('search')}<input id="file-query" placeholder="搜索文件与文件夹" aria-label="搜索文件与文件夹" autocomplete="off" spellcheck="false">${embedded?'<span id="search-inline-summary" role="status"></span>':''}${iconButton('search-clear','清空','close')}</header><div class="search-filter-row" id="search-filters">${[['','全部'],...(!embedded?[['app:','程序'],['setting:','设置']]:[]),['folder:','文件夹'],['doc:','文档'],['pic:','图片'],['video:','视频'],['audio:','音频']].map(([filter,label])=>`<button data-filter="${filter}" class="quiet">${label}</button>`).join('')}</div><div id="search-results" class="search-results" role="listbox" aria-label="搜索结果"></div><footer class="search-footer"><span id="search-summary" role="status"></span><span id="search-keys">↑↓ 选择 · Enter 打开 · Alt+P 预览</span></footer></div><div id="toast" class="toast" role="status" hidden></div>`;
 const input=q<HTMLInputElement>('file-query');let context:SearchContext={kind:'search',hwnd:0,pid:0,created:'',folders:[]},prefs:SearchSettings,items:SearchEntry[]=[],selected=0,revision=0,timer:ReturnType<typeof setTimeout>,filter='';
 const nameMarkup=(item:SearchEntry)=>{const terms=(input.value.match(/"[^"]*"|\S+/g)||[]).map(t=>t.replace(/^"|"$/g,'')).filter(t=>!t.includes(':'));const lower=item.name.toLowerCase();const matched=new Set<number>();for(const term of terms){const value=term.toLowerCase(),at=lower.indexOf(value);if(at>=0){for(let i=at;i<at+value.length;i++)matched.add(i);}else if(item.matchKind==='fuzzy'){let cursor=0;for(const char of value){const at=lower.indexOf(char,cursor);if(at<0)break;matched.add(at);cursor=at+1;}}}let offset=0;return Array.from(item.name).map(c=>{const active=matched.has(offset);offset+=c.length;return active?`<mark>${esc(c)}</mark>`:esc(c);}).join('');};
 const select=()=>{q('search-results').querySelectorAll<HTMLElement>('[data-result]').forEach((el,i)=>{el.classList.toggle('selected',i===selected);el.setAttribute('aria-selected',String(i===selected));});};
 const layout=()=>{const active=!!input.value.trim()||!!filter;document.body.classList.toggle('search-idle',!embedded&&!active);document.body.classList.toggle('search-has-results',embedded&&(items.length>0||active));void api.searchSize(items.length,active);};
 const render=()=>{layout();q('search-results').innerHTML=items.map((item,i)=>`<div class="search-result ${i===selected?'selected':''}" role="option" aria-selected="${i===selected}" data-result="${i}"><span class="result-icon" data-file-icon="${esc(item.path)}">${icon(item.launchKind==='setting'?'settings':item.launchKind==='app'?'window':item.directory?'folder':'file')}</span><div class="result-name" title="${esc(item.subtitle||item.path)}"><strong>${nameMarkup(item)}</strong><span>${esc(item.subtitle||item.path)}</span></div>${embedded&&i<9?`<kbd class="result-shortcut">Ctrl+${i+1}</kbd>`:''}${!item.launchKind?`<div class="search-row-actions"><button class="icon-button quiet" data-preview="${i}" aria-label="预览 ${esc(item.name)}" title="预览">${icon('preview')}</button><button class="icon-button quiet" data-reveal="${i}" aria-label="定位 ${esc(item.name)}" title="在资源管理器中显示">${icon('folder')}</button></div>`:''}</div>`).join('')||'<div class="search-empty">'+icon('search')+'<span>'+(input.value.trim()?'没有匹配的项目':'输入名称开始搜索')+'</span></div>';hydrateFileIcons(q('search-results'));q('search-results').querySelectorAll<HTMLElement>('[data-result]').forEach(e=>{e.onclick=()=>{selected=Number(e.dataset.result);select();};e.ondblclick=()=>void choose(Number(e.dataset.result));e.oncontextmenu=event=>{event.preventDefault();selected=Number(e.dataset.result);select();void api.searchContextMenu(items[selected].path,{x:event.clientX,y:event.clientY},items[selected].directory).catch(toast);};});q('search-results').querySelectorAll<HTMLButtonElement>('[data-preview]').forEach(b=>b.onclick=e=>{e.stopPropagation();void api.preview(items[Number(b.dataset.preview)].path).catch(toast);});q('search-results').querySelectorAll<HTMLButtonElement>('[data-reveal]').forEach(b=>b.onclick=e=>{e.stopPropagation();void api.revealFile(items[Number(b.dataset.reveal)].path).catch(toast);});};
 const choose=async(index=selected)=>{if(!items[index])return;try{await api.searchChoose(items[index].path);}catch(e){toast(e);}};
 const summary=(text:string,inline=items.length?`${items.length.toLocaleString()} 项`:'')=>{q('search-summary').textContent=text;if(embedded)q('search-inline-summary').textContent=inline;};
 const query=async()=>{if(!isWindowVisible())return;const version=++revision;const text=input.value.trim();layout();if(!embedded&&!text&&!filter){items=[];selected=0;render();return;}if(!text&&!filter){const seen=new Set<string>();items=[...(prefs?.bookmarks||[]),...context.folders.map(f=>f.path)].filter(p=>{const k=p.toLowerCase();if(seen.has(k))return false;seen.add(k);return true;}).map(path=>({path,name:path.split(/[\\/]/).filter(Boolean).pop()||path,directory:true,size:0,modified:0}));selected=0;render();const s=await api.searchState();if(version!==revision)return;summary(items.length?'收藏与已打开的文件夹':s.count?'输入名称开始搜索':'请先在 One 中添加索引目录');return;}
  q('search-results').setAttribute('aria-busy','true');if(embedded)q('search-inline-summary').textContent='搜索中';try{const result=await api.searchFiles(filter+' '+text,context.kind==='dialog');if(version!==revision)return;if(result.cancelled){q('search-results').setAttribute('aria-busy','false');return;}items=result.items;selected=0;render();q('search-results').setAttribute('aria-busy','false');summary(`${result.total.toLocaleString()} 项${result.total>100?' · 显示前 100 项':''} · ${Math.round(result.elapsed)} ms`,result.total?`${result.total.toLocaleString()} 项`:'无结果');}catch(e){if(version===revision){q('search-results').setAttribute('aria-busy','false');if(embedded)q('search-inline-summary').textContent='';toast(e);}}};
 input.addEventListener('input',e=>{revision++;layout();clearTimeout(timer);if((e as InputEvent).isComposing)return;timer=setTimeout(()=>void query(),75);});input.addEventListener('compositionstart',()=>clearTimeout(timer));input.addEventListener('compositionend',()=>void query());
 document.addEventListener('keydown',e=>{if(e.isComposing)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();selected=Math.max(0,Math.min(items.length-1,selected+(e.key==='ArrowDown'?1:-1)));select();q('search-results').querySelector('.selected')?.scrollIntoView({block:'nearest'});}else if(e.ctrlKey&&/^[1-9]$/.test(e.key)&&embedded){e.preventDefault();void choose(Number(e.key)-1);}else if(e.key==='Enter'){e.preventDefault();if(document.body.classList.contains('search-idle'))return;if(e.ctrlKey&&items[selected]&&!items[selected].launchKind)void api.revealFile(items[selected].path).catch(toast);else void choose();}else if(e.key==='Escape'){e.preventDefault();void api.closeWindow();}else if(e.altKey&&e.key.toLowerCase()==='p'&&items[selected]&&!items[selected].launchKind){e.preventDefault();void api.preview(items[selected].path).catch(toast);}});
 q('search-clear').onclick=()=>{if(!input.value){void api.closeWindow();return;}input.value='';input.focus();void query();};document.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter!;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));input.focus();void query();});
 const applyContext=(c:SearchContext)=>{context=c;document.title=(c.kind==='dialog'?'跳转文件夹':c.kind==='menu'?'文件夹菜单':'文件搜索')+' · One';q('search-keys').textContent=c.kind==='search'?'↑↓ 选择 · Enter 打开 · Alt+P 预览':'↑↓ 选择 · Enter 跳转 · Alt+P 预览';q('search-filters').hidden=c.kind==='dialog';input.placeholder=c.kind==='dialog'?'搜索要跳转的文件夹':embedded?'搜索文件与文件夹':'搜索文件、程序与设置';void query();};
 onWindowVisibility(visible=>{clearTimeout(timer);if(visible)void query();else revision++;});
 api.onSearchFilesChanged(()=>void query());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')clearTimeout(timer);});api.onSearchState(()=>{if(isWindowVisible()&&(input.value.trim()||filter)){clearTimeout(timer);timer=setTimeout(()=>void query(),160);}});api.onSearchContext(applyContext);api.onSearchReset(()=>{revision++;input.value='';filter='';input.focus();void api.searchPreferences().then(p=>{prefs=p;void query();});void api.searchReady();});input.focus();void api.searchReady();prefs=await api.searchPreferences();if(context.hwnd===0)applyContext(await api.searchContext());else void query();
}

