import {appearancePage,setupAppearancePage} from './appearance';
import {api,q,icon,button,switchControl,toast} from './ui';
import {bindPreference} from './preferences';
import {closeControls} from './controls';
import appIconURL from '../../assets/icons/one-small.svg?url';
export function settingsPage(){return `<div class="settings-layout"><nav class="settings-nav" aria-label="设置分类">${[['general','基本设置','system'],['appearance','外观','appearance'],['about','关于','info']].map(([id,title,glyph])=>`<button class="quiet ${id==='general'?'active':''}" data-settings-tab="${id}" ${id==='general'?'aria-current="page"':''}>${icon(glyph)}<span>${title}</span></button>`).join('')}</nav><div class="settings-panels"><section data-settings-panel="general"><h2 class="settings-title">基本设置</h2><div class="settings-card"><div class="setting-row"><div class="setting-copy"><h2>登录时启动 One</h2></div>${switchControl('general-launch','登录时启动 One')}</div><div class="setting-row"><div class="setting-copy"><h2>关闭窗口时</h2></div><select id="general-close" aria-label="关闭窗口时"><option value="tray">最小化到托盘</option><option value="quit">退出 One</option></select></div></div><div class="settings-card"><div class="setting-row"><div class="setting-copy"><h2>设置文件夹</h2></div>${button('settings-folder','打开','folder')}</div></div></section><section data-settings-panel="appearance" hidden><h2 class="settings-title">外观</h2>${appearancePage()}</section><section data-settings-panel="about" hidden><h2 class="settings-title">关于</h2><div class="about-brand"><img src="${appIconURL}" alt="" width="56" height="56"><div><strong>One</strong><span id="about-version"></span></div></div><div class="settings-card"><div class="setting-row"><h2>Windows 桌面工具箱</h2><span class="muted">本地运行</span></div></div></section></div></div>`;}
export function showSettingsTab(id:string){closeControls();document.querySelectorAll<HTMLElement>('[data-settings-panel]').forEach(panel=>panel.hidden=panel.dataset.settingsPanel!==id);document.querySelectorAll<HTMLElement>('[data-settings-tab]').forEach(b=>{const selected=b.dataset.settingsTab===id;b.classList.toggle('active',selected);if(selected)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
export function setupSettingsPage(){
  setupAppearancePage();document.querySelectorAll<HTMLButtonElement>('[data-settings-tab]').forEach(b=>b.onclick=()=>showSettingsTab(b.dataset.settingsTab!));
  const fill=async()=>{const s=await api.settings();q<HTMLInputElement>('general-launch').checked=s.general.launchAtLogin;q<HTMLSelectElement>('general-close').value=s.general.closeToTray?'tray':'quit';};void fill().catch(toast);
  bindPreference(q('general-launch'),()=>({general:{launchAtLogin:q<HTMLInputElement>('general-launch').checked}}),fill);
  bindPreference(q('general-close'),()=>({general:{closeToTray:q<HTMLSelectElement>('general-close').value==='tray'}}),fill);
  void api.appInfo().then(info=>{q('about-version').textContent=info.version;q('settings-folder').onclick=()=>void api.openFile(info.dataPath).catch(toast);q<HTMLInputElement>('general-launch').disabled=!info.packaged;q('general-launch').title=info.packaged?'':'打包后可用';}).catch(toast);
}
