import JSZip from 'jszip';
import DOMPurify from 'dompurify';
import {marked} from 'marked';
import {columnName,type WorkbookData} from '../shared/workbook';
import {iconButton,esc,api,toast} from './ui';
import {customControls,closeControls} from './controls';
import {isolatedFrame} from './document-frame';
import type {SetOutline} from './preview-outline';
const safeHTML=(html:string)=>DOMPurify.sanitize(html,{FORBID_TAGS:['script','iframe','object','embed','form','input','button','textarea','select','base','meta','link'],FORBID_ATTR:['srcset','action','formaction']});
const all=(node:Document|Element,name:string)=>Array.from(node.getElementsByTagNameNS('*',name));
function xml(text:string){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('文档包含不支持的 XML 声明');const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror'))throw new Error('文档 XML 无法读取');return doc;}
export function renderWorkbook(host:HTMLElement,data:WorkbookData,outline:SetOutline=()=>{}){
 const root=document.createElement('div');root.className='special-reader';host.append(root);let index=0,page=0,filter='';
 root.innerHTML=`<div class="reader-toolbar"><select id="sheet-select" aria-label="工作表">${data.sheets.map((s,i)=>`<option value="${i}">${esc(s.name)}</option>`).join('')}</select><input id="sheet-filter" placeholder="筛选行" aria-label="筛选行"><div class="spacer"></div>${iconButton('sheet-copy','复制当前页','copy')}</div><div class="sheet-formula" id="sheet-formula">选择单元格查看内容与公式</div><div class="sheet-scroll"><table class="sheet-table"></table></div><div class="reader-toolbar"><span id="sheet-count"></span><div class="spacer"></div>${iconButton('sheet-prev','上一页','back')}<span id="sheet-page"></span>${iconButton('sheet-next','下一页','arrow')}</div>`;
 const q=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;customControls(root);
 const rows=()=>data.sheets[index]?.rows.filter(row=>!filter||row.cells.some(cell=>cell.value.toLocaleLowerCase().includes(filter)))||[];
 const draw=()=>{const sheet=data.sheets[index],list=rows(),pages=Math.max(1,Math.ceil(list.length/100));page=Math.min(page,pages-1);q('#sheet-count').textContent=sheet?`${list.length.toLocaleString()} 行 · ${sheet.columns} 列${sheet.truncated?' · 已截取，最多 20,000 行 / 200 列 / 100,000 单元格':''}`:'空工作簿';q('#sheet-page').textContent=`${page+1} / ${pages}`;q<HTMLButtonElement>('#sheet-prev').disabled=page===0;q<HTMLButtonElement>('#sheet-next').disabled=page>=pages-1;const table=q('table');table.replaceChildren();if(!sheet)return;const head=document.createElement('thead');head.innerHTML='<tr><th></th>'+Array.from({length:sheet.columns},(_,i)=>`<th>${columnName(i)}</th>`).join('')+'</tr>';table.append(head);const body=document.createElement('tbody');for(const row of list.slice(page*100,page*100+100)){const tr=document.createElement('tr'),number=document.createElement('th');number.textContent=String(row.number);tr.append(number);const cells=new Map(row.cells.map(c=>[c.column,c]));for(let col=0;col<sheet.columns;col++){const cell=cells.get(col),td=document.createElement('td');td.textContent=cell?.value||'';td.title=cell?.formula?'='+cell.formula:cell?.value||'';td.tabIndex=0;td.onclick=()=>{table.querySelector('.active-cell')?.classList.remove('active-cell');td.classList.add('active-cell');q('#sheet-formula').textContent=`${columnName(col)}${row.number}  ${cell?.formula?'='+cell.formula:cell?.value||''}`;};td.onkeydown=e=>{if(e.key==='Enter')td.click();if(e.ctrlKey&&e.key.toLowerCase()==='c'){e.preventDefault();void api.copyText(cell?.value||'').catch(toast);}};tr.append(td);}body.append(tr);}table.append(body);q('.sheet-scroll').scrollTop=0;};
 q('#sheet-select').onchange=()=>{index=Number((q('#sheet-select') as HTMLSelectElement).value);q('#sheet-formula').textContent='选择单元格查看内容与公式';page=0;draw();};let timer:ReturnType<typeof setTimeout>;q<HTMLInputElement>('#sheet-filter').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>{filter=(e.target as HTMLInputElement).value.toLocaleLowerCase();page=0;draw();},180);};q('#sheet-prev').onclick=()=>{page--;draw();};q('#sheet-next').onclick=()=>{page++;draw();};q('#sheet-copy').onclick=()=>{const text=rows().slice(page*100,page*100+100).map(row=>{const values=Array(data.sheets[index].columns).fill('');for(const cell of row.cells)values[cell.column]=cell.value;return values.map(v=>/[\t\n"]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v).join('\t');}).join('\r\n');void api.copyText(text).then(()=>toast('已复制当前页')).catch(toast);};draw();outline(data.sheets.map((sheet,i)=>({label:sheet.name,icon:'list',activate:()=>{index=i;page=0;q<HTMLSelectElement>('#sheet-select').value=String(i);q('#sheet-select').dispatchEvent(new Event('change'));}})));return()=>{clearTimeout(timer);closeControls();root.remove();};
}
export async function renderFont(host:HTMLElement,url:string,metadata:(v:Record<string,string>)=>void){
 const root=document.createElement('div');root.className='font-reader';host.append(root);const name='OnePreview'+crypto.randomUUID().replace(/-/g,'');const face=new FontFace(name,await fetch(url).then(r=>r.arrayBuffer()));await face.load();document.fonts.add(face);metadata({'字体状态':'已加载，仅用于本次预览'});
 root.innerHTML=`<div class="reader-toolbar font-toolbar"><label for="font-size">字号</label><input id="font-size" type="range" min="12" max="120" value="48" aria-label="预览字号"><output id="font-size-value" for="font-size">48 px</output></div><div class="font-scroll"><textarea id="font-sample" aria-label="字体样张" spellcheck="false" maxlength="10000">天地玄黄，宇宙洪荒。\nThe quick brown fox jumps over the lazy dog.\n0123456789</textarea><div class="font-alphabet" aria-label="字形样张"></div></div>`;
 const sample=root.querySelector<HTMLTextAreaElement>('textarea')!,input=root.querySelector<HTMLInputElement>('input')!,alphabet=root.querySelector<HTMLElement>('.font-alphabet')!;sample.style.fontFamily=alphabet.style.fontFamily=`"${name}"`;
 // Grow the editor with its contents so the document owns the only scrollbar.
 let resizeFrame=0,lastWidth=-1;const fitSample=()=>{sample.style.height='auto';sample.style.height=sample.scrollHeight+'px';};const scheduleFit=()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(fitSample);};sample.oninput=scheduleFit;input.oninput=()=>{sample.style.fontSize=input.value+'px';root.querySelector('#font-size-value')!.textContent=input.value+' px';scheduleFit();};
 const resize=new ResizeObserver(entries=>{const width=entries[0].contentRect.width;if(width!==lastWidth){lastWidth=width;scheduleFit();}});resize.observe(sample);
 for(const ch of 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%&*()[]{}?'){const cell=document.createElement('span');cell.textContent=ch;alphabet.append(cell);}fitSample();return()=>{cancelAnimationFrame(resizeFrame);resize.disconnect();document.fonts.delete(face);root.remove();};
}
export async function renderEpub(host:HTMLElement,url:string,metadata:(v:Record<string,string>)=>void,outline:SetOutline=()=>{}){
 const root=document.createElement('div');root.className='special-reader';host.append(root);let disposed=false,revision=0;const urls:string[]=[];const zip=await JSZip.loadAsync(await fetch(url).then(r=>r.arrayBuffer()));const read=async(path:string)=>{const file=zip.file(path);if(!file)throw new Error('电子书缺少 '+path);return file.async('string');};
 const resolve=(base:string,target:string)=>{if(/^[a-z][\w+.-]*:|^[\\/]/i.test(target))return '';const parts=base.split('/').slice(0,-1);for(const part of decodeURIComponent(target.split('#')[0]).split('/')){if(part==='..'){if(!parts.length)return '';parts.pop();}else if(part&&part!=='.')parts.push(part);}return parts.join('/');};
 const container=xml(await read('META-INF/container.xml')),packagePath=all(container,'rootfile')[0]?.getAttribute('full-path');if(!packagePath)throw new Error('电子书缺少阅读顺序');const pkg=xml(await read(packagePath)),manifest=new Map(all(pkg,'item').map(item=>[item.getAttribute('id'),{path:resolve(packagePath,item.getAttribute('href')||''),type:item.getAttribute('media-type')||''}]));const chapters=all(pkg,'itemref').map(item=>manifest.get(item.getAttribute('idref'))).filter((item):item is {path:string;type:string}=>!!item&&/html/.test(item.type));if(!chapters.length||chapters.length>2000)throw new Error('电子书章节数量超出范围');metadata({'书名':all(pkg,'title')[0]?.textContent||'—','作者':all(pkg,'creator').map(n=>n.textContent).join('、')||'—','语言':all(pkg,'language')[0]?.textContent||'—','章节':String(chapters.length)});
 root.innerHTML=`<div class="reader-toolbar">${iconButton('book-prev','上一章','back')}<select id="book-chapter" aria-label="章节">${chapters.map((c,i)=>`<option value="${i}">${i+1} · ${esc(c.path.split('/').pop())}</option>`).join('')}</select>${iconButton('book-next','下一章','arrow')}<div class="spacer"></div>${iconButton('book-smaller','缩小文字','minus')}<span id="book-size">16</span>${iconButton('book-larger','放大文字','plus')}</div><div class="book-page"></div>`;customControls(root);let index=0,fontSize=16;
 const draw=async()=>{const version=++revision;for(const url of urls.splice(0))URL.revokeObjectURL(url);const chapter=chapters[index],doc=new DOMParser().parseFromString(safeHTML(await read(chapter.path)),'text/html');doc.querySelectorAll('a').forEach(a=>a.removeAttribute('href'));doc.querySelectorAll('style').forEach(s=>s.remove());
  for(const img of Array.from(doc.querySelectorAll('img')).slice(0,100)){const path=resolve(chapter.path,img.getAttribute('src')||''),file=zip.file(path),type=Array.from(manifest.values()).find(item=>item.path===path)?.type;if(file&&/^image\/(png|jpeg|gif|webp|svg\+xml)$/.test(type||'')){const bytes=await file.async('uint8array');if(disposed||version!==revision)return;if(bytes.length<=10*1024*1024){const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type}));urls.push(url);img.src=url;}else img.removeAttribute('src');}else img.removeAttribute('src');}
  if(disposed||version!==revision)return;const page=root.querySelector<HTMLElement>('.book-page')!;page.replaceChildren();const style=getComputedStyle(document.documentElement);isolatedFrame(page,doc.body.innerHTML,`body{font-size:${fontSize}px;line-height:1.9;padding:28px max(24px,calc((100vw - 720px)/2));background:${style.getPropertyValue('--surface')};color:${style.getPropertyValue('--fg')}}p{margin:1em 0}h1,h2,h3{line-height:1.4}img{display:block;max-height:75vh;object-fit:contain;margin:auto}`);(root.querySelector('#book-chapter') as HTMLSelectElement).value=String(index);(root.querySelector('#book-prev') as HTMLButtonElement).disabled=index===0;(root.querySelector('#book-next') as HTMLButtonElement).disabled=index===chapters.length-1;root.querySelector('#book-size')!.textContent=String(fontSize);};
 const redraw=()=>void draw().catch(toast);(root.querySelector('#book-chapter') as HTMLElement).onchange=e=>{index=Number((e.target as HTMLSelectElement).value);redraw();};(root.querySelector('#book-prev') as HTMLElement).onclick=()=>{if(index>0){index--;redraw();}};(root.querySelector('#book-next') as HTMLElement).onclick=()=>{if(index<chapters.length-1){index++;redraw();}};for(const [id,step] of [['book-smaller',-2],['book-larger',2]] as const)(root.querySelector('#'+id) as HTMLElement).onclick=()=>{fontSize=Math.max(12,Math.min(32,fontSize+step));redraw();};await draw();outline(chapters.map((chapter,i)=>({label:(i+1)+' · '+chapter.path.split('/').pop(),activate:()=>{index=i;redraw();}})));return()=>{disposed=true;revision++;for(const url of urls)URL.revokeObjectURL(url);closeControls();root.remove();};
}
export async function renderNotebook(host:HTMLElement,text:string){
 const notebook=JSON.parse(text);if(!Array.isArray(notebook.cells))throw new Error('不是有效的 Notebook');const cells=notebook.cells;if(cells.length>10000)throw new Error('Notebook 超过 10,000 个单元格');const root=document.createElement('div');root.className='special-reader';host.append(root);root.innerHTML=`<div class="reader-toolbar">${iconButton('notebook-prev','上一页','back')}<span id="notebook-page"></span>${iconButton('notebook-next','下一页','arrow')}<div class="spacer"></div><span>${cells.length} 个单元格</span></div><div class="notebook-page"></div>`;let page=0;const string=(value:unknown)=>Array.isArray(value)?value.join(''):String(value??'');
 const draw=async()=>{const content=root.querySelector<HTMLElement>('.notebook-page')!;let html='';for(const [offset,cell] of cells.slice(page*40,page*40+40).entries()){const source=string(cell.source);html+=`<section class="cell"><small>${page*40+offset+1} · ${cell.cell_type==='markdown'?'Markdown':cell.cell_type==='code'?'代码':'文本'}</small>`;html+=cell.cell_type==='markdown'?safeHTML(await marked.parse(source)):`<pre>${esc(source)}</pre>`;for(const out of Array.isArray(cell.outputs)?cell.outputs:[]){const image=string(out.data?.['image/png']),plain=string(out.text??out.data?.['text/plain']);if(image&&image.length<2_000_000&&/^[\w+/=\s]+$/.test(image))html+=`<img src="data:image/png;base64,${image}">`;else if(plain)html+=`<pre class="output">${esc(plain.slice(0,100000))}</pre>`;}html+='</section>';}content.replaceChildren();const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('a').forEach(a=>a.removeAttribute('href'));doc.querySelectorAll('img:not([src^="data:image/png;"])').forEach(img=>img.remove());const style=getComputedStyle(document.documentElement);isolatedFrame(content,doc.body.innerHTML,`body{padding:24px;color:${style.getPropertyValue('--fg')};background:${style.getPropertyValue('--surface')};font-size:13px;line-height:1.7}.cell{margin:0 auto 24px;max-width:900px}small{color:${style.getPropertyValue('--muted')};font-size:10px}pre{background:${style.getPropertyValue('--soft')};padding:16px;border-radius:8px}.output{border-left:2px solid ${style.getPropertyValue('--line')}}img{max-height:600px;object-fit:contain}`);root.querySelector('#notebook-page')!.textContent=`${page+1} / ${Math.max(1,Math.ceil(cells.length/40))}`;(root.querySelector('#notebook-prev') as HTMLButtonElement).disabled=page===0;(root.querySelector('#notebook-next') as HTMLButtonElement).disabled=(page+1)*40>=cells.length;};(root.querySelector('#notebook-prev') as HTMLElement).onclick=()=>{page--;void draw().catch(toast);};(root.querySelector('#notebook-next') as HTMLElement).onclick=()=>{page++;void draw().catch(toast);};await draw();return()=>root.remove();
}
