import {api,q,esc,icon,iconButton,button,action,toast,size} from './ui';
import {informationTabs,type InformationKind,type InformationReport,type InformationGroup} from '../shared/system-info';
import {isWindowVisible,onWindowVisibility} from './window-visibility';
export function systemInformationPage(){return `<div class="information-layout"><nav class="information-nav" role="tablist" aria-label="系统信息类别">${informationTabs.map(([id,name,glyph])=>`<button id="information-tab-${id}" role="tab" aria-selected="${id==='overview'}" data-information-tab="${id}" class="quiet ${id==='overview'?'active':''}">${icon(glyph)}<span>${name}</span><small data-information-count="${id}"></small></button>`).join('')}</nav><div class="information-content"><div class="information-toolbar"><h2 id="information-title">概览</h2><div class="spacer"></div><div class="filter-field">${icon('search')}<input id="information-query" aria-label="筛选系统信息" placeholder="筛选信息">${iconButton('information-clear-query','清除筛选','close')}</div>${iconButton('information-export','导出已读取的信息','download')}${iconButton('information-refresh','刷新当前页签','refresh')}</div><div id="information-live" class="information-live" hidden></div><div id="information-progress" class="information-progress" role="status"></div><div id="information-groups"></div><div id="information-footer" class="information-footer"></div></div></div>`;}
interface TabState {report?:InformationReport;groups:InformationGroup[];busy:boolean;status:string;error?:string;limit:number;query:string}
export function setupSystemInformation(){const states=Object.fromEntries(informationTabs.map(([id])=>[id,{groups:[],busy:false,status:'',limit:30,query:''}])) as unknown as Record<InformationKind,TabState>;let kind:InformationKind='overview',visible=false;
 const unavailable=(g:InformationGroup)=>g.error?/拒绝访问|access.*denied|0x80041003/i.test(g.error)?'需要管理员权限':/无效类|invalid class|not supported|不支持/i.test(g.error)?'当前设备未提供此信息':'暂时无法读取此信息':g.id==='wifi'?'当前没有可读取的 Wi-Fi 连接':'未检测到设备';
 const fields=(g:InformationGroup,r:InformationGroup['records'][number])=>`<dl class="information-fields">${r.fields.map(f=>`<div><dt>${esc(f.label)}</dt><dd class="${f.value==='未报告'?'unreported':''}" title="${esc(f.value)}">${esc(f.value)}</dd></div>`).join('')}</dl>`;
 const updateStatus=()=>{const s=states[kind];q('information-progress').textContent=s.error||s.status;q('information-progress').classList.toggle('task-running',s.busy);q<HTMLButtonElement>('information-refresh').disabled=s.busy;q('information-footer').textContent=s.report?`更新于 ${new Date(s.report.created).toLocaleTimeString()} · ${(s.report.elapsed/1000).toFixed(1)} 秒`:'';};
 const draw=()=>{if(!visible||!isWindowVisible())return;for(const [id]of informationTabs){const state=states[id];if(!state.report&&!state.groups.length)continue;const count=q('information-tab-'+id).querySelector('small')!,value=String(state.groups.reduce((n,g)=>n+g.records.length,0));if(count.textContent!==value)count.textContent=value;}const s=states[kind],query=s.query.trim().toLowerCase();q('information-title').textContent=informationTabs.find(t=>t[0]===kind)![1];q('information-live').hidden=kind!=='overview';q('information-clear-query').hidden=!query;const groups=s.groups.map(g=>({...g,records:g.records.filter(r=>!query||[g.title,r.title,...r.fields.flatMap(f=>[f.label,f.value])].join(' ').toLowerCase().includes(query))})).filter(g=>!query||g.records.length||g.title.includes(query));
  if(!groups.length){q('information-groups').innerHTML=`<div class="information-empty">${icon(s.busy?'refresh':query?'search':'info')}<span>${s.busy?'正在读取系统信息…':s.error||(query?'没有符合条件的信息':'选择页签读取信息')}</span></div>`;updateStatus();return;}
  q('information-groups').innerHTML=groups.map(g=>`<section class="information-group"><div class="information-group-heading"><h3>${esc(g.title)}</h3><span>${g.records.length?g.records.length+' 项':''}</span>${kind==='overview'?`<button class="quiet icon-button" data-information-link="${g.id==='computer'||g.id==='os'?'os':['gpu','dxgi','display-modes'].includes(g.id)?'display':g.id==='volume'?'storage':g.id}" aria-label="查看${esc(g.title)}详情" title="查看详情">${icon('arrow')}</button>`:''}</div>${g.records.length?g.records.slice(0,s.limit).map((r,i)=>kind==='drivers'||kind==='devices'?`<details class="information-record information-device"><summary>${icon(kind==='drivers'?'system':'devices')}<div><strong>${esc(r.title)}</strong><span>${esc(r.fields.find(f=>f.key==='DriverVersion'||f.key==='Manufacturer')?.value||'')}</span></div>${icon('chevron')}</summary>${fields(g,r)}</details>`:`<article class="information-record"><h4>${esc(r.title)}</h4>${fields(g,kind==='overview'?{...r,fields:r.fields.filter(f=>f.value!=='未报告').slice(0,6)}:r)}</article>`).join(''):`<div class="information-unavailable" title="${esc(g.error||'')}">${icon('info')}<span>${unavailable(g)}</span></div>`}${g.records.length>s.limit?`<button class="quiet information-more" data-information-more="${g.id}">显示更多 · ${s.limit} / ${g.records.length}</button>`:''}</section>`).join('');
  q('information-groups').querySelectorAll<HTMLButtonElement>('[data-information-more]').forEach(b=>b.onclick=()=>{s.limit+=30;draw();});q('information-groups').querySelectorAll<HTMLButtonElement>('[data-information-link]').forEach(b=>b.onclick=()=>q('information-tab-'+b.dataset.informationLink)?.click());updateStatus();
 };
 const load=async(target:InformationKind,refresh=false)=>{const s=states[target];if(s.busy)return;s.busy=true;s.error=undefined;s.status='正在读取…';if(refresh)s.groups=[];if(target===kind)draw();try{s.report=await api.systemInformation(target,refresh);s.groups=s.report.groups;s.status=`${s.groups.reduce((n,g)=>n+g.records.length,0)} 项 · ${s.groups.reduce((n,g)=>n+g.records.reduce((n,r)=>n+r.fields.length,0),0)} 个字段`;const count=q<HTMLElement>('information-tab-'+target).querySelector('small')!;if(visible&&isWindowVisible())count.textContent=String(s.groups.reduce((n,g)=>n+g.records.length,0));}catch(error){s.error=String(error).replace(/^Error.*?: /,'');toast(error);}finally{s.busy=false;if(kind===target)draw();}};
 api.onSystemInformationGroup(({kind:target,group})=>{const s=states[target];if(!s.busy)return;s.groups=s.groups.filter(g=>g.id!==group.id);s.groups.push(group);if(kind===target)draw();});api.onSystemInformationProgress(p=>{const s=states[p.kind];if(!s.busy)return;s.status=`读取中 · ${p.completed} / ${p.total}${p.group?' · '+p.group:''}`;if(kind===p.kind&&visible&&isWindowVisible())updateStatus();});
 document.querySelectorAll<HTMLButtonElement>('[data-information-tab]').forEach(b=>b.onclick=()=>{states[kind].query=q<HTMLInputElement>('information-query').value;kind=b.dataset.informationTab as InformationKind;document.querySelector('.content')!.scrollTop=0;q<HTMLInputElement>('information-query').value=states[kind].query;document.querySelectorAll<HTMLElement>('[data-information-tab]').forEach(t=>{const active=t===b;t.classList.toggle('active',active);t.setAttribute('aria-selected',String(active));});draw();void load(kind);});
 q('page-hardware').querySelector('.information-nav')!.addEventListener('wheel',(event)=>{const e=event as WheelEvent,nav=e.currentTarget as HTMLElement;if(nav.scrollWidth>nav.clientWidth&&e.deltaY){nav.scrollLeft+=e.deltaY;e.preventDefault();}},{passive:false});
 let filterTimer:ReturnType<typeof setTimeout>;q('information-query').oninput=()=>{clearTimeout(filterTimer);filterTimer=setTimeout(()=>{states[kind].query=q<HTMLInputElement>('information-query').value;draw();},120);};action('information-clear-query',()=>{q<HTMLInputElement>('information-query').value='';states[kind].query='';draw();});action('information-refresh',()=>load(kind,true));action('information-export',async()=>{const reports=Object.values(states).flatMap(s=>s.report?[s.report]:[]);if(!reports.length)return toast('请先读取系统信息');if(await api.exportSystemInformation(reports))toast('已导出');});
 api.onDiskMonitor(s=>{if(!visible||!isWindowVisible()||kind!=='overview')return;q('information-live').innerHTML=`<div>${icon('cpu')}<span>CPU</span><strong>${s.cpuPercent.toFixed(1)}<small>%</small></strong></div><div>${icon('memory')}<span>已用内存</span><strong>${size(s.memoryTotal-s.memoryFree)}<small> / ${size(s.memoryTotal)}</small></strong></div><div>${icon('awake')}<span>运行时间</span><strong>${Math.floor(s.uptimeSeconds/86400)?Math.floor(s.uptimeSeconds/86400)+' 天 ':''}${Math.floor(s.uptimeSeconds%86400/3600)}<small>小时</small></strong></div>`;});
 const sync=()=>{if(visible&&isWindowVisible()){draw();void load(kind);}void api.diskMonitor(visible&&isWindowVisible(),'information').catch(toast);};
 onWindowVisibility(sync);
 return {activate(active:boolean){visible=active;sync();}};
}
