/** One delegated tooltip for dynamic controls, including controls inside modal dialogs. */
export function setupTooltips(){
 const tip=document.createElement('div');tip.id='one-tooltip';tip.className='one-tooltip';tip.role='tooltip';
 let target:HTMLElement|null=null,timer:ReturnType<typeof setTimeout>,last=-1000;
 const convert=(el:Element)=>{if(el.hasAttribute('title')){const text=el.getAttribute('title')||'';el.removeAttribute('title');if(text)el.setAttribute('data-tooltip',text);else el.removeAttribute('data-tooltip');}};
 document.querySelectorAll('[title]').forEach(convert);
 new MutationObserver(records=>{for(const r of records){if(r.type==='attributes')convert(r.target as Element);else for(const node of r.addedNodes)if(node instanceof Element){convert(node);node.querySelectorAll('[title]').forEach(convert);}}}).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['title']});
 const hide=()=>{clearTimeout(timer);if(target){const ids=(target.getAttribute('aria-describedby')||'').split(' ').filter(id=>id&&id!==tip.id);if(ids.length)target.setAttribute('aria-describedby',ids.join(' '));else target.removeAttribute('aria-describedby');}target=null;tip.classList.remove('visible');last=performance.now();};
 const show=(el:HTMLElement)=>{if(el===target)return;const fast=performance.now()-last<200;hide();target=el;timer=setTimeout(()=>{if(target!==el||!el.isConnected)return;const label=el.dataset.tooltip||((el.matches('button.icon-button')||el.matches('.nav'))?el.getAttribute('aria-label'):'');if(!label)return;tip.textContent=label;(el.closest('dialog[open]')||document.body).append(tip);tip.classList.remove('visible');tip.style.left='0px';tip.style.top='0px';const r=el.getBoundingClientRect(),t=tip.getBoundingClientRect();tip.style.left=Math.round(Math.max(8,Math.min(innerWidth-t.width-8,r.left+(r.width-t.width)/2)))+'px';tip.style.top=Math.round(r.top>=t.height+12?r.top-t.height-8:Math.min(innerHeight-t.height-8,r.bottom+8))+'px';el.setAttribute('aria-describedby',[(el.getAttribute('aria-describedby')||''),tip.id].filter(Boolean).join(' '));requestAnimationFrame(()=>{if(target===el)tip.classList.add('visible');});},fast?90:380);};
 const candidate=(event:Event)=>{const el=event.target instanceof Element?event.target.closest<HTMLElement>('[data-tooltip],button.icon-button[aria-label],.nav[aria-label]'):null;if(el)show(el);};
 document.addEventListener('pointerover',candidate);document.addEventListener('pointerout',e=>{if(target&&e.target instanceof Node&&target.contains(e.target)&&(!e.relatedTarget||!target.contains(e.relatedTarget as Node)))hide();});
 document.addEventListener('focusin',e=>{if(e.target instanceof Element&&e.target.matches(':focus-visible'))candidate(e);});document.addEventListener('focusout',hide);document.addEventListener('pointerdown',hide,true);document.addEventListener('keydown',hide,true);document.addEventListener('scroll',hide,true);window.addEventListener('blur',hide);
}
