export const api = window.one;
export const q = <T extends HTMLElement = HTMLElement>(id: string) => document.getElementById(id) as T;
export const esc = (text: unknown) => String(text).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]!));
import {House,FolderCog,Link2,Scissors,Pencil,Activity,Star, createElement, Cpu, MemoryStick, CircuitBoard, Monitor, Network, Bluetooth, AudioLines, Battery, Download, Braces, WrapText, Ellipsis, Lock, Move, ToggleRight, Square, Trash2, Terminal, History, LockKeyhole, Coffee, AppWindow, FileText, Mouse, Eye, Settings2, Power, Folder, File, X, ArrowLeft, ArrowRight, ArrowUp, Search, RotateCw, Info, Play, Pause, Volume2, Sun, Minus, Plus, Maximize, HardDrive, ChevronRight, ChevronDown, Copy, List, Keyboard, Expand, Pin, SquareMousePointer, PanelLeft, PanelRight, Pipette, Palette, ExternalLink, Check, Music2, VolumeX, RotateCcw, PanelLeftClose, type IconNode } from 'lucide';
const icons:Record<string,IconNode>= {link:Link2,cut:Scissors,rename:Pencil,activity:Activity,star:Star,move:Move,toggle:ToggleRight,stop:Square,trash:Trash2,settings:Settings2,terminal:Terminal,history:History,locksmith:LockKeyhole,utilities:AppWindow,window:AppWindow,awake:Coffee,music:Music2,'volume-off':VolumeX,rewind:RotateCcw,forward:RotateCw,collapse:PanelLeftClose,text:FileText,input:Mouse,preview:Eye,system:Settings2,power:Power,folder:Folder,file:File,close:X,back:ArrowLeft,arrow:ArrowRight,up:ArrowUp,search:Search,refresh:RotateCw,rotate:RotateCw,info:Info,play:Play,pause:Pause,volume:Volume2,brightness:Sun,minus:Minus,plus:Plus,fit:Maximize,disk:HardDrive,chevron:ChevronRight,'chevron-down':ChevronDown,copy:Copy,list:List,keyboard:Keyboard,mouse:Mouse,expand:Expand,pin:Pin,hold:SquareMousePointer,'panel-left':PanelLeft,'panel-right':PanelRight,color:Pipette,appearance:Palette,open:ExternalLink,check:Check};
export const icon=(name:string)=>createElement(icons[name]||File,{'class':'icon lucide','aria-hidden':'true','focusable':'false','data-lucide-icon':name,'stroke-width':1.75}).outerHTML;
icons.home=House;icons.tools=FolderCog;icons.hardware=Cpu;icons.cpu=Cpu;icons.memory=MemoryStick;icons.board=CircuitBoard;icons.monitor=Monitor;icons.network=Network;icons.bluetooth=Bluetooth;icons.devices=AudioLines;icons.battery=Battery;icons.download=Download;icons.braces=Braces;icons.wrap=WrapText;icons.lock=Lock;icons.ellipsis=Ellipsis;
export function registerIcons(catalog:Record<string,IconNode>){for(const [name,node]of Object.entries(catalog))icons['lucide:'+name]=node;}
document.documentElement.style.setProperty('--check-icon',`url("data:image/svg+xml,${encodeURIComponent(icon('check'))}")`);
export const button = (id: string, text: string, glyph = '', primary = false) => `<button id="${id}"${primary ? ' class="primary"' : ''}>${glyph ? icon(glyph) : ''}${text}</button>`;
export const iconButton = (id: string, label: string, glyph: string) => `<button id="${id}" class="icon-button quiet" aria-label="${label}" title="${label}">${icon(glyph)}</button>`;
export const switchControl = (id: string, name: string) => `<label class="switch"><input type="checkbox" role="switch" id="${id}" aria-label="${name}"><span class="switch-track"></span></label>`;
export const size = (n: number) => { if (n < 1024) return `${n} B`; const power = Math.min(4,Math.floor(Math.log(n)/Math.log(1024))); return `${(n/1024**power).toFixed(power > 1 ? 2 : 1)} ${['B','KB','MB','GB','TB'][power]}`; };
let timer: ReturnType<typeof setTimeout>;
export function toast(message: unknown) { let node = q('toast'); const dialog=document.querySelector<HTMLDialogElement>('dialog[open]');if(dialog){node=dialog.querySelector<HTMLElement>('.dialog-error')!;if(!node){node=document.createElement('p');node.className='dialog-error';node.setAttribute('role','alert');(dialog.querySelector('.one-dialog-body')||dialog).append(node);}} if (!node) return; node.textContent = String(message).replace(/^Error: /,'').replace(/^Error invoking remote method '[^']+': Error: /,''); node.hidden = false; clearTimeout(timer); timer = setTimeout(() => node.hidden = true,5000); }
export function action(id: string, work: () => unknown | Promise<unknown>) { q(id).addEventListener('click',() => Promise.resolve().then(work).catch(toast)); }
