import {locksmithCard,setupLocksmith} from './locksmith-view';
import {api,q,button,iconButton,icon,esc,switchControl,toast} from './ui';
import {bindPreference} from './preferences';
import {setupShortcut} from './shortcut';
import {hydrateFileIcons} from './shell-icons';
import {isWindowVisible,onWindowVisibility} from './window-visibility';
import type {UtilityState} from '../shared/utilities';
export function utilitiesPage(){return `<div data-enhancement-panel="awake" hidden><div class="utility-tab-layout"><div class="settings-card"><div class="setting-row"><span class="setting-icon">${icon('awake')}</span><div class="setting-copy"><h2>唤醒</h2><p>临时阻止自动睡眠；退出 One 后恢复。</p></div><span class="utility-status" id="awake-state">已关闭</span></div>
<div class="preference-row"><label for="awake-mode">模式</label><select id="awake-mode" aria-label="唤醒模式"><option value="indefinite">保持唤醒</option><option value="timed">持续一段时间</option><option value="until">到指定时间</option></select></div>
<div class="preference-row" id="awake-duration-row" hidden><label for="awake-minutes">持续时间</label><div class="field-group"><input type="number" id="awake-minutes" min="1" max="525600" value="30" aria-label="唤醒分钟"><span>分钟</span></div></div>
<div class="preference-row" id="awake-until-row" hidden><label for="awake-until">结束时间</label><input id="awake-until" aria-label="唤醒结束时间" placeholder="2026-10-01 18:00"></div>
<div class="preference-row"><label><input type="checkbox" id="awake-display">保持屏幕开启</label></div><div class="settings-actions"><span class="utility-message" id="awake-message" role="status"></span><div class="spacer"></div>${button('awake-stop','停止')}${button('awake-start','开始','',true)}</div></div>
</div></div><div data-enhancement-panel="topmost" hidden><div class="utility-tab-layout topmost-layout"><div class="settings-card"><div class="setting-row"><span class="setting-icon">${icon('pin')}</span><div class="setting-copy"><h2>始终置顶</h2><p>对当前窗口按快捷键，再按一次取消。</p></div>${switchControl('topmost-enabled','开启始终置顶')}</div>
<div class="preference-row"><label for="topmost-shortcut">快捷键</label><input id="topmost-shortcut" aria-label="置顶快捷键"></div>
<div class="preference-row"><label><input type="checkbox" id="topmost-border">边框提示</label><input id="topmost-color" class="color-value" aria-label="置顶提示颜色" maxlength="7"></div>
<div class="preference-row"><label for="topmost-opacity">边框不透明度</label><div class="field-group"><input id="topmost-opacity" type="number" min="0" max="100" step="5" aria-label="边框不透明度"><span>%</span></div></div><div class="preference-row"><label for="topmost-thickness">边框粗细</label><div class="field-group"><input id="topmost-thickness" type="number" min="1" max="20" aria-label="边框粗细"><span>像素</span></div></div><div class="preference-row"><label for="topmost-sound">播放提示音</label>${switchControl('topmost-sound','置顶时播放提示音')}</div><div class="preference-row"><label for="topmost-contextMenu">标题栏菜单入口</label>${switchControl('topmost-contextMenu','标题栏菜单中显示始终置顶')}</div><div class="preference-row"><label for="topmost-excluded">排除应用</label><input id="topmost-excluded" aria-label="置顶排除应用" placeholder="程序名，用逗号分隔"></div>
<div class="preference-row"><label><input type="checkbox" id="topmost-fullscreen">全屏时暂停快捷键</label></div><div class="settings-actions"><span class="utility-message" id="topmost-error" role="status"></span><div class="spacer"></div></div>
</div><div class="settings-card topmost-window-card"><div class="section-heading utility-window-heading"><h2>窗口</h2><div>${button('topmost-clear','取消全部置顶')}${iconButton('topmost-refresh','刷新窗口','refresh')}</div></div><div class="window-list" id="topmost-windows"></div></div></div></div><div data-enhancement-panel="locksmith" hidden>${locksmithCard()}</div>`;}
export function setupUtilities(){
  setupLocksmith();
  setupShortcut(q<HTMLInputElement>('topmost-shortcut'));
  let latest:UtilityState|undefined;
  const renderState=(s:UtilityState)=>{latest=s;if(!isWindowVisible()||q('page-input').hidden)return;const a=s.awake;q('awake-state').textContent=a.active?'唤醒中':a.locked&&a.mode!=='off'?'锁屏暂停':'已关闭';q('awake-state').classList.toggle('running',a.active);q<HTMLButtonElement>('awake-stop').disabled=a.mode==='off';q('awake-message').textContent=a.error||((a.mode==='timed'||a.mode==='until')?`剩余 ${Math.ceil(a.remaining/60000)} 分钟 · ${new Date(a.expiresAt).toLocaleString()}`:a.active?(a.display?'保持系统与屏幕开启':'保持系统运行，屏幕可按原计划关闭'):'');q('topmost-error').textContent=s.shortcutError;};
  const fields=()=>{const value=q<HTMLSelectElement>('awake-mode').value;q('awake-duration-row').hidden=value!=='timed';q('awake-until-row').hidden=value!=='until';};q('awake-mode').addEventListener('change',fields);
  const load=async()=>{const s=await api.settings(),a=s.utilities.awake,t=s.utilities.topmost;q<HTMLSelectElement>('awake-mode').value=a.mode==='off'?'indefinite':a.mode;q<HTMLInputElement>('awake-display').checked=a.display;q<HTMLInputElement>('topmost-enabled').checked=t.enabled;q<HTMLInputElement>('topmost-shortcut').value=t.shortcut;q<HTMLInputElement>('topmost-border').checked=t.border;q<HTMLInputElement>('topmost-color').value=t.color;q<HTMLInputElement>('topmost-excluded').value=t.excludedApps;for(const key of ['opacity','thickness'] as const)q<HTMLInputElement>('topmost-'+key).value=String(t[key]);for(const key of ['sound','contextMenu'] as const)q<HTMLInputElement>('topmost-'+key).checked=t[key];q<HTMLInputElement>('topmost-fullscreen').checked=t.pauseFullscreen;fields();renderState(await api.utilityState());};
  const windows=async()=>{const entries=await api.topmostWindows();if(!isWindowVisible())return;q('topmost-windows').innerHTML=entries.length?entries.map(w=>`<div class="window-row"><span class="window-symbol" data-file-icon="${esc(w.process)}">${icon('window')}</span><div><strong title="${esc(w.title)}">${esc(w.title)}</strong><span>${esc(w.process.split('\\').pop())}</span></div><button class="icon-button quiet" data-pin="${w.id}" aria-label="${w.managed?'取消置顶':'置顶'} ${esc(w.title)}" aria-pressed="${w.managed}" ${w.topmost&&!w.managed?'disabled title="已由其他功能置顶"':''}>${icon('pin')}</button></div>`).join(''):'<div class="utility-message">没有可操作的窗口</div>';hydrateFileIcons(q('topmost-windows'));q('topmost-windows').querySelectorAll<HTMLButtonElement>('[data-pin]').forEach(b=>b.onclick=()=>void api.toggleTopmost(Number(b.dataset.pin)).then(windows).catch(toast));};
  q('awake-start').onclick=()=>void (async()=>{const s=await api.settings(),mode=q<HTMLSelectElement>('awake-mode').value as 'indefinite'|'timed'|'until',minutes=Number(q<HTMLInputElement>('awake-minutes').value);if(mode==='timed'&&(!Number.isInteger(minutes)||minutes<1||minutes>525600))throw new Error('持续时间应为 1–525600 分钟');const expiresAt=mode==='timed'?Date.now()+minutes*60000:mode==='until'?new Date(q<HTMLInputElement>('awake-until').value.replace(' ','T')).getTime():0;if(mode!=='indefinite'&&(!Number.isFinite(expiresAt)||expiresAt<=Date.now()))throw new Error('请输入未来的结束时间，例如 2026-10-01 18:00');await api.patchSettings({utilities:{awake:{mode,display:q<HTMLInputElement>('awake-display').checked,expiresAt}}});renderState(await api.utilityState());})().catch(toast);
  q('awake-stop').onclick=()=>void api.patchSettings({utilities:{awake:{mode:'off'}}}).catch(toast);
  bindPreference(q('awake-display'),()=>({utilities:{awake:{display:q<HTMLInputElement>('awake-display').checked}}}),load);
  for(const [id,key] of [['opacity','opacity'],['thickness','thickness'],['sound','sound'],['contextMenu','contextMenu'],['enabled','enabled'],['shortcut','shortcut'],['border','border'],['color','color'],['excluded','excludedApps'],['fullscreen','pauseFullscreen']] as const){const control=q<HTMLInputElement>('topmost-'+id);bindPreference(control,()=>({utilities:{topmost:{[key]:control.type==='checkbox'?control.checked:control.type==='number'?Number(control.value):control.value}}}),load);}
  q('topmost-refresh').onclick=()=>void windows().catch(toast);q('topmost-clear').onclick=()=>void api.clearTopmost().then(windows).catch(toast);
  api.onUtilityState(s=>{const changed=latest?.pinned!==s.pinned;renderState(s);if(changed&&isWindowVisible()&&!q('page-input').hidden&&!q('topmost-windows').closest<HTMLElement>('[data-enhancement-panel]')?.hidden)void windows().catch(toast);});void load().catch(toast);
  document.querySelector('#enhancement-tab-topmost')?.addEventListener('click',()=>void windows().catch(toast));
  const resume=()=>{if(latest)renderState(latest);if(isWindowVisible()&&!q('page-input').hidden&&!q('topmost-windows').closest<HTMLElement>('[data-enhancement-panel]')?.hidden)void windows().catch(toast);};
  onWindowVisibility(visible=>{if(visible)resume();});
  document.querySelector('[data-page=input]')?.addEventListener('click',resume);
  document.querySelector('#enhancement-tab-awake')?.addEventListener('click',()=>{if(latest)renderState(latest);});
}
